Repository mattermost/mattermost-mobile, pull requests merged in 2018-12, with the labels that each got.

#2418 translations PR 20181203
  assets/base/i18n/pl.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2417 NOTICE.txt updates for December 2018
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#2355 Add support for Elixir syntax highlighting
  app/utils/markdown.js
Labels: 3: Ready to Merge

#2416 Adding i18n-extract task to the Makefile
  Makefile
Labels: 3: Ready to Merge

#2384 Fixed typo in i18nId
  app/screens/settings/advanced_settings/advanced_settings.js
Labels: 2: Dev Review, CherryPickApproved

#2414 post menu and file attachments
  NOTICE.txt
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/actions/views/channel.js
  app/components/post/post.js
  app/components/post_body/post_body.js
  app/components/reactions/reactions.js
  app/components/slide_up_panel/slide_up_panel.js
  app/components/slide_up_panel/slide_up_panel_indicator.js
  app/screens/index.js
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
  app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
  app/screens/reaction_list/reaction_header.js
  app/screens/reaction_list/reaction_list.js
  app/selectors/post_list.js
  app/selectors/post_list.test.js
  index.js
  ios/Mattermost.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  test/setup.js
Labels: 3: Ready to Merge, Build Apps for PR, CherryPickApproved

#2421 Bump app build number to 161
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2419 Wait 1s before clearing notifications
  app/components/network_indicator/network_indicator.js
Labels: 3: Ready to Merge

#2302 [MM-8404] Channel notification setting for disabling channel mentions (#MM-8404)
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge, Hacktoberfest

#2422 [MM-13171] Make circular badge on jewel for single-digit mention
  app/components/__snapshots__/badge.test.js.snap
  app/components/badge.js
  app/components/badge.test.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
Labels: 2: Dev Review, CherryPickApproved

#2425 Fix opening documents on Android
  app/components/file_attachment_list/file_attachment_document.js
Labels: 3: Ready to Merge, CherryPickApproved

#2426 Android extension channel list to display all items
  share_extension/android/extension_channels/extension_channels.js
Labels: 3: Ready to Merge, CherryPickApproved

#2402 Update fastlane env vars example
  fastlane/env_vars_example
Labels: 3: Ready to Merge

#2424 Fix reaction list cutoff at end of list
  app/components/slide_up_panel/slide_up_panel.js
Labels: 3: Ready to Merge, CherryPickApproved

#2430 MM-13361 Set Open Teams icons background to white
  app/screens/select_team/select_team.js
Labels: 3: Ready to Merge, CherryPickApproved

#2431 MM-13362 Update account settings header color when changing theme
  app/screens/settings/display_settings/display_settings.js
  app/screens/settings/display_settings/display_settings.test.js
  app/screens/settings/general/settings.js
  app/screens/theme/theme.js
  app/screens/theme/theme.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2427 Fix team mention badge alignment on iOS
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
Labels: 3: Ready to Merge, CherryPickApproved

#2440 Sort pinned posts from newest to oldest
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2438 MM-13368 Do not truncate tall images in preview screen
  app/screens/image_preview/image_preview.js
  app/utils/images.js
  app/utils/images.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2429 MM-13358 iOS Share extension channel list
  share_extension/android/actions/index.js
  share_extension/android/extension_channels/index.js
  share_extension/common/selectors/index.js
  share_extension/ios/extension_channels.js
Labels: 3: Ready to Merge, CherryPickApproved

#2439 Hide Favorite channel section when there are not favorite channels
  app/components/sidebars/main/channels_list/list/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2441 Properly check if link is an image when link is shortened
  app/components/post_body_additional_content/post_body_additional_content.js
Labels: 3: Ready to Merge, CherryPickApproved

#2433 MM-13365/MM-13375 Fix edit profile image
  app/components/attachment_button.js
  app/components/profile_picture/profile_picture.js
  app/screens/edit_profile/edit_profile.js
Labels: 3: Ready to Merge, CherryPickApproved

#2442 MM-13419 Fix leaving private channel from another client
  app/components/post_textbox/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2444 [MM-13398] Update redux commit to fix sorting of channels at sidebar unreads section
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2445 Bump app build number to 162
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2446 Update react-native-image-picker dependency
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2447 translations PR 20181210
  assets/base/i18n/de.json
  assets/base/i18n/fr.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
Labels: 3: Ready to Merge

#2448 Fix edit profile image
  app/components/attachment_button.js
  app/screens/edit_profile/edit_profile.js
Labels: 3: Ready to Merge, CherryPickApproved

#2449 Fix copy markdown link
  app/components/markdown/markdown_link/markdown_link.js
Labels: 3: Ready to Merge, CherryPickApproved

#2451 MM-13420 Always show the Unreads section in the channel list
  app/components/sidebars/main/channels_list/list/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2450 MM-13421 Fix channel sidebar sometimes using old permissions
  app/components/sidebars/main/channels_list/list/list.js
Labels: 3: Ready to Merge, CherryPickApproved

#2381 Theme Selection - theme thumbnail images
  app/screens/theme/__snapshots__/theme.test.js.snap
  app/screens/theme/index.js
  app/screens/theme/theme.js
  app/screens/theme/theme.test.js
  app/screens/theme/theme_tile.js
  assets/base/images/themes/check.png
  assets/base/images/themes/check@2x.png
  assets/base/images/themes/check@3x.png
  assets/base/images/themes/mattermost.png
  assets/base/images/themes/mattermost@2x.png
  assets/base/images/themes/mattermost@3x.png
  assets/base/images/themes/mattermost_dark.png
  assets/base/images/themes/mattermost_dark@2x.png
  assets/base/images/themes/mattermost_dark@3x.png
  assets/base/images/themes/organization.png
  assets/base/images/themes/organization@2x.png
  assets/base/images/themes/organization@3x.png
  assets/base/images/themes/windows_dark.png
  assets/base/images/themes/windows_dark@2x.png
  assets/base/images/themes/windows_dark@3x.png
Labels: 3: Ready to Merge, Build Apps for PR

#2452 MM-13431 Fix load more posts
  app/actions/views/channel.js
  app/constants/view.js
  app/reducers/views/channel.js
Labels: 3: Ready to Merge, CherryPickApproved

#2453 Post Menu initial position to show one option cut off
  app/screens/post_options/post_options.js
Labels: 3: Ready to Merge, CherryPickApproved

#2456 MM-13333 Fix minor alignment issue with reply thread indicator
  app/components/post/post.js
Labels: 3: Ready to Merge, CherryPickApproved

#2458 translations PR 20181213
  assets/base/i18n/ru.json
Labels: 3: Ready to Merge

#2455 prevent double tap on Channel Info options
  app/screens/channel_info/channel_info.js
Labels: 3: Ready to Merge, CherryPickApproved

#2443 Update date separators when timezone changes
  app/components/post_list/date_header/__snapshots__/date_header.test.js.snap
  app/components/post_list/date_header/date_header.js
  app/components/post_list/date_header/date_header.test.js
  app/components/post_list/date_header/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2454 Remove extra divider below Edit Channel in Channel info
  app/screens/channel_info/channel_info.js
Labels: 3: Ready to Merge, CherryPickApproved

#2370 v1.15 Changelog
  CHANGELOG.md
Labels: 2: Dev Review, 2: PM Review

#2428 MM-12354 Remove Profile Image
  app/actions/views/edit_profile.js
  app/components/__snapshots__/profile_picture_button.test.js.snap
  app/components/attachment_button.js
  app/components/profile_picture/profile_picture.js
  app/components/profile_picture_button.js
  app/components/profile_picture_button.test.js
  app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
  app/screens/edit_profile/edit_profile.js
  app/screens/edit_profile/edit_profile.test.js
  app/screens/edit_profile/index.js
  app/screens/options_modal/options_modal_list.android.js
  app/screens/options_modal/options_modal_list.ios.js
Labels: 2: Dev Review

#2464 [MM-13433] Fix unnecessary rendering for reactions component and reaction list screen
  app/components/reactions/index.js
  app/components/reactions/reactions.js
  app/utils/reaction.js
  app/utils/reaction.test.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2462 Show an alert box when the team could not be joined
  app/screens/select_team/index.js
  app/screens/select_team/select_team.js
  app/screens/select_team/select_team.test.js
Labels: CherryPickApproved

#2469 Bump app build number to 164
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2474 Add the onMessage handler when sso completes
  app/screens/sso/sso.js
Labels: 3: Ready to Merge, CherryPickApproved

#2475 Bump App Version to 1.15.1 and Build number to 166
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2465 Fix formatting error in changelog and add note about Android compatibility change in v1.15
  CHANGELOG.md
Labels: 3: Ready to Merge

#2460 MM-13535/MM-13538 Fixes for duplicate text on message attachments and empty space
  app/components/message_attachments/attachment_fields.js
  app/components/message_attachments/message_attachment.js
Labels: 3: Ready to Merge, CherryPickCandidate

#2471 LHS use getSortedFavoriteChannelIds instead of getFavoriteChannelIds
  app/components/sidebars/main/channels_list/list/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2472 Fix post menu rounded corners
  app/components/slide_up_panel/slide_up_panel.js
Labels: 3: Ready to Merge, CherryPickApproved

#2479 translations PR 20181224
  assets/base/i18n/pl.json
  assets/base/i18n/ro.json
Labels: 3: Ready to Merge

#2481 Bump version to 1.16.0 and Build number to 167
  android/app/build.gradle
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge
