Repository mattermost/mattermost-mobile, pull requests merged in 2018-02, with the labels that each got.

#1422 Adjust margin and tap area of reply icon
  app/components/post_header/post_header.js
Labels: 2: Dev Review

#1425 Handle the good, warning, danger status for post attachments
  app/components/slack_attachments/slack_attachment.js
Labels: 3: Ready to Merge

#1429 Fix Android stuck when opening from push notification
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
Labels: 2: Dev Review

#1430 [ICU-680] Fix Duplicate posts
  app/actions/views/channel.js
  app/store/index.js
  app/store/middleware.js
  app/utils/promise_timeout.js
Labels: 2: Dev Review, Awaiting PR

#1431 Bump app build to 86
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1432 Update mattermost-redux
  yarn.lock
Labels: 3: Ready to Merge

#1433 translations PR 20180212
  assets/base/i18n/de.json
  assets/base/i18n/en.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#1438 Adding required NSAppleMusicUsageDescription by Apple
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
Labels: 3: Ready to Merge

#1440 Using the correct NSAppleMusicUsageDescription key
  ios/Mattermost/Info.plist
Labels: 3: Ready to Merge

#1441 Bump iOS build number to 87
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1442 Bump Android build number to 87
  android/app/build.gradle
Labels: 3: Ready to Merge

#1444 translations PR 20180215
  assets/base/i18n/de.json
  assets/base/i18n/en.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#1406 ABC-123 Add handling for loading custom emojis asynchronously
  app/actions/views/emoji.js
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/emoji_suggestion/index.js
  app/components/emoji/emoji.js
  app/components/emoji/index.js
  app/components/emoji_picker/emoji_picker.js
  app/components/emoji_picker/emoji_picker_row.js
  app/components/emoji_picker/index.js
  app/constants/view.js
  app/mattermost.js
  app/reducers/views/emoji.js
  app/reducers/views/index.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
  app/screens/select_server/index.js
  app/screens/select_server/select_server.js
  app/store/index.js
  yarn.lock
Labels: 3: Ready to Merge

#1434 ICU-624 Added markdown tables
  app/components/markdown/markdown.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_table/index.js
  app/components/markdown/markdown_table/markdown_table.js
  app/components/markdown/markdown_table_cell/index.js
  app/components/markdown/markdown_table_cell/markdown_table_cell.js
  app/components/markdown/markdown_table_image/index.js
  app/components/markdown/markdown_table_image/markdown_table_image.js
  app/components/markdown/markdown_table_row/index.js
  app/components/markdown/markdown_table_row/markdown_table_row.js
  app/components/markdown/transform.js
  app/screens/index.js
  app/screens/table/index.js
  app/screens/table/table.js
  app/screens/table_image/index.js
  app/screens/table_image/table_image.js
  app/utils/markdown.js
  assets/base/i18n/en.json
  package.json
  test/app/components/markdown/transform.test.js
  yarn.lock
Labels: 3: Ready to Merge

#1455 [MM-9321] Add a "+" button to make it easy to add Emoji Reactions
  app/components/post/post.js
  app/components/post_body/post_body.js
  app/components/reactions/reactions.js
Labels: 2: Dev Review

#1447 RN-9379 Updated react-native-sentry to 0.34.0
  android/app/build.gradle
  app/mattermost.js
  app/screens/settings/advanced_settings/advanced_settings.js
  app/screens/settings/settings_item/index.js
  app/screens/settings/settings_item/style.android.js
  app/screens/settings/settings_item/style.ios.js
  assets/base/config.json
  ios/bundleReactNative.sh
  ios/makeSentryProperties.sh
  ios/uploadDebugSymbols.sh
  package.json
  yarn.lock
Labels: 3: Ready to Merge

#1451 MM-9620: Add reactions permissions
  app/components/post_body/index.js
  app/components/post_body/post_body.js
  app/components/reactions/index.js
  app/components/reactions/reactions.js
Labels: 3: Ready to Merge

#1458 [MM-9559] use NSURLSessionUploadTask with the new files endpoint in extension
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.m
  ios/MattermostShare/PerformRequests.h
  ios/MattermostShare/PerformRequests.m
  ios/MattermostShare/SessionManager.h
  ios/MattermostShare/SessionManager.m
  ios/MattermostShare/ShareViewController.h
  ios/MattermostShare/ShareViewController.m
  share_extension/ios/extension_post.js
Labels: 3: Ready to Merge
