Repository mattermost/mattermost-mobile, pull requests merged in 2018-06, with the labels that each got.

#1721 [MM-10646] Fix DM's channel displayname (instead of "Someone") after creating a DM
  app/screens/more_dms/more_dms.js
Labels: 3: Ready to Merge

#1729 Fix push notification styling backwards compatibility
  android/app/src/main/java/com/mattermost/react_native_interface/AsyncStorageHelper.java
  android/app/src/main/java/com/mattermost/react_native_interface/KeysReadableArray.java
  android/app/src/main/java/com/mattermost/react_native_interface/ResolvePromise.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/InitializationModule.java
  fastlane/Fastfile
Labels: 3: Ready to Merge

#1730 MM-10372 Get channel if necessary when loading from push notification
  app/actions/views/root.js
Labels: 3: Ready to Merge

#1725 [MM-10303] Fix scrolling issue on profiles when adding user/s to a channel
  app/components/combined_system_message/combined_system_message.test.js
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/index.js
  app/components/custom_list/index.test.js
Labels: 2: Dev Review

#1727 Fix change team and channel in iOS share extension
  app/store/index.js
Labels: 3: Ready to Merge

#1732 Fix inline images in long posts
  app/components/markdown/markdown_image/markdown_image.js
Labels: 2: Dev Review

#1733 Bump iOS build number to 106
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1734 Bump Android build number to 106
  android/app/build.gradle
Labels: 3: Ready to Merge

#1731 Fixed dev-mode error relating to adjacent images
  app/components/markdown/transform.js
  app/components/markdown/transform.test.js
Labels: 3: Ready to Merge

#1735 Fix Team icon background and radius in team lists
  app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js
Labels: 3: Ready to Merge

#1736 Verify that the push notification version is not null
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 3: Ready to Merge

#1739 Ping server after setting app offline/online. Also include timeout
  app/utils/network.js
Labels: 3: Ready to Merge

#1738 Update mm-redux to use release-5.0 branch
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1740 [MM-10519] Remove converted channel (into private) from "MoreChannels" screen of joinable channels
  app/screens/more_channels/more_channels.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1737 Fix iOS type error warnings
  app/store/index.js
Labels: 3: Ready to Merge

#1743 MM-10823 Switch to default channel after leaving channel
  app/actions/views/channel.js
  app/screens/channel/channel.js
Labels: 2: Dev Review

#1710 MM-10340 Fix "More New Messages Above" that appears on top of the channel after joining
  app/selectors/post_list.js
  app/selectors/post_list.test.js
Labels: 3: Ready to Merge

#1745 Bump iOS build number to 107
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1746 Bump Android build number to 107
  android/app/build.gradle
Labels: 3: Ready to Merge

#1749 Fix inApp notification handler
  app/screens/entry/entry.js
  app/screens/notification/notification.js
Labels: 3: Ready to Merge

#1744 Fix user is typing cut off on iOS
  app/components/post_textbox/components/typing/typing.js
Labels: 3: Ready to Merge

#1753 Fix roles Set issue and update device-info to not cache appVersion
  app/store/index.js
  package-lock.json
  package.json
Labels: 2: Dev Review

#1754 Bump iOS build number to 108
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1759 MM-10815 Load more posts when post list is under 1 screen long
  app/actions/views/channel.js
  app/components/post_list/post_list.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel/channel_post_list/index.js
Labels: 3: Ready to Merge

#1761 Render SAML json errors and include special header in webview requests
  app/screens/sso/sso.js
Labels: 3: Ready to Merge

#1763 Set segment key for development
  assets/base/config.json
Labels: 3: Ready to Merge

#1762 translations PR 20180613
  assets/base/i18n/de.json
  assets/base/i18n/en.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#1764 Bump iOS build number to 109
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1765 Bump Android build number to 109
  android/app/build.gradle
Labels: 3: Ready to Merge

#1766 Merge Release 1.9 into master
  android/app/build.gradle
  app/actions/views/channel.js
  app/components/post_body/post_body.js
  app/components/post_list/post_list.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel/channel_post_list/index.js
  app/screens/permalink/permalink.js
  app/screens/sso/sso.js
  assets/base/config.json
  assets/base/i18n/de.json
  assets/base/i18n/en.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 2: Dev Review

#1768 MM-10888 Hide parts of combined system messages that don't affect the current user
  app/components/combined_system_message/combined_system_message.js
  app/components/combined_system_message/combined_system_message.test.js
  app/components/combined_system_message/index.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1771 Bump iOS build number to 110
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1772 Bump Android build number to 110
  android/app/build.gradle
Labels: 3: Ready to Merge

#1773 Release 1.9 into master
  android/app/build.gradle
  app/components/combined_system_message/combined_system_message.js
  app/components/combined_system_message/combined_system_message.test.js
  app/components/combined_system_message/index.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1717 v1.9 Changelog
  CHANGELOG.md
Labels: 3: Ready to Merge

#1775 Fix memory leak on combined_system_message component
  app/components/combined_system_message/combined_system_message.js
  app/components/combined_system_message/combined_system_message.test.js
  app/components/combined_system_message/index.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1776 Bump iOS build number to 111
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1778 Bump Android build number to 111
  android/app/build.gradle
Labels: 3: Ready to Merge

#1780 Fix fastlane ios release splash screen
  fastlane/Fastfile
Labels: 3: Ready to Merge

#1783 Bump iOS build number to 112
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1784 Bump Android build number to 112
  android/app/build.gradle
Labels: 3: Ready to Merge

#1786 Merge Release 1.9 into master
  android/app/build.gradle
  app/components/combined_system_message/combined_system_message.js
  app/components/combined_system_message/combined_system_message.test.js
  app/components/combined_system_message/index.js
  app/fetch_preconfig.js
  app/mattermost.js
  app/screens/permalink/permalink.js
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1781 translations PR 20180619
  assets/base/i18n/de.json
  assets/base/i18n/en.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#1777 MM-10822 Change post textbox to only be partially connected
  app/components/post_textbox/post_textbox.js
  app/components/quick_text_input.js
Labels: 3: Ready to Merge

#1770 Unread badge background is always white
  app/components/channel_drawer/channels_list/channel_item/channel_item.js
  app/components/channel_drawer/channels_list/channels_list.js
  app/components/channel_drawer/channels_list/switch_teams_button/switch_teams_button.js
  app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
Labels: 3: Ready to Merge

#1760 Make it clear MNPS is required
  README.md
Labels: 3: Ready to Merge

#1767 CBA support for iOS
  .gitignore
  app/components/custom_list/index.test.js
  app/components/file_attachment_list/file_attachment_document.js
  app/components/offline_indicator/offline_indicator.js
  app/fetch_preconfig.js
  app/screens/channel/channel.js
  app/screens/image_preview/downloader.ios.js
  app/screens/select_server/index.js
  app/screens/select_server/select_server.js
  app/store/middleware.js
  app/utils/image_cache_manager.js
  assets/base/config.json
  ios/0155-keys.png
  ios/KeyShareConsumer.storyboard
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/Mattermost.xcscheme
  ios/Mattermost/Mattermost.entitlements
  ios/MattermostShare/MattermostShare.entitlements
  ios/MattermostShare/SessionManager.h
  ios/MattermostShare/SessionManager.m
  ios/MattermostShare/ShareViewController.m
  packager/modulePaths.js
  share_extension/ios/extension_post.js
  share_extension/ios/index.js
Labels: 3: Ready to Merge

#1788 [MM-10929] Update mattermost-redux with fix on duplicated user of combined system messages
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1790 MM-8701 Get client config after logging in
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1789 Fix memory leak on offline indicator component
  app/components/offline_indicator/offline_indicator.js
Labels: 3: Ready to Merge

#1795 MM-10990: allow a pathname when selecting a server
  app/screens/select_server/select_server.js
Labels: 2: Dev Review

#1779 MM-10717: Update longpress buttons when add reaction, edit post, or d…
  app/actions/views/account_notifications.js
  app/actions/views/login.js
  app/actions/views/select_team.js
  app/components/channel_drawer/channels_list/list/index.js
  app/components/post/index.js
  app/components/post_body/index.js
  app/components/post_header/index.js
  app/components/post_profile_picture/index.js
  app/components/tooltip.js
  app/screens/about/index.js
  app/screens/channel_info/index.js
  app/screens/entry/index.js
  app/screens/login/index.js
  app/screens/login_options/index.js
  app/screens/more_channels/index.js
  app/screens/notification/index.js
  app/screens/select_server/index.js
  app/screens/settings/general/index.js
  app/screens/settings/notification_settings/index.js
  app/screens/user_profile/index.js
  share_extension/android/extension_post/index.js
Labels: 2: Dev Review

#1796 [MM-10817] Add option to send message via user profile even coming from DM channel
  app/screens/user_profile/index.js
  app/screens/user_profile/user_profile.js
Labels: 3: Ready to Merge

#1797 Silence fetch errors caused by websocket action
  app/fetch_preconfig.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1798 Fix user being "logged out" after upgrading
  app/app.js
Labels: 2: Dev Review

#1800 Bump iOS build number to 113
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1801 Bump Android build number to 113
  android/app/build.gradle
Labels: 3: Ready to Merge

#1804 Fixes entry point and keyboard lag
  app/screens/entry/entry.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1806 Fix android seach field population for in and from keywords
  app/components/search_bar/search_bar.android.js
Labels: 2: Dev Review

#1808 Bump iOS build number to 114
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1809 Bump Android build number to 114
  android/app/build.gradle
Labels: 3: Ready to Merge

#1810 merge Release 1.9 into master
  android/app/build.gradle
  app/components/search_bar/search_bar.android.js
  app/screens/entry/entry.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1792 Prevent "Invalid or expired session" errors from being added to error reducer
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1819 MM-11018 Provide default message for Sentry breadcrumbs (1.9.2)
  app/utils/sentry/middleware.js
Labels: 3: Ready to Merge

#1820 MM-11022 Revert "MM-10822 Change post textbox to only be partially connected"
  app/components/post_textbox/post_textbox.js
  app/components/quick_text_input.js
Labels: 3: Ready to Merge

#1822 Fix bad action when tapping on a push notification
  app/actions/views/root.js
Labels: 2: Dev Review

#1823 MM-11016 Updated redux to not error when failing to parse websocket origin
  package-lock.json
  package.json
Labels: 2: Dev Review

#1817 Fix opening video when file has localPath set
  app/screens/image_preview/downloader.ios.js
  app/screens/image_preview/video_preview.js
Labels: 3: Ready to Merge

#1824 Always create a temp file for Android share
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Labels: 2: Dev Review

#1825 Bump iOS build number to 115
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1826 Bump Android build number to 115
  android/app/build.gradle
Labels: 3: Ready to Merge

#1827 Merge release 1.9 into master
  Makefile
  android/app/build.gradle
  app/actions/views/root.js
  app/components/attachment_button.js
  app/components/post_textbox/post_textbox.js
  app/components/quick_text_input.js
  app/screens/image_preview/downloader.ios.js
  app/screens/image_preview/video_preview.js
  app/utils/sentry/middleware.js
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1787 Sidebars improvement
  app/actions/views/more_dms.js
  app/components/channel_loader/channel_loader.js
  app/components/channel_loader/index.js
  app/components/drawer.js
  app/components/search_bar/search_bar.android.js
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
  app/components/sidebars/main/channels_list/channel_item/index.js
  app/components/sidebars/main/channels_list/channels_list.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/filtered_list/index.js
  app/components/sidebars/main/channels_list/index.js
  app/components/sidebars/main/channels_list/list/index.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/channels_list/switch_teams_button/index.js
  app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
  app/components/sidebars/main/channels_list/unread_indicator/index.js
  app/components/sidebars/main/drawer_swipper/drawer_swiper.js
  app/components/sidebars/main/drawer_swipper/index.js
  app/components/sidebars/main/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/main/teams_list/index.js
  app/components/sidebars/main/teams_list/teams_list.js
  app/components/sidebars/main/teams_list/teams_list_item/index.js
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
  app/components/sidebars/settings/drawer_item.js
  app/components/sidebars/settings/index.js
  app/components/sidebars/settings/settings_sidebar.js
  app/components/sidebars/settings/status_label/index.js
  app/components/sidebars/settings/status_label/status_label.js
  app/components/sidebars/settings/user_info/index.js
  app/components/sidebars/settings/user_info/user_info.js
  app/components/swiper.js
  app/screens/channel/channel.js
  app/screens/code/code.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1794 Open YouTube videos at a specific time
  app/components/post_body_additional_content/post_body_additional_content.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1835 MM-10996 Fixed getting post thread after receiving posts over the websocket (1.9.2)
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1714 [MM-10285] Merge consecutive messages by same user
  app/components/post/index.js
  app/components/post/post.js
Labels: 1: Needs testing

#1456 Timezone feature
  app/actions/views/login.js
  app/components/formatted_time.js
  app/components/post_header/index.js
  app/components/post_header/post_header.js
  app/components/search_bar/search_bar.android.js
  app/screens/entry/entry.js
  app/screens/entry/index.js
  app/screens/index.js
  app/screens/settings/display_settings/display_settings.js
  app/screens/settings/display_settings/index.js
  app/screens/timezone/index.js
  app/screens/timezone/select_timezone/index.js
  app/screens/timezone/select_timezone/select_timezone.js
  app/screens/timezone/select_timezone/select_timezone_row.js
  app/screens/timezone/timezone.js
  app/screens/user_profile/index.js
  app/screens/user_profile/user_profile.js
  app/utils/timezone.js
  assets/base/i18n/en.json
  package-lock.json
  packager/modulePaths.js
Labels: 3: Ready to Merge

#1741 Upgrade to Gradle 3.0
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
Labels: 3: Ready to Merge

#1834 Fix jump to recent messages
  app/components/post_list/post_list.js
  app/screens/permalink/permalink.js
Labels: 3: Ready to Merge

#1836 Update RNFetchBlob to allow arabic chars
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1833 Set Android share extension default mime type for images and videos
  android/app/src/main/java/com/mattermost/share/ShareModule.java
Labels: 2: Dev Review

#1837 Fix uploading files from androids download provider
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Labels: 2: Dev Review

#1832 Fix iOS Share extension crash
  assets/base/i18n/en.json
  ios/MattermostShare/SessionManager.h
  ios/MattermostShare/SessionManager.m
  ios/MattermostShare/ShareViewController.m
  share_extension/ios/extension_post.js
Labels: 2: Dev Review

#1838 MM-11052 Cherry-pick RN fix for Android keyboard emoji autocomplete
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1839 Bump iOS build number to 116
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1840 Bump Android build number to 116
  android/app/build.gradle
Labels: 3: Ready to Merge

#1811 Fetch posts when receive push notifications as soon as possible
  app/actions/views/root.js
  app/utils/push_notifications.js
Labels: 3: Ready to Merge

#1818 MM-10970: Adds new FormattedMarkdownText to format translations using…
  app/components/formatted_markdown_text.js
Labels: 3: Ready to Merge

#1842 Fix android extension search
  share_extension/android/extension_channels/extension_channels.js
Labels: 2: Dev Review

#1843 Bump iOS build number to 117
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1844 Bump Android build number to 117
  android/app/build.gradle
Labels: 3: Ready to Merge

#1847 Merge release 1.9 into master
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  app/components/post_list/post_list.js
  app/screens/permalink/permalink.js
  assets/base/i18n/en.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostShare/SessionManager.h
  ios/MattermostShare/SessionManager.m
  ios/MattermostShare/ShareViewController.m
  ios/MattermostTests/Info.plist
  package-lock.json
  package.json
  share_extension/android/extension_channels/extension_channels.js
  share_extension/ios/extension_post.js
Labels: 3: Ready to Merge

#1848 Bump app version to 1.10.0
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1849 Fix bad merge
  ios/Mattermost.xcodeproj/project.pbxproj
Labels: 3: Ready to Merge

#1850 Bump iOS build number to 118
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#1854 Fix Main sidebar responder
  app/components/post_header/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/swiper.js
Labels: 3: Ready to Merge
