Repository mattermost/mattermost-mobile, pull requests merged in 2018-10, with the labels that each got.

#2189 [MM-12149] Add border to image of link preview and not allow such image width to exceed the view port width
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
  app/utils/images.js
  app/utils/images.test.js
Labels: 2: Dev Review

#2193 [MM-12390] Fix blank space on link preview when no site name
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
Labels: 3: Ready to Merge

#2171 Update unit test: use default theme, snapshot on wrapped elements and removal of unnecessary adapter
  app/components/announcement_banner/announcement_banner.test.js
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/index.test.js
  app/components/custom_list/user_list_row/user_list_test.test.js
  app/components/post_list/date_header/__snapshots__/date_header.test.js.snap
  app/components/post_list/date_header/date_header.test.js
  app/components/show_more_button/__snapshots__/show_more_button.test.js.snap
  app/components/show_more_button/show_more_button.test.js
  app/screens/error_teams_list/__snapshots__/error_teams_list.test.js.snap
  app/screens/error_teams_list/error_teams_list.test.js
  app/screens/menu_action_selector/__snapshots__/menu_action_selector.test.js.snap
  app/screens/menu_action_selector/menu_action_selector.test.js
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.test.js
  app/screens/select_team/__snapshots__/select_team.test.js.snap
  app/screens/select_team/select_team.test.js
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
  app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
  app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  app/screens/user_profile/user_profile.test.js
Labels: 3: Ready to Merge

#2196 [MM-12417] Fix empty reaction row when profile is missing
  app/utils/reaction.js
  app/utils/reaction.test.js
Labels: 2: Dev Review

#2205 MM-12347 Fix crash of app when accessing jumpTo
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
Labels: 3: Ready to Merge

#2203 MM-12424 Remove unused props from KeyboardLayout and simplify methods
  app/components/layout/keyboard_layout/index.js
  app/components/layout/keyboard_layout/keyboard_layout.js
  app/screens/channel/channel.js
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/thread/thread.js
Labels: 2: Dev Review

#2204 translations PR 20181001
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2209 Draft channel indicator to ignore message with whitespaces only
  app/components/sidebars/main/channels_list/channel_item/index.js
Labels: 3: Ready to Merge

#2210 image thumbnail not centered
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
Labels: 2: Dev Review

#2214 MM-12301 Add padding for error text on edit profile screen
  app/components/error_text/__snapshots__/error_text.test.js.snap
  app/components/error_text/error_text.js
  app/components/error_text/error_text.test.js
  app/components/error_text/index.js
  app/screens/edit_profile/edit_profile.js
Labels: 3: Ready to Merge

#2207 MM-12348 Persist interactive menu choices past channel switch and share with thread view
  app/actions/views/post.js
  app/components/message_attachments/action_menu/action_menu.js
  app/components/message_attachments/action_menu/index.js
  app/constants/view.js
  app/reducers/views/post.js
  app/screens/menu_action_selector/index.js
Labels: 2: Dev Review

#2208 Fastlane update to include new build process
  Makefile
  fastlane/Fastfile
  fastlane/Gemfile.lock
  fastlane/Pluginfile
Labels: 2: Dev Review

#2201 MM-12424 Properly set softInputMode on Android
  android/app/src/main/java/com/mattermost/rnbeta/NotificationsLifecycleFacade.java
Labels: 3: Ready to Merge

#2215 Fix search screen from braking and improved how to get more results
  app/constants/list.js
  app/screens/search/search.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2216 Bump app build number to 146
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2217 Fix fastlane android script
  fastlane/Fastfile
Labels: 3: Ready to Merge

#2220 Fix plist used for qa builds
  fastlane/plist.erb
Labels: 2: Dev Review

#2219 Revert "image thumbnail not centered (#2210)" and fix it properly
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
Labels: 3: Ready to Merge

#2221 [MM-12266] Fix issue that blocks adding test for thread screen and potentially to other components
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/screens/thread/__snapshots__/thread.test.js.snap
  app/screens/thread/thread.js
  app/screens/thread/thread.test.js
  package.json
  test/setup.js
Labels: 3: Ready to Merge, Awaiting Next Release

#2218 MM-12189 Set autocomplete max height based off available space
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/autocomplete.js
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/date_suggestion/date_suggestion.js
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  app/components/file_upload_preview/file_upload_preview.js
  app/components/file_upload_preview/index.js
  app/components/post_textbox/post_textbox.js
Labels: 3: Ready to Merge, CherryPickApproved

#2224 Reset isLoadingMoreTop flag when switching channels
  app/screens/channel/channel_post_list/channel_post_list.js
Labels: 3: Ready to Merge, CherryPickApproved

#2225 Fix Option to capture and share video
  Makefile
  app/components/attachment_button.js
  assets/base/i18n/en.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  native_modules/ImagePickerModule.java
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2228 [MM-12550] Fix hangup on permalink view when user deleted the post in it
  app/screens/permalink/__snapshots__/permalink.test.js.snap
  app/screens/permalink/permalink.js
  app/screens/permalink/permalink.test.js
  app/selectors/post_list.js
Labels: 3: Ready to Merge, CherryPickApproved

#2230 Fix gifs displaying as still images on Android
  android/app/build.gradle
Labels: 3: Ready to Merge, CherryPickApproved

#2233 [MM-12622] Add opacity of 0.3 to circle stroke of offline status
  app/components/user_status/__snapshots__/user_status.test.js.snap
  app/components/user_status/user_status.js
  app/components/user_status/user_status.test.js
Labels: 2: Dev Review, CherryPickApproved, CherryPickCandidate

#2232 [MM-12520] Add deactivated to separate row on user list and fix truncating user info
  app/components/custom_list/channel_list_row/channel_list_row.js
  app/components/custom_list/custom_list_row.js
  app/components/custom_list/option_list_row/option_list_row.js
  app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
  app/components/custom_list/user_list_row/user_list_row.js
  app/components/custom_section_list.js
  app/screens/more_channels/more_channels.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2222 MM-11477 Use custom thunk middleware to intercept leaked network errors
  app/fetch_preconfig.js
  app/store/index.js
  app/store/thunk.js
  app/utils/sentry/index.js
  app/utils/sentry/index.test.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2226 Fix KeyboardAvoidView for android
  app/components/emoji_picker/emoji_picker.js
  app/screens/mfa/mfa.js
  app/screens/select_server/select_server.js
Labels: 3: Ready to Merge, CherryPickApproved

#2229 Fix update keywords field on Android
  app/screens/settings/notification_settings_mentions/notification_settings_mention_base.js
  app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
Labels: 3: Ready to Merge, CherryPickApproved

#2231 Update Fastlane scripts
  Makefile
  fastlane/Fastfile
  fastlane/plist.erb
Labels: 2: Dev Review, CherryPickApproved

#2237 MM-12552: Adds parameter to include archived channel search results.
  app/screens/search/index.js
  app/screens/search/search.js
Labels: 3: Ready to Merge, CherryPickApproved

#2239 translations PR 20181009
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2240 Do not show the option to copy post if there is no text
  app/components/post_body/post_body.js
Labels: 3: Ready to Merge

#2245 Remove prepare-pr so it does not checkout the branch
  Makefile
Labels: 2: Dev Review, CherryPickApproved

#2246 MM-12560 Fix for infinite loading indicator for thread from search
  app/components/post_list/post_list_base.js
  app/screens/thread/__snapshots__/thread.test.js.snap
  app/screens/thread/thread.js
  app/screens/thread/thread.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2242 Fix iOS Share Extension crashes
  share_extension/ios/extension.js
Labels: 3: Ready to Merge

#2249 Bump app build number to 147
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2250 Change PR build filename to PR-{PR_ID}
  fastlane/Fastfile
  fastlane/plist.erb
Labels: 3: Ready to Merge, CherryPickApproved

#2200 MM-11589: Adds 'View Members' button to archived channels.
  app/screens/channel_info/channel_info.js
Labels: 2: Dev Review, 2: PM Review

#2244 Set Roboto as the default font family for Android
  android/app/src/main/assets/fonts/Roboto-Black.ttf
  android/app/src/main/assets/fonts/Roboto-BlackItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Bold.ttf
  android/app/src/main/assets/fonts/Roboto-BoldItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Italic.ttf
  android/app/src/main/assets/fonts/Roboto-Light.ttf
  android/app/src/main/assets/fonts/Roboto-LightItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Medium.ttf
  android/app/src/main/assets/fonts/Roboto-MediumItalic.ttf
  android/app/src/main/assets/fonts/Roboto-Regular.ttf
  android/app/src/main/assets/fonts/Roboto-Thin.ttf
  android/app/src/main/assets/fonts/Roboto-ThinItalic.ttf
  app/app.js
  assets/fonts/Roboto-Black.ttf
  assets/fonts/Roboto-BlackItalic.ttf
  assets/fonts/Roboto-Bold.ttf
  assets/fonts/Roboto-BoldItalic.ttf
  assets/fonts/Roboto-Italic.ttf
  assets/fonts/Roboto-Light.ttf
  assets/fonts/Roboto-LightItalic.ttf
  assets/fonts/Roboto-Medium.ttf
  assets/fonts/Roboto-MediumItalic.ttf
  assets/fonts/Roboto-Regular.ttf
  assets/fonts/Roboto-Thin.ttf
  assets/fonts/Roboto-ThinItalic.ttf
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
Labels: 3: Ready to Merge

#2254 Updates redux ref.
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2255 Updated redux ref.
  package-lock.json
  package.json
Labels: 2: Dev Review

#2248 Properly handle max file size
  app/components/attachment_button.js
  app/components/file_upload_preview/file_upload_preview.js
  app/components/post_textbox/index.js
  app/components/post_textbox/post_textbox.js
  assets/base/i18n/en.json
  share_extension/android/extension_post/extension_post.js
Labels: 3: Ready to Merge, CherryPickApproved

#2247 MM-11157 Switch ESLint to use eslint-config-mattermost
  .editorconfig
  .eslintrc.json
  app/actions/views/channel.js
  app/actions/views/command.js
  app/components/file_attachment_list/file_attachment_list.js
  app/fetch_preconfig.js
  app/screens/channel/channel.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_members/channel_members.js
  app/screens/menu_action_selector/menu_action_selector.js
  app/screens/more_channels/more_channels.js
  app/screens/more_dms/more_dms.js
  app/utils/general.js
  package-lock.json
  package.json
  share_extension/android/extension_post/extension_post.js
  share_extension/ios/extension_post.js
Labels: 3: Ready to Merge

#2253 MM-12491 Fix archive channels staying in LHS
  app/components/channel_icon.js
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
  app/components/sidebars/main/channels_list/channel_item/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2256 Set explicit white background to icon previews
  app/components/file_attachment_list/file_attachment_icon.js
Labels: 3: Ready to Merge, CherryPickApproved

#2257 MM-12652 Fix for android thread crash
  app/components/post_list/post_list.android.js
Labels: 3: Ready to Merge, Build Apps for PR, CherryPickApproved

#2258 Fix crash when loading the permalink view
  app/screens/permalink/permalink.js
Labels: 3: Ready to Merge, CherryPickApproved

#2259 Bump app build number to 148
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2241 Scroll search results to the top
  app/screens/search/search.js
Labels: 3: Ready to Merge

#2260 Fix uploading iOS videos
  app/components/attachment_button.js
Labels: 2: Dev Review, CherryPickApproved

#2264 Update build script to run npm ci instead of npm install
  Makefile
Labels: 3: Ready to Merge, CherryPickApproved

#2263 Fix for LHS populating you next to current user
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
  app/components/sidebars/main/channels_list/channel_item/index.js
  test/setup.js
Labels: 3: Ready to Merge, CherryPickApproved

#2265 MM-12198 React Native: Add "View Members" option in the channel menu for group messages
  app/screens/channel_info/channel_info.js
Labels: 3: Ready to Merge, Hacktoberfest

#2184 v1.13 Changelog
  CHANGELOG.md
Labels: 2: Dev Review

#2252 Fix Upload file size
  app/components/attachment_button.js
  ios/MattermostShare/ShareViewController.m
Labels: 3: Ready to Merge, CherryPickApproved

#2268 Fix backgroundColor when updating the theme in real time
  app/screens/channel/channel.js
Labels: 3: Ready to Merge, CherryPickApproved

#2270 Bump app version number to 1.14.0
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2272 Fix typo in build script
  Makefile
Labels: 3: Ready to Merge

#2273 Add ability to include custom headers with requests
  app/fetch_preconfig.js
  assets/base/config.json
Labels: 3: Ready to Merge

#2271 Hook the onMessage event only when needed
  app/screens/sso/sso.js
Labels: 3: Ready to Merge, Build Apps for PR, CherryPickApproved

#2275 Bump app build number to 150
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2277 MM-5957 Add mention highlighting on mobile
  app/components/markdown/index.js
  app/components/markdown/markdown.js
  app/components/markdown/transform.js
  app/components/markdown/transform.test.js
  app/utils/markdown.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2280 Refactor ChannelLink and add test into it
  app/components/channel_link/__snapshots__/channel_link.test.js.snap
  app/components/channel_link/channel_link.js
  app/components/channel_link/channel_link.test.js
  app/components/channel_link/channel_link_utils.js
  app/components/channel_link/channel_link_utils.test.js
Labels: 2: Dev Review

#2279 v1.13.1 CHANGELOG.md
  CHANGELOG.md
Labels: 3: Ready to Merge

#2281 Fix 'pre-buid' typo in build-android target
  Makefile
Labels: 3: Ready to Merge

#2282 Bump app build number to 152
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2284 translations PR 20181023
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2287 Capture video in high quality
  app/components/attachment_button.js
Labels: 3: Ready to Merge, CherryPickApproved

#2288 Retry fetching teams if no teams are found
  app/actions/views/select_team.js
  app/store/middleware.js
  app/utils/teams.js
  app/utils/teams.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2289 MM-12467 Made borders between autocomplete items consistent
  app/components/autocomplete/autocomplete_section_header.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
Labels: 3: Ready to Merge, CherryPickApproved

#2291 Add padding to tap effect for team list item
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
Labels: 3: Ready to Merge, CherryPickApproved

#2294 Bump app build number to 153
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2295 Fix team utils test eslint
  app/utils/teams.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2290 Allow channel drawer to close when showing the team list
  NOTICE.txt
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/settings/settings_sidebar.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2293 Show join teams option only if there are other joinable teams
  app/components/sidebars/main/teams_list/index.js
  app/components/sidebars/main/teams_list/teams_list.js
Labels: 3: Ready to Merge, CherryPickApproved
