Repository mattermost/mattermost-mobile, pull requests merged in 2018-11, with the labels that each got.

#2300 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#2285 Slide up panel for reaction list
  app/components/autocomplete/autocomplete.js
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/components/emoji_picker/emoji_picker.js
  app/components/offline_indicator/offline_indicator.js
  app/components/reactions/reactions.js
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/slide_up_panel/index.js
  app/components/slide_up_panel/slide_up_panel.js
  app/components/slide_up_panel/slide_up_panel_indicator.js
  app/components/start/empty_toolbar.js
  app/constants/device.js
  app/constants/index.js
  app/screens/channel/channel.js
  app/screens/channel/channel_nav_bar/channel_nav_bar.js
  app/screens/client_upgrade/client_upgrade.js
  app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_header_item.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_row.test.js.snap
  app/screens/reaction_list/reaction_header.js
  app/screens/reaction_list/reaction_header_item.js
  app/screens/reaction_list/reaction_list.js
  app/screens/reaction_list/reaction_list.test.js
  app/screens/reaction_list/reaction_row.js
  app/screens/search/search.js
  app/screens/select_server/select_server.js
  app/store/middleware.test.js
  app/utils/client_upgrade.js
  test/setup.js
Labels: 3: Ready to Merge, Build Apps for PR

#2309 MM-12841 Fix for unread muted channels sorting
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPickApproved, CherryPickDone

#2301 Allow user system CA's for Android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/xml/network_security_config.xml
Labels: 2: Dev Review, Build Apps for PR, CherryPickApproved

#2311 Bump app build number to 154
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2307 MM-12880 Properly link the next sibling following a combined text node
  app/components/markdown/transform.js
  app/components/markdown/transform.test.js
Labels: 3: Ready to Merge

#2314 Keep connection as active when retrying teams
  app/screens/error_teams_list/error_teams_list.js
Labels: 3: Ready to Merge, CherryPickCandidate

#2322 Bump app build number to 155
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2326 Fix Build on Jenkins
  fastlane/Fastfile
Labels: 3: Ready to Merge, CherryPickApproved, CherryPickDone

#2328 MM-11477 Wrap objects thrown by Client4 in a proper error type
  app/fetch_preconfig.js
  package-lock.json
  package.json
Labels: CherryPickApproved

#1928 Reorganize sidebar channel items via pref
  app/components/sidebars/main/channels_list/list/index.js
  app/components/sidebars/main/channels_list/list/list.js
  app/constants/view.js
  app/screens/create_channel/create_channel.js
  app/screens/options_modal/__snapshots__/option_modal_list.test.js.snap
  app/screens/options_modal/options_modal.js
  app/screens/options_modal/options_modal_list.android.js
  app/screens/options_modal/options_modal_list.ios.js
  assets/base/i18n/en.json
  package-lock.json
  package.json
  share_extension/ios/extension_channels.js
Labels: 3: Ready to Merge

#2323 Fix Android image preview
  app/components/file_attachment_list/file_attachment_list.js
Labels: CherryPickApproved

#2330 Fix prefetch
  app/fetch_preconfig.js
Labels: 2: Dev Review, CherryPickApproved

#2331 Fix when message have multiple actions
  app/actions/views/post.js
  app/components/message_attachments/action_menu/action_menu.js
  app/components/message_attachments/action_menu/index.js
  app/components/message_attachments/message_attachment.js
  app/reducers/views/post.js
Labels: 3: Ready to Merge, CherryPickApproved

#2333 Bump app build number to 156
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2335 MM-12952 Avoid iOS autocorrect from overriding autocomplete values
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
Labels: 2: Dev Review, Build Apps for PR, CherryPickApproved

#2338 Bump app build number to 157
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2332 Refactor CustomList to use Section and Flat Lists
  app/components/custom_flat_list.js
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/custom_list_row.js
  app/components/custom_list/index.js
  app/components/custom_list/index.test.js
  app/components/custom_list/option_list_row/option_list_row.js
  app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
  app/components/custom_list/user_list_row/user_list_row.js
  app/components/custom_section_list.js
  app/components/edit_channel_info/index.js
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_add_members/index.js
  app/screens/channel_members/channel_members.js
  app/screens/channel_members/index.js
  app/screens/create_channel/create_channel.js
  app/screens/menu_action_selector/__snapshots__/menu_action_selector.test.js.snap
  app/screens/menu_action_selector/index.js
  app/screens/menu_action_selector/menu_action_selector.js
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/index.js
  app/screens/more_channels/more_channels.js
  app/screens/more_channels/more_channels.test.js
  app/screens/more_dms/index.js
  app/screens/more_dms/more_dms.js
  app/utils/member_list.js
  assets/base/i18n/en.json
Labels: 2: Dev Review

#2337 MM-12923 Fix Downloading message on cancelling downloads
  app/screens/image_preview/__snapshots__/downloader_bottom_content.test.js.snap
  app/screens/image_preview/downloader.ios.js
  app/screens/image_preview/downloader_bottom_content.js
  app/screens/image_preview/downloader_bottom_content.test.js
Labels: 3: Ready to Merge

#2339 Fix regression when scrolling in search screen
  app/screens/search/search.js
Labels: 3: Ready to Merge, CherryPickApproved

#2234 [#MM-12410] Custom Terms of Service
  app/components/markdown/markdown.js
  app/screens/channel/channel.js
  app/screens/channel/index.js
  app/screens/error_teams_list/error_teams_list.js
  app/screens/index.js
  app/screens/permalink/permalink.js
  app/screens/select_team/select_team.js
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/terms_of_service/index.js
  app/screens/terms_of_service/terms_of_service.js
  app/screens/terms_of_service/terms_of_service.test.js
  app/screens/thread/thread.js
  app/screens/thread/thread.test.js
  app/screens/user_profile/user_profile.js
  assets/base/i18n/en.json
Labels: 2: Dev Review, Build Apps for PR

#2341 Bump app build number to 158
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2325 Update UX for post long press menu
  NOTICE.txt
  app/components/at_mention/at_mention.js
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_document.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/formatted_markdown_text.js
  app/components/markdown/markdown.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/message_attachments/index.js
  app/components/message_attachments/message_attachment.js
  app/components/options_context/index.js
  app/components/options_context/options_context.android.js
  app/components/options_context/options_context.ios.js
  app/components/post/index.js
  app/components/post/post.js
  app/components/post_add_channel_member/post_add_channel_member.js
  app/components/post_body/index.js
  app/components/post_body/post_body.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/reactions/reactions.js
  app/components/slide_up_panel/slide_up_panel.js
  app/screens/index.js
  app/screens/long_post/long_post.js
  app/screens/post_options/index.js
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
  app/screens/reaction_list/reaction_list.js
  app/utils/bottom_sheet/bottom_sheet.android.js
  app/utils/bottom_sheet/bottom_sheet.ios.js
  app/utils/bottom_sheet/index.js
  assets/base/i18n/en.json
  assets/base/images/post_menu/copy.png
  assets/base/images/post_menu/copy@2x.png
  assets/base/images/post_menu/copy@3x.png
  assets/base/images/post_menu/edit.png
  assets/base/images/post_menu/edit@2x.png
  assets/base/images/post_menu/edit@3x.png
  assets/base/images/post_menu/emoji.png
  assets/base/images/post_menu/emoji@2x.png
  assets/base/images/post_menu/emoji@3x.png
  assets/base/images/post_menu/flag.png
  assets/base/images/post_menu/flag@2x.png
  assets/base/images/post_menu/flag@3x.png
  assets/base/images/post_menu/link.png
  assets/base/images/post_menu/link@2x.png
  assets/base/images/post_menu/link@3x.png
  assets/base/images/post_menu/pin.png
  assets/base/images/post_menu/pin@2x.png
  assets/base/images/post_menu/pin@3x.png
  assets/base/images/post_menu/trash.png
  assets/base/images/post_menu/trash@2x.png
  assets/base/images/post_menu/trash@3x.png
  ios/Mattermost.xcodeproj/project.pbxproj
  package-lock.json
  package.json
Labels: 3: Ready to Merge, Build Apps for PR

#2310 v1.14 Changelog
  CHANGELOG.md
Labels: 3: Ready to Merge

#2345 Fix crash when deleting a post
  app/screens/channel/index.js
  app/screens/post_options/index.js
Labels: 3: Ready to Merge

#2316 Update dependencies
  android/app/build.gradle
  android/app/src/main/assets/fonts/AntDesign.ttf
  android/app/src/main/assets/fonts/EvilIcons.ttf
  android/app/src/main/assets/fonts/Feather.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  app/components/announcement_banner/__snapshots__/announcement_banner.test.js.snap
  app/components/channel_link/__snapshots__/channel_link.test.js.snap
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
  app/components/error_text/__snapshots__/error_text.test.js.snap
  app/components/markdown/hashtag/__snapshots__/hashtag.test.js.snap
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_list/date_header/__snapshots__/date_header.test.js.snap
  app/components/show_more_button/__snapshots__/show_more_button.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/screens/error_teams_list/__snapshots__/error_teams_list.test.js.snap
  app/screens/forgot_password/__snapshots__/forgot_password.test.js.snap
  app/screens/image_preview/__snapshots__/downloader_bottom_content.test.js.snap
  app/screens/image_preview/__snapshots__/image_preview.test.js.snap
  app/screens/menu_action_selector/__snapshots__/menu_action_selector.test.js.snap
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/options_modal/__snapshots__/option_modal_list.test.js.snap
  app/screens/permalink/__snapshots__/permalink.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_header_item.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_row.test.js.snap
  app/screens/select_team/__snapshots__/select_team.test.js.snap
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  fastlane/Fastfile
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2354 Bump version to 1.15.0 and build number to 159
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2343 Fix comma splice typo
  app/components/post_textbox/post_textbox.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge

#2188 Instantly show autocomplete channels
  app/components/autocomplete/autocomplete_section_header.js
  app/components/autocomplete/channel_mention/channel_mention.js
Labels: 2: Dev Review, Build Apps for PR

#2321 Android/iOS leave notifications until channel is read
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationDrawer.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
  app/components/network_indicator/index.js
  app/components/network_indicator/network_indicator.js
  app/push_notifications/push_notifications.android.js
  app/push_notifications/push_notifications.ios.js
  app/screens/channel/channel.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
  ios/Mattermost/AppDelegate.m
  ios/Mattermost/Info.plist
Labels: Build Apps for PR

#2358 MM-13020 Update mattermost-redux
  package-lock.json
  package.json
Labels: 2: Dev Review

#2360 Update fastlane to 2.108.0
  fastlane/Gemfile.lock
Labels: 3: Ready to Merge

#2359 MM-12755 Add reply mention highlight for replyBar
  app/components/post/index.js
  app/components/post/post.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2361 Refresh indicator fix
  app/components/post_list/post_list.ios.js
  app/components/post_list/post_list_base.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel/channel_post_list/index.js
Labels: 2: Dev Review

#2348 Properly scroll to search results
  app/screens/search/__snapshots__/modifier.test.js.snap
  app/screens/search/__snapshots__/recent_item.test.js.snap
  app/screens/search/modifier.js
  app/screens/search/modifier.test.js
  app/screens/search/recent_item.js
  app/screens/search/recent_item.test.js
  app/screens/search/search.js
Labels: 3: Ready to Merge

#2362 On fresh install the share extension will not properly show available channels
  share_extension/android/extension.js
  share_extension/android/index.js
  share_extension/android/selectors/index.js
Labels: 3: Ready to Merge

#2363 Fixing failed tests
  app/screens/search/__snapshots__/modifier.test.js.snap
  app/screens/search/__snapshots__/recent_item.test.js.snap
Labels: 3: Ready to Merge

#2366 Set the current user status as offline when the app loses connection
  app/actions/views/user.js
  app/actions/views/user.test.js
  app/components/network_indicator/index.js
  app/components/network_indicator/network_indicator.js
Labels: 3: Ready to Merge

#2356 [MM-12353] Add feature to render jumbo emoji and unwrapped Emoji component with Text when rendering message containing emoji/s only
  app/components/markdown/markdown_emoji/__snapshots__/markdown_emoji.test.js.snap
  app/components/markdown/markdown_emoji/index.js
  app/components/markdown/markdown_emoji/markdown_emoji.js
  app/components/markdown/markdown_emoji/markdown_emoji.test.js
  app/components/post_body/index.js
  app/components/post_body/post_body.js
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: 2: Dev Review, Build Apps for PR

#2304 Use post metadata to prevent scroll pop
  app/components/channel_intro/channel_intro.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/load_more_posts/load_more_posts.js
  app/components/markdown/markdown.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/message_attachments/attachement_pretext.js
  app/components/message_attachments/attachment_actions.js
  app/components/message_attachments/attachment_author.js
  app/components/message_attachments/attachment_fields.js
  app/components/message_attachments/attachment_image.js
  app/components/message_attachments/attachment_text.js
  app/components/message_attachments/attachment_thumbnail.js
  app/components/message_attachments/attachment_title.js
  app/components/message_attachments/index.js
  app/components/message_attachments/message_attachment.js
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
  app/components/post_body/index.js
  app/components/post_body/post_body.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/reactions/reactions.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, Awaiting PR, Build Apps for PR

#2369 Keep postlist scroll position on iOS and fix opengraph
  app/components/post_body_additional_content/index.js
  app/components/post_list/post_list.ios.js
Labels: 3: Ready to Merge

#2364 Add pinned post support
  app/components/no_results.js
  app/components/post_list/post_list_base.js
  app/components/slide_up_panel/slide_up_panel.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info_row.js
  app/screens/index.js
  app/screens/pinned_posts/index.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/post_options/index.js
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
  assets/base/i18n/en.json
  assets/base/images/channel_info/pin.png
  assets/base/images/channel_info/pin@2x.png
  assets/base/images/channel_info/pin@3x.png
  assets/base/images/no_results/pin.png
  assets/base/images/no_results/pin@2x.png
  assets/base/images/no_results/pin@3x.png
Labels: 3: Ready to Merge

#2373 Fix error text when intl object is not provided
  app/components/error_text/error_text.js
Labels: 3: Ready to Merge

#2372 Disable segment for dev env
  app/mattermost.js
  assets/base/config.json
Labels: 2: Dev Review

#2353 MM-12845 Add widgets and interactive dialogs
  app/actions/views/command.js
  app/actions/views/post.js
  app/components/autocomplete_selector/autocomplete_selector.js
  app/components/autocomplete_selector/index.js
  app/components/interactive_dialog_controller/index.js
  app/components/interactive_dialog_controller/interactive_dialog_controller.js
  app/components/message_attachments/action_menu/action_menu.js
  app/components/message_attachments/action_menu/index.js
  app/components/message_attachments/attachment_actions.js
  app/components/widgets/settings/text_setting.js
  app/components/widgets/settings/text_setting.test.js
  app/screens/channel/channel.js
  app/screens/edit_profile/edit_profile.js
  app/screens/edit_profile/edit_profile_item.js
  app/screens/index.js
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/index.js
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/interactive_dialog/interactive_dialog.test.js
  app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
  app/screens/selector_screen/index.js
  app/screens/selector_screen/selector_screen.js
  app/screens/selector_screen/selector_screen.test.js
  package-lock.json
Labels: 3: Ready to Merge

#2371 [MM-13074] Render text when named emoji does not match with the existing custom emojis
  app/components/emoji/index.js
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: 3: Ready to Merge

#2320 Theme selection screen
  app/screens/index.js
  app/screens/settings/display_settings/__snapshots__/display_settings.test.js.snap
  app/screens/settings/display_settings/display_settings.js
  app/screens/settings/display_settings/display_settings.test.js
  app/screens/settings/display_settings/index.js
  app/screens/theme/__snapshots__/theme.test.js.snap
  app/screens/theme/index.js
  app/screens/theme/theme.js
  app/screens/theme/theme.test.js
  app/selectors/theme.js
  app/utils/theme.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge

#2375 Disconnect the websocket on logout and connect appropiately
  app/components/network_indicator/network_indicator.js
  app/mattermost.js
Labels: 3: Ready to Merge

#2376 Add a threshold of 60px from the bottom to show new messages
  app/components/post_list/post_list.ios.js
Labels: CherryPickApproved

#2378 Count the posts received after combining join/leave
  app/actions/views/channel.js
Labels: CherryPickApproved

#2382 Fix Post and network indicator Layouts
  app/components/emoji/emoji.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/network_indicator/network_indicator.js
  app/components/post/post.js
  app/components/post_body/post_body.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/reactions/reactions.js
Labels: 3: Ready to Merge, CherryPickApproved

#2383 Fetch team channels on extension init
  share_extension/android/actions/index.js
  share_extension/android/extension_post/extension_post.js
  share_extension/android/extension_post/index.js
  share_extension/android/index.js
Labels: 2: Dev Review, CherryPickApproved

#2385 Fix post menu touchables
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
Labels: CherryPickApproved

#2389 MM-12960: Only back to previous channel if is not archived
  app/actions/views/channel.js
Labels: 2: Dev Review, CherryPickApproved

#2387 Fixing no parseable (by the i18n extractor) optional chaining construction
  app/components/post_body_additional_content/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2388 MM-13041: Not show direct channels without display name
  app/components/autocomplete/channel_mention_item/channel_mention_item.js
Labels: CherryPickApproved

#2390 Android: Fix crash when attaching files from the downloads folder
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Labels: 3: Ready to Merge, Build Apps for PR, CherryPickApproved

#2391 translations PR 20181128 (adds Ukrainian)
  app/i18n/index.js
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2392 Add Ukrainian to Mattermost
  app/i18n/index.js
  assets/base/i18n/uk.json
Labels: 3: Ready to Merge

#2393 Fix fetching more channels to join
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.js
Labels: CherryPickApproved

#2395 Fixed empty message attachment text
  app/components/message_attachments/message_attachment.js
Labels: 3: Ready to Merge, CherryPickApproved

#2396 Bump app build number to 160
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2408 More fixes to the post layout
  app/components/message_attachments/message_attachment.js
  app/components/post_body/post_body.js
Labels: CherryPickApproved

#2397 File image attachments sometimes do not open the image preview
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_list.js
Labels: 3: Ready to Merge, CherryPickApproved

#2410 Update mattermost-redux sidebar sorting and WS fixes
  package-lock.json
  package.json
Labels: 3: Ready to Merge
