Repository mattermost/mattermost-mobile, pull requests merged in 2018-05, with the labels that each got.

#1634 Whitelabel for Icons and Splash Screen
  assets/base/release/icons/ios/20@2x-1.png
  assets/base/release/icons/ios/29@2x-1.png
  assets/base/release/icons/ios/40@2x-1.png
  assets/base/release/icons/ios/Icon-60.png
  assets/base/release/icons/ios/Icon-72.png
  assets/base/release/icons/ios/Icon-72@2x.png
  assets/base/release/icons/ios/Icon-Small-50.png
  assets/base/release/icons/ios/Icon-Small-50@2x.png
  assets/base/release/icons/ios/Icon.png
  assets/base/release/icons/ios/Icon@2x.png
  assets/base/release/splash_screen/android/drawable-hdpi/splash.png
  assets/base/release/splash_screen/android/drawable-mdpi/splash.png
  assets/base/release/splash_screen/android/drawable-xhdpi/splash.png
  assets/base/release/splash_screen/android/drawable-xxhdpi/splash.png
  assets/base/release/splash_screen/android/drawable-xxxhdpi/splash.png
  assets/base/release/splash_screen/android/layout/launch_screen.xml
  assets/base/release/splash_screen/ios/LaunchScreen.xib
  assets/base/release/splash_screen/ios/splash.png
  fastlane/Fastfile
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/20@2x-1.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/29@2x-1.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/40@2x-1.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-60.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-72.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-72@2x.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-Small-50.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-Small-50@2x.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon.png
  ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon@2x.png
Labels: 2: Dev Review

#1650 Fixed Markdown links when SiteURL isn't configured
  app/components/markdown/markdown_link/markdown_link.js
Labels: 3: Ready to Merge

#1651 MM-10360 Render OpenGraph previews for pages with an empty description
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1609 Add animation to skeleton screen
  app/components/channel_loader/channel_loader.js
Labels: 2: Dev Review

#1655 MM-10360 Only show link previews if they have a url defined
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
Labels: 3: Ready to Merge

#1656 Ignore fastlane/.env file
  .gitignore
Labels: 3: Ready to Merge

#1660 Fixed empty OpenGraph previews from trying to render an empty string
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
Labels: 3: Ready to Merge

#1669 Cache team icon and set background to always be white
  app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js
  app/components/team_icon/team_icon.js
  share_extension/android/extension_teams/team_item/team_item.js
  share_extension/ios/extension_team_item.js
Labels: 3: Ready to Merge

#1670 Prevent duplicate flagged posts
  app/screens/flagged_posts/flagged_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/search/search.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1662 Ability to upload other file types
  Makefile
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  android/settings.gradle
  app/components/attachment_button.js
  assets/base/i18n/en.json
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost.entitlements
  native_modules/ImagePickerModule.java
  native_modules/RNDocumentPicker.m
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1663 Update Fastlane and include iCloud container for iOS
  fastlane/Fastfile
  fastlane/Gemfile.lock
  fastlane/actions/mattermost.rb
Labels: 2: Dev Review

#1676 Include "id" to data for UserTypes actions - RECEIVED_PROFILE_IN_CHANNEL
  app/actions/views/channel.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1677 Fix image preview zoom & scrolling jumps
  package-lock.json
  package.json
Labels: 2: Dev Review

#1681 MM-10617 Fixed checking if a link is an image
  app/utils/url.js
  app/utils/url.test.js
Labels: 3: Ready to Merge

#1679 Fix JS error on announcement banner when no license is set
  app/components/announcement_banner/__snapshots__/announcement_banner.test.js.snap
  app/components/announcement_banner/announcement_banner.js
  app/components/announcement_banner/announcement_banner.test.js
  app/components/announcement_banner/index.js
Labels: 2: Dev Review

#1684 Updated mattermost-redux which fixes combined post ignoring other post types
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1685 Update CONTRIBUTING.md with a link to pre-release
  CONTRIBUTING.md
Labels: 2: Dev Review

#1689 Fix issue where auto closed DMs would not show again
  app/actions/views/channel.js
  app/actions/views/more_dms.js
Labels: 2: Dev Review

#1694 Update fastlane
  fastlane/Gemfile.lock
  package-lock.json
Labels: 3: Ready to Merge

#1697 Update Android JavaScriptCore in release mode (perf part 1)
  android/app/build.gradle
  android/build.gradle
  app/mattermost.js
  package-lock.json
  package.json
Labels: 2: Dev Review

#1698 Remove orientation dependency
  Makefile
  NOTICE.txt
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/actions/device/index.js
  app/components/safe_area_view/safe_area_view.ios.js
  app/mattermost.js
  app/screens/login/login.js
  app/screens/login_options/login_options.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.m
  package-lock.json
  package.json
Labels: 2: Dev Review

#1699 Bump app version to 1.9.0
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 2: Dev Review

#1701 Remove test code from MattermostManaged
  app/mattermost_managed/mattermost-managed.ios.js
Labels: 2: Dev Review

#1682 [MM-10594] Add feature to combine join/add/leave/remove to channel/team system messages
  app/components/combined_system_message/__snapshots__/combined_system_message.test.js.snap
  app/components/combined_system_message/__snapshots__/last_users.test.js.snap
  app/components/combined_system_message/combined_system_message.js
  app/components/combined_system_message/combined_system_message.test.js
  app/components/combined_system_message/index.js
  app/components/combined_system_message/last_users.js
  app/components/combined_system_message/last_users.test.js
  app/components/post_body/index.js
  app/components/post_body/post_body.js
  assets/base/i18n/en.json
  test/intl-test-helper.js
Labels: 2: Dev Review

#1666 [MM-10394] Make hidden town-square (on read-only) be available to view by joining in more channels
  app/components/channel_drawer/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/channel_drawer/channels_list/channel_item/channel_item.js
  app/components/channel_drawer/channels_list/channel_item/channel_item.test.js
  app/components/channel_drawer/channels_list/channel_item/index.js
  app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.test.js
Labels: 2: Dev Review, Awaiting PR

#1704 Update redux to latest 1cc6009
  package-lock.json
  package.json
Labels: 2: Dev Review

#1706 [MM-10645] Remove desktop duration on notify props
  app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
Labels: 3: Ready to Merge

#1708 Fix bundling failed with "mime-db" error
  package-lock.json
Labels: 2: Dev Review

#1707 Entry screen and Channel Loader improvements (perf part 4)
  app/components/channel_loader/channel_loader.js
  app/components/channel_loader/index.js
  app/screens/channel/channel.js
  app/screens/channel/index.js
  app/screens/entry/entry.js
  app/screens/index.js
  app/utils/wrap_context_provider.js
  package-lock.json
  package.json
  packager/moduleNames.js
  packager/modulePaths.js
Labels: 3: Ready to Merge
