Repository mattermost/mattermost-mobile, pull requests merged in 2019-09, with the labels that each got.

#3220 MM-18179 Clear cache and cookies for SSO login
  app/components/failed_network_action/index.js
  native_modules/RNCookieManagerIOS.m
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3218 [MM-18172] Added state for message length such that alerts for long length aren't fired too often
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
Labels: 3: Reviews Complete, CherryPick/Approved, Tests/Done

#3206 MM-17966 - Updating background for archive wrapper
  app/components/post_textbox/post_textbox_base.js
Labels: 3: Reviews Complete

#3214 [MM-18349] Post menu delay animation speed and haptic feedback
  Makefile
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/components/post/post.js
  app/components/reactions/reaction.js
  app/components/slide_up_panel/slide_up_panel.js
  app/utils/general.js
  ios/Mattermost.xcodeproj/project.pbxproj
  native_modules/react-native-haptic-feedback+1.8.2.patch
  package-lock.json
  package.json
  test/setup.js
Labels: 3: Reviews Complete

#3221 MM-18223 Fix channel actions on combined sidebar
  app/components/sidebars/main/channels_list/list/index.js
  app/components/sidebars/main/channels_list/list/list.js
  app/screens/options_modal/options_modal_list.android.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3231 [MM-18178] Removing caching of failed image loading attempts
  app/utils/image_cache_manager.js
Labels: CherryPick/Approved

#3234 Automated cherry pick of #3231
  app/utils/image_cache_manager.js
Labels: AutomatedCherryPick

#3236 Automated cherry pick of #3219
  app/components/combined_system_message/combined_system_message.js
Labels: AutomatedCherryPick

#3233 Update webview library to remove deprecated API
  app/screens/sso/sso.js
  ios/Mattermost.xcodeproj/project.pbxproj
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3237 Automated cherry pick of #3233
  app/screens/sso/sso.js
  ios/Mattermost.xcodeproj/project.pbxproj
  package-lock.json
  package.json
Labels: AutomatedCherryPick

#2904 MM-12879 Fix iOS photo/camera permission denied prompt
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/components/attachment_button/attachment_button.js
  app/components/attachment_button/attachment_button.test.js
  app/screens/edit_profile/edit_profile.js
  app/screens/image_preview/image_preview.js
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
  package-lock.json
  package.json
  test/setup.js
Labels: 3: Reviews Complete

#3243 [MM-18182] Upgrade redux in mobile
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 2: Dev Review

#3228 GH-11994: Add support for footer and footer_icon in attachments
  app/components/message_attachments/__snapshots__/attachment_footer.test.js.snap
  app/components/message_attachments/attachment_footer.js
  app/components/message_attachments/attachment_footer.test.js
  app/components/message_attachments/message_attachment.js
  app/constants/attachment.js
Labels: 3: Reviews Complete

#3242 MM-18465 Add proper flags when opening settings
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/init/emm_provider.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3247 Automated cherry pick of #3242
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/init/emm_provider.js
Labels: AutomatedCherryPick

#3250 MM-18353 Do not update the theme when resetting the cache
  app/screens/settings/advanced_settings/advanced_settings.js
Labels: 2: Dev Review

#3202 [MM-17068] Add set post as unread option to menu
  app/reducers/views/channel.js
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  app/screens/post_options/index.js
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
  app/screens/post_options/post_options.test.js
  assets/base/i18n/en.json
  assets/base/images/post_menu/bookmark.png
  assets/base/images/post_menu/bookmark@2x.png
  assets/base/images/post_menu/bookmark@3x.png
  package-lock.json
  package.json
  packager/moduleNames.js
Labels: 3: Reviews Complete

#3245 MM-18466 Change recent date separators to yesterday/today
  app/components/post_list/date_header/__snapshots__/date_header.test.js.snap
  app/components/post_list/date_header/date_header.js
  app/components/recent_date.js
  app/components/recent_date.test.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#3134 Migrate Channel post List realm
  app/actions/views/channel.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/main/teams_list/index.js
  app/components/sidebars/main/teams_list/teams_list.js
  app/constants/general.js
  app/constants/index.js
  app/constants/posts.js
  app/realm/action_types/post.js
  app/realm/action_types/team.js
  app/realm/actions/channel.js
  app/realm/actions/post.js
  app/realm/actions/team.js
  app/realm/selectors/helper.js
  app/realm/selectors/post.js
  app/realm/writers/channel.js
  app/realm/writers/post.js
  app/realm/writers/team.js
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_nav_bar/__snapshots__/channel_nav_bar.test.js.snap
  app/screens/channel/channel_nav_bar/channel_nav_bar.js
  app/screens/channel/channel_nav_bar/channel_nav_bar.test.js
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/channel/channel_nav_bar/channel_title/index.js
  app/screens/channel/channel_nav_bar/index.js
  app/screens/channel/channel_nav_bar/settings_drawer_button.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel/channel_post_list/index.js
  app/screens/channel/index.js
  app/store/ephemeral_store.js
  app/utils/channels.js
  app/utils/post.js
  app/utils/timezone.js
  app/utils/users.js
Labels: 3: Reviews Complete

#3223 [MM-18362] Sidebar improvements
  android/app/src/main/assets/fonts/Mattermost-Regular.otf
  app/components/__snapshots__/badge.test.js.snap
  app/components/badge.js
  app/components/badge.test.js
  app/components/bot_tag.js
  app/components/channel_icon.js
  app/components/fade.js
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channels_list.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/channels_list/switch_teams_button/index.js
  app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
  app/components/sidebars/main/channels_list/unread_indicator/index.js
  app/components/sidebars/main/drawer_swipper/drawer_swiper.js
  app/components/sidebars/main/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
  app/components/swiper.js
  app/components/team_icon/index.js
  app/components/team_icon/team_icon.js
  app/components/user_status/__snapshots__/user_status.test.js.snap
  app/components/user_status/user_status.js
  app/components/vector_icon.js
  app/constants/list.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.android.js
  app/screens/thread/thread.ios.js
  assets/base/images/status/archive_avatar.png
  assets/base/images/status/away.png
  assets/base/images/status/away_avatar.png
  assets/base/images/status/dnd.png
  assets/base/images/status/dnd_avatar.png
  assets/base/images/status/offline.png
  assets/base/images/status/offline_avatar.png
  assets/base/images/status/online.png
  assets/base/images/status/online_avatar.png
  assets/base/mattermost-fonts.json
  assets/fonts/Mattermost-Regular.otf
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
Labels: 3: Reviews Complete, Build Apps for PR

#3222 MM-15219 Added support for introduction text in interactive dialogs
  app/components/interactive_dialog_controller/interactive_dialog_controller.test.js
  app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
  app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap
  app/screens/interactive_dialog/dialog_introduction_text.js
  app/screens/interactive_dialog/dialog_introduction_text.test.js
  app/screens/interactive_dialog/index.js
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/interactive_dialog/interactive_dialog.test.js
Labels: 2: Dev Review

#3149 v1.23 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#3211 Update session expiry push notification text
  app/actions/views/login.js
  app/utils/push_notifications.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#3262 MM-18588 Expand text input area in Android Share extension to use available space
  share_extension/android/extension_post/extension_post.js
Labels: 3: Reviews Complete

#3251 MM-17953 Do not show deactivated users in autocomplete
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
  app/components/sidebars/main/channels_list/channel_item/index.js
  app/selectors/autocomplete.js
Labels: 3: Reviews Complete

#3246 MM-18335 Keep the icon badge in sync
  app/push_notifications/push_notifications.android.js
  app/push_notifications/push_notifications.ios.js
  app/push_notifications/push_notifications.ios.test.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.test.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/index.js
Labels: 3: Reviews Complete

#3084 MM-9599 Paste image from clipboard
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/RNEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditText.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableImageFromUrl.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputManager.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputPackage.java
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.test.js
  app/components/pasteable_text_input/__snapshots__/custom_text_input.test.js.snap
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/custom_text_input.js
  app/components/pasteable_text_input/custom_text_input.test.js
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
  app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
  assets/base/i18n/en.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost+RCTUITextView.m
  ios/Mattermost/NSData+MimeType.h
  ios/Mattermost/NSData+MimeType.m
  ios/Mattermost/OnPasteEventManager.h
  ios/Mattermost/OnPasteEventManager.m
  ios/Mattermost/UIPasteboard+GetImageInfo.h
  ios/Mattermost/UIPasteboard+GetImageInfo.m
Labels: 3: Reviews Complete

#3239 MM-14273 Add boolean element support to interactive dialog
  app/components/widgets/settings/bool_setting.js
  app/components/widgets/settings/bool_setting.test.js
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_element.test.js
  app/screens/interactive_dialog/interactive_dialog.js
Labels: 3: Reviews Complete

#3266 [MM-18550] Force drawer to open to channel menu when new teams are added
  app/components/sidebars/main/drawer_swipper/drawer_swiper.js
  app/components/sidebars/main/main_sidebar.js
  app/components/swiper.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3212 Adds support for 'radio' type in interactive dialogs
  app/components/widgets/settings/__snapshots__/radio_setting.test.js.snap
  app/components/widgets/settings/radio_setting.js
  app/components/widgets/settings/radio_setting.test.js
  app/components/widgets/settings/text_setting.js
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_element.test.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3269 Automated cherry pick of #3266
  app/components/sidebars/main/drawer_swipper/drawer_swiper.js
  app/components/sidebars/main/main_sidebar.js
  app/components/swiper.js
Labels: AutomatedCherryPick

#3271 Automated cherry pick of #3268
  app/init/global_event_handler.js
  app/init/global_event_handler.test.js
  test/setup.js
Labels: AutomatedCherryPick

#3273 Automated cherry pick of #3270
  assets/base/i18n/en.json
Labels: AutomatedCherryPick

#3275 Updated Info.plist with new bluetooth usage description key
  ios/Mattermost/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3276 Automated cherry pick of #3275
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick

#3277 Bump app build number to 232
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3278 Automated cherry pick of #3277
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick

#3284 Revert "[MM-17001] Call scrollToIndex only when ref is set and index is in range"
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
Labels: 3: Reviews Complete

#3286 Automated cherry pick of #3285
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3296 MM-18752 Rename constant to handle iPhone X and new iPhone 11 insets
  app/components/autocomplete/autocomplete.js
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/components/emoji_picker/emoji_picker.ios.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/network_indicator/network_indicator.js
  app/components/safe_area_view/iphone_x_spacing/index.js
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/main/teams_list/teams_list.js
  app/components/slide_up_panel/slide_up_panel.js
  app/components/start/empty_toolbar.js
  app/components/swiper.js
  app/constants/device.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_nav_bar/channel_nav_bar.js
  app/screens/image_preview/image_preview.js
  app/screens/search/search.js
  package.json
Labels: CherryPick/Approved

#3300 Automated cherry pick of #3296
  app/components/autocomplete/autocomplete.js
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/components/emoji_picker/emoji_picker.ios.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/network_indicator/network_indicator.js
  app/components/safe_area_view/iphone_x_spacing/index.js
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/main/teams_list/teams_list.js
  app/components/slide_up_panel/slide_up_panel.js
  app/components/start/empty_toolbar.js
  app/components/swiper.js
  app/constants/device.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_nav_bar/channel_nav_bar.js
  app/screens/image_preview/image_preview.js
  app/screens/search/search.js
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3230 GH-11952 Adding option to convert public channel to private
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/index.js
  app/utils/general.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#3297 MM-18758 Fix channel info row to be toggleable or with an chevron
  app/screens/channel_info/channel_info_row.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3303 Automated cherry pick of #3297
  app/screens/channel_info/channel_info_row.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3307 Bump app build number to 233
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3308 Automated cherry pick of #3307
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3304 Automated cherry pick of #3289
  app/components/post_body/index.js
  app/components/post_body/index.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3291 [MM-18662] Trimming display_name in delete/leave channel alerts
  app/screens/channel_info/channel_info.js
Labels: 3: Reviews Complete

#3312 add circleci
  .circleci/config.yml
Labels: 3: Reviews Complete

#3314 Automated cherry pick of #3312
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3315 Automated cherry pick of #3312
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3316 Automated cherry pick of #3309
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3318 Automated cherry pick of #3310
  app/i18n/index.js
  app/init/global_event_handler.js
  app/init/global_event_handler.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3301 translations PR 20190923
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete

#3302 MM-18792 Fix paste files with multiple instances of PostTextbox
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/thread/thread.android.js
  app/screens/thread/thread.ios.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3320 Automated cherry pick of #3302
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/thread/thread.android.js
  app/screens/thread/thread.ios.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3260 MM-18453 Use native emojis
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/emoji/emoji.js
  app/components/emoji/index.js
  app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
  app/components/emoji_picker/emoji_picker.android.js
  app/components/emoji_picker/emoji_picker.ios.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/emoji_picker/emoji_picker_row.js
  app/components/emoji_picker/index.js
  app/components/reactions/reaction.js
  app/utils/emoji_utils.js
  app/utils/emojis.js
Labels: 3: Reviews Complete

#3317 MM-18658 Edit Channel MaxLength
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/edit_channel_info/edit_channel_info.js
  app/constants/view.js
Labels: 3: Reviews Complete

#3321 MM-18542 Fix file attachment scroll on tablets, MM-18732 Slow scroll …
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/file_attachment_list/index.js
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/__snapshots__/main_sidebar.test.js.snap
  app/components/sidebars/main/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/settings/index.js
  app/components/sidebars/settings/settings_sidebar.js
  package-lock.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3323 Automated cherry pick of #3321
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/file_attachment_list/index.js
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/__snapshots__/main_sidebar.test.js.snap
  app/components/sidebars/main/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/settings/index.js
  app/components/sidebars/settings/settings_sidebar.js
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3322 MM-18740 Sync app badge number when opening a push notification
  app/push_notifications/push_notifications.ios.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/index.js
  app/selectors/views.js
  app/utils/push_notifications.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3288 MM-16399 Clear current channel when leaving a team
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3326 Bump app version number to 1.23.1
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 2: Dev Review

#3327 Bump app build number to 234
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: CherryPick/Approved

#3324 Automated cherry pick of #3322
  app/push_notifications/push_notifications.ios.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/index.js
  app/selectors/views.js
  app/utils/push_notifications.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3319 MM-18236 Prevent the post menu from triggering when using the back gesture
  app/components/__snapshots__/send_button.test.js.snap
  app/components/attachment_button/__snapshots__/attachment_button.test.js.snap
  app/components/attachment_button/attachment_button.js
  app/components/autocomplete/at_mention_item/at_mention_item.js
  app/components/autocomplete/channel_mention_item/channel_mention_item.js
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
  app/components/autocomplete/special_mention_item.js
  app/components/autocomplete_selector/autocomplete_selector.js
  app/components/button.js
  app/components/channel_intro/channel_intro.js
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_document/file_attachment_document.js
  app/components/file_upload_preview/file_upload_remove.js
  app/components/file_upload_preview/file_upload_retry.js
  app/components/load_more_posts/load_more_posts.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_table/markdown_table.js
  app/components/message_attachments/attachment_image/__snapshots__/attachment_image.test.js.snap
  app/components/message_attachments/attachment_image/attachment_image.js
  app/components/post/post.js
  app/components/post_attachment_image/__snapshots__/index.test.js.snap
  app/components/post_attachment_image/index.js
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
  app/components/post_body/post_body.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/post_header/post_header.js
  app/components/post_list_retry.js
  app/components/post_profile_picture/post_profile_picture.js
  app/components/reactions/reaction.js
  app/components/reactions/reactions.js
  app/components/send_button.js
  app/components/show_more_button/__snapshots__/show_more_button.test.js.snap
  app/components/show_more_button/show_more_button.js
  app/components/show_more_button/show_more_button.test.js
  app/components/touchable_with_feedback/index.js
  app/components/touchable_with_feedback/touchable_with_feedback.android.js
  app/components/touchable_with_feedback/touchable_with_feedback.ios.js
  app/screens/user_profile/user_profile_row.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3330 Automated cherry pick of #3293
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
  app/screens/channel/channel_nav_bar/channel_title/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3333 Revert long post as ScrollView instead of View
  app/components/post_body/post_body.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3334 Automated cherry pick of #3333
  app/components/post_body/post_body.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3299 MM-18762 Remove some usage of deprecated lifecycle methods
  app/components/announcement_banner/announcement_banner.js
  app/components/badge.js
  app/components/emoji/emoji.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/progressive_image/progressive_image.js
  app/components/root/root.js
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/swiper.js
  app/screens/about/about.js
  app/screens/add_reaction/add_reaction.js
  app/screens/channel/channel_base.js
  app/screens/client_upgrade/client_upgrade.js
  app/screens/code/code.js
  app/screens/error_teams_list/error_teams_list.js
  app/screens/image_preview/video_preview.js
  app/screens/mfa/mfa.js
  app/screens/settings/notification_settings_mentions/notification_settings_mention_base.js
  app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
  app/screens/settings/timezone/timezone.js
  app/screens/table_image/table_image.js
  app/screens/text_preview/text_preview.js
  app/screens/user_profile/user_profile.js
  index.js
  share_extension/android/extension_channels/extension_channels.js
Labels: 3: Reviews Complete

#3329 MM-18176 Fix network indicator stock after re-connect
  app/components/network_indicator/network_indicator.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3336 Automated cherry pick of #3329
  app/components/network_indicator/network_indicator.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3338 Bump app build number to 235
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3339 Automated cherry pick of #3338
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3335 MM-18464 Interactive dialog renders out of safe area view on landscape orientation
  app/components/autocomplete_selector/autocomplete_selector.js
  app/components/autocomplete_selector/index.js
  app/components/custom_list/option_list_row/index.js
  app/components/custom_list/option_list_row/option_list_row.js
  app/components/widgets/settings/bool_setting.js
  app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
  app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_introduction_text.js
  app/screens/interactive_dialog/dialog_introduction_text.test.js
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
  app/screens/selector_screen/index.js
  app/screens/selector_screen/selector_screen.js
  app/screens/selector_screen/selector_screen.test.js
Labels: CherryPick/Approved, QA Review Done

#3341 Automated cherry pick of #3335
  app/components/autocomplete_selector/autocomplete_selector.js
  app/components/autocomplete_selector/index.js
  app/components/custom_list/option_list_row/index.js
  app/components/custom_list/option_list_row/option_list_row.js
  app/components/widgets/settings/bool_setting.js
  app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
  app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_introduction_text.js
  app/screens/interactive_dialog/dialog_introduction_text.test.js
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
  app/screens/selector_screen/index.js
  app/screens/selector_screen/selector_screen.js
  app/screens/selector_screen/selector_screen.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3281 1.23.1 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#3344 Fix channel navbar title displayName variable
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3345 Automated cherry pick of #3344
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3349 MM-18832 Update message count string
  app/components/post_textbox/post_textbox_base.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, Do Not Merge/Awaiting Next Release, QA Review Done

#3072 MM-17759 Add code highlighting
  NOTICE.txt
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/screens/code/code.js
  app/utils/theme.js
  app/utils/theme.test.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done
