Repository mattermost/mattermost-mobile, pull requests merged in 2019-10, with the labels that each got.

#3342 MM-18997 Fix More unread overlay preventing interactions
  app/components/__snapshots__/fade.test.js.snap
  app/components/fade.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/channels_list/unread_indicator/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3354 Automated cherry pick of #3342
  app/components/__snapshots__/fade.test.js.snap
  app/components/fade.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/channels_list/unread_indicator/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3259 MM-15220 Support generic error message in interactive dialog
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/interactive_dialog/interactive_dialog.test.js
Labels: 3: Reviews Complete, Hacktoberfest

#3361 Automated cherry pick of #3353
  app/init/fetch.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3343 MM-18999 Fix search in: modifier to show the appropriate badge when n…
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/channel_mention_item/channel_mention_item.js
  app/components/autocomplete/channel_mention_item/index.js
  app/components/sidebars/main/channels_list/channel_item/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3359 Set Sidebar channel item display name opacity as 0.6 (same as webapp)
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3363 Automated cherry pick of #3343
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/channel_mention_item/channel_mention_item.js
  app/components/autocomplete/channel_mention_item/index.js
  app/components/sidebars/main/channels_list/channel_item/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3364 Automated cherry pick of #3359
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3365 Bump app build number to 236
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3366 Automated cherry pick of #3365
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3358 Fix native emojis being cutoff in emoji picker
  app/components/emoji_picker/emoji_picker_base.js
  app/components/emoji_picker/emoji_picker_row.js
Labels: 3: Reviews Complete, QA Review Done

#3306 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#3378 Automated cherry pick of #3306
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3352 MM-18463 Added update_badge notification when marking a channel as unread
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  ios/Mattermost/AppDelegate.m
Labels: 3: Reviews Complete

#3374 Add android/app/bin to .gitignore
  .gitignore
Labels: 3: Reviews Complete

#3385 Fix running mm-i18n that crashes on conditional operators
  app/components/sidebars/drawer_layout.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3386 Automated cherry pick of #3385
  app/components/sidebars/drawer_layout.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3280 GH-11948 Adding expand button to markdown tables
  app/components/markdown/markdown_table/markdown_table.js
Labels: Build Apps for PR, QA Review Done

#3390 Automated cherry pick of #3379
  app/components/file_attachment_list/__snapshots__/file_attachment.test.js.snap
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3383 Fixing DMs guest label behavior
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/channel_info_header.test.js
  app/screens/channel_info/index.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3391 Fixing DMs guest label behavior (#3383)
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/channel_info_header.test.js
  app/screens/channel_info/index.js
Labels: CherryPick/Approved

#3384 MM-19180 - Updating spacing for mentions component
  app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
  app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3394 Automated cherry pick of #3384
  app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
  app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3395 Bump app build number to 237
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, CherryPick/Approved

#3396 Automated cherry pick of #3395
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3372 Fixing mention text color
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/utils/markdown.js
  package-lock.json
Labels: Build Apps for PR, CherryPick/Approved, Hacktoberfest, QA Review Done

#3397 Bump app build number to 238
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3399 Automated cherry pick of #3397
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3375 MM-17157 Only send notification receipt if server url and session token are set
  app/store/store.js
  ios/MattermostShare/ShareViewController.swift
  ios/UploadAttachments/UploadAttachments/StoreManager.m
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: 3: Reviews Complete, CherryPick/Approved

#3393 Not show the guest badge for system messages
  app/components/post_header/post_header.js
Labels: 2: QA Review, 3: Reviews Complete, CherryPick/Approved

#3406 Automated cherry pick of #3393
  app/components/post_header/post_header.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3405 Revert accidentally merged changes from mark-as-unread branch
  app/reducers/views/channel.js
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  app/screens/post_options/index.js
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
  app/screens/post_options/post_options.test.js
  assets/base/i18n/en.json
  assets/base/images/post_menu/bookmark.png
  assets/base/images/post_menu/bookmark@2x.png
  assets/base/images/post_menu/bookmark@3x.png
  package-lock.json
  package.json
  packager/moduleNames.js
Labels: 3: Reviews Complete

#3404 [MM-19243] Disable reactions on read only channel
  app/components/reactions/index.js
Labels: CherryPick/Approved, QA Review Done, Tests/Done

#3407 Automated cherry pick of #3404
  app/components/reactions/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3370 MM-18829 Updated Channel Header SafeAreaView
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/channel_info_header.test.js
Labels: 3: Reviews Complete, QA Review Done

#3371 MM-18173 Removed getState from Add Channel Member method
  app/actions/views/channel_add_members.js
Labels: Tests/Not Needed

#3347 MM-18791: Add spacing to Helper text on Settings Screen
  app/screens/settings/section.js
Labels: 3: Reviews Complete, QA Review Done

#3351 MM-18054: Removed Commented On from new messages in thread with same poster
  app/components/post/index.js
  app/components/post/post.js
  app/components/post_header/post_header.js
  app/components/post_list/post_list.js
Labels: 3: Reviews Complete, QA Review Done

#3346 MM-18935: Added SafeAreaView padding for the SSO screen
  app/screens/sso/index.js
  app/screens/sso/sso.js
Labels: 3: Reviews Complete, QA Review Done

#3418 translations PR 20191014
  assets/base/i18n/fr.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete

#3419 Automated cherry pick of #3411
  patches/react-native-image-picker+0.28.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3402 MM-19286 Disable Haptic Feedback
  app/utils/general.js
Labels: CherryPick/Approved, QA Review Done

#3420 Automated cherry pick of #3402
  app/utils/general.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3417 [MM-19307] Make LHS channel item display name not overlap with mention count
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
Labels: 2: Dev Review

#3421 Bump app build number to 239
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, CherryPick/Approved

#3422 Automated cherry pick of #3421
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3264 MM-15469 (Android) Alert if shared text is longer than message limit
  assets/base/i18n/en.json
  share_extension/android/extension_post/extension_post.js
  share_extension/android/extension_post/extension_post.test.js
Labels: 3: Reviews Complete, QA Review Done, Tests/Done

#3267 v1.24 Changelog
  CHANGELOG.md
Labels: 2: Dev Review, 3: Reviews Complete

#3425 Update fastlane
  fastlane/Gemfile.lock
Labels: 3: Reviews Complete

#3224 Fix wording for mobile
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3430 Fix building unsigned apps
  Makefile
  ios/Mattermost/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3431 Automated cherry pick of #3430
  Makefile
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3433 Automated cherry pick of #3356
  app/screens/search/search.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3434 Automated cherry pick of #3375
  app/store/store.js
  ios/MattermostShare/ShareViewController.swift
  ios/UploadAttachments/UploadAttachments/StoreManager.m
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3435 Automated cherry pick of #3362
  app/screens/flagged_posts/__snapshots__/flagged_posts.test.js.snap
  app/screens/flagged_posts/flagged_posts.js
  app/screens/flagged_posts/flagged_posts.test.js
  app/screens/recent_mentions/__snapshots__/recent_mentions.test.js.snap
  app/screens/recent_mentions/recent_mentions.js
  app/screens/recent_mentions/recent_mentions.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3438 Automated cherry pick of #3351
  app/components/post/index.js
  app/components/post/post.js
  app/components/post_header/post_header.js
  app/components/post_list/post_list.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3439 Automated cherry pick of #3346
  app/screens/sso/index.js
  app/screens/sso/sso.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3442 Bump app version number to 1.25.0
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 2: Dev Review, CherryPick/Approved

#3443 Bump app build number to 240
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, CherryPick/Approved

#3444 Automated cherry pick of #3443
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3450 Automated cherry pick of #3415
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
  app/screens/settings/theme/theme.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3448 MM-19328 | Add accessibility label to channel drawer button.
  app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.test.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Done

#3380 MM-18790 Fix Keyboard Color Flash
  app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.js
Labels: 2: QA Review, Build Apps for PR, CherryPick/Approved

#3426 Remove deprecated lifecycle methods from misc components
  app/components/profile_picture/profile_picture.js
  app/components/retry_bar_indicator/retry_bar_indicator.js
  app/components/search_bar/search_box.js
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3453 Automated cherry pick of #3380
  app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3458 MM-19493 For manually unread channel, don't mark as read on new message
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3424 Fix iOS crash when pasting large images and included other file types
  app/components/post_textbox/post_textbox_base.js
  assets/base/i18n/en.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost+RCTUITextView.m
  ios/Mattermost/NSData+MimeType.m
  ios/Mattermost/OnPasteEventManager.h
  ios/Mattermost/OnPasteEventManager.m
  ios/Mattermost/SwimeProxy.swift
  ios/Mattermost/UIImage+vImageScaling.h
  ios/Mattermost/UIImage+vImageScaling.m
  ios/Mattermost/UIPasteboard+GetImageInfo.h
  ios/Mattermost/UIPasteboard+GetImageInfo.m
  ios/Podfile
  ios/Podfile.lock
  ios/SwimeProxy.swift
  package-lock.json
Labels: Build Apps for PR, QA Review Done

#3463 MM-18647 Request only needed Android permissions for storage and camera
  package-lock.json
  patches/react-native-image-picker+0.28.1.patch
Labels: 3: Reviews Complete, CherryPick/Approved

#3464 Automated cherry pick of #3463
  patches/react-native-image-picker+0.28.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3465 MM-18463 Added update_badge notification when marking a channel as unread (1.25)
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  ios/Mattermost/AppDelegate.m
Labels: 3: Reviews Complete

#3461 Migrate Channel info screen to realm
  app/components/sidebars/main/channels_list/channel_item/index.js
  app/constants/general.js
  app/realm/action_types/channel.js
  app/realm/actions/channel.js
  app/realm/actions/emoji.js
  app/realm/selectors/channel.js
  app/realm/utils/channel.js
  app/realm/utils/user.js
  app/realm/writers/channel.js
  app/screens/channel/channel_nav_bar/channel_title/index.js
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/index.js
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/Mattermost.xcscheme
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3467 Bump app build number to 241
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3468 Automated cherry pick of #3467
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3470 Automated cherry pick of #3457
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/safe_area_view/safe_area_view.ios.test.js
  app/constants/view.js
  app/store/ephemeral_store.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3469 Fix Android senderName call
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 3: Reviews Complete

#3462 MM-18313 Fix update timezone automatically
  app/actions/views/login.js
  app/init/global_event_handler.js
  app/init/global_event_handler.test.js
  app/screens/settings/timezone/timezone.js
  app/utils/timezone.js
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3473 Automated cherry pick of #3462
  app/actions/views/login.js
  app/init/global_event_handler.js
  app/init/global_event_handler.test.js
  app/screens/settings/timezone/timezone.js
  app/utils/timezone.js
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3471 Fix android senderName call (mark-as-unread)
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 3: Reviews Complete

#3474 Fix app deploy path
  .circleci/config.yml
Labels: 3: Reviews Complete, CherryPick/Approved

#3475 Automated cherry pick of #3474
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3376 MM-13413 Make user names in system messages tappable
  app/components/post_body/__snapshots__/system_message_helpers.test.js.snap
  app/components/post_body/post_body.js
  app/components/post_body/post_body.test.js
  app/components/post_body/system_message_helpers.js
  app/components/post_body/system_message_helpers.test.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, Build Apps for PR, Hacktoberfest, QA Review Done

#3290 MM-10272 Add a count for pinned posts header icon
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
Labels: 3: Reviews Complete, Build Apps for PR, Lifecycle/1:stale, QA Review Done

#3295 MM-13842 Add Autocomplete to post edit screen
  app/screens/edit_post/edit_post.js
Labels: 3: Reviews Complete, Build Apps for PR, QA Review Done

#3476 Fix android and iOS deployment on circleCI
  .circleci/config.yml
  fastlane/Fastfile
Labels: 3: Reviews Complete, CherryPick/Approved

#3483 Automated cherry pick of #3476
  .circleci/config.yml
  fastlane/Fastfile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3479 Automated cherry pick of #3357
  app/components/radio_button/radio_button_group.js
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings_email/index.js
  app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
  app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
  app/screens/settings/notification_settings_email/notification_settings_email_base.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3445 MM-19308 Fixed date wrapping
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/post_header.js
  app/components/post_header/post_header.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3481 MM-19734 Patch RN to remove the placeholder for emojis in a markdown
  patches/react-native+0.59.9.patch
Labels: 3: Reviews Complete, CherryPick/Approved

#3485 Automated cherry pick of #3481
  patches/react-native+0.59.9.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3494 Automated cherry pick of #3482
  app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings/notification_settings.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3477 MM-19731 Fix at-channel autocomplete to return out of channel mentions
  app/selectors/autocomplete.js
  app/selectors/autocomplete.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3493 [MM-19448] Get user preferences on WebSocket reconnect
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#3484 Automated cherry pick of #3445
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/post_header.js
  app/components/post_header/post_header.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3500 Manual Cherrypick of #3493
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3495 Automated cherry pick of #3477
  app/selectors/autocomplete.js
  app/selectors/autocomplete.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3499 Updated PR Template
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete, Tests/Not Needed

#3472 MM-19655 - Reverted mention color to user linkColor
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/utils/markdown.js
Labels: CherryPick/Approved, QA Review Done

#3502 Automated cherry pick of #3472
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/utils/markdown.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3503 circleCI change persist root from / to ~/
  .circleci/config.yml
Labels: 2: Dev Review, CherryPick/Approved

#3504 Cherrypick for #3466 into 1.25 release
  app/components/message_attachments/attachment_image/__snapshots__/index.test.js.snap
  app/components/message_attachments/attachment_image/index.js
  app/components/progressive_image/progressive_image.js
Labels: 2: Dev Review

#3505 Automated cherry pick of #3503
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3507 Automated cherry pick of #3506
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
