Repository mattermost/mattermost-mobile, pull requests merged in 2019-01, with the labels that each got.

#2486 v1.15.1 Changelog
  CHANGELOG.md
Labels: 2: Dev Review, 2: PM Review

#2488 Handling nulls in getMyCurrentChannelMembership
  app/screens/channel/channel_post_list/index.js
  app/screens/thread/thread.js
Labels: 3: Ready to Merge

#2490 MM-13432 Remove unsed request flags from channel_members
  app/initial_state.js
  app/screens/channel_members/index.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2467 MM-11232 Fix table column width to better support wide tables
  app/components/markdown/markdown.js
  app/components/markdown/markdown_table/markdown_table.js
  app/components/markdown/markdown_table_cell/markdown_table_cell.js
  app/components/markdown/markdown_table_row/markdown_table_row.js
  app/screens/table/table.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2492 Fix visibility of retry failed message option
  app/components/post_body/post_body.js
Labels: 2: Dev Review, CherryPickApproved

#2491 MM-13594 Fix other users status changes
  app/actions/views/user.js
  app/actions/views/user.test.js
  app/components/network_indicator/index.js
  app/components/network_indicator/network_indicator.js
Labels: 2: Dev Review, CherryPickApproved

#2494 Update fastlane
  fastlane/Gemfile.lock
Labels: 3: Ready to Merge, CherryPickApproved

#2496 MM-13432 Remove getFilesForPost request state and use react state
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/file_attachment_list/file_attachment_list.js
  app/components/file_attachment_list/file_attachment_list.test.js
  app/components/file_attachment_list/index.js
Labels: 2: Dev Review

#2498 Fix Keywords modal title on Android
  app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
Labels: 3: Ready to Merge

#2497 MM-13666 Detect post as emoji only if not a codeblock
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2495 MM-13654: Removes pin and delete longpress options from posts in arch…
  app/screens/post_options/index.js
  app/screens/post_options/post_options.js
Labels: 3: Ready to Merge, CherryPickApproved

#2500 MM-13703 Fix settings screen not showing joinable teams
  app/screens/settings/general/settings.js
Labels: 3: Ready to Merge

#2504 translations PR 20190110
  assets/base/i18n/ko.json
  assets/base/i18n/pl.json
  assets/base/i18n/uk.json
Labels: 3: Ready to Merge

#2505 Bump app build number to 168
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2503 MM-13665 Prevent quick multiple taps on file to open multiple file previews
  app/components/file_attachment_list/file_attachment_document.js
Labels: 3: Ready to Merge

#2508 MM-13751: Fix for incorrect access to delete button.
  app/screens/post_options/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2510 Bump app build number to 169
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge

#2487 v1.16 Changelog
  CHANGELOG.md
Labels: 2: Dev Review, 2: PM Review

#2518 translations PR 20190121
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2489 Clicking username in read-only allows sending message
  app/components/post/post.js
Labels: 2: Dev Review, Lifecycle/1:stale

#2526 Update fastlane
  fastlane/Gemfile.lock
Labels: 3: Ready to Merge

#2527 Fastlane env vars example update
  fastlane/env_vars_example
Labels: 3: Ready to Merge

#2523 MM-13722 Reset application badge when there are no more mentions
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
Labels: 3: Ready to Merge

#2525 MM-13846 Alert boxes to follow UX Guidelines
  app/components/attachment_button.js
  app/screens/terms_of_service/terms_of_service.js
  app/utils/status.js
Labels: 3: Ready to Merge, CherryPickApproved

#2473 MM-13525 Fix alignment of jewel on channel drawer icon
  app/components/__snapshots__/badge.test.js.snap
  app/components/badge.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
Labels: 3: Ready to Merge, CherryPickApproved

#2530 Bump Version to 1.16.0 and Build number 171
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2501 [MM-13412 & MM-13711] Allow showing of all post options if possible to fit 75% of the screen height
  app/screens/post_options/post_options.js
  app/screens/post_options/post_options_utils.js
  app/screens/post_options/post_options_utils.test.js
Labels: 2: PM Review, CherryPickApproved

#2532 translations PR 20190128
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2531 Update mattermost-redux version.
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2533 MM-13875 Fix user profile icon for a Webhook to follow the prop for use_user_icon
  app/components/post/index.js
  app/components/post_header/index.js
  app/components/post_profile_picture/index.js
  app/screens/notification/notification.js
Labels: 3: Ready to Merge

#2536 MM-13876 Webhook icon is misaligned and bottom edges are cut off
  assets/base/images/icons/webhook.jpg
Labels: 3: Ready to Merge, CherryPickApproved

#2535 Enable tapping on channels when jump to textfield is focused.
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
Labels: 3: Ready to Merge

#2539 MM-13866 Never ending loader if app is un authenticated
  share_extension/android/extension_post/extension_post.js
Labels: 3: Ready to Merge, CherryPickApproved
