Repository mattermost/mattermost-mobile, pull requests merged in 2019-11, with the labels that each got.

#3517 Automated cherry pick of #3515
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3377 [MM-18768] Remove deprecated lifecycle methods from channel info
  app/screens/channel_info/channel_info.js
  app/screens/edit_channel/edit_channel.js
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3513 MM-19853 Fix iOS SafeAreaView for Server URL screen
  app/initial_state.js
  app/screens/select_server/select_server.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3520 Automated cherry pick of #3513
  app/initial_state.js
  app/screens/select_server/select_server.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3509 MM-19599 Updated Channel Nav Bar height
  app/constants/view.js
Labels: 3: Reviews Complete, QA Review Done

#3522 Bump app build number to 243
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3508 Update unsigned android and ios builds
  .circleci/config.yml
  Makefile
  android/app/build.gradle
  fastlane/Fastfile
  fastlane/Gemfile.lock
  fastlane/metadata/changelog
  patches/react-native+0.59.9.patch
  patches/react-native+0.61.2.patch
Labels: 2: Dev Review

#3518 MM-19730 Add channel info pinned post count to Realm
  app/realm/models/channel.js
  app/realm/writers/channel.js
  app/screens/channel_info/index.js
Labels: 3: Reviews Complete

#3526 Fix release 1.25 Android build
  package-lock.json
Labels: 3: Reviews Complete

#3528 Automated cherry pick of #3527
  app/push_notifications/push_notifications.ios.js
  app/utils/push_notifications.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3531 MM-19812 Properly handle in-app update_badge notifications
  app/utils/push_notifications.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3540 Automated cherry pick of #3531
  app/utils/push_notifications.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3543 translations PR 20191111
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete

#3535 MM-19966 Fixed Notification Settings
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings/notification_settings.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3546 Automated cherry pick of #3535
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings/notification_settings.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3548 Bump app build number to 244
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3524 MM-19482 Stop rendering New Messages line differently for manually unread channels
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#3549 MM-20149 Fix marking channels as read
  app/actions/views/channel.js
  app/actions/views/channel.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3550 Automated cherry pick of #3549
  app/actions/views/channel.js
  app/actions/views/channel.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3551 Bump app build number to 245
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3553 MM-19961 Sync persisted channels with the ones returned by the server
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3541 Adding ability to disable attachment buttons and fields.
  app/components/autocomplete_selector/autocomplete_selector.js
  app/components/message_attachments/action_button/action_button.js
  app/components/message_attachments/action_menu/action_menu.js
  app/components/message_attachments/action_menu/action_menu.test.js
  app/components/message_attachments/attachment_actions.js
Labels: 3: Reviews Complete

#3555 Fix partially shown drawers when orientation change on iOS
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/sidebars/drawer_layout.js
Labels: 2: Dev Review

#3536 MM-19696 Added font color for GlobalStyle Input
  app/screens/forgot_password/__snapshots__/forgot_password.test.js.snap
  app/styles/index.js
Labels: 3: Reviews Complete, QA Review Done

#3537 MM-19697 - Fixed CameraRoll for iOS
  app/screens/image_preview/downloader.ios.js
  ios/Podfile.lock
  package.json
Labels: 3: Reviews Complete, Build Apps for PR, QA Review Done

#3511 [MM-10813] Design update for Post attachments
  app/components/file_attachment_list/__snapshots__/file_attachment.test.js.snap
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_document/file_attachment_document.js
  app/components/file_attachment_list/file_attachment_icon.js
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/file_attachment_list/file_attachment_list.test.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
  app/components/message_attachments/attachment_image/__snapshots__/index.test.js.snap
  app/components/message_attachments/attachment_image/index.js
  app/components/post_body/post_body.js
  app/components/progressive_image/progressive_image.js
  app/constants/attachment.js
  app/screens/image_preview/image_preview.js
  assets/base/images/icons/audio.png
  assets/base/images/icons/code.png
  assets/base/images/icons/excel.png
  assets/base/images/icons/generic.png
  assets/base/images/icons/image.png
  assets/base/images/icons/patch.png
  assets/base/images/icons/pdf.png
  assets/base/images/icons/ppt.png
  assets/base/images/icons/text.png
  assets/base/images/icons/video.png
  assets/base/images/icons/word.png
Labels: 2: PM Review, 3: Reviews Complete, Hacktoberfest

#3559 MM-19600 Align Sidebar separator line between Teams and Channel view
  app/components/sidebars/main/teams_list/teams_list.js
Labels: 3: Reviews Complete, QA Review Done

#3523 MM-18054 Checked for prev post comment line
  app/components/post/post.js
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/post_header.js
  app/components/post_header/post_header.test.js
Labels: 3: Reviews Complete, QA Review Done

#3209 [mm 15792] Fix massive app slowdown with many emojis
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/components/emoji/emoji.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Build Apps for PR, QA Review Done, Tests/Not Needed

#3414 MM-19037 Updated Progressive Image Loader
  app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
  app/components/progressive_image/progressive_image.js
  app/components/progressive_image/progressive_image.test.js
  app/utils/image_cache_manager.js
Labels: 3: Reviews Complete, QA Review Done

#3558 MM-19993 Fix Channel spinner is black on dark theme
  app/components/autocomplete/autocomplete_section_header.js
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/index.js
  app/components/edit_channel_info/edit_channel_info.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/load_more_posts/load_more_posts.js
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/post_list.js
  app/screens/channel/channel_base.js
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_members/channel_members.js
  app/screens/edit_post/edit_post.js
  app/screens/edit_profile/edit_profile.js
  app/screens/error_teams_list/error_teams_list.js
  app/screens/more_channels/more_channels.js
  app/screens/more_dms/more_dms.js
  app/screens/permalink/__snapshots__/permalink.test.js.snap
  app/screens/permalink/permalink.js
  app/screens/search/search.js
  app/screens/select_team/__snapshots__/select_team.test.js.snap
  app/screens/select_team/select_team.js
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/terms_of_service/terms_of_service.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.android.js
  app/screens/thread/thread.ios.js
  app/screens/thread/thread_base.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3564 Automated cherry pick of #3558
  app/components/autocomplete/autocomplete_section_header.js
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/index.js
  app/components/edit_channel_info/edit_channel_info.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/load_more_posts/load_more_posts.js
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/post_list.js
  app/screens/channel/channel_base.js
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_members/channel_members.js
  app/screens/edit_post/edit_post.js
  app/screens/edit_profile/edit_profile.js
  app/screens/error_teams_list/error_teams_list.js
  app/screens/more_channels/more_channels.js
  app/screens/more_dms/more_dms.js
  app/screens/permalink/__snapshots__/permalink.test.js.snap
  app/screens/permalink/permalink.js
  app/screens/search/search.js
  app/screens/select_team/__snapshots__/select_team.test.js.snap
  app/screens/select_team/select_team.js
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/terms_of_service/terms_of_service.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.android.js
  app/screens/thread/thread.ios.js
  app/screens/thread/thread_base.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3514 MM-19337 Enable users to view archived channels
  app/actions/views/channel.js
  app/components/custom_list/channel_list_row/channel_list_row.js
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/index.js
  app/screens/more_channels/more_channels.js
  app/screens/more_channels/more_channels.test.js
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3565 Fix theme color for the more channel options
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3566 Automated cherry pick of #3565
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3563 MM-20007 Fix app crashes when previewing some gif files
  app/components/message_attachments/attachment_thumbnail.js
  app/components/progressive_image/progressive_image.js
  app/screens/image_preview/image_preview.js
  package-lock.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3567 Automated cherry pick of #3563
  app/components/message_attachments/attachment_thumbnail.js
  app/components/progressive_image/progressive_image.js
  app/screens/image_preview/image_preview.js
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3568 Automated cherry pick of #3561
  app/components/autocomplete/channel_mention_item/index.js
  app/selectors/autocomplete.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3440 v1.25 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#3570 Automated cherry pick of #3562
  .circleci/config.yml
  Makefile
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/push_notifications/push_notifications.ios.js
  ios/NotificationService/NotificationService.swift
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
  patches/react-native-notifications+2.0.6.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3144 MM-17838 Wrap reactions when they exceed screen size
  app/components/reactions/index.js
  app/components/reactions/reactions.js
  app/constants/emoji.js
  app/screens/post_options/index.js
  app/screens/post_options/index.test.js
  package-lock.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3569 translations PR 20191118
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete, QA Review Done

#3574 Fix CircleCI iOS build by adding watchman
  .circleci/config.yml
Labels: 3: Reviews Complete, CherryPick/Approved

#3576 Automated cherry pick of #3574
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3577 Automated cherry pick of #3571
  app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
  app/components/markdown/markdown_table/markdown_table.js
  app/components/markdown/markdown_table/markdown_table.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3580 Fixes crash when sso cookies does not contain an expiration date
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3579 Avoid OOM crash on iOS13 Share Extension
  ios/MattermostShare/ShareViewController.swift
Labels: CherryPick/Approved, QA Review Done

#3583 Automated cherry pick of #3579
  ios/MattermostShare/ShareViewController.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3585 Automated cherry pick of #3578
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/ManagedActivityLifecycleCallbacks.java
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/mattermost_managed/mattermost-managed.android.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3584 1.25.1 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#3587 Bump version to 1.25.1 and Build number to 246
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3591 Automated cherry pick of #3590
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3592 Automated cherry pick of #3590
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3593 Bump app build number to 247
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete

#3586 MM-20347 Handle Flag for ID Loaded Push Notifications
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  ios/NotificationService/NotificationService.swift
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3594 Automated cherry pick of #3586
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  ios/NotificationService/NotificationService.swift
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3588 MM-20201 Fixed asterisk on Nickname
  app/screens/edit_profile/edit_profile.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3596 Automated cherry pick of #3588
  app/screens/edit_profile/edit_profile.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3601 Bump Version to 1.26 and Build number to 248
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3602 Automated cherry pick of #3601
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3600 1.25.1 changelog
  CHANGELOG.md
Labels: 2: PM Review, 3: Reviews Complete

#3560 MM-17915 Migrate edit channel to realm
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/edit_channel_info/edit_channel_info.js
  app/components/edit_channel_info/edit_channel_info.test.js
  app/components/edit_channel_info/index.js
  app/realm/actions/channel.js
  app/screens/edit_channel/edit_channel.js
  app/screens/edit_channel/index.js
Labels: 3: Reviews Complete

#3605 Automated cherry pick of #3604
  app/screens/image_preview/video_preview.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3572 MM-19834 Fixed direct mentions highlight color
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
  app/components/at_mention/at_mention.test.js
  app/components/at_mention/index.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3612 Automated cherry pick of #3572
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
  app/components/at_mention/at_mention.test.js
  app/components/at_mention/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3609 [MM-20667] Fixes crash on Android release build
  assets/base/release/splash_screen/android/layout/launch_screen.xml
Labels: 3: Reviews Complete, CherryPick/Approved, Tests/Not Needed

#3613 Automated cherry pick of #3609
  assets/base/release/splash_screen/android/layout/launch_screen.xml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3615 Automated cherry pick of #3603
  patches/react-native-cookies+3.3.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3610 MM-20694 Fix race condition when the store has not rehydrated
  app/mattermost.js
  app/store/utils.js
  app/utils/push_notifications.js
Labels: 3: Reviews Complete, CherryPick/Approved, Tests/Not Needed

#3616 Automated cherry pick of #3610
  app/mattermost.js
  app/store/utils.js
  app/utils/push_notifications.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3619 Automated cherry pick of #3595
  app/components/autocomplete/autocomplete.js
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/edit_channel_info/edit_channel_info.js
  app/components/edit_channel_info/edit_channel_info.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3608 MM-20326 - Updating markdown table css
  app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
  app/components/markdown/markdown_table/markdown_table.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3620 Automated cherry pick of #3608
  app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
  app/components/markdown/markdown_table/markdown_table.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3621 MM-20729 & MM-20731 Fix YouTube playback and rotation
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-youtube+2.0.0-beta.3.patch
  patches/react-native-youtube+2.0.0.patch
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3623 MM-20689 Long post to use all available space
  app/screens/long_post/__snapshots__/long_post.test.js.snap
  app/screens/long_post/index.js
  app/screens/long_post/long_post.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3626 Automated cherry pick of #3623
  app/screens/long_post/__snapshots__/long_post.test.js.snap
  app/screens/long_post/index.js
  app/screens/long_post/long_post.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3624 Automated cherry pick of #3621
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-youtube+2.0.0-beta.3.patch
  patches/react-native-youtube+2.0.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3627 Automated cherry pick of #3618
  app/screens/image_preview/image_preview.js
  app/screens/image_preview/image_preview.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3607 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#3629 Automated cherry pick of #3607
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3599 MM-19708 Adjusted display name width to 80% for landscape
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/index.js
  app/components/post_header/post_header.js
  app/components/post_header/post_header.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3617 MM-19990 Prevent glimpse of the app if TOS not accepted
  app/screens/terms_of_service/terms_of_service.js
  app/screens/terms_of_service/terms_of_service.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3634 MM-20228 Update Mark as Unread menu option text
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  app/screens/post_options/post_options.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3639 Automated cherry pick of #3634
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  app/screens/post_options/post_options.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3249 MM-15635 - Making markdown tables more responsive
  app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
  app/components/markdown/markdown_table/markdown_table.js
  app/components/markdown/markdown_table_cell/markdown_table_cell.js
  app/components/markdown/markdown_table_row/markdown_table_row.js
  app/screens/table/table.js
Labels: 3: Reviews Complete, QA Review Done
