Repository mattermost/mattermost-mobile, pull requests merged in 2019-06, with the labels that each got.

#2854 MM-15959 disable android firebase analytics
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
Labels: CherryPick/Approved

#2841 MM-11287 Add support for plus sign and period/dot in custom URL schemes (#9155)
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2857 Fix server version for Android telemetry
  app/telemetry/telemetry.android.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2848 MM-15774 Add native code to support RNN v2 on iOS
  Makefile
  app/mattermost.js
  app/screens/index.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.m
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2832 [MM-13879] Add Edit profile button to RHS menu and own profile pop-over
  app/components/sidebars/settings/settings_sidebar.js
  app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
  app/screens/edit_profile/edit_profile.js
  app/screens/edit_profile/edit_profile.test.js
  app/screens/user_profile/index.js
  app/screens/user_profile/user_profile.js
  app/screens/user_profile/user_profile.test.js
Labels: 3: Reviews Complete

#2856 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#2859 translations PR 20190603
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 2: Dev Review

#2860 MM-16013 make paperplain animation faster
  app/components/fade.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2862 MM-15643 Fix race condition to prompt for passcode and
  app/app.js
  app/mattermost.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2861 Fix build after #2840
  fastlane/Fastfile
Labels: 3: Reviews Complete

#2863 Fix opengraph image on tablet to account for the sidebar
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2864 MM-16070 Fix channel sidebar state while filtering
  app/components/sidebars/main/channels_list/channels_list.js
  app/components/sidebars/main/channels_list/index.js
  app/components/sidebars/main/drawer_swipper/drawer_swiper.js
  app/components/sidebars/main/main_sidebar.js
  app/components/swiper.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2866 Fix file upload not completing
  app/components/file_upload_preview/file_upload_preview.js
  app/components/file_upload_preview/index.js
  app/components/post_textbox/post_textbox.android.js
  app/screens/channel/channel.ios.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.ios.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2867 Fix image preview width on tablets
  app/components/post_body_additional_content/post_body_additional_content.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2868 Show broken image for inline images without dimensions
  app/components/markdown/markdown_image/markdown_image.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2865 MM-16061 Keep unread channels in place on Tablets
  app/actions/views/channel.js
  app/components/sidebars/main/channels_list/list/index.js
  app/constants/view.js
  app/reducers/views/channel.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2872 Bump app build number to 197
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#2870 MM-16011 Update navigation through Login and Channel screens
  app/actions/navigation.js
  app/app.js
  app/constants/view.js
  app/mattermost.js
  app/screens/entry/entry.js
  app/screens/index.js
  app/screens/login/index.js
  app/screens/login/login.js
  app/screens/login/login.test.js
  app/screens/login_options/login_options.js
  app/screens/select_server/index.js
  app/screens/select_server/select_server.js
Labels: 2: Dev Review

#2879 MM-16281 Fix regression on android push notification messages
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 3: Reviews Complete, CherryPick/Approved

#2880 MM-16280 Fix when post fail to send
  package-lock.json
  package.json
Labels: 2: Dev Review

#2883 MM-16228 Add compatibility for removal of ExperimentalEnablePostMetadata data flag from config
  app/components/emoji/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2884 Bump app build number to 198
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: CherryPick/Approved

#2803 v1.20 Changelog
  CHANGELOG.md
Labels: 2: PM Review

#2876 MM-16095 Android share extension to use keychain for authentication
  assets/base/i18n/en.json
  share_extension/android/extension_post/extension_post.js
  share_extension/android/extension_post/index.js
  share_extension/android/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2845 [MM-14105] Long-press menu cannot be dragged up when rotating device to landscape while menu is open
  app/screens/post_options/post_options.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2858 fix ios sso cookie bug when running on top-level domain
  native_modules/RNCookieManagerIOS.m
Labels: 3: Reviews Complete, CherryPick/Approved

#2735 [MM-14917] RN Android: Push notification settings are only saved when closing settings page
  app/screens/settings/notification_settings_mobile/index.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
Labels: Build Apps for PR, CherryPick/Approved

#2882 MM-15486 - Archived channels appear incorrectly on mobile
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/filtered_list/index.js
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2888 Set post list data and timestamp based on the user timezone if available
  app/actions/views/login.js
  app/components/formatted_time.js
  app/components/post_header/index.js
  app/components/post_list/date_header/index.js
  app/screens/entry/index.js
  app/screens/search/index.js
  app/screens/settings/display_settings/index.js
  app/screens/user_profile/index.js
  app/utils/timezone.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2878 MM-16239 disable fields according to SAML or LDAP
  app/screens/edit_profile/edit_profile.js
  app/screens/edit_profile/edit_profile.test.js
  app/screens/edit_profile/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2891 translations PR 20190617
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete

#2889 Update Github issues link
  README.md
Labels: 3: Reviews Complete

#2893 Update gradle to use android-jsc as instructed
  android/app/build.gradle
Labels: 3: Reviews Complete, CherryPick/Approved

#2894 Bump app version number to 1.21.0
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2896 Bump app build number to 199
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: CherryPick/Approved

#2900 Fix crash on Android by Updating JSC
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved

#2901 MM-16432 Fix missing posts when using since API
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2903 Bump app build number to 201
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#2909 MM-16472 Fix renderItem not returning anything
  app/screens/channel_members/channel_members.js
Labels: 2: Dev Review, CherryPick/Approved

#2898 MM-16392 Split view support & hide sidebar on tablets
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/app.js
  app/components/sidebars/main/main_sidebar.js
  app/mattermost.js
  app/mattermost_managed/mattermost-managed.android.js
  app/mattermost_managed/mattermost-managed.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_nav_bar/channel_nav_bar.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost+RCTUITextView.h
  ios/Mattermost/Mattermost+RCTUITextView.m
  ios/Mattermost/MattermostManaged.m
Labels: 3: Reviews Complete, CherryPick/Approved

#2842 Ios accessibility fixes
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/screens/settings/settings_item/style.ios.js
Labels: 2: PM Review, Build Apps for PR, CherryPick/Approved

#2902 1.20.1 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#2899 MM-16397 save draft when app state changes
  app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
Labels: 3: Reviews Complete

#2838 Mm 15570 - Add Webdriver.io for E2E tests
  e2e/android/index.js
  e2e/android/smoke.js
  e2e/config.js
  e2e/package-lock.json
  e2e/package.json
  e2e/screens/index.js
  e2e/script/e2e_init.js
  e2e/script/retry_exec.js
  e2e/scripts/run_android_tests.sh
  e2e/test/configs/android.conf.js
  e2e/test/configs/shared.conf.js
  e2e/test/specs/smoke.test.js
  package.json
Labels: 2: Dev Review, Do Not Merge/Awaiting PR

#2910 MM-16442: count actual reactions before falling back to has_reactions
  app/components/post_body/index.js
  app/screens/long_post/index.js
Labels: 2: Dev Review

#2917 MM-16480 Update mattermost-redux
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved

#2919 translations PR 20190624
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/it.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: 2: Dev Review

#2927 MM-16463 Fix replying from push notification to a message in a thread
  android/app/src/main/java/com/mattermost/rnbeta/InitializationModule.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  app/mattermost.js
  app/push_notifications/push_notifications.android.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2926 MM-16467 Fix iOS layout when playing a youtube video in landscape
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/safe_area_view/safe_area_view.ios.js
Labels: 3: Reviews Complete

#2924 MM-16430 refactor app entry point
  android/app/src/main/java/com/mattermost/rnbeta/InitializationModule.java
  android/app/src/main/java/com/mattermost/rnbeta/InitializationPackage.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/actions/views/channel.js
  app/actions/views/login.js
  app/actions/views/login.test.js
  app/app.js
  app/init/credentials.js
  app/init/emm_provider.js
  app/init/fetch.js
  app/init/global_event_handler.js
  app/mattermost.js
  app/mattermost_managed/mattermost-managed.android.js
  app/mattermost_managed/mattermost-managed.ios.js
  app/screens/channel/channel_base.js
  app/screens/entry/entry.js
  app/screens/entry/index.js
  app/screens/index.js
  app/screens/select_server/select_server.js
  app/store/ephemeral_store.js
  app/store/index.js
  app/utils/error_handling.js
  app/utils/push_notifications.js
  app/utils/url.js
  index.js
  ios/Mattermost/MattermostManaged.m
  ios/UploadAttachments/UploadAttachments.xcodeproj/project.pbxproj
  ios/UploadAttachments/UploadAttachments/MMKeychainManager.h
  ios/UploadAttachments/UploadAttachments/MMKeychainManager.m
  ios/UploadAttachments/UploadAttachments/StoreManager.h
  ios/UploadAttachments/UploadAttachments/StoreManager.m
  ios/UploadAttachments/UploadAttachments/UploadAttachments-Bridging-Header.h
  packager/moduleNames.js
  packager/modulePaths.js
  share_extension/android/extension_post/extension_post.js
Labels: 3: Reviews Complete

#2934 Update redux update to use the release-5.13 branch
  package-lock.json
  package.json
Labels: 2: Dev Review
