Repository mattermost/mattermost-mobile, pull requests merged in 2019-05, with the labels that each got.

#2740 MM-15161 show icon for bot instead of system icon in ephemeral post
  app/components/post_profile_picture/index.js
  app/components/post_profile_picture/post_profile_picture.js
Labels: 3: Ready to Merge

#2753 MM-15315 Add native module to reset TextInput to fix bad cursors in some Android keyboards
  android/app/src/main/java/com/mattermost/rnbeta/MattermostPackage.java
  android/app/src/main/java/com/mattermost/rnbeta/RNTextInputResetModule.java
  app/components/autocomplete/autocomplete.js
  app/components/post_textbox/post_textbox.js
Labels: 2: Dev Review

#2750 MM-14030 Don't show large gifs in posts
  app/components/markdown/markdown.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/message_attachments/attachment_fields.js
  app/components/message_attachments/attachment_image.js
  app/components/message_attachments/attachment_pretext.js
  app/components/message_attachments/attachment_text.js
  app/components/message_attachments/message_attachment.js
  app/components/post_attachment_image/index.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
  app/components/post_body/post_body.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/utils/images.js
  app/utils/images.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2756 MM-15284 Disable allowBackup on Android
  android/app/src/main/AndroidManifest.xml
Labels: 3: Ready to Merge, CherryPickApproved

#2758 Use of cached managed config in components
  app/components/at_mention/at_mention.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list_base.js
  app/mattermost_managed/mattermost-managed.android.js
  app/mattermost_managed/mattermost-managed.ios.js
  app/screens/flagged_posts/flagged_posts.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/search/search.js
Labels: 3: Ready to Merge, CherryPickApproved

#2759 Remove outdated information from contributing file
  CONTRIBUTING.md
Labels: 2: Dev Review

#2760 Handle postIds null or undefined in channel_post_list
  app/screens/channel/channel_post_list/__snapshots__/channel_post_list.test.js.snap
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel/channel_post_list/channel_post_list.test.js
Labels: 2: Dev Review, CherryPick/Approved

#2748 MM-14921 Fix iPad layout including safeAreaInsets
  app/components/network_indicator/network_indicator.js
  app/components/post_list/post_list_base.js
  app/components/safe_area_view/safe_area_view.ios.js
  app/components/slide_up_panel/slide_up_panel.js
  app/constants/device.js
  app/mattermost_managed/mattermost-managed.ios.js
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  ios/Mattermost/MattermostManaged.h
  ios/Mattermost/MattermostManaged.m
  test/setup.js
Labels: 3: Reviews Complete

#2767 Fixes master branch from crashing when building in release mode
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2768 MM-15428 Fix iOS when managed config is not set
  app/mattermost_managed/mattermost-managed.ios.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2770 MM-15428 Return empty object for native managed configuration when not set
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/components/at_mention/at_mention.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list.android.js
  app/components/post_list/post_list.ios.js
  app/mattermost_managed/mattermost-managed.ios.js
  app/screens/post_options/index.js
  ios/Mattermost/MattermostManaged.m
Labels: CherryPick/Approved

#2761 MM-14958 Scroll to bottom when posting a new message
  NOTICE.txt
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/components/post_list/post_list.android.js
  app/components/post_list/post_list.ios.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/components/post_textbox/post_textbox.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2719 [MM-13955] Add telemetry for Android
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  app/actions/views/channel.js
  app/components/post/post.js
  app/components/post_body/post_body.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/main/teams_list/teams_list.js
  app/mattermost.js
  app/screens/channel/channel.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel_peek/channel_peek.js
  app/screens/login/login.js
  app/screens/select_server/select_server.js
  app/telemetry/index.js
  app/telemetry/telemetry.android.js
  app/telemetry/telemetry.ios.js
  app/telemetry/telemetry_utils.js
  assets/base/config.json
  fastlane/Fastfile
  index.js
  package-lock.json
  package.json
  packager/moduleNames.js
  packager/modulePaths.js
Labels: 3: Reviews Complete

#2775 MM-15363 Update mattermost-redux
  package-lock.json
  package.json
  share_extension/common/selectors/index.js
Labels: 2: Dev Review

#2746 MM-15228 consecutive bot posts maintain the profile image
  app/components/post/index.js
  app/components/post/post.js
Labels: 2: Dev Review

#2776 Removed @babel/polyfill
  NOTICE.txt
  app/app.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2772 translations PR 20190506
  assets/base/i18n/es.json
  assets/base/i18n/ja.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/tr.json
Labels: 3: Reviews Complete

#2780 [MM-13955] Add lastPostIndex props to Thread and Permalink, and add markers for those screens
  app/components/post_body/post_body.js
  app/components/post_list/post_list.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/permalink/permalink.js
  app/screens/thread/__snapshots__/thread.test.js.snap
  app/screens/thread/thread.js
  app/telemetry/telemetry_utils.js
Labels: 3: Reviews Complete

#2785 Update fastlane iOS beta tester link
  fastlane/Fastfile
Labels: 3: Reviews Complete, CherryPick/Approved

#2790 Update help text for at-here, at-channel, at-all
  app/components/autocomplete/at_mention/at_mention.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#2787 MM-15442 Filtered list not showing bot account icon
  app/components/sidebars/main/channels_list/channel_item/index.js
Labels: 2: Dev Review

#2789 MM-15532 properly mark channel as read when reading the channel in another client
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2777 Upgrade to RN 0.59.6 and dependencies
  .flowconfig
  Makefile
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/app.js
  app/components/autocomplete/index.js
  app/components/channel_loader/channel_loader.js
  app/components/fade.test.js
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/formatted_time.js
  app/components/markdown/markdown.js
  app/components/network_indicator/network_indicator.js
  app/components/post/post.js
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_body/index.js
  app/components/post_header/__snapshots__/post_pre_header.test.js.snap
  app/components/post_list/date_header/__snapshots__/date_header.test.js.snap
  app/components/post_list/date_header/date_header.js
  app/components/post_textbox/index.js
  app/components/progressive_image/index.js
  app/components/sidebars/main/drawer_swipper/drawer_swiper.js
  app/components/sidebars/main/drawer_swipper/index.js
  app/components/sidebars/main/index.js
  app/components/sidebars/main/main_sidebar.js
  app/components/sidebars/settings/index.js
  app/components/slide_up_panel/index.js
  app/components/swiper.js
  app/components/user_status/__snapshots__/user_status.test.js.snap
  app/screens/channel/channel.js
  app/screens/forgot_password/__snapshots__/forgot_password.test.js.snap
  app/screens/permalink/index.js
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  app/screens/post_options/post_options.js
  app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
  app/screens/reaction_list/reaction_list.js
  app/screens/search/search.js
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/thread/__snapshots__/thread.test.js.snap
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  app/store/index.js
  app/utils/network.js
  fastlane/Fastfile
  index.js
  ios/Mattermost.xcodeproj/project.pbxproj
  metro.config.js
  native_modules/RNCWKWebView.m
  native_modules/RNCWebViewManager.java
  package-lock.json
  package.json
  packager/moduleNames.js
  packager/modulePaths.js
Labels: 3: Reviews Complete

#2786 MM-15528: Updates to channel info for group-constrained channels.
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/index.js
  app/screens/channel_members/index.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#2791 MM-15059: Restict the permissions for guests
  app/components/sidebars/main/channels_list/list/index.js
  app/components/sidebars/main/channels_list/list/list.js
Labels: 3: Reviews Complete

#2720 v1.19 Changelog
  CHANGELOG.md
Labels: 2: Dev Review, 2: PM Review

#2755 Notification receipt delivery for Android and iOS
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.m
  ios/NotificationService/Info.plist
  ios/NotificationService/NotificationService.entitlements
  ios/NotificationService/NotificationService.swift
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: 3: Reviews Complete

#2737 [MM-14751] Take group_constrained into account when adding users to channels
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_add_members/index.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2802 MM-15518 Update rnfetchblob
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2792 MM-15427 Google Play 64-bit requirement compliance
  android/app/build.gradle
Labels: 3: Reviews Complete

#2797 MM-15481 close post menu when replying to a message
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/post_options/index.js
  app/screens/post_options/post_options.js
  app/screens/post_options/post_options.test.js
Labels: 3: Reviews Complete

#2800 Fix select default channel
  app/actions/views/channel.js
  package-lock.json
  package.json
  share_extension/android/actions/index.js
Labels: 3: Reviews Complete

#2798 MM-15282 Fix cutoff placeholder on Android
  app/components/post_textbox/post_textbox.js
  app/constants/post_textbox.js
Labels: 3: Reviews Complete

#2796 [MM-15407] Add ability to upload compiled app to S3 via fastlane with S3 path as "<s3_bucket>/<version_number>/<build_number>/<file>.(apk | ipa | app.zip)"
  Makefile
  fastlane/Fastfile
Labels: 3: Reviews Complete

#2799 MM-9494 & MM-13888 Tapping execute actions & interactive keyboard dismissal
  NOTICE.txt
  app/components/autocomplete/autocomplete.js
  app/components/autocomplete/index.js
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/custom_list/index.js
  app/components/edit_channel_info/index.js
  app/components/emoji/emoji.js
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/file_attachment_list/file_attachment_list.js
  app/components/file_upload_preview/file_upload_preview.js
  app/components/file_upload_preview/index.js
  app/components/layout/keyboard_layout/index.js
  app/components/post/post.js
  app/components/post_body/post_body.js
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/post_list.js
  app/components/post_textbox/post_textbox.js
  app/components/reactions/reactions.js
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/list.js
  app/mattermost.js
  app/screens/channel/channel.js
  app/screens/channel/channel_nav_bar/channel_search_button/channel_search_button.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.js
  app/screens/selector_screen/selector_screen.js
  app/screens/thread/__snapshots__/thread.test.js.snap
  app/screens/thread/thread.js
  app/utils/images.js
  assets/base/i18n/en.json
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/bundleReactNative.sh
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2810 MM-14802 Add autocorrect when editing a post
  app/screens/edit_post/edit_post.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2808 [MM-15695] Move i18n check from shared pipelines to makefile as i18n-extract-ci
  .gitignore
  Makefile
Labels: 3: Reviews Complete

#2814 Update mmjstool commit with fix on newline to end of file
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2816 Fix code so it can be parsed by mmjstool
  app/actions/views/channel.js
Labels: CherryPick/Approved

#2817 translations PR 20190522
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete

#2811 MM-15582 Don't show forgot password link without email/username login
  app/screens/login/login.js
  app/screens/login/login.test.js
  test/setup.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2818 Bump Version & Build number
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2819 Fix Build script apk location
  fastlane/Fastfile
Labels: CherryPick/Approved

#2820 move apk using the full path
  fastlane/Fastfile
Labels: CherryPick/Approved

#2821 Fix android release link
  fastlane/Fastfile
Labels: 2: Dev Review, CherryPick/Approved

#2822 Quick fix: link on Android beta signup message
  fastlane/Fastfile
Labels: CherryPick/Approved

#2823 Allow drawer pan responder when switching teams
  app/components/sidebars/drawer_layout.js
Labels: 2: Dev Review, CherryPick/Approved

#2824 update react-native-device-info crash fix
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2831 MM-15667 if post was removed exclude it from postsInChannel
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2834 Quick fix: build for unsigned and ios-sim-x86_64
  Makefile
Labels: 3: Reviews Complete

#2830 Fix autocomplete showing behind the keyboard on iOS and not working on Android
  app/components/post_body/post_body.js
  app/components/post_list/post_list.js
  app/components/post_textbox/post_textbox.android.js
  app/components/post_textbox/post_textbox.ios.js
  app/components/post_textbox/post_textbox_base.js
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/post_options/post_options.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.android.js
  app/screens/thread/thread.ios.js
  app/screens/thread/thread.ios.test.js
  app/screens/thread/thread_base.js
  package-lock.json
  package.json
  packager/moduleNames.js
  packager/modulePaths.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2836 MM-15643 Send user to settings when passcode is required
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/mattermost.js
  app/mattermost_managed/mattermost-managed.android.js
  app/mattermost_managed/mattermost-managed.ios.js
  assets/base/i18n/en.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/MattermostManaged.h
  ios/Mattermost/MattermostManaged.m
  ios/MattermostShare/Config.swift
  ios/MattermostShare/ShareViewController.swift
  ios/UploadAttachments/UploadAttachments.xcodeproj/project.pbxproj
  share_extension/android/extension_post/extension_post.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2835 MM-12320 - Change "about" section references to use the site name when it is configured
  app/screens/settings/general/settings.js
  app/screens/settings/settings_item/index.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#2839 MM-15575 Make Entry mount properly after hydration
  app/screens/entry/entry.js
Labels: 3: Reviews Complete

#2843 Bump app build number to 195
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#2840 MM-15575 Rename Constants.h to fix naming conflict
  ios/MattermostShare/MattermostShare-Bridging-Header.h
  ios/UploadAttachments/UploadAttachments.xcodeproj/project.pbxproj
  ios/UploadAttachments/UploadAttachments/MMMConstants.h
  ios/UploadAttachments/UploadAttachments/MMMConstants.m
  ios/UploadAttachments/UploadAttachments/MattermostBucket.m
  ios/UploadAttachments/UploadAttachments/StoreManager.m
  ios/UploadAttachments/UploadAttachments/UploadAttachments-Bridging-Header.h
Labels: 2: Dev Review

#2846 MM-15643 Better close app when checking for pin code
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/mattermost_managed/mattermost-managed.android.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2847 MM-15912 Fix uploads stuck at 100%
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
Labels: 2: Dev Review, CherryPick/Approved

#2849 Update missed MMMConstant.h reference
  ios/Mattermost/MattermostManaged.m
Labels: 3: Reviews Complete

#2852 [MM-15885] Configure telemetry on build
  fastlane/Fastfile
Labels: 3: Reviews Complete, CherryPick/Approved

#2850 Update netInfo to check for internet connectivity
  Makefile
  app/components/network_indicator/network_indicator.js
  app/utils/network.js
  native_modules/RNCNetInfo.m
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2853 Bump app build number to 196
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete
