Repository mattermost/mattermost-mobile, pull requests merged in 2019-02, with the labels that each got.

#2540 [MM-13839] Remove possibility to change eMail within mobile app
  app/screens/edit_profile/edit_profile.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2541 MM-13897 preserve iOS push notifications when opening the app
  app/push_notifications/push_notifications.ios.js
  app/screens/channel/channel.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
  ios/Mattermost/AppDelegate.m
Labels: 3: Ready to Merge, CherryPickApproved

#2537 MM-13859 set the auth token when fetching images from the server
  app/store/index.js
  app/utils/image_cache_manager.js
Labels: 3: Ready to Merge, CherryPickApproved

#2543 Bump app build number to 172
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2544 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#2547 translations PR 20190204
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2545 [MM-13677] Fix to ensure unsupported unicode emoji can be rendered jumbo size
  NOTICE.txt
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
  package-lock.json
  package.json
Labels: 2: Dev Review

#2550 Fix previewing doc files more than once on Android
  app/components/file_attachment_list/file_attachment_document.js
Labels: 3: Ready to Merge, CherryPickApproved

#2549 MM-13974 Missing translations
  app/components/sidebars/main/channels_list/list/list.js
  app/screens/edit_profile/edit_profile.js
  app/screens/settings/advanced_settings/advanced_settings.js
  app/screens/theme/__snapshots__/theme.test.js.snap
  app/screens/theme/theme.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2551 MM-13976 Fix placeholder image on Android when profile pic is removed
  app/components/profile_picture/profile_picture.js
Labels: 3: Ready to Merge, CherryPickApproved

#2554 Ensure schedule of session expired notification
  app/actions/views/login.js
  app/screens/login/login.js
  app/screens/select_server/index.js
  app/screens/select_server/select_server.js
  app/screens/sso/index.js
  app/screens/sso/sso.js
Labels: CherryPickApproved

#2555 Add support for relative permalinks
  app/components/markdown/markdown_link/markdown_link.js
  app/utils/url.js
Labels: 3: Ready to Merge, CherryPickApproved

#2557 Bump app build number to 173
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2558 MM-13337 Fix EMM connections using VPN on-demand
  app/fetch_preconfig.js
  app/screens/select_server/select_server.js
  app/utils/network.js
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPickApproved

#2566 MM-13428 Opening channels with unreads has loading indicator placed above unread messages line
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2563 [MM 13720] Fix for "No internet connection" banner not always showing
  app/components/network_indicator/network_indicator.js
Labels: 2: Dev Review

#2564 MM-14001 Don't mount PostBodyAdditionalContent for system messages
  app/components/post_body/post_body.js
  app/components/post_body/post_body.test.js
Labels: CherryPickApproved

#2565 translations PR 20190211
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 2: Dev Review

#2567 MM-14055: Load the channel even if not joining.
  app/screens/permalink/permalink.js
Labels: 2: Dev Review, CherryPickCandidate

#2569 [MM-13525] Fix alignment of count on channel drawer
  app/components/__snapshots__/badge.test.js.snap
  app/components/badge.js
  app/screens/channel/channel_nav_bar/channel_drawer_button.js
Labels: 2: Dev Review, CherryPickApproved

#2570 [MM 13934] Prevent blank mention keys from crashing the app
  app/components/markdown/transform.js
  app/components/markdown/transform.test.js
Labels: 2: Dev Review, CherryPickCandidate

#2542 Deep linking based on channel url
  app/actions/views/channel.js
  app/actions/views/root.test.js
  app/components/markdown/markdown_link/index.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/index.js
  app/components/post_list/post_list.test.js
  app/components/post_list/post_list_base.js
  app/constants/deep_linking.js
  app/constants/index.js
  app/utils/url.js
Labels: Hackfest

#2572 Bump app build number to 174
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2573 Bump app build number to 175
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2574 Update mattermost-redux to latest
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2529 v1.16 Changelog
  CHANGELOG.md
Labels: 3: Ready to Merge

#2548 MM-13896 Sync channel as read between clients (including opening Push Notifications)
  app/actions/views/channel.js
  app/actions/views/create_channel.js
  app/actions/views/root.js
  app/actions/views/select_team.js
  app/actions/views/user.js
  app/actions/views/user.test.js
  app/app.js
  app/components/channel_loader/channel_loader.js
  app/components/channel_loader/index.js
  app/components/network_indicator/index.js
  app/components/network_indicator/network_indicator.js
  app/constants/view.js
  app/mattermost.js
  app/reducers/views/channel.js
  app/screens/channel/channel.js
  app/screens/channel/channel_post_list/index.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
  app/screens/entry/entry.js
  app/screens/permalink/index.js
  app/screens/permalink/permalink.js
  app/screens/permalink/permalink.test.js
  app/screens/select_team/index.js
  app/screens/select_team/select_team.js
  app/screens/select_team/select_team.test.js
  app/utils/push_notifications.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2466 [MM-13295] Make channel link clickable for user who's not member of the public channel
  app/components/channel_link/channel_link.js
  app/components/channel_link/channel_link.test.js
  app/components/channel_link/index.js
  app/components/markdown/markdown.js
  app/components/post_body/post_body.js
Labels: 2: Dev Review, CherryPickApproved

#2556 Don't show confusing versioning message in "Check for Updates" screen…
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/constants/view.js
  app/screens/client_upgrade/client_upgrade.js
  app/screens/select_server/select_server.js
  app/utils/client_upgrade.js
Labels: 3: Ready to Merge

#2581 MM-14117 Fix opengraph and reactions for older servers
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/reactions/reactions.js
Labels: 3: Ready to Merge, CherryPickApproved

#2580 [MM-14017] Fix whitespace between input box and post list on iOS
  app/components/post_list/post_list.ios.js
  app/components/post_list/post_list_base.js
  app/constants/screen.js
  app/screens/thread/__snapshots__/thread.test.js.snap
  app/screens/thread/thread.js
Labels: CherryPickApproved

#2559 [MM-13975] Add Terms of Service and Privacy Policy Links
  app/screens/about/about.js
  assets/base/i18n/en.json
Labels: Hackfest

#2534 [MM-10346] Set CSRF Token from Cookie after Login / on App load
  app/actions/views/login.js
  app/actions/views/login.test.js
  app/app.js
  app/mattermost.js
  app/utils/security.js
Labels: 3: Ready to Merge

#2582 Prevent the app from crashing when file mime type is null
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
  android/app/src/main/java/com/mattermost/share/ShareModule.java
Labels: 3: Ready to Merge, CherryPickApproved

#2584 Bump app Version to 1.16.1 and Build Number to 176
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2576 Dependencies update
  Makefile
  android/app/build.gradle
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/java/com/mattermost/react_native_interface/ResolvePromise.java
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  app/actions/views/login.js
  app/components/profile_picture_button.js
  app/components/progressive_image/progressive_image.js
  app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
  app/screens/select_server/select_server.js
  app/screens/sso/sso.js
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/thread/__snapshots__/thread.test.js.snap
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.m
  native_modules/RNDocumentPicker.m
  package-lock.json
  package.json
  share_extension/android/extension_post/extension_post.js
  share_extension/android/navigation.js
  test/setup.js
Labels: 3: Ready to Merge, CherryPickApproved

#2577 [MM-10380] Migrate Android from GCM to FCM
  android/app/build.gradle
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPickApproved

#2586 Fix utils reference
  app/app.js
Labels: 2: Dev Review

#2587 Update mattermost-redux
  package-lock.json
  package.json
Labels: 2: Dev Review

#2589 v1.16.1 changelog
  CHANGELOG.md
Labels: 3: Ready to Merge

#2591 [MM-14193] Render emojis in Message Attachment title
  app/components/message_attachments/attachment_title.js
  app/components/message_attachments/message_attachment.js
Labels: 3: Ready to Merge, Hackfest

#2594 [MM-14044] Fix for "No internet connection" not showing up for a minute after connection loss
  app/utils/network.js
Labels: 3: Ready to Merge, CherryPickApproved

#2585 Update Android RAM Bundle
  packager/README.md
  packager/moduleNames.js
  packager/modulePaths.js
Labels: 2: Dev Review, CherryPickApproved

#2592 fix README.md formatting
  README.md
Labels: 3: Ready to Merge, Hackfest

#2595 translations PR 20190225
  assets/base/i18n/pl.json
  assets/base/i18n/ro.json
Labels: 3: Ready to Merge

#2553 MM-13957 Reorganize post actions
  app/actions/views/post.js
  app/actions/views/root.js
  package-lock.json
  package.json
Labels: Awaiting PR

#2602 Bump Version to 1.17.0 Build 177
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 3: Ready to Merge, CherryPickApproved

#2603 Update sentry to fix android build
  ios/Mattermost.xcodeproj/project.pbxproj
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPickApproved

#2606 Handle pending posts when dispatching RECEIVED_NEW_POST
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPickApproved

#2608 Fix crash when fresh install android when getting the fcm token
  android/app/build.gradle
  android/build.gradle
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPickApproved

#2601 Add coverage to .gitignore
  .gitignore
Labels: 3: Ready to Merge, Hackfest
