Repository mattermost/mattermost-mobile, pull requests merged in 2019-04, with the labels that each got.

#2406 MM-13151 Increase double tap delay for post action buttons
  app/components/message_attachments/action_button/action_button.js
  app/utils/tap.js
Labels: 3: Ready to Merge

#2685 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#2687 translations PR 20190401
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2686 [MM-14698] Add CSRF Header in File Upload and Profile Image Set Operations
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
  app/screens/edit_profile/edit_profile.js
Labels: 3: Ready to Merge, CherryPickApproved

#2694 [MM-13516] Update commit of commonmark.js that fixes "blank spaces break markdown table"
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2695 Bump app build number to 184
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 2: Dev Review, CherryPickApproved

#2699 MM-14960 Use the correct icon set for channel types
  app/components/channel_icon.js
  app/components/vector_icon.js
Labels: 2: Dev Review, CherryPickApproved

#2704 translations PR 20190408
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/zh-TW.json
Labels: 3: Ready to Merge

#2640 [MM-14823] Render emojis in Interactive Message Buttons
  app/components/message_attachments/action_button/action_button.js
  app/components/message_attachments/action_button/action_button_text.js
  app/components/message_attachments/action_button/action_button_text.test.js
  app/utils/emoji_utils.js
Labels: 3: Ready to Merge

#2698 MM-14959 iOS Share Extension channel search open by default
  ios/MattermostShare/ChannelsViewController.swift
  ios/MattermostShare/ShareViewController.swift
  ios/MattermostShare/TeamsViewController.swift
Labels: 3: Ready to Merge, CherryPickApproved

#2703 MM-14351: Improving translation strings for intro text in channels
  app/components/channel_intro/channel_intro.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge

#2708 Bump app build number to 185
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 2: Dev Review, CherryPickApproved

#2688 Proposed changelog update regarding AppConfig compatability
  CHANGELOG.md
Labels: 3: Ready to Merge

#2716 Bump app build number to 186
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
Labels: 2: Dev Review, CherryPickApproved

#2717 DateHeader rendering bug fix
  app/screens/flagged_posts/flagged_posts.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/search/search.js
Labels: 3: Ready to Merge

#2671 v1.18 Changelog
  CHANGELOG.md
Labels: 2: Dev Review, 2: PM Review

#2674 Creating the concept of RedirectChannel and use it before the DefaultChannel when we are redirecting the user
  app/actions/views/channel.js
  package-lock.json
  package.json
  share_extension/android/actions/index.js
  share_extension/common/selectors/index.js
Labels: 3: Ready to Merge, Awaiting PR

#2711 MM-14417: Add messaging for channel mentions of users not in constrai…
  app/components/post_add_channel_member/post_add_channel_member.js
  app/components/post_body/post_body.js
  assets/base/i18n/en.json
Labels: 3: Ready to Merge, Awaiting PR

#2726 v1.18.1 Changelog
  CHANGELOG.md
Labels: Work In Progress

#2724 MM-14741 Add default option to post action dropdown
  app/components/message_attachments/action_menu/action_menu.js
  app/components/message_attachments/action_menu/action_menu.test.js
  app/components/message_attachments/attachment_actions.js
Labels: 3: Ready to Merge

#2734 translations PR 20190422
  assets/base/i18n/es.json
  assets/base/i18n/it.json
  assets/base/i18n/ro.json
  assets/base/i18n/tr.json
Labels: 2: Dev Review

#2710 MM-15050 Reminder message (`/remind`) do not show message text on mobile.
  app/components/post_body/post_body.js
Labels: 3: Ready to Merge, CherryPickApproved

#2718 [MM-14619] Remove Client4.online and related setOnline function
  app/actions/device/index.js
  app/fetch_preconfig.js
  app/mattermost.js
  app/screens/select_server/select_server.js
  package-lock.json
  package.json
Labels: CherryPickApproved

#2713 MM-14907 RN: iOS - No MattermostShare error when sharing text that is over server's max post size
  ios/MattermostShare/ShareViewController.swift
  ios/UploadAttachments/UploadAttachments/Constants.h
  ios/UploadAttachments/UploadAttachments/Constants.m
  ios/UploadAttachments/UploadAttachments/StoreManager.h
  ios/UploadAttachments/UploadAttachments/StoreManager.m
Labels: CherryPickApproved

#2663 [MM-12599] Implement assets for Adaptive icons
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  assets/base/release/icons/android/mipmap-anydpi-v26/ic_launcher.xml
  assets/base/release/icons/android/mipmap-anydpi-v26/ic_launcher_round.xml
  assets/base/release/icons/android/mipmap-hdpi/ic_launcher_background.png
  assets/base/release/icons/android/mipmap-hdpi/ic_launcher_foreground.png
  assets/base/release/icons/android/mipmap-hdpi/ic_launcher_round.png
  assets/base/release/icons/android/mipmap-hdpi/ic_notification.png
  assets/base/release/icons/android/mipmap-mdpi/ic_launcher_background.png
  assets/base/release/icons/android/mipmap-mdpi/ic_launcher_foreground.png
  assets/base/release/icons/android/mipmap-mdpi/ic_launcher_round.png
  assets/base/release/icons/android/mipmap-mdpi/ic_notification.png
  assets/base/release/icons/android/mipmap-xhdpi/ic_launcher_background.png
  assets/base/release/icons/android/mipmap-xhdpi/ic_launcher_foreground.png
  assets/base/release/icons/android/mipmap-xhdpi/ic_launcher_round.png
  assets/base/release/icons/android/mipmap-xhdpi/ic_notification.png
  assets/base/release/icons/android/mipmap-xxhdpi/ic_launcher_background.png
  assets/base/release/icons/android/mipmap-xxhdpi/ic_launcher_foreground.png
  assets/base/release/icons/android/mipmap-xxhdpi/ic_launcher_round.png
  assets/base/release/icons/android/mipmap-xxhdpi/ic_notification.png
  assets/base/release/icons/android/mipmap-xxxhdpi/ic_launcher_background.png
  assets/base/release/icons/android/mipmap-xxxhdpi/ic_launcher_foreground.png
  assets/base/release/icons/android/mipmap-xxxhdpi/ic_launcher_round.png
  assets/base/release/icons/android/mipmap-xxxhdpi/ic_notification.png
Labels: 1: Needs dev testing, 2: Dev Review

#2677 [MM-9454] Added fade to send button
  app/components/__mocks__/react.js
  app/components/__snapshots__/fade.test.js.snap
  app/components/__snapshots__/send_button.test.js.snap
  app/components/fade.js
  app/components/fade.test.js
  app/components/post_textbox/post_textbox.js
  app/components/send_button.js
  app/components/send_button.test.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2741 Remove the RN bridge from MattermostManaged
  app/fetch_preconfig.js
  app/mattermost_managed/mattermost-managed.ios.js
  ios/Mattermost/MattermostManaged.h
  ios/Mattermost/MattermostManaged.m
Labels: 3: Ready to Merge

#2754 Fix mattermostManaged event name
  app/components/post_list/post_list_base.js
  app/screens/flagged_posts/flagged_posts.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/search/search.js
Labels: 3: Ready to Merge

#2731 Allow user to install mattermost on sd card
  android/app/src/main/AndroidManifest.xml
Labels: 2: Dev Review

#2747 MM-14885 Android use sender_name in push notifications
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 3: Ready to Merge
