Repository mattermost/mattermost-mobile, pull requests merged in 2020-02, with the labels that each got.

#3879 MM-22165 Fix channel sidebar close gesture
  app/components/sidebars/drawer_layout.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3882 Automated cherry pick of #3879
  app/components/sidebars/drawer_layout.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3887 Automated cherry pick of #3884
  app/push_notifications/push_notifications.android.js
  app/push_notifications/push_notifications.ios.js
  app/utils/push_notifications.test.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.h
  ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3760 Mm 10601 - Use Enter Key to send message on Hardware Keyboards
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/components/post_textbox/post_textbox_base.js
  ios/Mattermost/AppDelegate.m
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#3889 Automated cherry pick of #3888
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3893 Automated cherry pick of #3890
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3895 Automated cherry pick of #3892
  app/components/post_textbox/components/camera_button.js
  app/components/post_textbox/components/camera_button.test.js
  app/components/post_textbox/components/file_upload_button.js
  app/components/post_textbox/components/file_upload_button.test.js
  app/components/post_textbox/components/image_upload_button.js
  app/components/post_textbox/components/image_upload_button.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3894 [MM-22344] Remove ChannelPeek
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
  app/components/sidebars/main/channels_list/channels_list.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/main_sidebar.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel_peek/channel_peek.js
  app/screens/channel_peek/index.js
  app/screens/index.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3897 Automated cherry pick of #3894
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
  app/components/sidebars/main/channels_list/channels_list.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/main_sidebar.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel_peek/channel_peek.js
  app/screens/channel_peek/index.js
  app/screens/index.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3899 Automated cherry pick of #3891
  app/screens/image_preview/downloader.ios.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3900 MM-22253 Reduce unnecessary re-renders in channel switching
  app/components/post_list/new_messages_divider.js
  app/components/post_list/post_list.js
  app/screens/channel/channel_post_list/channel_post_list.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3901 Automated cherry pick of #3900
  app/components/post_list/new_messages_divider.js
  app/components/post_list/post_list.js
  app/screens/channel/channel_post_list/channel_post_list.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3905 Automated cherry pick of #3898
  app/components/conditionalWrapper.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
  app/components/file_upload_preview/file_upload_preview.js
  app/components/file_upload_preview/file_upload_remove.js
  app/components/file_upload_preview/file_upload_retry.js
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
  app/components/post_textbox/post_textbox_base.js
  app/constants/view.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3906 Automated cherry pick of #3902
  app/mattermost.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3907 Re-enable ram-bundles
  android/app/build.gradle
  app/mattermost_managed/mattermost-managed.android.js
  app/screens/channel/channel.android.js
  app/screens/index.js
  app/store/utils.js
  app/utils/segment.js
  app/utils/sentry/index.js
  app/utils/sentry/middleware.js
  index.js
  metro.config.js
  package-lock.json
  packager/moduleNames.js
  packager/modulePaths.js
  share_extension/android/index.js
Labels: 2: Dev Review, CherryPick/Approved

#3908 Automated cherry pick of #3907
  android/app/build.gradle
  app/mattermost_managed/mattermost-managed.android.js
  app/screens/channel/channel.android.js
  app/screens/index.js
  app/store/utils.js
  app/utils/segment.js
  app/utils/sentry/index.js
  app/utils/sentry/middleware.js
  index.js
  metro.config.js
  packager/moduleNames.js
  packager/modulePaths.js
  share_extension/android/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3910 Automated cherry pick of #3909
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3912 translations PR 20200211
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 2: Dev Review

#3914 Bump app build number to 266
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3915 Automated cherry pick of #3914
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3916 MM-22487 Fix race condition causing the user to logout
  app/screens/channel/channel_base.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3918 Automated cherry pick of #3917
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3926 Automated cherry pick of #3925
  ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3928 Automated cherry pick of #3927
  android/app/build.gradle
  fastlane/metadata/android/en-US/full_description.txt
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3817 v1.28 Changelog
  CHANGELOG.md
  README.md
Labels: 2: PM Review

#3919 MM-20184 Remove ios drawer hack and Fix right drawer partially shown …
  app/components/sidebars/drawer_layout.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3932 Automated cherry pick of #3913
  patches/react-native-notifications+2.0.6.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3933 Automated cherry pick of #3919
  app/components/sidebars/drawer_layout.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3936 Automated cherry pick of #3935
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3943 Automated cherry pick of #3942
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3944 Update mm-redux
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Done

#3931 [MM-22629] Center-align tall & thin image attachments
  app/components/file_attachment_list/file_attachment_image.js
Labels: CherryPick/Approved, QA Review Done

#3945 Automated cherry pick of #3931
  app/components/file_attachment_list/file_attachment_image.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3954 Automated cherry pick of #3952
  patches/rn-fetch-blob+0.12.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3955 Automated cherry pick of #3953
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3956 Automated cherry pick of #3923
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3950 [MM-22129] - Change "Copy Permalink" text in post options menu
  app/screens/post_options/post_options.js
  assets/base/i18n/en.json
Labels: 2: PM Review, 2: QA Review, CherryPick/Approved

#3957 Automated cherry pick of #3950
  app/screens/post_options/post_options.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3961 translations PR 20200225
  assets/base/i18n/nl.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/uk.json
Labels: 3: Reviews Complete

#3947 Update redux to include new changes
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3963 Update redux (#3947)
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3962 Update Fastlane
  fastlane/Gemfile.lock
Labels: 3: Reviews Complete, CherryPick/Approved

#3966 Automated cherry pick of #3962
  fastlane/Gemfile.lock
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3967 Fix in-app notification crashing when receiving multiple
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/screens/notification/notification.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3969 Automated cherry pick of #3967
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/screens/notification/notification.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3951 MM-13669: Fix stutter on long reaction lists
  app/components/slide_up_panel/slide_up_panel.js
Labels: 3: Reviews Complete

#3958 Update mattermost-redux version to latest
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3922 MM-22375: Remove mark as unread post option in archived channels
  app/screens/post_options/index.js
  app/screens/post_options/index.test.js
Labels: 3: Reviews Complete, QA Review Done

#3885 MM-12148: Prevent emdash convert in a Code Block on ios
  app/components/post_textbox/post_textbox_base.js
  app/screens/edit_post/edit_post.js
  app/utils/markdown.js
  app/utils/markdown.test.js
Labels: 3: Reviews Complete, QA Review Done

#3663 [MM-20804] Add "Unarchive Channel" option to the channel info screen
  app/components/post_body/__snapshots__/system_message_helpers.test.js.snap
  app/components/post_body/system_message_helpers.js
  app/components/post_body/system_message_helpers.test.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/index.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3896 MM-10160 - support interactive button styles
  app/components/message_attachments/action_button/action_button.js
  app/components/message_attachments/action_button/action_button.test.js
  app/components/message_attachments/attachment_actions.js
  app/components/message_attachments/message_attachment.js
  app/constants/colors.js
Labels: 3: Reviews Complete, QA Review Done

#3875 [MM-21923] Enforce channel mentions permission
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/at_mention/index.js
  app/components/post_textbox/index.js
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
Labels: 3: Reviews Complete, QA Review Done

#3964 Fetch archived channels
  app/actions/views/channel.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3973 Automated cherry pick of #3964
  app/actions/views/channel.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3970 [MM-22687] Update Android downloader
  app/screens/image_preview/downloader.android.js
  assets/base/i18n/en.json
Labels: CherryPick/Approved, QA Review Done

#3974 Automated cherry pick of #3970
  app/screens/image_preview/downloader.android.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3971 MM-22379 & MM-22598 Boost perf by using FastImage cache in favor of ImageCacheManager
  app/components/emoji/emoji.js
  app/components/file_attachment_list/file_attachment_document/file_attachment_document.js
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/message_attachments/attachment_image/index.js
  app/components/message_attachments/attachment_image/index.test.js
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/profile_picture/profile_picture.js
  app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
  app/components/progressive_image/progressive_image.js
  app/components/progressive_image/progressive_image.test.js
  app/components/team_icon/team_icon.js
  app/init/global_event_handler.js
  app/utils/file.js
  package-lock.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3976 Automated cherry pick of #3971
  app/components/emoji/emoji.js
  app/components/file_attachment_list/file_attachment_document/file_attachment_document.js
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/message_attachments/attachment_image/index.js
  app/components/message_attachments/attachment_image/index.test.js
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/profile_picture/profile_picture.js
  app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
  app/components/progressive_image/progressive_image.js
  app/components/progressive_image/progressive_image.test.js
  app/components/team_icon/team_icon.js
  app/init/global_event_handler.js
  app/utils/file.js
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3921 MM-21276 & MM-22419 Fix PostList insets and Channel Intro
  app/components/channel_intro/channel_intro.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-keyboard-tracking-view+5.6.1.patch
Labels: CherryPick/Approved, QA Review Done

#3977 Automated cherry pick of #3921
  app/components/channel_intro/channel_intro.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-keyboard-tracking-view+5.6.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3979 Automated cherry pick of #3940
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
