Repository mattermost/mattermost-mobile, pull requests merged in 2020-10, with the labels that each got.

#4856 Automated cherry pick of #4853
  app/components/post_draft/uploads/upload_item/upload_item.js
  app/components/post_draft/uploads/upload_item/upload_remove.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4836 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#4859 Automated cherry pick of #4836
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4861 Automated cherry pick of #4860
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/message_attachments/attachment_author.js
  app/components/message_attachments/attachment_title.js
  app/screens/client_upgrade/client_upgrade.js
  app/screens/settings/general/settings.js
  app/utils/supported_server.ts
  assets/base/i18n/en.json
  test/setup.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4862 Automated cherry pick of #4857
  assets/base/i18n/en.json
  ios/MattermostShare/ShareViewController.swift
  ios/UploadAttachments/UploadAttachments/StoreManager.h
  ios/UploadAttachments/UploadAttachments/StoreManager.m
  share_extension/android/extension_post/extension_post.js
  share_extension/android/extension_post/extension_post.test.js
  share_extension/android/extension_post/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4865 Automated cherry pick of #4864
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4871 Fix typo in 3 files: consecutive occurrences of 'the'
  app/mm-redux/actions/posts.ts
  app/mm-redux/utils/helpers.ts
  detox/e2e/support/server_api/post.js
Labels: 4: Reviews Complete, Hacktoberfest

#4868 [MM-29275]: Remove first char of slash cmd autocomplete suggestion text, only if it is a top-level command
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4873 Automated cherry pick of #4868
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4875 Automated cherry pick of #4872
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4877 Automated cherry pick of #4876
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4833 MM-T3187 Unread channels sort at top
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channels_list.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
  detox/e2e/test/smoke_test/channels.e2e.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4852 MM-29083 Detox/E2E: Make error handling on unreachable server to be explicit
  detox/e2e/init.js
  detox/e2e/support/server_api/common.js
  detox/e2e/support/server_api/setup.js
  detox/e2e/support/server_api/system.js
Labels: 4: Reviews Complete

#4855 MM-29046 Add unit and e2e tests for autocomplete popover
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/date_suggestion/date_suggestion.js
  app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/edit_channel_info/edit_channel_info.js
  app/components/search_bar/index.js
  app/screens/channel/channel_nav_bar/channel_search_button/__snapshots__/channel_search_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_search_button/channel_search_button.js
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  app/screens/edit_post/__snapshots__/edit_post.test.js.snap
  app/screens/edit_post/edit_post.js
  app/screens/search/modifier.js
  app/screens/search/search.js
  detox/e2e/test/autocomplete/edit_channel.e2e.js
  detox/e2e/test/autocomplete/edit_post.e2e.js
  detox/e2e/test/autocomplete/post_draft.e2e.js
  detox/e2e/test/autocomplete/search.e2e.js
Labels: 2: Dev Review

#4878 Detox/E2E: Add E2E comment guideline
  detox/e2e/test/messaging/message_posting.e2e.js
  detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
  detox/e2e/test/on_boarding/login.e2e.js
  detox/e2e/test/smoke_test/login_email.e2e.js
Labels: 4: Reviews Complete

#4886 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/ko.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
Labels: 4: Reviews Complete

#4885 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/ko.json
  assets/base/i18n/uk.json
Labels: 4: Reviews Complete

#4863 MM-T3180 Detox/E2E for LDAP login
  .gitignore
  detox/e2e/support/fixtures/ldap_users.json
  detox/e2e/support/server_api/common.js
  detox/e2e/support/server_api/index.js
  detox/e2e/support/server_api/ldap.js
  detox/e2e/support/server_api/system.js
  detox/e2e/support/server_api/team.js
  detox/e2e/support/server_api/user.js
  detox/e2e/support/test_config.js
  detox/e2e/support/ui/screen.js
  detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
  detox/e2e/test/on_boarding/login.e2e.js
  detox/e2e/test/smoke_test/login_email.e2e.js
  detox/e2e/test/smoke_test/login_ldap.e2e.js
  detox/package-lock.json
  detox/package.json
Labels: 4: Reviews Complete

#4889 Detox/E2E: Added missing comment guideline
  detox/e2e/test/autocomplete/edit_channel.e2e.js
  detox/e2e/test/autocomplete/edit_post.e2e.js
  detox/e2e/test/autocomplete/post_draft.e2e.js
  detox/e2e/test/autocomplete/search.e2e.js
  detox/e2e/test/smoke_test/channels.e2e.js
  detox/e2e/test/smoke_test/login_ldap.e2e.js
Labels: 4: Reviews Complete

#4888 MM-28653 Detox/E2E: Add jest-junit, jest-html-reporters and pathbuilders for test report/artifacts
  .gitignore
  detox/.detoxrc.json
  detox/e2e/config.js
  detox/e2e/config.json
  detox/e2e/path_builder.js
  detox/package-lock.json
  detox/package.json
Labels: 4: Reviews Complete

#4879 MM-29039: unit and e2e tests for #4821
  app/screens/long_post/__snapshots__/long_post.test.js.snap
  app/screens/select_server/select_server.test.js
  app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
  detox/e2e/test/on_boarding/login.e2e.js
  test/setup.js
Labels: 4: Reviews Complete

#4867 MM-T3201 create public channel e2e test
  app/components/channel_intro/channel_intro.js
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/edit_channel_info/edit_channel_info.js
  app/components/sidebars/main/channels_list/list/list.js
  app/screens/create_channel/create_channel.js
  app/screens/more_channels/more_channels.js
  detox/e2e/test/channels/create_public_channel.e2e.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4896 Update README.md
  README.md
Labels: 2: Dev Review

#4887 MM-28539 Fix wrong participant count in GM info
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/components/channel_icon.js
  app/components/custom_list/custom_list_row.js
  app/components/custom_list/index.js
  app/components/custom_list/user_list_row/user_list_row.js
  app/components/layout/keyboard_layout/keyboard_layout.js
  app/components/post_body/post_body.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/settings/settings_sidebar_base.js
  app/components/slide_up_panel/slide_up_panel.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_nav_bar/__snapshots__/settings_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/settings_drawer_button.js
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/index.js
  app/screens/edit_post/edit_post.js
  app/screens/more_dms/more_dms.js
  detox/e2e/support/ui/screen.js
  detox/e2e/test/autocomplete/edit_channel.e2e.js
  detox/e2e/test/autocomplete/edit_post.e2e.js
  detox/e2e/test/autocomplete/post_draft.e2e.js
  detox/e2e/test/autocomplete/search.e2e.js
  detox/e2e/test/channel_info/header.e2e.js
  detox/e2e/test/messaging/message_posting.e2e.js
  detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
  detox/e2e/test/on_boarding/login.e2e.js
  detox/e2e/test/smoke_test/channels.e2e.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4880 [MM-22366] Make user autocomplete also match on spaces
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/at_mention_item/at_mention_item.js
  app/constants/autocomplete.js
  app/selectors/autocomplete.js
  app/selectors/autocomplete.test.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4901 Automated cherry pick of #4880
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/at_mention_item/at_mention_item.js
  app/constants/autocomplete.js
  app/selectors/autocomplete.js
  app/selectors/autocomplete.test.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4903 MM-28539 Fix wrong participant count in GM info (#4887)
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/components/channel_icon.js
  app/components/custom_list/custom_list_row.js
  app/components/custom_list/index.js
  app/components/custom_list/user_list_row/user_list_row.js
  app/components/layout/keyboard_layout/keyboard_layout.js
  app/components/post_body/post_body.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/settings/settings_sidebar_base.js
  app/components/slide_up_panel/slide_up_panel.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_nav_bar/__snapshots__/settings_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/settings_drawer_button.js
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/index.js
  app/screens/edit_post/edit_post.js
  app/screens/more_dms/more_dms.js
  detox/e2e/support/ui/screen.js
  detox/e2e/test/channel_info/header.e2e.js
  detox/e2e/test/messaging/message_posting.e2e.js
  detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
  detox/e2e/test/on_boarding/login.e2e.js
Labels: CherryPick/Done

#4893 Refactor Android Share extension (js)
  android/app/src/main/java/com/mattermost/share/ShareActivity.java
  app/actions/views/channel.js
  app/constants/view.js
  app/mm-redux/types/module.d.ts
  app/reducers/views/extension.js
  app/reducers/views/index.js
  app/store/index.ts
  app/utils/file.js
  babel.config.js
  index.js
  package-lock.json
  package.json
  share_extension/actions/index.ts
  share_extension/android/actions/index.js
  share_extension/android/extension_channels/extension_channel_item.js
  share_extension/android/extension_channels/extension_channels.js
  share_extension/android/extension_channels/index.js
  share_extension/android/extension_post/channel_button/channel_button.js
  share_extension/android/extension_post/channel_button/index.js
  share_extension/android/extension_post/extension_post.js
  share_extension/android/extension_post/extension_post.test.js
  share_extension/android/extension_post/index.js
  share_extension/android/extension_post/team_button/index.js
  share_extension/android/extension_post/team_button/team_button.js
  share_extension/android/extension_teams/extension_teams.js
  share_extension/android/extension_teams/index.js
  share_extension/android/extension_teams/team_item/index.js
  share_extension/android/extension_teams/team_item/team_item.js
  share_extension/android/index.js
  share_extension/common/selectors/index.js
  share_extension/components/body.tsx
  share_extension/components/channel_button.tsx
  share_extension/components/channel_item.tsx
  share_extension/components/channel_type.tsx
  share_extension/components/chars_remaining.tsx
  share_extension/components/close_header_button.tsx
  share_extension/components/error.tsx
  share_extension/components/files.tsx
  share_extension/components/image_file.tsx
  share_extension/components/other_file.tsx
  share_extension/components/post_header_button.tsx
  share_extension/components/team_button.tsx
  share_extension/components/team_item.tsx
  share_extension/components/video_file.tsx
  share_extension/index.tsx
  share_extension/screens/channel_list.tsx
  share_extension/screens/extension.tsx
  share_extension/screens/navigation.tsx
  share_extension/screens/share.tsx
  share_extension/screens/team_list.tsx
  share_extension/selectors/index.ts
  share_extension/types/index.d.ts
  share_extension/utils/index.tsx
  tsconfig.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4904 Automated cherry pick of #4893
  android/app/src/main/java/com/mattermost/share/ShareActivity.java
  app/actions/views/channel.js
  app/constants/view.js
  app/mm-redux/types/module.d.ts
  app/reducers/views/extension.js
  app/reducers/views/index.js
  app/store/index.ts
  app/utils/file.js
  babel.config.js
  index.js
  package-lock.json
  package.json
  share_extension/actions/index.ts
  share_extension/android/actions/index.js
  share_extension/android/extension_channels/extension_channel_item.js
  share_extension/android/extension_channels/extension_channels.js
  share_extension/android/extension_channels/index.js
  share_extension/android/extension_post/channel_button/channel_button.js
  share_extension/android/extension_post/channel_button/index.js
  share_extension/android/extension_post/extension_post.js
  share_extension/android/extension_post/extension_post.test.js
  share_extension/android/extension_post/index.js
  share_extension/android/extension_post/team_button/index.js
  share_extension/android/extension_post/team_button/team_button.js
  share_extension/android/extension_teams/extension_teams.js
  share_extension/android/extension_teams/index.js
  share_extension/android/extension_teams/team_item/index.js
  share_extension/android/extension_teams/team_item/team_item.js
  share_extension/android/index.js
  share_extension/common/selectors/index.js
  share_extension/components/body.tsx
  share_extension/components/channel_button.tsx
  share_extension/components/channel_item.tsx
  share_extension/components/channel_type.tsx
  share_extension/components/chars_remaining.tsx
  share_extension/components/close_header_button.tsx
  share_extension/components/error.tsx
  share_extension/components/files.tsx
  share_extension/components/image_file.tsx
  share_extension/components/other_file.tsx
  share_extension/components/post_header_button.tsx
  share_extension/components/team_button.tsx
  share_extension/components/team_item.tsx
  share_extension/components/video_file.tsx
  share_extension/index.tsx
  share_extension/screens/channel_list.tsx
  share_extension/screens/extension.tsx
  share_extension/screens/navigation.tsx
  share_extension/screens/share.tsx
  share_extension/screens/team_list.tsx
  share_extension/selectors/index.ts
  share_extension/types/index.d.ts
  share_extension/utils/index.tsx
  tsconfig.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4894 MM-28336 Align hamburger menu badges
  .circleci/config.yml
  app/constants/view.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
  fastlane/Fastfile
  fastlane/plist.erb
Labels: 4: Reviews Complete, CherryPick/Approved

#4905 Automated cherry pick of #4894
  .circleci/config.yml
  app/constants/view.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
  fastlane/Fastfile
  fastlane/plist.erb
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4897 MM-28688 Close sidebar when current channel is selected
  app/components/sidebars/main/drawer_swiper/drawer_swiper.js
  app/components/sidebars/main/main_sidebar_base.js
  app/components/swiper.js
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  detox/e2e/support/utils.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
  detox/e2e/test/channels/create_public_channel.e2e.js
  detox/e2e/test/main_sidebar/select_channel.e2e.js
  detox/e2e/test/smoke_test/login_email.e2e.js
  detox/e2e/test/smoke_test/login_ldap.e2e.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4906 Manual Cherry pick #4897
  app/components/sidebars/main/drawer_swiper/drawer_swiper.js
  app/components/sidebars/main/main_sidebar_base.js
  app/components/swiper.js
  app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
  app/screens/channel/channel_nav_bar/channel_title/channel_title.js
  detox/e2e/support/utils.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
  detox/e2e/test/main_sidebar/select_channel.e2e.js
  detox/e2e/test/smoke_test/login_email.e2e.js
Labels: 4: Reviews Complete, CherryPick/Candidate

#4907 Bump Version to 1.37.0 and Build to 331
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4908 Automated cherry pick of #4907
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4909 Update rudderStack
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4910 Automated cherry pick of #4909
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4912 Upgrade rudderstack attempt 2
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4913 Automated cherry pick of #4912
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4915 MM-28105 do not crash when in-app notification shows
  app/components/reaction_picker/__snapshots__/reaction_picker.test.js.snap
  app/components/reaction_picker/reaction_picker.js
  app/init/push_notifications.js
  app/screens/add_reaction/index.js
  app/screens/index.js
  app/screens/notification/__snapshots__/notification.test.js.snap
  app/screens/notification/index.js
  app/screens/notification/index.tsx
  app/screens/notification/notification.js
  app/screens/notification/notification.test.js
  app/screens/notification/notification_icon.tsx
  app/screens/notification/notification_title.tsx
  app/types/push_notification.d.ts
  assets/base/i18n/en.json
  detox/e2e/test/channel_info/header.e2e.js
  detox/e2e/test/channels/create_public_channel.e2e.js
  detox/e2e/test/in_app_notification/notification.e2e.js
  detox/e2e/test/messaging/message_posting.e2e.js
  patches/react-native-notifications+2.1.7.patch
  scripts/pre-commit.sh
Labels: 4: Reviews Complete, CherryPick/Approved

#4918 MM-28968 Fix redux-persist serializer
  app/store/index.ts
  app/store/utils.js
  app/store/utils.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4916 MM-29620 Add props to post input to prevent autofill
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4920 Automated cherry pick of #4918
  app/store/index.ts
  app/store/utils.js
  app/store/utils.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4921 Automated cherry pick of #4916
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4919 Detox/E2E: Fix some specs and comments
  detox/e2e/test/autocomplete/edit_channel.e2e.js
  detox/e2e/test/autocomplete/edit_post.e2e.js
  detox/e2e/test/channels/create_public_channel.e2e.js
  detox/e2e/test/in_app_notification/notification.e2e.js
  detox/e2e/test/main_sidebar/select_channel.e2e.js
  detox/e2e/test/messaging/message_posting.e2e.js
  detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
  detox/e2e/test/on_boarding/login.e2e.js
  detox/e2e/test/smoke_test/channels.e2e.js
Labels: 4: Reviews Complete

#4834 [MM-25349] centre failed network action component and improve responsiveness to orientation change
  app/components/failed_network_action/cloud.js
  app/components/failed_network_action/failed_network_action.js
  app/components/failed_network_action/failed_network_action.test.js
  app/components/failed_network_action/index.js
  app/screens/error_teams_list/__snapshots__/error_teams_list.test.js.snap
  app/screens/flagged_posts/__snapshots__/flagged_posts.test.js.snap
  app/screens/pinned_posts/__snapshots__/pinned_posts.test.js.snap
  app/screens/recent_mentions/__snapshots__/recent_mentions.test.js.snap
  app/screens/select_team/__snapshots__/select_team.test.js.snap
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
Labels: 4: Reviews Complete

#4924 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 2: Dev Review

#4925 Translations update from Weblate
  assets/base/i18n/es.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
Labels: 2: Dev Review

#4926 MM-29252 Tapping on invalid permalink shows an error
  app/actions/views/channel.js
  app/actions/views/permalink.ts
  app/components/post_body/system_message_helpers.js
  app/components/post_list/index.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/index.js
  app/screens/flagged_posts/flagged_posts.js
  app/screens/flagged_posts/flagged_posts.test.js
  app/screens/flagged_posts/index.js
  app/screens/permalink/permalink.js
  app/screens/pinned_posts/index.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/pinned_posts/pinned_posts.test.js
  app/screens/recent_mentions/index.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/recent_mentions/recent_mentions.test.js
  app/screens/search/index.js
  app/screens/search/search.js
  app/utils/general.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4929 Automated cherry pick of #4926
  app/actions/views/channel.js
  app/actions/views/permalink.ts
  app/components/post_body/system_message_helpers.js
  app/components/post_list/index.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/index.js
  app/screens/flagged_posts/flagged_posts.js
  app/screens/flagged_posts/flagged_posts.test.js
  app/screens/flagged_posts/index.js
  app/screens/permalink/permalink.js
  app/screens/pinned_posts/index.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/pinned_posts/pinned_posts.test.js
  app/screens/recent_mentions/index.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/recent_mentions/recent_mentions.test.js
  app/screens/search/index.js
  app/screens/search/search.js
  app/utils/general.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4927 MM-29948 Display error msg when pasting files and uploads are disabled
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/uploads/index.js
  app/components/post_draft/uploads/uploads.js
  app/components/post_draft/uploads/uploads.test.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4923 Fix build for iOS for local simulator and Android test
  detox/.detoxrc.json
  fastlane/Fastfile
Labels: 4: Reviews Complete

#4930 Automated cherry pick of #4927
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/uploads/index.js
  app/components/post_draft/uploads/uploads.js
  app/components/post_draft/uploads/uploads.test.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4917 Upgrade Dependencies
  detox/.detoxrc.json
  detox/package-lock.json
  detox/package.json
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.63.3.patch
  patches/react-native-device-info+7.0.2.patch
  patches/react-native-haptic-feedback+1.11.0.patch
  patches/react-native-image-picker+2.3.4.patch
  patches/react-native-vector-icons+7.1.0.patch
Labels: 4: Reviews Complete

#4928 MM-29869 Replace radio button Material with Compass icons
  android/app/src/main/assets/fonts/compass-icons.ttf
  app/components/radio_button/radio_button.js
  assets/base/compass-icons.json
  assets/fonts/compass-icons.ttf
Labels: 4: Reviews Complete, CherryPick/Approved

#4932 Automated cherry pick of #4928
  android/app/src/main/assets/fonts/compass-icons.ttf
  app/components/radio_button/radio_button.js
  assets/base/compass-icons.json
  assets/fonts/compass-icons.ttf
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4933 Bump app build number to 332
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#4934 Automated cherry pick of #4933
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
