Repository mattermost/mattermost-mobile, pull requests merged in 2020-01, with the labels that each got.

#3754 MM-21148 - `make i18n-extract` throws an error if mobile repo is not checked out
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Tests/Not Needed

#3765 Automated cherry pick of #3763
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3766 Automated cherry pick of #3764
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3753 Realm Migration for Client Upgrade
  app/screens/client_upgrade/client_upgrade.js
  app/screens/client_upgrade/index.js
  app/utils/client_upgrade.js
Labels: 2: Dev Review

#3774 Bump app version number to 1.26.2
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3762 Enable Deep Links for Android
  android/app/src/main/AndroidManifest.xml
Labels: 2: Dev Review

#3773 MM-21476 Fix iOS inAppPinCode
  ios/Mattermost/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-local-auth+1.5.0.patch
  patches/react-native-passcode-status+1.1.2.patch
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3775 Bump app build number to 258
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3781 Automated cherry pick of #3775
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3771 MM-20627: Create SECURITY.md
  SECURITY.md
Labels: 3: Reviews Complete

#3782 Automated cherry pick of #3769
  android/app/build.gradle
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3656 MM-17044 Load posts until no more are needed
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
Labels: 3: Reviews Complete

#3776 translations PR 20200106
  assets/base/i18n/de.json
  assets/base/i18n/ro.json
  assets/base/i18n/zh-CN.json
Labels: 2: Dev Review, Tests/Not Needed

#3777 MM-20998 - Preventing the @ icon from being repeatedly tappable
  app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
  app/components/post_textbox/post_textbox_base.js
Labels: 3: Reviews Complete

#3736 MM-9548 - Scroll to top when iOS status bar is pressed
  patches/react-native+0.61.2.patch
Labels: 3: Reviews Complete, QA Review Done

#3768 MM-20949 Updated verbiage for profile image error
  app/screens/edit_profile/edit_profile.js
  assets/base/i18n/en.json
Labels: CherryPick/Approved, QA Review Done

#3783 v1.26.2 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#3757 Realm migration for About Screen
  app/screens/about/about.js
  app/screens/about/index.js
Labels: 3: Reviews Complete

#3791 Automated cherry pick of #3790
  app/init/fetch.js
  app/init/fetch.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3666 MM-15307 Updated to use InteractionManager
  app/components/conditionalWrapper.js
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/post_textbox/post_textbox_base.js
  app/constants/view.js
Labels: 3: Reviews Complete, QA Review Done

#3761 MM-18571: Include self user in autocomplete
  app/components/autocomplete/at_mention_item/at_mention_item.js
  app/components/autocomplete/at_mention_item/index.js
  app/selectors/autocomplete.js
  app/selectors/autocomplete.test.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3785 Automated cherry pick of #3768
  app/screens/edit_profile/edit_profile.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3697 MM-18767 Remove deprecated lifecycle methods from post textbox
  app/components/file_attachment_list/file_attachment_list.js
  app/components/file_attachment_list/file_attachment_list.test.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.test.js
  app/components/post_textbox/components/typing/typing.js
  app/components/post_textbox/components/typing/typing.test.js
  app/components/post_textbox/post_textbox.test.js
  app/components/post_textbox/post_textbox_base.js
Labels: 3: Reviews Complete, QA Review Done

#3767 [MM-12215] Make deep link URL prefix configurable for Release/Beta
  android/app/src/main/AndroidManifest.xml
  app/utils/url.js
  fastlane/Fastfile
  fastlane/env_vars_example
  ios/Mattermost/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3792 MM-21613 Fix iOS Share extension alert message when file size is larger than allowed
  app/store/store.js
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3794 Automated cherry pick of #3792
  app/store/store.js
  ios/UploadAttachments/UploadAttachments/UploadSession.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3796 [MM-17083] Removed Markdown from Purpose on Channel Info
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info_header.js
Labels: 3: Reviews Complete, QA Review Done

#3800 Automated cherry pick of #3786
  app/components/post_list/post_list.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3787 MM-20625 Unit Tests
  app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
  app/components/progressive_image/progressive_image.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3801 Automated cherry pick of #3787
  app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
  app/components/progressive_image/progressive_image.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3770 [MM-21369] Require server/site URL for deep links
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/utils/url.js
  app/utils/url.test.js
  assets/base/i18n/en.json
  fastlane/Fastfile
Labels: QA Review Done

#3803 Revert "MM-17519: do not stringify booleans (#3717)"
  app/components/widgets/settings/bool_setting.js
  app/components/widgets/settings/bool_setting.test.js
Labels: CherryPick/Approved, QA Review Done

#3797 MM-21342 Fix leading zero on post by using react-intl by default and fallback to moment-timezone for unsupported locale
  app/components/__snapshots__/formatted_time.test.js.snap
  app/components/__snapshots__/swiper.test.js.snap
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/formatted_time.js
  app/components/formatted_time.test.js
  app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap
  app/screens/long_post/__snapshots__/long_post.test.js.snap
  app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
  app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
  app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
  app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3805 MM-21288 Fix attaching files on Android
  android/app/src/main/AndroidManifest.xml
  app/mattermost.js
Labels: 2: QA Review, 3: Reviews Complete, CherryPick/Approved

#3804 translations PR 20200113
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 3: Reviews Complete

#3808 Automated cherry pick of #3805
  android/app/src/main/AndroidManifest.xml
  app/mattermost.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3759 [MM-21068] Notify when attempting to enter private channel/group via explicit link
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  app/components/markdown/markdown_link/markdown_link.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete

#3809 Bump app build number to 259
  .circleci/config.yml
  android/app/build.gradle
  fastlane/Fastfile
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3810 Automated cherry pick of #3809
  .circleci/config.yml
  android/app/build.gradle
  fastlane/Fastfile
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3812 MM-13953 Channel Info screen transition
  app/components/no_results.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
  app/screens/channel_info/channel_info.js
  package-lock.json
Labels: 3: Reviews Complete

#3802 [MM-14470] Deep links launch when app is not already open
  app/components/post_list/post_list.js
Labels: 3: Reviews Complete, QA Review Done

#3789 MM-20627: Update wording in SECURITY.md
  SECURITY.md
Labels: 3: Reviews Complete

#3816 Patch rn-fetch-blob with CBA support
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/rn-fetch-blob+0.12.0.patch
Labels: 3: Reviews Complete

#3716 v1.27 Changelog
  CHANGELOG.md
Labels: 3: Reviews Complete

#3793 MM-21632: fix toggling interactive dialog boolean
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_element.test.js
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/interactive_dialog/interactive_dialog.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3820 Automated cherry pick of #3793
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_element.test.js
  app/screens/interactive_dialog/interactive_dialog.js
  app/screens/interactive_dialog/interactive_dialog.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3821 Automated cherry pick of #3819
  app/actions/views/login.js
  app/actions/views/login.test.js
  app/init/fetch.js
  app/init/fetch.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3822 Automated cherry pick of #3819
  app/actions/views/login.js
  app/actions/views/login.test.js
  app/init/fetch.js
  app/init/fetch.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3813 MM-21634 Fix keyboard glitch when returning to channel screen from the code screen
  app/components/markdown/markdown_code_block/markdown_code_block.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3824 Automated cherry pick of #3813
  app/components/markdown/markdown_code_block/markdown_code_block.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3827 Set default app scheme to `mattermost`
  android/app/src/main/AndroidManifest.xml
  app/components/post_list/post_list.test.js
  app/utils/url.test.js
  fastlane/Fastfile
  fastlane/env_vars_example
  ios/Mattermost/Info.plist
Labels: 3: Reviews Complete, CherryPick/Approved

#3828 Automated cherry pick of #3827
  android/app/src/main/AndroidManifest.xml
  app/components/post_list/post_list.test.js
  app/utils/url.test.js
  fastlane/Fastfile
  fastlane/env_vars_example
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3830 Automated cherry pick of #3829
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3831 Automated cherry pick of #3829
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3833 Automated cherry pick of #3832
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3834 Automated cherry pick of #3832
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3837 MM-21892 Fix TypeError cause by mm-redux#1006
  app/components/autocomplete/slash_suggestion/index.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3838 Fix Fastlane script to bump version number
  fastlane/Fastfile
Labels: 3: Reviews Complete

#3839 Automated cherry pick of #3837
  app/components/autocomplete/slash_suggestion/index.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3815 [MM-21723] Handle deep link errors to inaccessible teams, channels & permalinks
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list.js
  app/screens/permalink/permalink.js
  app/selectors/channel.js
  assets/base/i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3840 Automated cherry pick of #3815
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list.js
  app/screens/permalink/permalink.js
  app/selectors/channel.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3818 Fixing post draft style to comply with design specs
  app/components/__snapshots__/send_button.test.js.snap
  app/components/attachment_button/index.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.js
  app/components/file_upload_preview/file_upload_item/file_upload_item.test.js
  app/components/file_upload_preview/file_upload_preview.js
  app/components/file_upload_preview/file_upload_remove.js
  app/components/pasteable_text_input/index.js
  app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
  app/components/post_textbox/components/cameraButton.js
  app/components/post_textbox/components/fileUploadButton.js
  app/components/post_textbox/components/imageUploadButton.js
  app/components/post_textbox/post_textbox_base.js
  app/components/send_button.js
  app/constants/post_textbox.js
  app/constants/view.js
  index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3841 Fix Android unsigned releases to work with Hermes
  android/app/build.gradle
Labels: 3: Reviews Complete, CherryPick/Approved

#3842 Automated cherry pick of #3841
  android/app/build.gradle
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3844 Automated cherry pick of #3843
  android/app/src/main/AndroidManifest.xml
  app/mattermost.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3825 v1.27.1 Changelog
  CHANGELOG.md
Labels: 2: Dev Review

#3848 Bump version to 1.28.0 and build number to 261
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3847 Temporary replace Hermes with V8
  android/app/build.gradle
  android/build.gradle
  index.js
  package-lock.json
  package.json
  packager/README.md
  packager/generateModulePaths.js
  packager/moduleNames.js
  packager/modulePaths.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3850 Automated cherry pick of #3847
  android/app/build.gradle
  android/build.gradle
  index.js
  package-lock.json
  package.json
  packager/README.md
  packager/generateModulePaths.js
  packager/moduleNames.js
  packager/modulePaths.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3849 Automated cherry pick of #3848
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3836 MM-18901 Update commit hash of mattermost-redux and cleanup initial state of requests.preferences
  app/initial_state.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#3857 Automated cherry pick of #3854
  ios/Mattermost/UIPasteboard+GetImageInfo.m
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3855 MM-17649 - fix VoiceOver on server select & login
  app/screens/login/login.js
  app/screens/select_server/select_server.js
Labels: 3: Reviews Complete, QA Review Done

#3861 MM-21961 Fix Incorrect Timestamp on Android Mobile App
  app/components/formatted_time.js
  app/components/formatted_time.test.js
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/root/root.js
  app/i18n/index.js
Labels: 2: QA Review, 3: Reviews Complete, CherryPick/Approved

#3863 Automated cherry pick of #3845
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  test/setup.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3864 Automated cherry pick of #3861
  app/components/formatted_time.js
  app/components/formatted_time.test.js
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/root/root.js
  app/i18n/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3859 MM-18530 iOS Slide open main sidebar from anywhere
  app/components/sidebars/drawer_layout.js
Labels: 3: Reviews Complete, QA Review Done

#3866 Automated cherry pick of #3859
  app/components/sidebars/drawer_layout.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3862 MM-22096 Handle links with no server URL provided
  app/utils/url.js
  app/utils/url.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3867 Automated cherry pick of #3862
  app/utils/url.js
  app/utils/url.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3870 Automated cherry pick of #3865
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/emoji_picker/emoji_picker_base.js
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3872 Automated cherry pick of #3871
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3876 Automated cherry pick of #3874
  app/init/global_event_handler.js
  app/init/global_event_handler.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3877 Bump Build number to 263
  README.md
  android/app/build.gradle
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
  fastlane/metadata/en-US/name.txt
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, CherryPick/Approved

#3878 Automated cherry pick of #3877
  README.md
  android/app/build.gradle
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
  fastlane/metadata/en-US/name.txt
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/MattermostTests/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3873 iOS - open link from phone
  README.md
Labels: 3: Reviews Complete
