Repository mattermost/mattermost-mobile, pull requests merged in 2020-12, with the labels that each got.

#4951 [MM-29037]: Unit and e2e tests for MM-28100
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  detox/e2e/test/messaging/tapping_channel_url_link_joins_channel.e2e.js
Labels: 4: Reviews Complete

#4996 Fix eol-last lint issues on master
  app/components/post_draft/quick_actions/quick_actions.test.js
Labels: 4: Reviews Complete

#4980 MM-18771 Removed componentwillreceiveprops
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
Labels: 4: Reviews Complete

#4983 MM-18769 Removed deprecated lifecycles
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/screens/select_team/__snapshots__/select_team.test.js.snap
  app/screens/select_team/select_team.js
  detox/e2e/support/server_api/channel.js
  detox/e2e/support/server_api/team.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/select_team.js
  detox/e2e/test/smoke_test/login_ldap.e2e.js
  detox/e2e/test/teams/select_team.e2e.js
Labels: 4: Reviews Complete

#4999 Automated cherry pick of #4998
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5013 Automated cherry pick of #5007
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/message_attachments/attachment_author.js
  app/components/message_attachments/attachment_title.js
  app/screens/client_upgrade/client_upgrade.js
  app/screens/settings/general/settings.js
  app/utils/supported_server.ts
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
  test/setup.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5011 MM-30858 fix: follow config to show the option to copy file public link
  app/screens/gallery/footer/index.tsx
  app/screens/gallery/footer/summary/actions/actions.tsx
  app/screens/gallery/footer/summary/actions/index.ts
  types/screens/gallery.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5009 MM-31114 fix: regression for in: autocomplete modifier in search screen
  app/components/autocomplete/channel_mention_item/channel_mention_item.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5010 MM-30850 fix(android): Failure to share self-uploaded file
  app/screens/gallery/footer/prepare_file/prepare_file.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5019 Automated cherry pick of #5008
  app/screens/client_upgrade/client_upgrade.js
  app/screens/forgot_password/__snapshots__/forgot_password.test.js.snap
  app/screens/forgot_password/forgot_password.js
  app/screens/login/login.js
  app/screens/login_options/login_options.js
  app/screens/mfa/mfa.js
  app/screens/select_server/select_server.js
  app/styles/index.js
  assets/base/images/logo.png
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5018 Automated cherry pick of #5010
  app/screens/gallery/footer/prepare_file/prepare_file.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5017 Automated cherry pick of #5009
  app/components/autocomplete/channel_mention_item/channel_mention_item.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5016 Automated cherry pick of #5011
  app/screens/gallery/footer/index.tsx
  app/screens/gallery/footer/summary/actions/actions.tsx
  app/screens/gallery/footer/summary/actions/index.ts
  types/screens/gallery.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4950 Typo error update in README.md
  README.md
Labels: 4: Reviews Complete

#4981 MM-18764 Remove deprecated lifecycles
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/list.js
  app/screens/create_channel/create_channel.js
  app/screens/more_channels/more_channels.js
Labels: 4: Reviews Complete

#4989 filtered_list : removed deprecated lifecycles and memoized dataSource
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
Labels: 4: Reviews Complete

#5022 Automated cherry pick of #5015
  app/init/push_notifications.test.js
  app/init/push_notifications.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4911 [MM-23391] Sort sidebar teams order by user preference
  app/actions/views/select_team.js
  app/mm-redux/constants/preferences.ts
  app/mm-redux/selectors/entities/teams.test.js
  app/mm-redux/selectors/entities/teams.ts
  app/mm-redux/utils/team_utils.test.js
  app/mm-redux/utils/team_utils.ts
  app/utils/teams.js
  app/utils/teams.test.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#5014 MM-31202 | MM-30866 fix: Video playback button & hide header footer on playback
  app/screens/gallery/footer/index.tsx
  app/screens/gallery/gallery.js
  app/screens/gallery/gallery_video.tsx
  app/screens/gallery/gallery_viewer.tsx
  app/screens/gallery/video_controls.tsx
  types/screens/gallery.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5025 Automated cherry pick of #5021
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/post_body_additional_content/post_body_additional_content.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5027 Automated cherry pick of #5014
  app/screens/gallery/footer/index.tsx
  app/screens/gallery/gallery.js
  app/screens/gallery/gallery_video.tsx
  app/screens/gallery/gallery_viewer.tsx
  app/screens/gallery/video_controls.tsx
  types/screens/gallery.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5029 Automated cherry pick of #5024
  patches/react-native-keyboard-tracking-view+5.7.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4986 MM-18998 Add emojis in the post to recent emojis
  app/actions/views/emoji.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/draft_input/draft_input.test.js
  app/components/post_draft/draft_input/index.js
  app/components/reaction_picker/reaction_picker.js
  app/constants/view.js
  app/mm-redux/actions/posts.ts
  app/reducers/views/recent_emojis.js
  detox/e2e/test/messaging/recent_emojis.e2e.js
Labels: 4: Reviews Complete

#5030 Automated cherry pick of #5026
  app/components/post_draft/uploads/uploads.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5000 [MM-30857] request postssince on reconnect
  app/actions/websocket/index.ts
  app/actions/websocket/websocket.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5032 Automated cherry pick of #5000
  app/actions/websocket/index.ts
  app/actions/websocket/websocket.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5036 Automated cherry pick of #5035
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5003 MM-30286 Detox/E2E: Add e2e test for MM-T3235
  app/screens/permalink/__snapshots__/permalink.test.js.snap
  app/screens/permalink/permalink.js
  detox/e2e/support/server_api/channel.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/permalink.js
  detox/e2e/test/smoke_test/search.e2e.js
Labels: 4: Reviews Complete

#5006 MM-30286 Detox/E2E: Add e2e test for MM-T3255
  app/components/__snapshots__/badge.test.js.snap
  app/components/badge.js
  app/components/badge.test.js
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/switch_teams_button/__snapshots__/switch_teams_button.test.js.snap
  app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
  app/components/sidebars/main/teams_list/teams_list_item/__snapshots__/teams_list_item.test.js.snap
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
  app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/__snapshots__/main_sidebar_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.js
  detox/e2e/support/ui/component/channels_list.js
  detox/e2e/support/ui/component/main_sidebar.js
  detox/e2e/support/ui/component/teams_list.js
  detox/e2e/support/ui/screen/channel.js
  detox/e2e/support/ui/screen/select_team.js
  detox/e2e/test/smoke_test/mention_badges.e2e.js
Labels: 4: Reviews Complete

#5045 Automated cherry pick of #5042
  app/components/autocomplete/index.js
  app/components/edit_channel_info/index.js
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/post_input/post_input.js
  app/constants/device.js
  app/screens/channel/channel.ios.js
  app/screens/edit_post/edit_post.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.ios.js
  patches/react-native-keyboard-tracking-view+5.7.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5048 Update Rudder
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5051 Automated cherry pick of #5048
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5052 Automated cherry pick of #5048
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5049 MM-31491 Set Tablet orientation explicitly to all
  app/actions/navigation/index.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5056 Automated cherry pick of #5055
  app/components/channel_loader/channel_loader.js
  app/components/channel_loader/channel_loader.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5057 Automated cherry pick of #5055
  app/components/channel_loader/channel_loader.js
  app/components/channel_loader/channel_loader.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5053 Automated cherry pick of #5049
  app/actions/navigation/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5054 Automated cherry pick of #5049
  app/actions/navigation/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5058 Bump app build number to 338 and version to 1.38.1
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5059 Automated cherry pick of #5058
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5060 Automated cherry pick of #5058
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5068 MM_30476 [v2] Updated Babel configs
  babel.config.js
  package.json
  tsconfig.json
Labels: 4: Reviews Complete

#5069 MM_30476 [v2] Updated all models and typings for the default database
  app/database/default/models/app.ts
  app/database/default/models/global.ts
  app/database/default/models/index.ts
  app/database/default/models/server.ts
  app/database/default/models/servers.ts
  app/init/emm_provider.ts
  package-lock.json
  types/database/app.d.ts
  types/database/global.d.ts
  types/database/server.d.ts
  types/database/servers.d.ts
Labels: 4: Reviews Complete
