Repository mattermost/mattermost-mobile, pull requests merged in 2020-08, with the labels that each got.

#4614 Update netinfo dependency and RN to 0.63.2
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.63.2.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4634 DOPS-90 fix folder for iOS simulator CI build
  .circleci/config.yml
  fastlane/Fastfile
Labels: 4: Reviews Complete, CherryPick/Approved

#4636 Upgrade sentry dependency
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4642 Cleanup fetch error & add details to sso
  app/init/fetch.js
  app/screens/sso/sso.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4643 Automated cherry pick of #4642
  app/init/fetch.js
  app/screens/sso/sso.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4640 Upgrade fuse.js dependency
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4647 MM-27488 Fix edit post input text selection
  app/components/autocomplete/autocomplete.js
  app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
  app/components/edit_channel_info/edit_channel_info.js
  app/screens/edit_post/__snapshots__/edit_post.test.js.snap
  app/screens/edit_post/edit_post.js
  app/screens/post_options/post_options.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4646 Update moment-timezone & react-native-calendars dependency
  package-lock.json
  package.json
  patches/moment-timezone+0.5.29.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4649 Automated cherry pick of #4648
  app/actions/views/root.js
  app/components/post_list/more_messages_button/more_messages_button.js
  app/components/post_list/more_messages_button/more_messages_button.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4621 MM-23090 MM-26078 && MM-26876 Refactor post draft component
  .eslintrc.json
  app/components/__snapshots__/profile_picture_button.test.js.snap
  app/components/attachment_button/index.js
  app/components/attachment_button/index.test.js
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/draft_input/draft_input.test.js
  app/components/post_draft/draft_input/index.js
  app/components/post_draft/index.js
  app/components/post_draft/index.test.js
  app/components/post_draft/post_draft.js
  app/components/post_draft/post_draft.test.js
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
  app/components/post_draft/quick_actions/camera_quick_action/camera_quick_action.test.js
  app/components/post_draft/quick_actions/camera_quick_action/index.js
  app/components/post_draft/quick_actions/file_quick_action/file_quick_action.test.js
  app/components/post_draft/quick_actions/file_quick_action/index.js
  app/components/post_draft/quick_actions/image_quick_action/image_quick_action.test.js
  app/components/post_draft/quick_actions/image_quick_action/index.js
  app/components/post_draft/quick_actions/index.js
  app/components/post_draft/quick_actions/quick_actions.js
  app/components/post_draft/read_only/__snapshots__/read_only.test.js.snap
  app/components/post_draft/read_only/index.tsx
  app/components/post_draft/read_only/read_only.test.js
  app/components/post_draft/send_action/__snapshots__/send.test.js.snap
  app/components/post_draft/send_action/index.js
  app/components/post_draft/send_action/paper_plane.js
  app/components/post_draft/send_action/send.test.js
  app/components/post_draft/uploads/index.js
  app/components/post_draft/uploads/uploads.js
  app/components/profile_picture_button.test.js
  app/components/progressive_image/progressive_image.js
  app/components/progressive_image/progressive_image.test.js
  app/constants/post_draft.js
  app/mm-redux/selectors/entities/channels.ts
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/edit_profile/edit_profile.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.ios.js
  app/selectors/file.js
  app/selectors/views.js
  app/utils/draft.js
  app/utils/draft.test.js
  assets/base/i18n/en.json
  share_extension/android/extension_post/extension_post.js
  test/setup.js
  tsconfig.json
Labels: 4: Reviews Complete

#4644 [MM-26972] Ignore pagination when loading group data
  app/actions/views/channel.js
  app/mm-redux/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4651 Automated cherry pick of #4644
  app/actions/views/channel.js
  app/mm-redux/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4652 Bump app build number to 317
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#4653 Automated cherry pick of #4652
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4633 [MM-12526] removed from channel alert
  app/actions/websocket/users.ts
  app/mm-redux/constants/general.ts
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete

#4657 MM-27607 Fix filter undefined when searching profiles
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_members/channel_members.js
  app/screens/more_dms/more_dms.js
  app/screens/selector_screen/selector_screen.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4659 Automated cherry pick of #4657
  app/screens/channel_add_members/channel_add_members.js
  app/screens/channel_members/channel_members.js
  app/screens/more_dms/more_dms.js
  app/screens/selector_screen/selector_screen.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4662 Automated cherry pick of #4661
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4658 Update react-native-elements
  package-lock.json
  package.json
  patches/react-native-elements+2.2.0.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4596 [MM-18765] remove lifecycle methods from settings
  app/components/radio_button/radio_button_group.js
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings_email/notification_settings_email_base.js
Labels: 4: Reviews Complete

#4584 v1.34 Changelog
  CHANGELOG.md
Labels: 4: Reviews Complete

#4641 MM-23739 Empty search state for emoji picker
  app/components/emoji_picker/emoji_picker_base.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4664 Upgrade react-native-device-info dependency
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-device-info+5.6.4.patch
Labels: 3: QA Review, CherryPick/Approved

#4666 MM-27711 Play YouTube video using expanded link
  app/components/post_body_additional_content/post_body_additional_content.js
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#4669 Upgrade react-native-document-picker dependency
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4670 Upgrade react-native-image-picker dependency
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-image-picker+2.3.3.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4673 Automated cherry pick of #4610
  app/components/post_draft/quick_actions/file_quick_action/index.js
  app/utils/file.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4675 Automated cherry pick of #4595
  app/screens/image_preview/downloader.ios.js
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4676 Automated cherry pick of #4599
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4677 Automated cherry pick of #4633
  app/actions/websocket/users.ts
  app/mm-redux/constants/general.ts
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4678 Automated cherry pick of #4636
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4679 Automated cherry pick of #4640
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4680 Automated cherry pick of #4641
  app/components/emoji_picker/emoji_picker_base.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4681 Automated cherry pick of #4646
  package-lock.json
  package.json
  patches/moment-timezone+0.5.29.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4682 Automated cherry pick of #4656
  app/components/file_attachment_list/__snapshots__/file_attachment_image.test.js.snap
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_attachment_list/file_attachment_image.test.js
  app/components/file_attachment_list/file_attachment_list.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4683 Automated cherry pick of #4658
  package-lock.json
  package.json
  patches/react-native-elements+2.2.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4684 Automated cherry pick of #4664
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-device-info+5.6.4.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4685 Automated cherry pick of #4666
  app/components/post_body_additional_content/post_body_additional_content.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4686 Automated cherry pick of #4669
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4687 Automated cherry pick of #4670
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-image-picker+2.3.3.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4674 Automated cherry pick of #4668
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4635 [MM-22948] - Improve unread badge UI on the hamburger menu and team icons
  app/components/badge.js
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
  app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
  app/constants/view.js
  app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
  app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
Labels: 4: Reviews Complete

#4671 Upgrade react-native-mmkv-storage dependency
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-mmkv-storage+0.3.5.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4691 Automated cherry pick of #4671
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-mmkv-storage+0.3.5.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3852 MM-15323 autofill server Url when opening the app from deeplink (#10788)
  app/mattermost.js
  app/screens/select_server/index.js
  app/screens/select_server/select_server.js
Labels: 4: Reviews Complete

#4660 MM-26436: Allows others' posts to be delete with just 'delete_others_…
  app/mm-redux/utils/post_utils.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4694 Automated cherry pick of #4660
  app/mm-redux/utils/post_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4693 Upgrade react-native-permissions dependency
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4695 Automated cherry pick of #4693
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4688 MM-27527 Allow swipe to close the sidebar after search is cancelled
  app/components/sidebars/main/main_sidebar.ios.js
  app/components/sidebars/main/main_sidebar_base.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4697 Automated cherry pick of #4688
  app/components/sidebars/main/main_sidebar.ios.js
  app/components/sidebars/main/main_sidebar_base.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4699 Bump Version to 1.35.0 and Build to 319
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4700 Automated cherry pick of #4699
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4692 MM-26329 Fix Channel info guests info in landscape
  app/mm-redux/types/actions.ts
  app/mm-redux/types/general.ts
  app/mm-redux/types/module.d.ts
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/add_members/__snapshots__/add_members.test.js.snap
  app/screens/channel_info/add_members/add_members.test.js
  app/screens/channel_info/add_members/add_members.tsx
  app/screens/channel_info/add_members/index.js
  app/screens/channel_info/archive/__snapshots__/archive.test.js.snap
  app/screens/channel_info/archive/archive.test.js
  app/screens/channel_info/archive/archive.tsx
  app/screens/channel_info/archive/index.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/channel_info_row.js
  app/screens/channel_info/convert_private/__snapshots__/convert_private.test.js.snap
  app/screens/channel_info/convert_private/convert_private.test.js
  app/screens/channel_info/convert_private/convert_private.tsx
  app/screens/channel_info/convert_private/index.js
  app/screens/channel_info/edit_channel/__snapshots__/edit_channel.test.js.snap
  app/screens/channel_info/edit_channel/edit_channel.test.js
  app/screens/channel_info/edit_channel/edit_channel.tsx
  app/screens/channel_info/edit_channel/index.js
  app/screens/channel_info/favorite/__snapshots__/favorite.test.js.snap
  app/screens/channel_info/favorite/favorite.test.js
  app/screens/channel_info/favorite/favorite.tsx
  app/screens/channel_info/favorite/index.js
  app/screens/channel_info/ignore_mentions/__snapshots__/ignore_mentions.test.js.snap
  app/screens/channel_info/ignore_mentions/ignore_mentions.test.js
  app/screens/channel_info/ignore_mentions/ignore_mentions.tsx
  app/screens/channel_info/ignore_mentions/index.js
  app/screens/channel_info/index.js
  app/screens/channel_info/leave/__snapshots__/leave.test.js.snap
  app/screens/channel_info/leave/index.js
  app/screens/channel_info/leave/leave.test.js
  app/screens/channel_info/leave/leave.tsx
  app/screens/channel_info/manage_members/__snapshots__/manage_members.test.js.snap
  app/screens/channel_info/manage_members/index.js
  app/screens/channel_info/manage_members/manage_members.test.js
  app/screens/channel_info/manage_members/manage_members.tsx
  app/screens/channel_info/mute/__snapshots__/mute.test.js.snap
  app/screens/channel_info/mute/index.js
  app/screens/channel_info/mute/mute.test.js
  app/screens/channel_info/mute/mute.tsx
  app/screens/channel_info/pinned/__snapshots__/pinned.test.js.snap
  app/screens/channel_info/pinned/index.js
  app/screens/channel_info/pinned/pinned.test.js
  app/screens/channel_info/pinned/pinned.tsx
  app/screens/channel_info/separator.tsx
  tsconfig.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4702 Automated cherry pick of #4692
  app/mm-redux/types/actions.ts
  app/mm-redux/types/general.ts
  app/mm-redux/types/module.d.ts
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/add_members/__snapshots__/add_members.test.js.snap
  app/screens/channel_info/add_members/add_members.test.js
  app/screens/channel_info/add_members/add_members.tsx
  app/screens/channel_info/add_members/index.js
  app/screens/channel_info/archive/__snapshots__/archive.test.js.snap
  app/screens/channel_info/archive/archive.test.js
  app/screens/channel_info/archive/archive.tsx
  app/screens/channel_info/archive/index.js
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/channel_info_row.js
  app/screens/channel_info/convert_private/__snapshots__/convert_private.test.js.snap
  app/screens/channel_info/convert_private/convert_private.test.js
  app/screens/channel_info/convert_private/convert_private.tsx
  app/screens/channel_info/convert_private/index.js
  app/screens/channel_info/edit_channel/__snapshots__/edit_channel.test.js.snap
  app/screens/channel_info/edit_channel/edit_channel.test.js
  app/screens/channel_info/edit_channel/edit_channel.tsx
  app/screens/channel_info/edit_channel/index.js
  app/screens/channel_info/favorite/__snapshots__/favorite.test.js.snap
  app/screens/channel_info/favorite/favorite.test.js
  app/screens/channel_info/favorite/favorite.tsx
  app/screens/channel_info/favorite/index.js
  app/screens/channel_info/ignore_mentions/__snapshots__/ignore_mentions.test.js.snap
  app/screens/channel_info/ignore_mentions/ignore_mentions.test.js
  app/screens/channel_info/ignore_mentions/ignore_mentions.tsx
  app/screens/channel_info/ignore_mentions/index.js
  app/screens/channel_info/index.js
  app/screens/channel_info/leave/__snapshots__/leave.test.js.snap
  app/screens/channel_info/leave/index.js
  app/screens/channel_info/leave/leave.test.js
  app/screens/channel_info/leave/leave.tsx
  app/screens/channel_info/manage_members/__snapshots__/manage_members.test.js.snap
  app/screens/channel_info/manage_members/index.js
  app/screens/channel_info/manage_members/manage_members.test.js
  app/screens/channel_info/manage_members/manage_members.tsx
  app/screens/channel_info/mute/__snapshots__/mute.test.js.snap
  app/screens/channel_info/mute/index.js
  app/screens/channel_info/mute/mute.test.js
  app/screens/channel_info/mute/mute.tsx
  app/screens/channel_info/pinned/__snapshots__/pinned.test.js.snap
  app/screens/channel_info/pinned/index.js
  app/screens/channel_info/pinned/pinned.test.js
  app/screens/channel_info/pinned/pinned.tsx
  app/screens/channel_info/separator.tsx
  tsconfig.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4696 MM-25832 Prevent permalink view from loading posts multiple times
  app/mm-redux/client/client4.ts
  app/screens/permalink/permalink.js
  app/screens/permalink/permalink.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4703 Automated cherry pick of #4696
  app/mm-redux/client/client4.ts
  app/screens/permalink/permalink.js
  app/screens/permalink/permalink.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4698 Upgrade fast-image, localize, vector-icons, video & dev dependencies
  app/screens/channel/channel_nav_bar/settings_drawer_button.js
  app/screens/image_preview/__snapshots__/image_preview.test.js.snap
  app/screens/image_preview/downloader.ios.js
  app/screens/image_preview/image_preview.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-fast-image+8.3.2.patch
  patches/react-native-vector-icons+7.0.0.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4705 MM-27982 Fix soft crash for edge emoji formatting
  app/components/markdown/markdown_emoji/markdown_emoji.js
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4706 Automated cherry pick of #4698
  app/screens/channel/channel_nav_bar/settings_drawer_button.js
  app/screens/image_preview/__snapshots__/image_preview.test.js.snap
  app/screens/image_preview/downloader.ios.js
  app/screens/image_preview/image_preview.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-fast-image+8.3.2.patch
  patches/react-native-vector-icons+7.0.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4708 Automated cherry pick of #4705
  app/components/markdown/markdown_emoji/markdown_emoji.js
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4709 Automated cherry pick of #4707
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4720 Update dev dependencies & some others
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-device-info+5.6.5.patch
  patches/react-native-elements+2.2.1.patch
  patches/react-native-mmkv-storage+0.3.7.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4721 Automated cherry pick of #4720
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-device-info+5.6.5.patch
  patches/react-native-elements+2.2.1.patch
  patches/react-native-mmkv-storage+0.3.7.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4717 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#4724 Automated cherry pick of #4717
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4725 Upgrade depdendencies
  app/components/slide_up_panel/slide_up_panel.js
  app/screens/reaction_list/__snapshots__/reaction_header_item.test.js.snap
  app/screens/reaction_list/reaction_header_item.js
  app/screens/reaction_list/reaction_row/__snapshots__/reaction_row.test.js.snap
  app/screens/reaction_list/reaction_row/reaction_row.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-navigation+6.12.1.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4727 Automated cherry pick of #4725
  app/components/slide_up_panel/slide_up_panel.js
  app/screens/reaction_list/__snapshots__/reaction_header_item.test.js.snap
  app/screens/reaction_list/reaction_header_item.js
  app/screens/reaction_list/reaction_row/__snapshots__/reaction_row.test.js.snap
  app/screens/reaction_list/reaction_row/reaction_row.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-navigation+6.12.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4729 Automated cherry pick of #4728
  app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
  app/components/emoji_picker/emoji_picker.ios.js
  app/components/emoji_picker/emoji_picker_base.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4726 [MM-27132] Handle group mention keys for group synced channels and teams
  app/components/at_mention/index.js
  app/components/autocomplete/at_mention/index.js
  app/components/post_body/index.js
  app/components/post_draft/draft_input/index.js
  app/mm-redux/selectors/entities/groups.ts
  app/mm-redux/selectors/entities/roles.ts
  app/mm-redux/selectors/entities/search.test.js
  app/mm-redux/selectors/entities/search.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4731 SSO: Rebuild the server url without query string and/or hash
  app/screens/sso/sso.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4734 Automated cherry pick of #4731
  app/screens/sso/sso.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4737 Automated cherry pick of #4707
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4736 Automated cherry pick of #4731
  app/screens/sso/sso.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4738 Automated cherry pick of #4705
  app/components/markdown/markdown_emoji/markdown_emoji.js
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4739 Bump app version number to 1.34.1
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#4740 Bump app build number to 320
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#4741 Automated cherry pick of #4740
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4735 Update Dependencies
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-elements+2.3.0.patch
  patches/react-native-navigation+6.12.2.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4743 Automated cherry pick of #4735
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-elements+2.3.0.patch
  patches/react-native-navigation+6.12.2.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4742 1.34.1 Changelog
  CHANGELOG.md
Labels: 4: Reviews Complete

#4745 Show arrows in calendar
  app/components/autocomplete/date_suggestion/date_suggestion.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4746 Automated cherry pick of #4745
  app/components/autocomplete/date_suggestion/date_suggestion.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4733 MM-25684 Highlight at-mention followed by a period
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
  app/components/at_mention/at_mention.test.js
  app/components/markdown/transform.js
  app/components/markdown/transform.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4747 Automated cherry pick of #4733
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
  app/components/at_mention/at_mention.test.js
  app/components/markdown/transform.js
  app/components/markdown/transform.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4750 Automated cherry pick of #4749
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4535 E2E: Initial Detox setup for Mobile UI automation
  .eslintrc.json
  android/app/build.gradle
  android/app/src/androidTest/java/com/mattermost/rnbeta/DetoxTest.java
  android/build.gradle
  app/components/error_text/__snapshots__/error_text.test.js.snap
  app/components/error_text/error_text.js
  app/components/formatted_text.js
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/send_action/__snapshots__/send.test.js.snap
  app/components/post_draft/send_action/index.js
  app/components/sidebars/drawer_layout.js
  app/components/sidebars/main/main_sidebar.ios.js
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/login/login.js
  app/screens/select_server/select_server.js
  detox/.babelrc
  detox/.detoxrc.json
  detox/e2e/config.json
  detox/e2e/environment.js
  detox/e2e/init.js
  detox/e2e/support/server_api/channel.js
  detox/e2e/support/server_api/client.js
  detox/e2e/support/server_api/common.js
  detox/e2e/support/server_api/default_config.json
  detox/e2e/support/server_api/index.js
  detox/e2e/support/server_api/setup.js
  detox/e2e/support/server_api/system.js
  detox/e2e/support/server_api/team.js
  detox/e2e/support/server_api/user.js
  detox/e2e/support/test_config.js
  detox/e2e/support/ui/screen.js
  detox/e2e/support/utils.js
  detox/e2e/test/messaging/message_posting.e2e.js
  detox/e2e/test/on_boarding/login.e2e.js
  detox/package-lock.json
  detox/package.json
  fastlane/Fastfile
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#4718 Add check for empty translation strings.
  .circleci/config.yml
  Makefile
  package-lock.json
  package.json
  scripts/pre-commit.sh
  scripts/precommit/i18n.sh
Labels: 4: Reviews Complete
