Repository mattermost/mattermost-mobile, pull requests merged in 2020-07, with the labels that each got.

#4511 MM-25967 Disable Shared Process Pool in WebView
  app/screens/sso/sso.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4515 Automated cherry pick of #4511
  app/screens/sso/sso.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4518 MM-26638 MM-26656 await when dismissing post options modal
  app/screens/post_options/post_options.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4522 Automated cherry pick of #4518
  app/screens/post_options/post_options.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4519 MM-26667 Set EMM username as the initial loginId
  app/screens/login/login.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4524 Automated cherry pick of #4519
  app/screens/login/login.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4523 Wait for hydration before app launch
  app/mattermost.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4525 Automated cherry pick of #4523
  app/mattermost.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4517 Update settings.js
  app/screens/settings/general/settings.js
Labels: 4: Reviews Complete

#4534 Fix LHS team icon on team switch
  app/components/team_icon/team_icon.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4537 MM-26722 check for switchKeyboardForCodeBlocks only on iOS 12+
  app/utils/markdown.js
  app/utils/markdown.test.js
  test/setup.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4545 Automated cherry pick of #4534
  app/components/team_icon/team_icon.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4546 Automated cherry pick of #4537
  app/utils/markdown.js
  app/utils/markdown.test.js
  test/setup.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4538 MM-26490 Dismiss keyboard when closing more dms / channels / create channel
  app/screens/create_channel/create_channel.js
  app/screens/more_channels/more_channels.js
  app/screens/more_dms/more_dms.js
Labels: 4: Reviews Complete

#4118 [MM-23158] Group Mentions & Invites - Display group mentions in suggestions list in the main channel textbox
  app/actions/views/channel.js
  app/actions/websocket.ts
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/at_mention/index.js
  app/components/autocomplete/at_mention_group/at_mention_group.js
  app/constants/websocket.ts
  app/mm-redux/action_types/groups.ts
  app/mm-redux/actions/groups.test.js
  app/mm-redux/actions/groups.ts
  app/mm-redux/actions/index.ts
  app/mm-redux/client/client4.ts
  app/mm-redux/reducers/entities/channels.ts
  app/mm-redux/reducers/entities/groups.ts
  app/mm-redux/selectors/entities/groups.test.js
  app/mm-redux/selectors/entities/groups.ts
  app/mm-redux/types/groups.ts
  app/mm-redux/utils/group_utils.test.js
  app/mm-redux/utils/group_utils.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete

#4539 MM-26699 Track open modals
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/screens/search/search.js
  app/store/ephemeral_store.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4549 Bump app build number to 309
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#4550 Automated cherry pick of #4549
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4384 Show toast when pressing back button on channel screen
  android/app/src/main/java/com/mattermost/share/ShareActivity.java
  app/screens/channel/channel.android.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete

#4507 MM-25956 Use new mobile modal style on Other User Profile
  app/components/at_mention/at_mention.js
  app/components/channel_intro/channel_intro.js
  app/components/post/post.js
  app/components/sidebars/settings/settings_sidebar_base.js
  app/screens/channel/channel_base.js
  app/screens/reaction_list/reaction_row/reaction_row.js
  app/screens/user_profile/user_profile.js
  app/screens/user_profile/user_profile.test.js
Labels: 4: Reviews Complete

#4552 Fix i18n merge conflicts with weblate
  assets/base/i18n/de.json
  assets/base/i18n/nl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/uk.json
Labels: 4: Reviews Complete

#4553 Fix i18n release-1.33
  assets/base/i18n/de.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/uk.json
Labels: 4: Reviews Complete

#4543 DOPS-90 Add CI build for iOS App iPhone simulator
  .circleci/config.yml
  Makefile
  fastlane/Fastfile
Labels: 4: Reviews Complete

#4556 MM-26749 Fix race condition when open from PN
  app/actions/views/root.js
  app/init/push_notifications.js
  app/mattermost.js
  app/push_notifications/push_notifications.android.js
  app/push_notifications/push_notifications.ios.js
  app/screens/channel/channel_base.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4558 Automated cherry pick of #4556
  app/actions/views/root.js
  app/init/push_notifications.js
  app/mattermost.js
  app/push_notifications/push_notifications.android.js
  app/push_notifications/push_notifications.ios.js
  app/screens/channel/channel_base.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4555 Translations update from Weblate
  assets/base/i18n/nl.json
Labels: 4: Reviews Complete

#4560 Bump app build number to 310
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#4561 Automated cherry pick of #4560
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4106 MM-26827 Add ShowFullName property
  app/mm-redux/types/config.ts
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  app/screens/user_profile/user_profile.js
Labels: 4: Reviews Complete

#4567 Fix unhandled exception when current user is not defined
  app/components/post_draft/index.js
  app/mm-redux/selectors/entities/users.ts
  app/screens/channel_info/index.js
Labels: 4: Reviews Complete

#4451 v1.33 Changelog
  CHANGELOG.md
Labels: 4: Reviews Complete

#4536 MM-22029 clear the text input as soon as possible
  app/components/post_draft/post_draft.js
  app/components/post_draft/post_input/post_input.js
Labels: 4: Reviews Complete

#4565 MM-26744 in-prompt for end users if server is unsupported
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
  app/screens/terms_of_service/terms_of_service.js
  app/utils/supported_server.test.js
  app/utils/supported_server.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete

#4571 MM-26946 Handle invalid YouTube links
  app/components/post_body_additional_content/post_body_additional_content.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4573 Automated cherry pick of #4571
  app/components/post_body_additional_content/post_body_additional_content.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4576 Bump Version to 1.33.1 and build to 311
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4577 Automated cherry pick of #4576
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4572 v1.33.1 Changelog
  CHANGELOG.md
Labels: 4: Reviews Complete

#4548 [MM 23785] Show confirmation dialogue when mention groups 2
  app/components/post_draft/index.js
  app/components/post_draft/index.test.js
  app/components/post_draft/post_draft.js
  app/components/post_draft/post_draft.test.js
  app/constants/autocomplete.js
  app/mm-redux/action_types/channels.ts
  app/mm-redux/actions/channels.test.js
  app/mm-redux/actions/channels.ts
  app/mm-redux/client/client4.ts
  app/mm-redux/reducers/entities/channels.test.js
  app/mm-redux/reducers/entities/channels.ts
  app/mm-redux/selectors/entities/channels.test.js
  app/mm-redux/selectors/entities/channels.ts
  app/mm-redux/selectors/entities/groups.ts
  app/mm-redux/types/channels.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4521 MM-26828 We can allow events to RudderStack since we don't have any rate limit…
  app/mm-redux/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4520 MM-26829 Rename actual_user_id to user_actual_id to be more consistent with the rest of MM telemetry.
  app/init/analytics.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4585 Automated cherry pick of #4521
  app/mm-redux/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4586 Automated cherry pick of #4520
  app/init/analytics.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4551 [MM-23160][MM-24633][MM-24697] Highlight Group Names 2
  app/actions/views/channel.js
  app/components/at_mention/at_mention.js
  app/components/at_mention/index.js
  app/components/markdown/__snapshots__/markdown.test.js.snap
  app/components/markdown/index.js
  app/components/markdown/markdown.js
  app/components/markdown/markdown.test.js
  app/components/post_body/index.js
  app/components/post_body/index.test.js
  app/components/post_body/post_body.js
  app/mm-redux/client/client4.ts
  app/mm-redux/reducers/entities/groups.ts
  app/mm-redux/selectors/entities/groups.ts
  app/mm-redux/selectors/entities/search.test.js
  app/mm-redux/selectors/entities/search.ts
  app/mm-redux/types/groups.ts
  app/mm-redux/types/posts.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4587 Automated cherry pick of #4551
  app/actions/views/channel.js
  app/components/at_mention/at_mention.js
  app/components/at_mention/index.js
  app/components/markdown/__snapshots__/markdown.test.js.snap
  app/components/markdown/index.js
  app/components/markdown/markdown.js
  app/components/markdown/markdown.test.js
  app/components/post_body/index.js
  app/components/post_body/index.test.js
  app/components/post_body/post_body.js
  app/mm-redux/client/client4.ts
  app/mm-redux/reducers/entities/groups.ts
  app/mm-redux/selectors/entities/groups.ts
  app/mm-redux/selectors/entities/search.test.js
  app/mm-redux/selectors/entities/search.ts
  app/mm-redux/types/groups.ts
  app/mm-redux/types/posts.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4579 [MM-25749] Implement non-cached autocomplete for mobile
  app/components/autocomplete/slash_suggestion/index.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
  app/components/post_draft/post_draft.js
  app/mm-redux/action_types/integrations.ts
  app/mm-redux/actions/integrations.ts
  app/mm-redux/client/client4.ts
  app/mm-redux/reducers/entities/integrations.ts
  app/mm-redux/selectors/entities/integrations.ts
  app/mm-redux/types/integrations.ts
  app/screens/channel/channel.ios.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.ios.js
Labels: CherryPick/Approved, QA Review Done

#4592 Automated cherry pick of #4579
  app/components/autocomplete/slash_suggestion/index.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
  app/components/post_draft/post_draft.js
  app/mm-redux/action_types/integrations.ts
  app/mm-redux/actions/integrations.ts
  app/mm-redux/client/client4.ts
  app/mm-redux/reducers/entities/integrations.ts
  app/mm-redux/selectors/entities/integrations.ts
  app/mm-redux/types/integrations.ts
  app/screens/channel/channel.ios.js
  app/screens/thread/__snapshots__/thread.ios.test.js.snap
  app/screens/thread/thread.ios.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4590 Allow to post attachment only messages
  app/components/post_draft/post_draft.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4594 Automated cherry pick of #4590
  app/components/post_draft/post_draft.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4595 Update camera-roll dependency
  app/screens/image_preview/downloader.ios.js
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4601 Automated cherry pick of #4600
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4597 Add analytics to the command autocomplete
  app/actions/views/root.js
  app/actions/views/user.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
  app/components/post_draft/uploads/upload_item/upload_item.js
  app/init/analytics.ts
  app/init/credentials.js
  app/init/global_event_handler.js
  app/mm-redux/actions/channels.ts
  app/mm-redux/actions/gifs.ts
  app/mm-redux/actions/integrations.ts
  app/mm-redux/actions/posts.ts
  app/mm-redux/actions/search.ts
  app/mm-redux/actions/users.ts
  app/mm-redux/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4603 MM-24895 Load team member and roles in the WebSocket event
  app/actions/websocket.test.js
  app/actions/websocket.ts
  app/actions/websocket/channels.test.js
  app/actions/websocket/channels.ts
  app/actions/websocket/general.test.js
  app/actions/websocket/general.ts
  app/actions/websocket/groups.ts
  app/actions/websocket/index.ts
  app/actions/websocket/integrations.test.js
  app/actions/websocket/integrations.ts
  app/actions/websocket/posts.test.js
  app/actions/websocket/posts.ts
  app/actions/websocket/preferences.ts
  app/actions/websocket/reactions.test.js
  app/actions/websocket/reactions.ts
  app/actions/websocket/roles.ts
  app/actions/websocket/teams.test.js
  app/actions/websocket/teams.ts
  app/actions/websocket/users.test.js
  app/actions/websocket/users.ts
  app/actions/websocket/websocket.test.js
  app/mm-redux/actions/helpers.ts
  app/mm-redux/types/websocket.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#4609 Fix the display the error message if ssoLogin action fails
  app/actions/views/user.js
  app/init/fetch.js
  app/screens/sso/sso.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4613 Automated cherry pick of #4609
  app/actions/views/user.js
  app/init/fetch.js
  app/screens/sso/sso.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4599 Update async-storage dependency
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#4611 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#4608 Show the unsupported alert if server version is available
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
  ios/Podfile.lock
Labels: 4: Reviews Complete, CherryPick/Approved

#4623 [MM-27381] Fix autocomplete after cache delete
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4625 Automated cherry pick of #4623
  app/components/autocomplete/slash_suggestion/slash_suggestion.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4626 Automated cherry pick of #4619
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/constants/navigation.js
  app/screens/user_profile/user_profile.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4628 Automated cherry pick of #4627
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4631 Automated cherry pick of #4630
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
