Repository mattermost/mattermost-mobile, pull requests merged in 2020-11, with the labels that each got.

#4870 [MM-28845]: Add storybook to mobile repo
  .env
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  app/components/loading.stories.tsx
  babel.config.js
  env.d.ts
  index.js
  package-lock.json
  package.json
  storybook/addons.ts
  storybook/index.ts
  storybook/mattermost_storybook.ts
  storybook/storyLoader.js
Labels: 4: Reviews Complete

#4939 Fix Storybook iOS Pods dependencies
  ios/Podfile.lock
Labels: 4: Reviews Complete

#4938 MM-30185 Fix bad permalink reference for saved posts screen
  app/screens/flagged_posts/flagged_posts.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4940 Automated cherry pick of #4938
  app/screens/flagged_posts/flagged_posts.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4936 make mattermost resizeable on Android DeX #3427
  android/app/src/main/AndroidManifest.xml
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4935 MM-30101 Match channel specific global notification preference
  app/screens/channel_notification_preference/channel_notification_preference.android.js
  app/screens/channel_notification_preference/channel_notification_preference.ios.js
  app/screens/channel_notification_preference/channel_notification_preference.test.js
  app/screens/channel_notification_preference/channel_notification_preference_base.js
  app/screens/channel_notification_preference/index.js
  assets/base/i18n/en.json
  test/intl-test-helper.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4946 Automated cherry pick of #4935
  app/screens/channel_notification_preference/channel_notification_preference.android.js
  app/screens/channel_notification_preference/channel_notification_preference.ios.js
  app/screens/channel_notification_preference/channel_notification_preference.test.js
  app/screens/channel_notification_preference/channel_notification_preference_base.js
  app/screens/channel_notification_preference/index.js
  assets/base/i18n/en.json
  test/intl-test-helper.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4948 Automated cherry pick of #4947
  ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4943 Group mentions are not highlighted until they are posted
  app/components/post_body/index.js
Labels: 4: Reviews Complete

#4953 Automated cherry pick of #4952
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4945 MM-27354 Progressive image loading
  android/app/src/main/AndroidManifest.xml
  app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
  app/components/file_attachment_list/file_attachment.js
  app/components/file_attachment_list/file_attachment_image.js
  app/components/file_attachment_list/file_attachment_list.js
  app/components/post_list/post_list.js
  app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
  app/components/progressive_image/progressive_image.js
  app/components/progressive_image/progressive_image.test.js
Labels: 4: Reviews Complete

#4960 Fix the Post List gap visible on iOS 14.2
  patches/react-native-keyboard-tracking-view+5.7.0.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#4962 Automated cherry pick of #4960
  patches/react-native-keyboard-tracking-view+5.7.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4937 MM-29965 Fix at_mention autocomplete selection bug
  app/components/autocomplete/at_mention/at_mention.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
Labels: 4: Reviews Complete, CherryPick/Approved

#4963 Automated cherry pick of #4937
  app/components/autocomplete/at_mention/at_mention.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4964 Bump app build number to 334
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#4965 Automated cherry pick of #4964
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4944 On change, Group mentions are updated in autocomplete
  app/components/autocomplete/at_mention/at_mention.js
  app/mm-redux/selectors/entities/groups.ts
Labels: 4: Reviews Complete

#4961 MM-27354 Emit the event for visible items in the thread screen
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/post_list.js
  app/screens/flagged_posts/flagged_posts.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/search/search.js
  ios/Podfile.lock
Labels: 4: Reviews Complete

#4974 Automated cherry pick of #4972
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4975 Automated cherry pick of #4973
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4976 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#4982 Automated cherry pick of #4976
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
