Repository mattermost/mattermost-mobile, pull requests merged in 2021-04, with the labels that each got.

#5259 [MM-33892] Replace em dash with double dash for commands
  app/actions/views/command.ts
Labels: 4: Reviews Complete, QA Review Done

#5263 Automated cherry pick of #5259
  app/actions/views/command.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5251 Add parsing error to suggestions, add more information to text suggestions and avoid empty suggestions
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.test.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.tsx
  assets/base/i18n/en.json
  assets/base/images/autocomplete/slash_command_error.png
  assets/base/images/autocomplete/slash_command_error@2x.png
  assets/base/images/autocomplete/slash_command_error@3x.png
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#5264 Automated cherry pick of #5251
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.test.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/autocomplete/slash_suggestion/slash_suggestion_item.tsx
  assets/base/i18n/en.json
  assets/base/images/autocomplete/slash_command_error.png
  assets/base/images/autocomplete/slash_command_error@2x.png
  assets/base/images/autocomplete/slash_command_error@3x.png
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5255 MM_33226 [v2] DataOperator - User section
  app/database/admin/data_operator/comparators/index.ts
  app/database/admin/data_operator/handlers/index.ts
  app/database/admin/data_operator/handlers/test.ts
  app/database/admin/data_operator/index.ts
  app/database/admin/data_operator/operators/index.ts
  app/database/admin/data_operator/operators/test.ts
  app/database/admin/data_operator/utils/index.ts
  app/database/admin/data_operator/utils/test.ts
  app/database/admin/data_operator/wrapper/index.ts
  app/database/admin/data_operator/wrapper/test.ts
  app/database/admin/database_manager/__mocks__/index.ts
  app/database/admin/database_manager/index.ts
  app/database/admin/database_manager/test.ts
  app/database/admin/exceptions/data_operator_exception.ts
  app/database/server/models/user.ts
  app/database/server/schema/table_schemas/user.ts
  app/database/server/schema/test.ts
  types/database/database.d.ts
  types/database/enums.ts
  types/database/index.d.ts
  types/database/user.d.ts
Labels: 2: Dev Review, 3: QA Review

#5258 MM_33225 [v2] DataOperator Group section
  app/database/admin/data_operator/comparators/index.ts
  app/database/admin/data_operator/handlers/index.ts
  app/database/admin/data_operator/handlers/test.ts
  app/database/admin/data_operator/operators/index.ts
  app/database/admin/data_operator/operators/test.ts
  types/database/database.d.ts
Labels: 4: Reviews Complete

#5256 Post app call response ephemeral messages as bot
  app/actions/views/command.ts
  app/actions/views/post.js
  app/components/embedded_bindings/button_binding/button_binding.tsx
  app/components/embedded_bindings/button_binding/index.ts
  app/components/embedded_bindings/menu_binding/index.ts
  app/components/embedded_bindings/menu_binding/menu_binding.tsx
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/post_header.js
  app/mm-redux/types/apps.ts
  app/screens/apps_form/apps_form_container.tsx
  app/screens/apps_form/index.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
  types/actions/posts.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5265 Automated cherry pick of #5256
  app/actions/views/command.ts
  app/actions/views/post.js
  app/components/embedded_bindings/button_binding/button_binding.tsx
  app/components/embedded_bindings/button_binding/index.ts
  app/components/embedded_bindings/menu_binding/index.ts
  app/components/embedded_bindings/menu_binding/menu_binding.tsx
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/post_header.js
  app/mm-redux/types/apps.ts
  app/screens/apps_form/apps_form_container.tsx
  app/screens/apps_form/index.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
  types/actions/posts.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5269 MM-32828 Copy temp file if isMediaDocument contentUri is null
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Labels: 4: Reviews Complete, CherryPick/Approved

#5271 Automated cherry pick of #5269
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5261 MM-32725 Reduce KeyStore qty access
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  patches/react-native-keychain+6.2.0.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#5267 MM-31496 Fix modifier typo in search screen
  app/screens/search/__snapshots__/search.test.js.snap
  app/screens/search/search.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5268 MM-31874 Properly use theme mention highlight color
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
  app/components/at_mention/at_mention.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5270 MM-33778 Cancel gallery prepare file when Android's back button is pressed
  app/screens/gallery/footer/prepare_file/prepare_file.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5279 Automated cherry pick of #5261
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  patches/react-native-keychain+6.2.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5280 Automated cherry pick of #5267
  app/screens/search/__snapshots__/search.test.js.snap
  app/screens/search/search.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5281 Automated cherry pick of #5268
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
  app/components/at_mention/at_mention.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5282 Automated cherry pick of #5270
  app/screens/gallery/footer/prepare_file/prepare_file.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5284 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#5286 Automated cherry pick of #5284
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5285 Fix propTypes warnings
  app/components/at_mention/at_mention.js
  app/components/channel_link/channel_link.js
  app/components/channel_loader/channel_loader.js
  app/components/conditional_touchable.js
  app/components/custom_list/custom_list_row.js
  app/components/embedded_bindings/button_binding/button_binding_text.tsx
  app/components/embedded_bindings/embed_text.tsx
  app/components/emoji/emoji.js
  app/components/error_text/error_text.js
  app/components/formatted_markdown_text.js
  app/components/formatted_time.js
  app/components/layout/keyboard_layout/keyboard_layout.js
  app/components/markdown/hashtag/index.js
  app/components/markdown/markdown.js
  app/components/markdown/markdown_block_quote.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_emoji/markdown_emoji.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/markdown/markdown_list_item.js
  app/components/message_attachments/attachment_fields.js
  app/components/message_attachments/attachment_pretext.js
  app/components/message_attachments/attachment_text.js
  app/components/message_attachments/index.js
  app/components/message_attachments/message_attachment.js
  app/components/post_add_channel_member/post_add_channel_member.js
  app/components/post_body/__snapshots__/system_message_helpers.test.js.snap
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/progressive_image/progressive_image.js
  app/components/search_bar/index.js
  app/components/touchable_with_feedback/touchable_with_feedback.android.js
  app/components/touchable_with_feedback/touchable_with_feedback.ios.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5278 [MM-34491] Respect slash command root label
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5288 Automated cherry pick of #5278
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5287 Automated cherry pick of #5285
  app/components/at_mention/at_mention.js
  app/components/channel_link/channel_link.js
  app/components/channel_loader/channel_loader.js
  app/components/conditional_touchable.js
  app/components/custom_list/custom_list_row.js
  app/components/embedded_bindings/button_binding/button_binding_text.tsx
  app/components/embedded_bindings/embed_text.tsx
  app/components/emoji/emoji.js
  app/components/error_text/error_text.js
  app/components/formatted_markdown_text.js
  app/components/formatted_time.js
  app/components/layout/keyboard_layout/keyboard_layout.js
  app/components/markdown/hashtag/index.js
  app/components/markdown/markdown.js
  app/components/markdown/markdown_block_quote.js
  app/components/markdown/markdown_code_block/markdown_code_block.js
  app/components/markdown/markdown_emoji/markdown_emoji.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/markdown/markdown_list_item.js
  app/components/message_attachments/attachment_fields.js
  app/components/message_attachments/attachment_pretext.js
  app/components/message_attachments/attachment_text.js
  app/components/message_attachments/index.js
  app/components/message_attachments/message_attachment.js
  app/components/post_add_channel_member/post_add_channel_member.js
  app/components/post_body/__snapshots__/system_message_helpers.test.js.snap
  app/components/post_body_additional_content/post_body_additional_content.js
  app/components/progressive_image/progressive_image.js
  app/components/search_bar/index.js
  app/components/touchable_with_feedback/touchable_with_feedback.android.js
  app/components/touchable_with_feedback/touchable_with_feedback.ios.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5274 MM-34508 in-app browser emm configuration
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/app_restrictions.xml
  app/init/emm_provider.js
  app/screens/sso/index.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  app/utils/general.js
  app/utils/url.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Docs/Needed

#5289 Automated cherry pick of #5274
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/app_restrictions.xml
  app/init/emm_provider.js
  app/screens/sso/index.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  app/utils/general.js
  app/utils/url.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5290 Automated cherry pick of #5274
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/app_restrictions.xml
  app/init/emm_provider.js
  app/screens/sso/index.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  app/utils/general.js
  app/utils/url.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5291 Bump app build number to 349
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#5296 Bump app build number to 350
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#5293 MM-30430 Detox/E2E: MM-T3189, MM-T3231, MM-T3233
  app/components/post_list/post_list.js
  detox/.detoxrc.json
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/component/post_options.js
  detox/e2e/support/ui/screen/channel.js
  detox/e2e/support/ui/screen/channel_add_members.js
  detox/e2e/support/ui/screen/channel_info.js
  detox/e2e/support/ui/screen/channel_members.js
  detox/e2e/support/ui/screen/permalink.js
  detox/e2e/support/ui/screen/thread.js
  detox/e2e/test/smoke_test/message_deletion.e2e.js
  detox/e2e/test/smoke_test/message_posting.e2e.js
  ios/Podfile.lock
Labels: 2: Dev Review, 4: Reviews Complete

#5294 MM-34681 Validate OpenGraph Image before attempting to load
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5273 MM-31968 Save auto response props on keyboard done
  app/mm-redux/types/users.ts
  app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings_auto_responder/index.ts
  app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.js
  app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.tsx
  app/screens/settings/notification_settings_mentions/notification_settings_mention_base.js
Labels: 4: Reviews Complete

#5295 MM-29317 Select default team when current team is archived
  app/components/post/post.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
  app/screens/channel/index.js
Labels: 4: Reviews Complete

#5277 MM-33227 [v2] Data Operator Channel section
  app/database/admin/data_operator/comparators/index.ts
  app/database/admin/data_operator/handlers/index.ts
  app/database/admin/data_operator/handlers/test.ts
  app/database/admin/data_operator/operators/index.ts
  app/database/admin/data_operator/operators/test.ts
  app/database/admin/data_operator/utils/index.ts
  app/database/admin/database_manager/test.ts
  app/database/default/models/servers.ts
  app/database/server/models/channel.ts
  app/database/server/schema/table_schemas/channel.ts
  app/database/server/schema/test.ts
  types/database/channel.d.ts
  types/database/database.d.ts
  types/database/servers.d.ts
Labels: 2: Dev Review, Do Not Merge/Awaiting PR

#5272 MM-33224 [v2] Data Operator Team section
  app/database/admin/data_operator/comparators/index.ts
  app/database/admin/data_operator/handlers/index.ts
  app/database/admin/data_operator/handlers/test.ts
  app/database/admin/data_operator/operators/index.ts
  app/database/admin/data_operator/operators/test.ts
  app/database/admin/data_operator/utils/index.ts
  app/database/admin/database_manager/test.ts
  app/database/default/models/servers.ts
  app/database/server/models/channel.ts
  app/database/server/models/my_team.ts
  app/database/server/models/slash_command.ts
  app/database/server/models/team.ts
  app/database/server/schema/table_schemas/channel.ts
  app/database/server/schema/table_schemas/slash_command.ts
  app/database/server/schema/table_schemas/team.ts
  app/database/server/schema/test.ts
  types/database/channel.d.ts
  types/database/database.d.ts
  types/database/my_team.d.ts
  types/database/servers.d.ts
  types/database/slash_command.d.ts
  types/database/team.d.ts
Labels: 2: Dev Review

#5303 Automated cherry pick of #5302
  app/components/profile_picture/profile_picture.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5301 Fix logout by preventing the app from showing ErrorTeamsList screen
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
Labels: 4: Reviews Complete

#5300 MM-34714 fix mention highlight to dismiss mentions for non existent users
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5298 Automated cherry pick of #5199
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/slash_suggestion/__snapshots__/slash_suggestion.test.tsx.snap
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
  app/components/emoji_picker/emoji_picker_base.js
  app/components/post_list/__snapshots__/post_list.test.js.snap
  app/components/post_list/post_list.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/teams_list/teams_list.js
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/saved_posts/saved_posts.js
  app/screens/search/__snapshots__/search.test.js.snap
  app/screens/search/search.js
  app/screens/settings/timezone/select_timezone/__snapshots__/select_timezone.test.js.snap
  app/screens/settings/timezone/select_timezone/select_timezone.js
  app/utils/images.js
  share_extension/screens/channel_list.tsx
  share_extension/screens/team_list.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5299 Automated cherry pick of #5294
  app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5305 Automated cherry pick of #5300
  app/components/at_mention/__snapshots__/at_mention.test.js.snap
  app/components/at_mention/at_mention.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5309 Bump app build number to 351
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#5311 Automated cherry pick of #5309
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5313 MM-30431 Detox/E2E: Added e2e for MM-T3196, MM-T3210, MM-T3211, MM-T3262, MM-T3264
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/screens/about/about.js
  app/screens/settings/advanced_settings/advanced_settings.js
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  app/screens/user_profile/user_profile.js
  app/screens/user_profile/user_profile_row.js
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/screen/about.js
  detox/e2e/support/ui/screen/advanced_settings.js
  detox/e2e/support/ui/screen/channel_add_members.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/user_profile.js
  detox/e2e/test/smoke_test/about.e2e.js
  detox/e2e/test/smoke_test/advanced_settings.e2e.js
  detox/e2e/test/smoke_test/channel_add_members.e2e.js
  detox/e2e/test/smoke_test/direct_messages.e2e.js
  ios/Podfile.lock
Labels: 4: Reviews Complete

#5317 [MM-34823, MM-34825] Use RNN 7.11.3
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-navigation+7.11.3.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#5319 Automated cherry pick of #5317
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-navigation+7.11.3.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5322 Set url trailing slash
  app/mm-redux/client/client4.test.js
  app/mm-redux/client/client4.ts
Labels: 3: QA Review, CherryPick/Approved

#5323 Automated cherry pick of #5322
  app/mm-redux/client/client4.test.js
  app/mm-redux/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5325 Automated cherry pick of #5324
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5327 MM-34585 Fix at_mention and channel_mention autocomplete on iOS
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/channel_mention/index.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5297 MM-27849 render emojis with appended skin tone
  app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap
  app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
  app/selectors/emojis.js
  app/utils/emojis.js
Labels: 4: Reviews Complete

#5276 MM-30429 Detox/E2E: Added e2e for MM-T3190, MM-T3212, MM-T3214, MM-T3227
  detox/e2e/support/ui/component/post_options.js
  detox/e2e/support/ui/screen/edit_channel.js
  detox/e2e/support/ui/screen/edit_post.js
  detox/e2e/test/guest_account/guest_experience.e2e.js
  detox/e2e/test/smoke_test/edit_channel.e2e.js
  detox/e2e/test/smoke_test/message_edit.e2e.js
  detox/e2e/test/smoke_test/saved_messages.e2e.js
  detox/e2e/test/smoke_test/search.e2e.js
  detox/package-lock.json
  detox/package.json
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5329 Automated cherry pick of #5327
  app/components/autocomplete/at_mention/at_mention.js
  app/components/autocomplete/channel_mention/channel_mention.js
  app/components/autocomplete/channel_mention/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5332 Automated cherry pick of #5331
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5328 MM-27251 Fetch team channels including archived since last known timestamp
  app/actions/views/channel.js
  app/actions/websocket/websocket.test.js
  app/client/rest/channels.ts
  app/mm-redux/actions/channels.ts
Labels: 4: Reviews Complete

#5339 Fixes for release 1.42
  app/constants/view.js
  app/mm-redux/selectors/entities/teams.ts
  app/store/mmkv_adapter.ts
  app/utils/supported_server.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-mmkv-storage+0.4.4.patch
  patches/react-native-mmkv-storage+0.5.3.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#5340 Automated cherry pick of #5339
  app/constants/view.js
  app/mm-redux/selectors/entities/teams.ts
  app/store/mmkv_adapter.ts
  app/utils/supported_server.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-mmkv-storage+0.4.4.patch
  patches/react-native-mmkv-storage+0.5.3.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5341 Bump app build number to 354
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#5342 Automated cherry pick of #5341
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5343 Bump app version number to 1.42.1
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5344 Specifying minimum server version in README.md
  README.md
  fastlane/metadata/changelog
Labels: 4: Reviews Complete

#5321 add PR/Issue template and release notes section in the PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete

#5351 Translations update from Weblate
  assets/base/i18n/it.json
  assets/base/i18n/nl.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5349 [MM-25709] Keyboard / Input height in iOS for post edits
  app/screens/edit_post/edit_post.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5355 Automated cherry pick of #5349
  app/screens/edit_post/edit_post.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#5163 MM-24693 Add since query param to the getGroups api request
  app/actions/views/channel.js
  app/actions/websocket/index.ts
  app/client/rest/groups.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5356 Automated cherry pick of #5163
  app/actions/views/channel.js
  app/actions/websocket/index.ts
  app/client/rest/groups.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#5354 Detox/E2E: Update android emulator using Pixel 4 XL
  .gitignore
  detox/.detoxrc.json
  detox/android_emulator/config.ini
  detox/android_emulator/pixel_4_xl_skin/back.webp
  detox/android_emulator/pixel_4_xl_skin/layout
  detox/android_emulator/pixel_4_xl_skin/mask.webp
  detox/android_emulator/quickbootChoice.ini
  detox/create_android_emulator.sh
  detox/package.json
Labels: 4: Reviews Complete, release-note-none

#5352 MM-35073 Detox/E2E: Add e2e for remaining eligible mobile smoke tests
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/screen/channel_info.js
  detox/e2e/test/smoke_test/direct_messages.e2e.js
  detox/e2e/test/smoke_test/private_channels.e2e.js
  detox/e2e/test/smoke_test/public_channels.e2e.js
  package.json
Labels: 4: Reviews Complete, release-note-none

#5347 MM-35071 Detox/E2E: Add e2e for MM-T287, MM-T290, MM-T300, MM-T2350, MM-T3151, MM-T3472
  app/components/at_mention/at_mention.js
  app/components/channel_intro/channel_intro.js
  app/components/post/post.js
  app/components/sidebars/settings/settings_sidebar_base.js
  app/components/widgets/settings/text_setting.js
  app/screens/edit_profile/edit_profile.js
  app/screens/reaction_list/reaction_row/index.js
  app/screens/user_profile/__snapshots__/user_profile.test.js.snap
  app/screens/user_profile/user_profile.js
  detox/e2e/support/server_api/user.js
  detox/e2e/support/ui/screen/edit_profile.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/user_profile.js
  detox/e2e/test/account_settings/advanced_settings.e2e.js
  detox/e2e/test/account_settings/user_profile.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5334 MM-34407 Use Avatars for Sidebar DMs
  app/components/channel_icon.js
  app/components/channel_icon.tsx
  app/components/profile_picture/profile_picture.js
  app/components/profile_picture/profile_picture.tsx
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/index.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/components/user_status/__snapshots__/user_status.test.js.snap
  app/components/user_status/user_status.js
  app/components/user_status/user_status.tsx
  app/hooks/did_update.ts
  app/hooks/index.ts
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/index.js
  babel.config.js
  tsconfig.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5353 [MM-26160] Updates to check if text is string before attaching as string
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  share_extension/types/index.d.ts
  share_extension/utils/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5359 Automated cherry pick of #5353
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  share_extension/types/index.d.ts
  share_extension/utils/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5357 Adding new language Hungarian Beta
  app/i18n/index.js
  assets/base/i18n/hu.json
Labels: 4: Reviews Complete, release-note

#5358 Automated cherry pick of #5334
  app/components/channel_icon.js
  app/components/channel_icon.tsx
  app/components/profile_picture/profile_picture.js
  app/components/profile_picture/profile_picture.tsx
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/components/sidebars/main/channels_list/channel_item/index.js
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/components/user_status/__snapshots__/user_status.test.js.snap
  app/components/user_status/user_status.js
  app/components/user_status/user_status.tsx
  app/hooks/did_update.ts
  app/hooks/index.ts
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info.test.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/index.js
  babel.config.js
  tsconfig.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5304 [MM-34746] Fix ephemeral error message response
  app/actions/apps.ts
  app/actions/views/command.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
  app/components/embedded_bindings/button_binding/button_binding.tsx
  app/components/embedded_bindings/button_binding/index.ts
  app/components/embedded_bindings/menu_binding/index.ts
  app/components/embedded_bindings/menu_binding/menu_binding.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_container.tsx
  app/screens/apps_form/index.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
  types/actions/apps.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5316 [MM-34203] Send team id on bindings call
  app/client/rest/apps.ts
  app/mm-redux/actions/apps.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note-none

#5361 Automated cherry pick of #5316
  app/client/rest/apps.ts
  app/mm-redux/actions/apps.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5360 Automated cherry pick of #5304
  app/actions/apps.ts
  app/actions/views/command.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
  app/components/embedded_bindings/button_binding/button_binding.tsx
  app/components/embedded_bindings/button_binding/index.ts
  app/components/embedded_bindings/menu_binding/index.ts
  app/components/embedded_bindings/menu_binding/menu_binding.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_container.tsx
  app/screens/apps_form/index.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
  types/actions/apps.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5308 MM-34069 include current user in return values from getProfile* actions
  app/mm-redux/actions/users.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5363 Automated cherry pick of #5308
  app/mm-redux/actions/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
