Repository mattermost/mattermost-mobile, pull requests merged in 2021-01, with the labels that each got.

#5044 Add check for empty translation source strings
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/precommit/i18n.sh
Labels: 4: Reviews Complete

#4620 Handle go to location from CommandResponse
  app/actions/views/channel.js
  app/actions/views/permalink.ts
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/draft_input/draft_input.test.js
  app/components/post_draft/draft_input/index.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/constants/deep_linking.js
  app/mm-redux/actions/integrations.ts
  app/utils/draft.js
  app/utils/url.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5082 Automated cherry pick of #4620
  app/actions/views/channel.js
  app/actions/views/permalink.ts
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/draft_input/draft_input.test.js
  app/components/post_draft/draft_input/index.js
  app/components/post_list/post_list.js
  app/components/post_list/post_list.test.js
  app/constants/deep_linking.js
  app/mm-redux/actions/integrations.ts
  app/utils/draft.js
  app/utils/url.js
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5085 Automated cherry pick of #5084
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5087 Automated cherry pick of #5086
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5091 Automated cherry pick of #5067
  app/components/client_upgrade_listener/client_upgrade_listener.js
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/message_attachments/attachment_author.js
  app/components/message_attachments/attachment_title.js
  app/components/post_attachment_opengraph/post_attachment_opengraph.js
  app/components/post_body_additional_content/post_body_additional_content.js
  app/mm-redux/actions/integrations.ts
  app/screens/about/about.js
  app/screens/client_upgrade/client_upgrade.js
  app/screens/settings/general/settings.js
  app/screens/user_profile/user_profile.js
  app/utils/draft.js
  app/utils/supported_server.ts
  app/utils/url.js
  app/utils/url.test.js
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
  test/setup.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5070 MM_30476 [v2] Added all isolated tables from the server schema
  app/database/default/models/index.ts
  app/database/default/schema/index.ts
  app/database/default/schema/test.ts
  app/database/server/migration/index.ts
  app/database/server/models/custom_emoji.ts
  app/database/server/models/role.ts
  app/database/server/models/system.ts
  app/database/server/models/terms_of_service.ts
  app/database/server/schema/index.ts
  app/database/server/schema/table_schemas/custom_emoji.ts
  app/database/server/schema/table_schemas/index.ts
  app/database/server/schema/table_schemas/role.ts
  app/database/server/schema/table_schemas/system.ts
  app/database/server/schema/table_schemas/terms_of_service.ts
  app/database/server/schema/test.ts
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  test/setup.ts
  types/database/custom_emoji.d.ts
  types/database/role.d.ts
  types/database/system.d.ts
  types/database/terms_of_service.d.ts
Labels: 4: Reviews Complete

#5095 Automated cherry pick of #5094
  app/components/sidebars/main/channels_list/channel_item/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5097 Automated cherry pick of #5096
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5090 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/sv.json
Labels: 4: Reviews Complete

#5098 [MM-31778]: fix false error message on tapping channel link
  app/components/markdown/markdown_link/markdown_link.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5099 Automated cherry pick of #5098
  app/components/markdown/markdown_link/markdown_link.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5092 MM-31272 Detox/E2E - Add e2e test for MM-T3646
  detox/e2e/support/server_api/index.js
  detox/e2e/support/server_api/preference.js
  detox/e2e/support/server_api/user.js
  detox/e2e/support/utils.js
  detox/e2e/test/teams/teams_order.e2e.js
Labels: 4: Reviews Complete

#5100 MM-31272 Detox/E2E - Add e2e tests for MM-T3232 and MM-T3234
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/component/index.js
  detox/e2e/support/ui/component/post_options.js
  detox/e2e/support/ui/screen/channel.js
  detox/e2e/support/ui/screen/thread.js
  detox/e2e/test/autocomplete/edit_post.e2e.js
  detox/e2e/test/messaging/recent_emojis.e2e.js
  detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
  detox/e2e/test/messaging/tapping_channel_url_link_joins_channel.e2e.js
  detox/e2e/test/notifications/in_app_notification.e2e.js
  detox/e2e/test/smoke_test/message_deletion.e2e.js
Labels: 4: Reviews Complete

#5071 MM_30476 [v2] Section 'Team' of the Server schema
  app/database/server/models/index.ts
  app/database/server/models/my_team.ts
  app/database/server/models/slash_command.ts
  app/database/server/models/team.ts
  app/database/server/models/team_channel_history.ts
  app/database/server/models/team_membership.ts
  app/database/server/models/team_search_history.ts
  app/database/server/schema/index.ts
  app/database/server/schema/table_schemas/index.ts
  app/database/server/schema/table_schemas/my_team.ts
  app/database/server/schema/table_schemas/slash_command.ts
  app/database/server/schema/table_schemas/team.ts
  app/database/server/schema/table_schemas/team_channel_history.ts
  app/database/server/schema/table_schemas/team_membership.ts
  app/database/server/schema/table_schemas/team_search_history.ts
  app/database/server/schema/test.ts
  types/database/channel.d.ts
  types/database/groups_in_team.d.ts
  types/database/my_team.d.ts
  types/database/slash_command.d.ts
  types/database/team.d.ts
  types/database/team_channel_history.d.ts
  types/database/team_membership.d.ts
  types/database/team_search_history.d.ts
  types/database/user.d.ts
Labels: 4: Reviews Complete

#5104 MM-31873 fix race condition that prevented the device id registration
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5108 Automated cherry pick of #5104
  app/init/push_notifications.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5109 MM-31705 allow file local path to use multiple dots
  app/utils/file.js
  app/utils/file.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5110 Automated cherry pick of #5109
  app/utils/file.js
  app/utils/file.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5106 [MM-30976] fix viewing/joining archived channels using channel links
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  app/selectors/channel.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5113 Automated cherry pick of #5106
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  app/selectors/channel.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5114 Automated cherry pick of #5112
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5093 Added Bulgarian and Swedish translation
  app/i18n/index.js
Labels: 4: Reviews Complete

#5073 MM_30476 [v2] Section 'User' of the server schema
  app/database/server/models/channel_membership.ts
  app/database/server/models/index.ts
  app/database/server/models/preference.ts
  app/database/server/models/reaction.ts
  app/database/server/models/user.ts
  app/database/server/schema/index.ts
  app/database/server/schema/table_schemas/channel_membership.ts
  app/database/server/schema/table_schemas/index.ts
  app/database/server/schema/table_schemas/preference.ts
  app/database/server/schema/table_schemas/reaction.ts
  app/database/server/schema/table_schemas/user.ts
  app/database/server/schema/test.ts
  types/database/channel_membership.d.ts
  types/database/group_membership.d.ts
  types/database/index.d.ts
  types/database/post.d.ts
  types/database/preference.d.ts
  types/database/reaction.d.ts
  types/database/user.d.ts
Labels: 4: Reviews Complete

#5115 MM-31764 Fix image attachment layout when permanent sidebar is visible
  app/components/file_attachment_list/file_attachment_list.js
  app/components/image_viewport.js
  app/components/sidebars/main/main_sidebar.ios.js
  app/components/sidebars/main/main_sidebar.test.js
  app/init/device.ts
  app/init/global_event_handler.js
  app/mattermost.js
  packager/moduleNames.js
  packager/modules.android.js
  packager/modules.ios.js
Labels: 4: Reviews Complete

#5105 MM-31196 Add missing "(you)" in at_mention autocomplete
  app/components/autocomplete/at_mention_item/at_mention_item.tsx
Labels: 4: Reviews Complete

#5103 Upgrade Dependencies
  .eslintrc.json
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  app/actions/navigation/index.js
  app/actions/navigation/index.test.js
  app/client/websocket.ts
  app/components/autocomplete/autocomplete.js
  app/components/edit_channel_info/edit_channel_info.test.js
  app/components/sidebars/main/channels_list/list/list.js
  app/mm-redux/actions/preferences.ts
  app/mm-redux/client/websocket_client.ts
  app/mm-redux/types/users.ts
  app/screens/edit_profile/edit_profile.test.js
  app/screens/gallery/gallery.js
  app/screens/gallery/video_controls.tsx
  app/screens/settings/theme/__snapshots__/theme.test.js.snap
  app/screens/settings/theme/theme.test.js
  app/store/index.ts
  detox/package-lock.json
  detox/package.json
  fastlane/Gemfile.lock
  ios/Gemfile
  ios/Gemfile.lock
  ios/Mattermost/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.63.4.patch
  patches/react-native-device-info+8.0.0.patch
  patches/react-native-elements+3.1.0.patch
  patches/react-native-keychain+6.2.0.patch
  patches/react-native-localize+2.0.0.patch
  patches/react-native-mmkv-storage+0.4.1.patch
  patches/react-native-mmkv-storage+0.4.3.patch
  patches/react-native-navigation+7.8.1.patch
  patches/react-native-notifications+3.4.2.patch
  types/modules/react-native-slider.d.ts
Labels: 4: Reviews Complete

#5072 MM_30476 [v2] Section 'Group' of the server schema
  app/database/server/models/channel_membership.ts
  app/database/server/models/group.ts
  app/database/server/models/group_membership.ts
  app/database/server/models/groups_in_channel.ts
  app/database/server/models/groups_in_team.ts
  app/database/server/models/index.ts
  app/database/server/models/my_team.ts
  app/database/server/models/reaction.ts
  app/database/server/models/team_search_history.ts
  app/database/server/schema/index.ts
  app/database/server/schema/table_schemas/group.ts
  app/database/server/schema/table_schemas/group_membership.ts
  app/database/server/schema/table_schemas/groups_in_channel.ts
  app/database/server/schema/table_schemas/groups_in_team.ts
  app/database/server/schema/table_schemas/index.ts
  app/database/server/schema/test.ts
  types/database/channel_membership.d.ts
  types/database/group.d.ts
  types/database/group_membership.d.ts
  types/database/groups_in_channel.d.ts
  types/database/my_team.d.ts
  types/database/posts_in_channel.d.ts
  types/database/reaction.d.ts
  types/database/team_search_history.d.ts
Labels: 4: Reviews Complete

#5077 MM_30476 [v2] Section 'Post' of the server schema
  app/database/server/models/draft.ts
  app/database/server/models/file.ts
  app/database/server/models/index.ts
  app/database/server/models/post.ts
  app/database/server/models/post_metadata.ts
  app/database/server/models/posts_in_thread.ts
  app/database/server/schema/index.ts
  app/database/server/schema/table_schemas/draft.ts
  app/database/server/schema/table_schemas/file.ts
  app/database/server/schema/table_schemas/index.ts
  app/database/server/schema/table_schemas/post.ts
  app/database/server/schema/table_schemas/post_metadata.ts
  app/database/server/schema/table_schemas/posts_in_thread.ts
  app/database/server/schema/test.ts
  types/database/draft.d.ts
  types/database/file.d.ts
  types/database/index.d.ts
  types/database/post.d.ts
  types/database/post_metadata.d.ts
  types/database/posts_in_channel.d.ts
  types/database/posts_in_thread.d.ts
Labels: 4: Reviews Complete

#5118 Detox/E2E: Fix CustomDetoxEnvironment constructor args
  detox/e2e/environment.js
Labels: 4: Reviews Complete

#5117 MM-32008 Do not cache request body
  app/mm-redux/client/client4.ts
Labels: 4: Reviews Complete

#5078 MM_30476 [v2] Section 'Channel' of the server schema
  app/database/server/models/channel.ts
  app/database/server/models/channel_info.ts
  app/database/server/models/index.ts
  app/database/server/models/my_channel.ts
  app/database/server/models/my_channel_settings.ts
  app/database/server/models/posts_in_channel.ts
  app/database/server/models/reaction.ts
  app/database/server/models/team.ts
  app/database/server/models/team_channel_history.ts
  app/database/server/schema/index.ts
  app/database/server/schema/table_schemas/channel.ts
  app/database/server/schema/table_schemas/channel_info.ts
  app/database/server/schema/table_schemas/index.ts
  app/database/server/schema/table_schemas/my_channel.ts
  app/database/server/schema/table_schemas/my_channel_settings.ts
  app/database/server/schema/table_schemas/posts_in_channel.ts
  app/database/server/schema/test.ts
  types/database/channel.d.ts
  types/database/channel_info.d.ts
  types/database/channel_membership.d.ts
  types/database/my_channel.d.ts
  types/database/my_channel_settings.d.ts
  types/database/reaction.d.ts
  types/database/team.d.ts
  types/database/team_channel_history.d.ts
Labels: 4: Reviews Complete

#5123 MM-31882 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete

#5075 OAuth through OS browser, added google login & open id methods
  android/app/src/main/AndroidManifest.xml
  app/constants/view.js
  app/mm-redux/types/config.ts
  app/mm-redux/types/module.d.ts
  app/screens/login_options/login_options.js
  app/screens/login_options/login_options.test.js
  app/screens/select_server/select_server.js
  app/screens/sso/index.js
  app/screens/sso/index.tsx
  app/screens/sso/sso.js
  app/screens/sso/sso.test.tsx
  app/screens/sso/sso_with_redirect_url.test.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  app/screens/sso/sso_with_webview.tsx
  assets/base/i18n/en.json
  assets/base/images/google.png
  fastlane/Fastfile
  ios/Mattermost/Info.plist
Labels: 4: Reviews Complete

#5121 MM-31990 fix limit reacting to a post to 40 different emojis
  app/components/reactions/index.js
  app/screens/post_options/index.js
  app/selectors/emojis.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5129 Automated cherry pick of #5121
  app/components/reactions/index.js
  app/screens/post_options/index.js
  app/selectors/emojis.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5132 MM-32183 Fix in-app notification + Android ack
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  app/screens/notification/index.tsx
  patches/react-native-navigation+7.8.1.patch
Labels: 4: Reviews Complete, CherryPick/Approved

#5138 Automated cherry pick of #5132
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  app/screens/notification/index.tsx
  patches/react-native-navigation+7.8.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5120 [MM-30994] tweak emoji search options for better results
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.test.js
  app/components/emoji_picker/emoji_picker.test.js
  app/components/emoji_picker/index.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5139 Automated cherry pick of #5120
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.test.js
  app/components/emoji_picker/emoji_picker.test.js
  app/components/emoji_picker/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5141 Automated cherry pick of #5140
  android/app/build.gradle
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5143 Automated cherry pick of #5142
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
