Repository mattermost/mattermost-mobile, pull requests merged in 2021-12, with the labels that each got.

#5790 [Gekidou] Adding logic to hide the list of teams on the teams sidebar when needed
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/channel_list/channel_list.tsx
  app/components/channel_list/header/__snapshots__/header.test.tsx.snap
  app/components/channel_list/header/header.tsx
  app/components/channel_list/index.test.tsx
  app/components/channel_list/index.tsx
  app/components/team_sidebar/team_sidebar.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
Labels: release-note-none

#5860 Bump Version 1.48.1 build 381
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5861 Automated cherry pick of #5860
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5871 [Gekidou] update dependencies
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/post_list/post/system_message/system_message_helpers.test.js
  app/screens/in_app_notification/index.tsx
  detox/package-lock.json
  detox/package.json
  env.d.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+7.1.5.patch
  patches/react-native+0.66.4.patch
  patches/react-native-navigation+7.24.0.patch
  patches/react-native-reanimated+2.2.4.patch
Labels: 4: Reviews Complete, release-note-none

#5872 [Gekidou] Add color to loading spinners
  app/components/loading/__snapshots__/index.test.tsx.snap
  app/components/loading/index.tsx
  app/screens/channel/failed_channels/index.tsx
  app/screens/channel/failed_teams/index.tsx
  app/screens/login/form.tsx
  app/screens/mfa/index.tsx
  app/screens/server/form.tsx
Labels: 2: Dev Review, release-note-none

#5869 MM-40530 Support SVG for markdown inline images
  app/components/markdown/markdown_image/markdown_image.js
  app/components/markdown/markdown_table_image/markdown_table_image.tsx
  app/utils/images.test.ts
  app/utils/images.ts
Labels: 4: Reviews Complete, release-note

#5870 Update dependencies
  .eslintrc.json
  android/app/build.gradle
  app/components/avatars/avatars.stories.tsx
  app/components/loading.stories.tsx
  app/components/post_draft/post_draft.test.js
  app/components/post_list/post/system_message/system_message_helpers.test.js
  app/screens/notification/index.tsx
  app/screens/selector_screen/selector_screen.test.tsx
  detox/package-lock.json
  detox/package.json
  env.d.ts
  fastlane/Gemfile.lock
  index.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+7.1.5.patch
  patches/react-native+0.66.4.patch
  patches/react-native-navigation+7.24.0.patch
  storybook/addons.ts
  storybook/index.ts
  storybook/mattermost_storybook.ts
  storybook/storyLoader.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#5634 [MM-11997] - Date picker should re-open on previously selected date
  app/components/autocomplete/date_suggestion/date_suggestion.js
Labels: 4: Reviews Complete, release-note

#5823 [Gekidou]: MM-39757 - Recent mentions
  app/actions/local/post.ts
  app/actions/remote/post.ts
  app/actions/remote/search.ts
  app/client/rest/posts.ts
  app/components/post_list/date_separator/index.tsx
  app/components/post_list/post/avatar/index.tsx
  app/components/post_list/post/header/header.tsx
  app/components/system_avatar/index.tsx
  app/constants/database.ts
  app/constants/screens.ts
  app/database/models/server/index.ts
  app/database/models/server/user.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/index.ts
  app/queries/servers/channel.ts
  app/screens/home/recent_mentions/components/channel_info/channel_info.tsx
  app/screens/home/recent_mentions/components/channel_info/index.ts
  app/screens/home/recent_mentions/components/empty.tsx
  app/screens/home/recent_mentions/components/mention/index.ts
  app/screens/home/recent_mentions/components/mention/mention.tsx
  app/screens/home/recent_mentions/components/mention_icon.svg
  app/screens/home/recent_mentions/index.ts
  app/screens/home/recent_mentions/index.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/utils/helpers.ts
  app/utils/post/index.ts
  app/utils/post_list/index.ts
  app/utils/user/index.ts
  assets/base/i18n/en.json
  types/api/posts.d.ts
  types/database/database.d.ts
  types/database/models/servers/user.d.ts
Labels: release-note-none

#5879 Detox/E2E: Fix android build command and update deps
  detox/.detoxrc.json
  detox/package-lock.json
  detox/package.json
  package-lock.json
  package.json
  patches/@rudderstack+rudder-sdk-react-native+1.1.0.patch
  patches/react-native-mmkv-storage+0.6.6.patch
Labels: 4: Reviews Complete, release-note-none

#5881 Fixes custom status update with no expiry
  app/actions/views/custom_status.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#5846 [Gekidou] - Channel Intro
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/preference.ts
  app/actions/remote/systems.ts
  app/actions/remote/user.ts
  app/actions/websocket/index.ts
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/channel_list/index.tsx
  app/components/post_list/index.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap
  app/components/post_list/post/system_message/system_message.tsx
  app/components/post_list/post_list.tsx
  app/components/tag/index.tsx
  app/constants/screens.ts
  app/database/operator/server_data_operator/handlers/user.test.ts
  app/database/operator/server_data_operator/handlers/user.ts
  app/i18n/index.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.ts
  app/queries/servers/preference.ts
  app/screens/channel/index.tsx
  app/screens/channel/intro/direct_channel/direct_channel.tsx
  app/screens/channel/intro/direct_channel/group/group.tsx
  app/screens/channel/intro/direct_channel/group/index.ts
  app/screens/channel/intro/direct_channel/index.ts
  app/screens/channel/intro/direct_channel/member/index.ts
  app/screens/channel/intro/direct_channel/member/member.tsx
  app/screens/channel/intro/illustration/private.tsx
  app/screens/channel/intro/illustration/public.tsx
  app/screens/channel/intro/index.ts
  app/screens/channel/intro/intro.tsx
  app/screens/channel/intro/options/favorite/favorite.tsx
  app/screens/channel/intro/options/favorite/index.ts
  app/screens/channel/intro/options/index.tsx
  app/screens/channel/intro/options/item.tsx
  app/screens/channel/intro/public_or_private_channel/index.ts
  app/screens/channel/intro/public_or_private_channel/public_or_private_channel.tsx
  app/screens/channel/intro/townsquare/index.tsx
  assets/base/i18n/en.json
  types/api/channels.d.ts
  types/database/database.d.ts
  types/database/raw_values.d.ts
Labels: 2: Dev Review, release-note-none

#5878 [Gekidou] Add is_unread to MyChannel model
  app/actions/local/channel.ts
  app/components/team_sidebar/team_list/team_item/index.ts
  app/database/models/server/my_channel.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/table_schemas/my_channel.ts
  app/database/schema/server/test.ts
  app/screens/home/tab_bar/home.tsx
  types/api/channels.d.ts
  types/database/models/servers/my_channel.d.ts
Labels: 2: Dev Review, release-note-none

#5849 MM-39712 - Edit Profile Screen without image picker
  app/actions/local/timezone.ts
  app/actions/local/user.ts
  app/actions/remote/user.ts
  app/components/error_text/index.tsx
  app/components/floating_text_input_label/index.tsx
  app/components/profile_picture/index.tsx
  app/components/tablet_title/index.tsx
  app/constants/files.ts
  app/constants/screens.ts
  app/i18n/index.ts
  app/screens/edit_profile/components/email_field.tsx
  app/screens/edit_profile/components/field.tsx
  app/screens/edit_profile/components/profile_error.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/edit_profile/index.ts
  app/screens/home/account/components/options/your_profile/index.tsx
  app/screens/home/account/components/tablet_view/index.ts
  app/screens/home/account/index.tsx
  app/screens/index.tsx
  app/screens/navigation.ts
  assets/base/i18n/en.json
  types/api/config.d.ts
  types/screens/edit_profile.d.ts
  types/screens/navigation.d.ts
  types/utils/index.d.ts
Labels: 4: Reviews Complete, release-note-none

#5885 [Gekidou] Update dependencies
  NOTICE.txt
  babel.config.js
  detox/package-lock.json
  detox/package.json
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+7.1.7.patch
  patches/expo-file-system+13.1.0.patch
  patches/react-native-navigation+7.24.3.patch
  patches/react-native-notifications+4.1.3.patch
  patches/react-native-reanimated+2.3.0.patch
Labels: 4: Reviews Complete, release-note-none
