Repository mattermost/mattermost-mobile, pull requests merged in 2021-10, with the labels that each got.

#5707 [Gekidou] Entry point when upgrading from v1
  app/actions/remote/entry.ts
  app/init/launch.ts
  app/utils/file/index.ts
  app/utils/mattermost_managed.ts
  ios/Mattermost/MattermostManaged.m
  types/launch/index.ts
Labels: 2: Dev Review, release-note-none

#5706 update dependencies
  ios/Podfile
  ios/Podfile.lock
  ios/patches/XCDYouTubeVideoOperation.patch
  package-lock.json
  package.json
  patches/react-native-fast-image+8.5.11.patch
  patches/react-native-mmkv-storage+0.6.4.patch
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#5709 Automated cherry pick of #5706
  ios/Podfile
  ios/Podfile.lock
  ios/patches/XCDYouTubeVideoOperation.patch
  package-lock.json
  package.json
  patches/react-native-fast-image+8.5.11.patch
  patches/react-native-mmkv-storage+0.6.4.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5710 Remove team unreads and rely on channel member instead
  app/actions/local/channel.ts
  app/actions/remote/entry.ts
  app/actions/remote/retry.ts
  app/actions/remote/team.ts
  app/actions/remote/user.ts
  app/client/rest/teams.ts
  app/database/models/server/my_team.ts
  app/database/operator/server_data_operator/handlers/team.test.ts
  app/database/operator/server_data_operator/transformers/team.test.ts
  app/database/operator/server_data_operator/transformers/team.ts
  app/database/schema/server/table_schemas/my_team.ts
  app/database/schema/server/test.ts
  app/queries/servers/entry.ts
  app/queries/servers/team.ts
  ios/Mattermost/MattermostManaged.m
  types/api/teams.d.ts
  types/database/models/servers/my_team.d.ts
  types/database/raw_values.d.ts
Labels: 4: Reviews Complete, release-note-none

#5711 [Gekidou] Upgrade to RN 0.66.0
  .flowconfig
  android/app/build.gradle
  android/gradle.properties
  app/context/theme/index.tsx
  ios/Mattermost/AppDelegate.m
  ios/Podfile
  ios/Podfile.lock
  ios/bundleReactNative.sh
  package-lock.json
  package.json
  patches/react-native+0.66.0.patch
  patches/react-native-keychain+8.0.0.patch
Labels: 4: Reviews Complete, release-note-none

#5713 Translations update from Weblate
  assets/base/i18n/es.json
  assets/base/i18n/sv.json
Labels: release-note-none

#5714 Automated cherry pick of #5713
  assets/base/i18n/es.json
  assets/base/i18n/sv.json
Labels: release-note-none

#5715 Bump app build number to 371
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5716 Automated cherry pick of #5715
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5678 [MM-31389] Show confirm modal for `@here` mentions
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/draft_input/draft_input.test.js
  app/utils/draft.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#5719 Translations update from Weblate
  assets/base/i18n/de.json
Labels: release-note-none

#5720 Automated cherry pick of #5719
  assets/base/i18n/de.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5663 Draft - Add Server Screen Gekidou Updates
  android/app/src/main/AndroidManifest.xml
  app/actions/remote/general.ts
  app/actions/remote/session.ts
  app/components/app_version/__snapshots__/index.test.tsx.snap
  app/components/app_version/index.tsx
  app/components/floating_text_input_label/index.tsx
  app/screens/login/index.tsx
  app/screens/login_options/index.tsx
  app/screens/mfa/index.tsx
  app/screens/mfa/mfa.test.tsx
  app/screens/navigation.ts
  app/screens/server/background.tsx
  app/screens/server/form.tsx
  app/screens/server/header.tsx
  app/screens/server/index.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso.test.tsx
  app/store/ephemeral_store.ts
  app/utils/buttonStyles.ts
  app/utils/client_error.ts
  app/utils/typography.ts
  assets/base/i18n/en.json
  types/database/database.d.ts
Labels: release-note-none

#5727 Upgrade to rn 0.66.1
  .eslintrc.json
  .flowconfig
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap
  app/components/autocomplete/slash_suggestion/__snapshots__/slash_suggestion.test.tsx.snap
  app/components/autocomplete/slash_suggestion/app_slash_suggestion/__snapshots__/app_slash_suggestion.test.tsx.snap
  app/components/custom_list/__snapshots__/index.test.js.snap
  app/components/global_threads/thread_list/__snapshots__/index.test.tsx.snap
  app/components/image_viewport.tsx
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/quick_actions/camera_quick_action/__snapshots__/camera_quick_action.test.js.snap
  app/components/post_draft/quick_actions/file_quick_action/__snapshots__/file_quick_action.test.js.snap
  app/components/post_draft/quick_actions/image_quick_action/__snapshots__/image_quick_action.test.js.snap
  app/components/sidebars/main/channels_list/list/index.js
  app/components/sidebars/main/channels_list/list/list.js
  app/components/sidebars/main/main_sidebar.ios.js
  app/hooks/permanent_sidebar.ts
  app/init/credentials.js
  app/init/device.ts
  app/init/global_event_handler.js
  app/mm-redux/selectors/entities/common.ts
  app/mm-redux/selectors/entities/preferences.ts
  app/mm-redux/selectors/entities/teams.ts
  app/screens/channel/channel_nav_bar/channel_nav_bar.js
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/select_server/select_server.js
  app/screens/select_server/select_server.test.js
  app/screens/settings/sidebar/index.js
  app/screens/settings/timezone/select_timezone/__snapshots__/select_timezone.test.js.snap
  app/screens/sso/sso_with_webview.tsx
  app/store/helpers.ts
  app/store/index.ts
  ios/Gemfile
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.66.1.patch
  patches/react-native-device-info+8.4.3.patch
  patches/react-native-haptic-feedback+1.11.0.patch
  patches/react-native-haptic-feedback+1.13.0.patch
  patches/react-native-keychain+8.0.0.patch
  patches/react-native-mmkv-storage+0.6.6.patch
  patches/react-native-navigation+7.23.1.patch
  patches/react-native-vector-icons+9.0.0.patch
  test/setup.js
Labels: 4: Reviews Complete, release-note-none
