Repository mattermost/mattermost-mobile, pull requests merged in 2021-08, with the labels that each got.

#5581 [Gekidou] Update dependencies
  android/app/src/main/java/com/mattermost/helpers/Credentials.java
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferences.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/manager/test.ts
  app/database/manager/test_manual.ts
  app/database/operator/base_data_operator/index.ts
  app/database/operator/server_data_operator/handlers/posts_in_channel.ts
  app/database/operator/utils/test.ts
  app/init/launch.ts
  app/init/push_notifications.ts
  detox/package-lock.json
  detox/package.json
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@nozbe+watermelondb+0.23.0.patch
  patches/react-native-device-info+8.1.4.patch
  patches/react-native-fast-image+8.3.7.patch
  patches/react-native-navigation+7.18.1.patch
  patches/react-native-notifications+4.1.1.patch
Labels: 2: Dev Review, release-note-none

#5587 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5588 [Gekidou] Fix database models type definition
  types/database/models/servers/channel.d.ts
  types/database/models/servers/group.d.ts
  types/database/models/servers/post.d.ts
  types/database/models/servers/user.d.ts
Labels: 2: Dev Review, release-note-none

#5589 Custom status warning issue fix
  app/screens/channel_info/index.js
Labels: release-note

#5590 [Gekidou] fixes
  app/context/theme/index.tsx
  app/screens/channel/index.tsx
  ios/Podfile.lock
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#5594 [Gekidou] Allow multiple posts in thread and posts in channel for a specific root or channel
  app/database/models/server/channel.ts
  app/database/models/server/post.ts
  app/database/models/server/posts_in_channel.ts
  app/database/models/server/posts_in_thread.ts
  app/database/operator/server_data_operator/handlers/posts_in_channel.ts
  app/database/operator/server_data_operator/handlers/posts_in_thread.ts
  app/database/operator/server_data_operator/transformers/post.test.ts
  app/database/operator/server_data_operator/transformers/post.ts
  app/database/schema/server/table_schemas/posts_in_channel.ts
  app/database/schema/server/table_schemas/posts_in_thread.ts
  app/database/schema/server/test.ts
  app/queries/servers/post.ts
  types/database/models/servers/posts_in_channel.d.ts
  types/database/models/servers/posts_in_thread.d.ts
  types/database/raw_values.d.ts
Labels: 2: Dev Review, release-note-none

#5591 Gekidou about screen
  app/components/app_version/index.tsx
  app/constants/screens.ts
  app/screens/about/index.tsx
  app/screens/about/learn_more.tsx
  app/screens/about/server_version.tsx
  app/screens/about/subtitle.tsx
  app/screens/about/title.tsx
  app/screens/about/tos_privacy.tsx
  app/screens/channel/channel_nav_bar/channel_title/channel_guest_label/index.tsx
  app/screens/channel/index.tsx
  app/screens/index.tsx
  app/screens/login/index.tsx
  app/screens/mfa/index.tsx
  app/utils/draft/index.ts
  app/utils/i18n.ts
  assets/base/i18n/en.json
  babel.config.js
  ios/Podfile.lock
Labels: 4: Reviews Complete, release-note-none

#5596 Fix android share extension crash
  patches/react-native-navigation+7.18.1.patch
  share_extension/components/channel_button.tsx
  share_extension/components/team_button.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5598 Automated cherry pick of #5596
  patches/react-native-navigation+7.18.1.patch
  share_extension/components/channel_button.tsx
  share_extension/components/team_button.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5593 [Gekidou] groups
  app/actions/remote/entry.ts
  app/actions/remote/group.ts
  app/client/rest/groups.ts
  app/components/markdown/at_mention/index.tsx
  app/constants/database.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/models/server/channel.ts
  app/database/models/server/group.ts
  app/database/models/server/groups_channel.ts
  app/database/models/server/groups_team.ts
  app/database/models/server/index.ts
  app/database/models/server/team.ts
  app/database/operator/server_data_operator/comparators/index.ts
  app/database/operator/server_data_operator/handlers/group.test.ts
  app/database/operator/server_data_operator/handlers/group.ts
  app/database/operator/server_data_operator/transformers/group.test.ts
  app/database/operator/server_data_operator/transformers/group.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/group.ts
  app/database/schema/server/table_schemas/groups_channel.ts
  app/database/schema/server/table_schemas/groups_team.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/test.ts
  app/utils/user/index.ts
  types/api/groups.d.ts
  types/database/database.d.ts
  types/database/models/servers/channel.d.ts
  types/database/models/servers/group.d.ts
  types/database/models/servers/groups_channel.d.ts
  types/database/models/servers/groups_team.d.ts
  types/database/models/servers/team.d.ts
  types/database/raw_values.d.ts
Labels: 4: Reviews Complete, release-note-none

#5597 MM-37660 Fix keep mention for channel A when opening a push notification on channel B
  app/actions/views/root.js
  app/components/network_indicator/network.tsx
  app/init/push_notifications.ts
  app/screens/channel/channel_base.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5599 MM-37666 Properly dismiss edit profile screen
  app/actions/navigation/index.js
  app/screens/edit_profile/edit_profile.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5604 Automated cherry pick of #5597
  app/actions/views/root.js
  app/components/network_indicator/network.tsx
  app/init/push_notifications.ts
  app/screens/channel/channel_base.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5601 MM-37674 Fix android push notification crash
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5595 MM-37609 Specify screenId for files uploads handler
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
  app/components/post_draft/post_input/post_input.test.js
  app/components/post_draft/quick_actions/quick_actions.js
  app/components/post_draft/quick_actions/quick_actions.test.js
  app/components/post_draft/uploads/uploads.js
  app/components/post_draft/uploads/uploads.test.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5605 Automated cherry pick of #5599
  app/actions/navigation/index.js
  app/screens/edit_profile/edit_profile.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5606 Automated cherry pick of #5601
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5607 Automated cherry pick of #5595
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
  app/components/post_draft/post_input/post_input.test.js
  app/components/post_draft/quick_actions/quick_actions.js
  app/components/post_draft/quick_actions/quick_actions.test.js
  app/components/post_draft/uploads/uploads.js
  app/components/post_draft/uploads/uploads.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5602 MM-37577 Do not set post id when posting a message
  app/mm-redux/actions/posts.test.js
  app/mm-redux/actions/posts.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#5608 Automated cherry pick of #5602
  app/mm-redux/actions/posts.test.js
  app/mm-redux/actions/posts.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5394 [MM-35617] App modals are now opened from components instead of actions
  app/actions/apps.ts
  app/actions/navigation/index.js
  app/actions/views/command.ts
  app/components/post_draft/draft_input/draft_input.js
  app/components/post_list/post/body/content/embedded_bindings/button_binding/button_binding.tsx
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.ts
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.ts
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/menu_binding.tsx
  app/screens/apps_form/apps_form_component.test.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_container.tsx
  app/screens/apps_form/index.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
Labels: QA Review Done, release-note-none

#5592 MM-37608 and MM-37416 issue fixes
  app/components/sidebars/settings/settings_sidebar.ios.js
  app/components/sidebars/settings/settings_sidebar_base.js
  app/screens/custom_status_clear_after/clear_after_menu_item.tsx
  app/screens/custom_status_clear_after/clear_after_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5613 Automated cherry pick of #5592
  app/components/sidebars/settings/settings_sidebar.ios.js
  app/components/sidebars/settings/settings_sidebar_base.js
  app/screens/custom_status_clear_after/clear_after_menu_item.tsx
  app/screens/custom_status_clear_after/clear_after_modal.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5614 Translations update from Weblate
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/sv.json
Labels: release-note-none

#5612 MM-37485 MM-37602 MM-37610 MM-37684 MM-37719 MM-37522 MM-37720 App crash, Sync issue fixes
  app/components/global_threads/global_threads.tsx
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/mm-redux/actions/threads.ts
  app/mm-redux/reducers/entities/threads.ts
  app/mm-redux/utils/channel_utils.ts
  app/screens/post_options/post_options.js
  app/screens/thread/thread_base.js
  app/store/middlewares/helpers.js
  app/store/middlewares/middleware.test.js
Labels: CherryPick/Approved, QA Review Done, release-note-none

#5615 Automated cherry pick of #5612
  app/components/global_threads/global_threads.tsx
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/mm-redux/actions/threads.ts
  app/mm-redux/reducers/entities/threads.ts
  app/mm-redux/utils/channel_utils.ts
  app/screens/post_options/post_options.js
  app/screens/thread/thread_base.js
  app/store/middlewares/helpers.js
  app/store/middlewares/middleware.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5616 Bump app build number to 367
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5617 Automated cherry pick of #5616
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5620 Android Send Notification event to JS only once when the app is in the foreground
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5621 Automated cherry pick of #5620
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5623 [MM-37840, MM-37841] do not mark channel as read when clearing push notifications
  app/components/network_indicator/network.tsx
  app/screens/edit_post/edit_post.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5624 Automated cherry pick of #5623
  app/components/network_indicator/network.tsx
  app/screens/edit_post/edit_post.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5625 Bump app build number to 368
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5626 Automated cherry pick of #5625
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5333 [MM-33600, MM-34679] Apps commands invalidate form cache
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
Labels: 4: Reviews Complete, release-note-none

#5619 updated threads illustration SVG to align with new branding
  app/components/global_threads/empty_state.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#5628 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/hu.json
Labels: release-note-none

#5629 Update en.json
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note-none

#5541 [MM-29217] Remove Posts.ParentId
  app/actions/views/command.ts
  app/actions/views/post.js
  app/actions/websocket/posts.test.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/post_draft/draft_input/draft_input.js
  app/mm-redux/types/integrations.ts
  app/mm-redux/types/posts.ts
  detox/e2e/plugins/post_message_as.js
  detox/e2e/support/server_api/post.js
  detox/webhook_server.js
Labels: 4: Reviews Complete, release-note

#5622 [MM-37602] fix channel unread filtering for CRT
  app/mm-redux/utils/channel_utils.ts
Labels: 4: Reviews Complete, release-note

#5618 MM-36980, MM-37030: Opens the thread on push notification and Notifications settings
  app/actions/views/root.js
  app/init/global_event_handler.js
  app/init/push_notifications.ts
  app/mm-redux/selectors/entities/posts.ts
  app/mm-redux/types/users.ts
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
  app/screens/notification/index.tsx
  app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
  app/screens/settings/notification_settings/index.js
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings/notification_settings.test.js
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
  app/screens/settings/notification_settings_email/index.js
  app/screens/settings/notification_settings_email/notification_settings_email.android.js
  app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
  app/screens/settings/notification_settings_email/notification_settings_email.ios.js
  app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
  app/screens/settings/notification_settings_email/notification_settings_email_base.js
  app/screens/settings/notification_settings_mentions/index.js
  app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
  app/screens/settings/notification_settings_mentions/notification_settings_mentions.ios.js
  app/screens/settings/notification_settings_mobile/index.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile.ios.js
  app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
  app/utils/notify_props.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#5638 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5642 Remove duplicated code on cleanUrlForLogging
  app/utils/client_error.ts
  app/utils/logging.ts
Labels: 2: Dev Review, release-note-none

#5552 [MM-31257] Bump max allowed file uploads per post
  app/components/post_draft/quick_actions/__snapshots__/quick_actions.test.js.snap
  app/components/post_draft/quick_actions/file_quick_action/index.tsx
  app/components/post_draft/quick_actions/image_quick_action/index.tsx
  app/components/post_draft/quick_actions/index.js
  app/components/post_draft/quick_actions/quick_actions.js
  app/components/post_draft/quick_actions/quick_actions.test.js
  app/components/post_draft/uploads/index.js
  app/components/post_draft/uploads/uploads.js
  app/constants/post_draft.js
  app/utils/file.js
  assets/base/i18n/en.json
  share_extension/screens/share.tsx
  share_extension/utils/index.tsx
Labels: 4: Reviews Complete, release-note

#5641 [MM-37423] Custom Status: Don't show 'Custom Date and Time' for recent statuses
  app/screens/custom_status/custom_status_suggestion.tsx
Labels: 4: Reviews Complete, release-note

#5650 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
Labels: release-note-none

#5647 Fix upside down loading message text while scrolling the post list
  app/components/load_more_posts/load_more_posts.js
Labels: 2: Dev Review, QA Review Done, release-note-none

#5643 [MM-36792] Consistent query param names
  app/client/rest/posts.ts
Labels: release-note

#5600 [GEKIDOU] Bottom Tab Navigation
  android/app/src/main/assets/fonts/compass-icons.ttf
  app/components/badge/index.tsx
  app/components/error_text/__snapshots__/error_text.test.tsx.snap
  app/components/error_text/error_text.test.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/profile_picture/index.tsx
  app/constants/device.ts
  app/constants/navigation.ts
  app/constants/preferences.ts
  app/constants/screens.ts
  app/constants/view.ts
  app/context/theme/index.tsx
  app/database/components/index.tsx
  app/database/models/server/channel.ts
  app/database/models/server/my_channel.ts
  app/hooks/device.ts
  app/init/device.ts
  app/init/launch.ts
  app/screens/channel/channel_nav_bar/index.tsx
  app/screens/channel_list/index.tsx
  app/screens/forgot_password/__snapshots__/forgot_password.test.tsx.snap
  app/screens/forgot_password/forgot_password.test.tsx
  app/screens/home/account/index.tsx
  app/screens/home/channel_list/index.tsx
  app/screens/home/index.tsx
  app/screens/home/recent_mentions/index.tsx
  app/screens/home/search/index.tsx
  app/screens/home/tab_bar/account.tsx
  app/screens/home/tab_bar/home.tsx
  app/screens/home/tab_bar/index.tsx
  app/screens/home/tab_bar/mentions.tsx
  app/screens/home/tab_bar/search.tsx
  app/screens/index.tsx
  app/screens/login/__snapshots__/login.test.tsx.snap
  app/screens/login/index.tsx
  app/screens/login/login.test.tsx
  app/screens/login_options/index.tsx
  app/screens/mfa/__snapshots__/mfa.test.tsx.snap
  app/screens/mfa/index.tsx
  app/screens/mfa/mfa.test.tsx
  app/screens/modal/index.tsx
  app/screens/navigation.ts
  app/screens/server/index.tsx
  app/screens/sso/sso.test.tsx
  app/screens/sso/sso_with_redirect_url.test.tsx
  app/store/ephemeral_store.ts
  app/utils/images/index.ts
  app/utils/theme/index.ts
  app/utils/theme/test.ts
  assets/base/compass-icons.json
  assets/fonts/compass-icons.ttf
  index.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  types/api/preferences.d.ts
Labels: release-note-none
