Repository mattermost/mattermost-mobile, pull requests merged in 2021-02, with the labels that each got.

#5148 MM-32254 Update CommonMark and fix handling of deeply nested Markdown
  app/components/markdown/markdown.test.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5150 Automated cherry pick of #5148
  app/components/markdown/markdown.test.js
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5153 Automated cherry pick of #5151
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5155 Automated cherry pick of #5154
  app/components/post_draft/draft_input/draft_input.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5157 Automated cherry pick of #5156
  package-lock.json
  package.json
  patches/react-native-elements+2.3.2.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5159 Automated cherry pick of #5158
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5136 MM-31322: redirect permalink handler
  app/components/markdown/markdown_link/index.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/index.js
  app/components/post_list/post_list.js
  app/utils/url.js
  detox/e2e/test/messaging/permalink.e2e.js
Labels: 4: Reviews Complete

#5012 Apps bindings support
  app/actions/apps.ts
  app/actions/views/channel.js
  app/actions/views/post.js
  app/constants/screen.js
  app/mm-redux/action_types/apps.ts
  app/mm-redux/action_types/index.ts
  app/mm-redux/actions/apps.ts
  app/mm-redux/client/client4.ts
  app/mm-redux/constants/apps.ts
  app/mm-redux/reducers/entities/apps.ts
  app/mm-redux/reducers/entities/index.ts
  app/mm-redux/selectors/entities/apps.ts
  app/mm-redux/types/apps.ts
  app/mm-redux/types/integrations.ts
  app/mm-redux/types/store.ts
  app/screens/channel/channel_post_list/__snapshots__/channel_post_list.test.js.snap
  app/screens/channel/channel_post_list/channel_post_list.js
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info_row.js
  app/screens/permalink/permalink.js
  app/screens/post_options/__snapshots__/post_options.test.js.snap
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
  app/screens/post_options/index.js
  app/screens/post_options/post_option.js
  app/screens/post_options/post_options.js
  app/screens/post_options/post_options.test.js
  app/screens/search/search_result_post/__snapshots__/search_result_post.test.js.snap
  app/screens/search/search_result_post/search_result_post.js
  app/utils/apps.ts
Labels: 4: Reviews Complete

#5170 Automated cherry pick of #5168
  app/components/autocomplete/at_mention_item/at_mention_item.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5171 Automated cherry pick of #5164
  app/components/markdown/markdown.js
  app/components/markdown/markdown.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5135 MM-30695 Detox/E2E: Add e2e for MM-T3218
  detox/e2e/test/smoke_test/message_reply.e2e.js
Labels: 4: Reviews Complete

#5137 MM-30698 Detox/E2E: Add e2e for MM-T3191
  app/screens/channel_info/channel_info_row.js
  detox/e2e/support/ui/screen/channel_info.js
  detox/e2e/test/smoke_test/favorite_channels.e2e.js
Labels: 4: Reviews Complete

#5172 Automated cherry pick of #5167
  app/components/progressive_image/progressive_image.js
  app/components/retriable_fast_image/index.tsx
  app/components/retriable_fast_image/retriable_fast_image.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5133 MM-30289 Detox/E2E - Add e2e tests for MM-T3184 and MM-T3186
  app/components/markdown/markdown_link/index.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/index.js
  app/components/post_list/post_list.js
  app/utils/url.js
  detox/e2e/support/server_api/channel.js
  detox/e2e/support/server_api/preference.js
  detox/e2e/support/ui/component/channels_list.js
  detox/e2e/support/ui/component/main_sidebar.js
  detox/e2e/test/messaging/permalink.e2e.js
  detox/e2e/test/smoke_test/channels.e2e.js
Labels: 4: Reviews Complete

#5144 MM-31256 Detox/E2E: Add e2e for MM-T3618
  app/components/custom_list/channel_list_row/channel_list_row.js
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/archive/archive.tsx
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/leave/leave.tsx
  app/screens/more_channels/__snapshots__/more_channels.test.js.snap
  app/screens/more_channels/more_channels.js
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/component/bottom_sheet.js
  detox/e2e/support/ui/component/index.js
  detox/e2e/support/ui/screen/channel_info.js
  detox/e2e/support/ui/screen/more_channels.js
  detox/e2e/test/channels/archived_channels.e2e.js
  detox/e2e/test/channels/create_public_channel.e2e.js
Labels: 4: Reviews Complete

#5147 MM-30696 Detox/E2E: Add e2e for MM-T3213
  app/components/channel_icon.js
  app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
  app/components/custom_list/user_list_row/user_list_row.js
  app/components/custom_list/user_list_row/user_list_test.test.js
  app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
  app/components/sidebars/main/channels_list/channel_item/channel_item.js
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/channel_info_header.js
  app/screens/channel_info/channel_info_header.test.js
  app/screens/more_dms/more_dms.js
  detox/e2e/support/ui/screen/channel_info.js
  detox/e2e/support/ui/screen/more_direct_messages.js
  detox/e2e/test/channel_info/header.e2e.js
  detox/e2e/test/smoke_test/group_message_channel.e2e.js
Labels: 4: Reviews Complete

#5174 Automated cherry pick of #5173
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5130 MM_30478 [v2] Database Manager
  .eslintrc.json
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/build.gradle
  android/settings.gradle
  app/constants/database.ts
  app/constants/index.ts
  app/database/admin/database_manager/__mocks__/index.ts
  app/database/admin/database_manager/index.ts
  app/database/admin/database_manager/test.ts
  app/database/admin/database_manager/test_manual.ts
  app/database/default/migration/index.ts
  app/database/default/schema/index.ts
  app/database/default/schema/table_schemas/app.ts
  app/database/default/schema/table_schemas/global.ts
  app/database/default/schema/table_schemas/index.ts
  app/database/default/schema/table_schemas/servers.ts
  app/database/server/models/channel.ts
  app/database/server/models/channel_info.ts
  app/database/server/models/channel_membership.ts
  app/database/server/models/group_membership.ts
  app/database/server/models/groups_in_team.ts
  app/database/server/models/my_channel.ts
  app/database/server/models/my_channel_settings.ts
  app/database/server/models/my_team.ts
  app/database/server/models/post.ts
  app/database/server/models/post_metadata.ts
  app/database/server/models/posts_in_channel.ts
  app/database/server/models/posts_in_thread.ts
  app/database/server/models/preference.ts
  app/database/server/models/reaction.ts
  app/database/server/models/slash_command.ts
  app/database/server/models/team.ts
  app/database/server/models/team_channel_history.ts
  app/database/server/models/team_membership.ts
  app/database/server/models/team_search_history.ts
  app/database/server/models/user.ts
  app/database/server/schema/test.ts
  app/screens/channel/index.tsx
  app/screens/server/index.tsx
  app/utils/mattermost_managed.ts
  detox/e2e/environment.js
  detox/package-lock.json
  detox/package.json
  ios/Mattermost/MattermostManaged.m
  jest.config.js
  package-lock.json
  package.json
  patches/@nozbe+watermelondb+0.20.0.patch
  types/database/database.d.ts
  types/database/team_membership.d.ts
Labels: 4: Reviews Complete

#4988 Added "Join prompt" when sys admin clicks on perma links of private channels
  app/actions/views/channel.js
  app/actions/views/channel.test.js
  app/actions/views/permalink.ts
  app/components/channel_intro/channel_intro.js
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list.js
  app/mm-redux/actions/channels.ts
  app/mm-redux/actions/integrations.ts
  app/screens/permalink/index.js
  app/screens/permalink/permalink.js
  app/utils/channels.js
  assets/base/i18n/en.json
  detox/e2e/support/ui/component/alert.js
  detox/e2e/test/messaging/tapping_channel_url_link_joins_channel.e2e.js
Labels: 4: Reviews Complete

#5165 Detox/E2E: Upgrade detox version
  detox/package-lock.json
  detox/package.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5183 MM-32851: honour defaults in interactive dialogs
  app/screens/interactive_dialog/dialog_element.js
  app/screens/interactive_dialog/dialog_element.test.js
Labels: 4: Reviews Complete

#5180 MM-30423 Detox/E2E: Add e2e for MM-T3192, MM-T3215, MM-T3219, MM-T3221, MM-T3256
  app/components/post_header/__snapshots__/post_pre_header.test.js.snap
  app/components/post_header/post_pre_header.js
  app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
  app/screens/settings/notification_settings/notification_settings.js
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
  app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
  app/screens/settings/notification_settings_email/notification_settings_email.android.js
  app/screens/settings/notification_settings_email/notification_settings_email.ios.js
  app/screens/settings/section_item.js
  detox/e2e/support/server_api/channel.js
  detox/e2e/support/server_api/index.js
  detox/e2e/support/server_api/preference.js
  detox/e2e/support/server_api/status.js
  detox/e2e/support/server_api/system.js
  detox/e2e/support/test_config.js
  detox/e2e/support/ui/component/post.js
  detox/e2e/support/ui/component/post_list.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/notification_settings.js
  detox/e2e/support/ui/screen/notification_settings_email.js
  detox/e2e/support/utils.js
  detox/e2e/test/notifications/channel_notification_default.e2e.js
  detox/e2e/test/smoke_test/direct_messages.e2e.js
  detox/e2e/test/smoke_test/email_notifications.e2e.js
  detox/e2e/test/smoke_test/favorite_channels.e2e.js
  detox/e2e/test/smoke_test/group_messages.e2e.js
  detox/e2e/test/smoke_test/saved_messages.e2e.js
  detox/package-lock.json
  detox/package.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5119 Updates to animations for new gallery
  app/screens/gallery/footer/index.tsx
  app/screens/gallery/gallery.js
  app/screens/gallery/gallery_viewer.tsx
  app/utils/images.js
Labels: 4: Reviews Complete, Lifecycle/1:stale

#5187 Unable to open previews from search, pinned and mentions after permalink prompt implemented
  app/screens/permalink/permalink.js
Labels: 4: Reviews Complete

#4987 Calculate the filteredEmojis on first change.
  app/components/emoji_picker/emoji_picker_base.js
Labels: 4: Reviews Complete

#5191 Automated cherry pick of #5190
  fastlane/Fastfile
  fastlane/Gemfile.lock
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5182 MM_30482 [v2] DataOperator for all the isolated tables
  app/database/admin/data_operator/index.ts
  app/database/admin/data_operator/operators.ts
  app/database/admin/data_operator/test.ts
  app/database/admin/database_manager/__mocks__/index.ts
  app/database/admin/database_manager/index.ts
  app/database/admin/database_manager/test_manual.ts
  app/screens/server/index.tsx
  types/database/database.d.ts
  types/database/index.d.ts
Labels: 4: Reviews Complete

#5116 [MM-31133]: participants screen component
  app/components/avatars/__snapshots__/avatars.test.tsx.snap
  app/components/avatars/avatars.tsx
  app/mm-redux/selectors/entities/users.test.js
  app/mm-redux/selectors/entities/users.ts
  app/screens/index.js
  app/screens/participants_list/index.ts
  app/screens/participants_list/participant_row/index.tsx
  app/screens/participants_list/participants_list.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review

#5177 Add App Forms
  app/actions/apps.ts
  app/components/embedded_bindings/button_binding/button_binding.tsx
  app/components/embedded_bindings/menu_binding/menu_binding.tsx
  app/components/widgets/settings/text_setting.js
  app/mm-redux/actions/helpers.ts
  app/mm-redux/constants/apps.ts
  app/mm-redux/types/apps.ts
  app/screens/app_selector_screen/__snapshots__/app_selector_screen.test.tsx.snap
  app/screens/app_selector_screen/app_selector_screen.test.tsx
  app/screens/app_selector_screen/app_selector_screen.tsx
  app/screens/app_selector_screen/index.ts
  app/screens/apps_form/__snapshots__/dialog_introduction_text.test.tsx.snap
  app/screens/apps_form/app_form_selector/app_form_selector.tsx
  app/screens/apps_form/app_form_selector/index.ts
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_container.tsx
  app/screens/apps_form/apps_form_field.tsx
  app/screens/apps_form/dialog_introduction_text.test.tsx
  app/screens/apps_form/dialog_introduction_text.tsx
  app/screens/apps_form/index.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/index.js
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
Labels: 2: Dev Review
