Repository mattermost/mattermost-mobile, pull requests merged in 2021-06, with the labels that each got.

#5410 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/es.json
  assets/base/i18n/hu.json
  assets/base/i18n/nl.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
Labels: release-note-none

#5408 MM-35992 set android activity affinity to blank
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
Labels: 4: Reviews Complete, release-note-none

#5404 MM-35674 Detox/E2E: Add e2e for autocomplete and at-mention
  app/components/autocomplete/at_mention_item/at_mention_item.tsx
  detox/e2e/support/server_api/user.js
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/component/autocomplete.js
  detox/e2e/support/ui/screen/channel.js
  detox/e2e/support/ui/screen/permalink.js
  detox/e2e/support/ui/screen/thread.js
  detox/e2e/test/autocomplete/at_mention.e2e.js
  detox/e2e/test/autocomplete/autocomplete.e2e.js
  detox/e2e/test/messaging/at_mention.e2e.js
  detox/e2e/test/smoke_test/search.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5403 MM-35673 Detox/E2E: Add e2e for messaging
  detox/e2e/support/ui/component/alert.js
  detox/e2e/support/ui/component/post_options.js
  detox/e2e/test/messaging/message_deletion.e2e.js
  detox/e2e/test/messaging/message_draft.e2e.js
  detox/e2e/test/messaging/message_edit.e2e.js
  detox/e2e/test/messaging/message_posting.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5406 MM-35675 Detox/E2E: Add e2e for message reply
  app/components/post_header/__snapshots__/post_header.test.js.snap
  app/components/post_header/post_header.js
  detox/e2e/support/ui/component/post.js
  detox/e2e/support/ui/component/post_list.js
  detox/e2e/test/messaging/message_reply.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5412 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/fr.json
Labels: release-note-none

#5414 Force CI to use npm 6.14.11
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#5415 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5416 Automated cherry pick of #5415
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#5421 Version number
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5422 Automated cherry pick of #5421
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5423 Automated cherry pick of #5414
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5424 Fix Fastlane WebHook
  fastlane/Gemfile
  fastlane/Gemfile.lock
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5425 Automated cherry pick of #5424
  fastlane/Gemfile
  fastlane/Gemfile.lock
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5427 set npm version as part of the npm-dependencies CI task
  .circleci/config.yml
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5428 Automated cherry pick of #5427
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5431 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: release-note-none

#5435 Detox/E2E: Cleanup long post e2e
  detox/e2e/support/ui/screen/channel.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/long_post.js
  detox/e2e/support/ui/screen/permalink.js
  detox/e2e/support/ui/screen/thread.js
  detox/e2e/test/smoke_test/message_posting.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5433 fix start since launch metric
  app/mattermost.js
  app/telemetry/index.ts
Labels: 4: Reviews Complete, release-note-none

#5411 MM-34093 Add support for English Australian
  app/i18n/index.js
  app/i18n/languages.ts
Labels: 4: Reviews Complete, release-note

#5437 Automated cherry pick of #5432
  android/app/src/main/java/com/mattermost/share/RealPathUtil.java
  patches/react-native-image-picker+2.3.4.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5436 Fixed custom status warning issue
  app/screens/channel_info/index.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5439 Automated cherry pick of #5436
  app/screens/channel_info/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5442 Automated cherry pick of #5438
  app/components/post_list/post/body/reactions/reaction.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5443 MM-35676 Detox/E2E: Add e2e for emojis and reactions, pinned messages, saved messages
  app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
  app/screens/reaction_list/reaction_list.js
  app/screens/reaction_list/reaction_row/__snapshots__/reaction_row.test.js.snap
  app/screens/reaction_list/reaction_row/index.js
  detox/e2e/support/ui/component/post_options.js
  detox/e2e/support/ui/screen/index.js
  detox/e2e/support/ui/screen/reaction_list.js
  detox/e2e/test/channels/pinned_messages.e2e.js
  detox/e2e/test/messaging/emojis_and_reactions.e2e.js
  detox/e2e/test/messaging/pinned_messages.e2e.js
  detox/e2e/test/messaging/recent_emojis.e2e.js
  detox/e2e/test/messaging/saved_messages.e2e.js
  detox/e2e/test/smoke_test/search.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5444 1.44 fixes
  app/components/network_indicator/network.tsx
  app/components/post_list/post_list.tsx
  app/mm-redux/actions/users.ts
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/saved_posts/saved_posts.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5446 Automated cherry pick of #5444
  app/components/network_indicator/network.tsx
  app/components/post_list/post_list.tsx
  app/mm-redux/actions/users.ts
  app/screens/pinned_posts/pinned_posts.js
  app/screens/recent_mentions/recent_mentions.js
  app/screens/saved_posts/saved_posts.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5447 fix: reset iOS scrollView when switching channels
  app/components/post_draft/post_draft.js
  app/components/post_list/post_list.tsx
  app/hooks/index.ts
  app/hooks/reset_native_scrollview.ts
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_post_list/channel_post_list.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5448 Automated cherry pick of #5447
  app/components/post_draft/post_draft.js
  app/components/post_list/post_list.tsx
  app/hooks/index.ts
  app/hooks/reset_native_scrollview.ts
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_post_list/channel_post_list.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5450 Bump app build number to 358
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5451 Automated cherry pick of #5450
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5453 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/hu.json
Labels: release-note-none

#5456 fix: connect WebSocket when the network component mounts
  app/components/network_indicator/network.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5457 Automated cherry pick of #5456
  app/components/network_indicator/network.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5458 Bump app build number to 359
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5459 Automated cherry pick of #5458
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5452 Update react-native-cookies & react-native-webview + always use defaultStore
  app/init/global_event_handler.js
  app/screens/sso/sso_with_webview.tsx
  app/utils/security.js
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-webview+7.0.1.patch
  test/setup.js
Labels: 4: Reviews Complete, release-note-none

#5454 MM-36205 [GEKIDOU] Login Flow SSO
  android/app/src/main/AndroidManifest.xml
  app/components/loading/index.tsx
  app/components/loading/loading.stories.tsx
  app/constants/index.ts
  app/constants/screens.ts
  app/constants/sso.ts
  app/constants/view.ts
  app/database/operator/index.ts
  app/requests/local/systems.ts
  app/requests/remote/user.ts
  app/screens/forgot_password/__snapshots__/forgot_password.test.tsx.snap
  app/screens/forgot_password/forgot_password.test.tsx
  app/screens/forgot_password/index.tsx
  app/screens/index.tsx
  app/screens/login/__snapshots__/login.test.tsx.snap
  app/screens/login/index.tsx
  app/screens/login/login.test.tsx
  app/screens/login_options/gitlab.tsx
  app/screens/login_options/google.tsx
  app/screens/login_options/index.tsx
  app/screens/login_options/office365.tsx
  app/screens/login_options/open_id.tsx
  app/screens/login_options/saml.tsx
  app/screens/mfa/__snapshots__/mfa.test.tsx.snap
  app/screens/mfa/index.tsx
  app/screens/mfa/mfa.test.tsx
  app/screens/navigation.ts
  app/screens/server/index.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso.test.tsx
  app/screens/sso/sso_with_redirect_url.test.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  app/screens/sso/sso_with_webview.tsx
  app/styles/index.ts
  app/utils/database.ts
  app/utils/general/index.ts
  app/utils/helpers.ts
  app/utils/key_mirror.ts
  ios/Mattermost/AppDelegate.m
  ios/Mattermost/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  test/setup.ts
  types/database/database.d.ts
Labels: 3: QA Review, release-note

#5449 [Gekidou] Database HOC component to set the active server database in WDB Provider
  app/database/components/index.tsx
  app/database/models/default/servers.ts
  app/database/operator/handlers/base_handler.test.ts
  app/database/operator/prepareRecords/general.test.ts
  app/database/operator/prepareRecords/general.ts
  app/database/schema/default/index.ts
  app/database/schema/default/table_schemas/servers.ts
  app/database/schema/default/test.ts
  app/screens/index.tsx
  types/database/database.d.ts
  types/database/servers.d.ts
Labels: 2: Dev Review, release-note-none

#5469 Translations update from Weblate
  assets/base/i18n/hu.json
  assets/base/i18n/sv.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5472 MM-36588 iOS: rebind the correct post list to the native view
  app/components/post_draft/post_draft.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5473 Automated cherry pick of #5472
  app/components/post_draft/post_draft.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5474 Update dependencies and setup project with node 16 / npm 7
  .circleci/config.yml
  android/app/src/main/java/com/mattermost/rnbeta/CustomMMKVJSIModulePackage.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  app/components/post_draft/quick_actions/__snapshots__/quick_actions.test.js.snap
  app/components/post_draft/quick_actions/camera_quick_action/__snapshots__/camera_quick_action.test.js.snap
  app/components/post_draft/quick_actions/camera_quick_action/camera_quick_action.test.js
  app/components/post_draft/quick_actions/camera_quick_action/camera_type.tsx
  app/components/post_draft/quick_actions/camera_quick_action/index.js
  app/components/post_draft/quick_actions/camera_quick_action/index.tsx
  app/components/post_draft/quick_actions/file_quick_action/__snapshots__/file_quick_action.test.js.snap
  app/components/post_draft/quick_actions/file_quick_action/file_quick_action.test.js
  app/components/post_draft/quick_actions/file_quick_action/index.js
  app/components/post_draft/quick_actions/file_quick_action/index.tsx
  app/components/post_draft/quick_actions/image_quick_action/__snapshots__/image_quick_action.test.js.snap
  app/components/post_draft/quick_actions/image_quick_action/image_quick_action.test.js
  app/components/post_draft/quick_actions/image_quick_action/index.js
  app/components/post_draft/quick_actions/image_quick_action/index.tsx
  app/components/post_list/post_list.tsx
  app/constants/navigation.js
  app/screens/index.js
  app/screens/permalink/permalink.test.js
  app/screens/slide_up/index.tsx
  app/store/mmkv_adapter.ts
  app/utils/permission.ts
  assets/base/i18n/en.json
  detox/package-lock.json
  detox/package.json
  fastlane/Gemfile.lock
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/jail-monkey+2.4.0.patch
  patches/react-native+0.64.2.patch
  patches/react-native-elements+3.4.2.patch
  patches/react-native-image-picker+2.3.4.patch
  patches/react-native-mmkv-storage+0.4.4.patch
  patches/react-native-mmkv-storage+0.6.0.patch
  patches/react-native-notifications+3.5.0.patch
  tsconfig.json
  types/components/post_draft_quick_action.d.ts
Labels: 4: Reviews Complete, release-note-none

#5476 Fixed custom status issues
  app/actions/websocket/index.ts
  app/components/custom_status/custom_status_emoji.tsx
  app/components/post_list/post/header/header.tsx
  detox/e2e/test/custom_statuses/custom_status.e2e.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5477 Automated cherry pick of #5476
  app/actions/websocket/index.ts
  app/components/custom_status/custom_status_emoji.tsx
  app/components/post_list/post/header/header.tsx
  detox/e2e/test/custom_statuses/custom_status.e2e.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5475 [Gekidou] update dependencies & use node 16 with npm 7
  .circleci/config.yml
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/i18n/index.ts
  app/i18n/languages.ts
  app/screens/sso/index.tsx
  assets/base/i18n/en_AU.json
  detox/package-lock.json
  detox/package.json
  index.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@nozbe+watermelondb+0.21.0.patch
  patches/@nozbe+watermelondb+0.22.0.patch
  patches/react-native+0.64.2.patch
  patches/react-native-device-info+8.1.3.patch
  patches/react-native-elements+3.4.2.patch
  patches/react-native-notifications+3.5.0.patch
  patches/react-native-youtube+2.0.2.patch
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note-none

#5480 MM-36628 fix iOS app icon badge count
  app/init/push_notifications.test.js
  app/init/push_notifications.ts
  app/screens/channel/channel_base.js
  app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.js
  app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.test.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5478 Fix upload progress indicator when uploading multiple files at once
  package.json
  patches/rn-fetch-blob+0.12.0.patch
Labels: 2: UX Review, 4: Reviews Complete, release-note-none

#5482 MM-36640 Bring back permalink view on search/recent mentions/pinned and saved posts
  app/actions/views/permalink.ts
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/components/post_list/post_list.tsx
  app/screens/search/search_result_post/__snapshots__/search_result_post.test.js.snap
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-navigation+7.11.3.patch
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5483 Automated cherry pick of #5480
  app/init/push_notifications.test.js
  app/init/push_notifications.ts
  app/screens/channel/channel_base.js
  app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.js
  app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5467 MM-36532 navigate to channel from any screen when channel link is pressed
  app/components/markdown/markdown_link/markdown_link.js
Labels: 4: Reviews Complete, release-note

#5465 MM-35677 Detox/E2E: Add e2e for channel link and scrolling
  app/components/post_list/post/header/commented_on/index.tsx
  detox/e2e/support/ui/component/post.js
  detox/e2e/support/ui/component/post_list.js
  detox/e2e/test/messaging/channel_link.e2e.js
  detox/e2e/test/messaging/scrolling.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5481 MM-35678 Detox/E2E: Add e2e for hashtags, empty mentions and reactions, jump to search
  detox/e2e/test/channels/channels_list.e2e.js
  detox/e2e/test/messaging/emojis_and_reactions.e2e.js
  detox/e2e/test/messaging/hashtags.e2e.js
  detox/e2e/test/messaging/recent_mentions.e2e.js
Labels: 3: QA Review, release-note-none

#5484 Detox/E2E: Fix search and pinned messages e2e
  detox/e2e/test/messaging/pinned_messages.e2e.js
  detox/e2e/test/smoke_test/search.e2e.js
Labels: 4: Reviews Complete, release-note-none

#5479 Clear cookies but keep files
  app/init/global_event_handler.js
Labels: 4: Reviews Complete, release-note-none

#5486 Content safety
  app/components/post_list/post/body/content/embedded_bindings/index.tsx
  app/components/post_list/post/body/content/index.tsx
  ios/Podfile
  ios/Podfile.lock
Labels: CherryPick/Approved, release-note

#5489 Do not recreate onViewableItemsChange when the deeplink changes
  app/components/post_list/post_list.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#5487 Bump Version to 1.44.1 and build to 360
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5493 Automated cherry pick of #5489
  app/components/post_list/post_list.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5495 Translations update from Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/hu.json
  assets/base/i18n/nl.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5494 Allow reply from individual notifications on Android
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationDrawer.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferences.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableImageFromUrl.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputManager.java
  android/app/src/main/java/com/mattermost/rnbeta/RNTextInputResetModule.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/init/push_notifications.ts
  package-lock.json
  package.json
  patches/react-native-notifications+3.5.0.patch
Labels: 4: Reviews Complete, release-note

#5501 Prevent the initialIndex from being less than 0
  app/components/post_list/index.ts
Labels: 4: Reviews Complete, release-note-none

#5491 MM-17135 ignore at sign when searching for users
  app/components/sidebars/main/channels_list/filtered_list/filtered_list.js
  app/selectors/autocomplete.js
Labels: 4: Reviews Complete, release-note

#5497 [MM-35909] Support for emoji 13
  app/actions/views/emoji.js
  app/client/rest/emojis.ts
  app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.test.js
  app/components/emoji/index.ts
  app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
  app/components/emoji_picker/emoji_picker.test.js
  app/components/emoji_picker/emoji_picker_base.js
  app/components/emoji_picker/emoji_picker_row.js
  app/mm-redux/actions/emojis.ts
  app/mm-redux/actions/posts.test.js
  app/mm-redux/actions/posts.ts
  app/mm-redux/types/emojis.ts
  app/mm-redux/utils/emoji_utils.test.js
  app/mm-redux/utils/emoji_utils.ts
  app/selectors/emojis.js
  app/utils/emoji.json
  app/utils/emoji_utils.js
  app/utils/emoji_utils.test.js
  app/utils/emojis.js
  assets/base/i18n/en.json
  ios/Podfile.lock
Labels: 4: Reviews Complete, release-note

#5407 Add Markdown fields to modals
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
  app/mm-redux/constants/apps.ts
  app/screens/apps_form/apps_form_field.tsx
Labels: 4: Reviews Complete, release-note

#5488 MM-34619 post draft to use the channelId prop when assigned
  app/components/post_draft/index.js
Labels: 4: Reviews Complete, release-note
