Repository mattermost/mattermost-mobile, pull requests merged in 2021-09, with the labels that each got.

#5639 MM-38065 Render system messages for guest added or joined a channel
  app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap
  app/components/post_list/post/system_message/system_message.tsx
  app/components/post_list/post/system_message/system_message_helpers.test.js
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#5659 Fix Share extension authentication and error alerts
  ios/MattermostShare/ChannelsViewController.swift
  ios/MattermostShare/ShareViewController.swift
Labels: 3: QA Review, release-note

#5649 [MM-37686] Invert colours for teams button to "fix" starkness on light backgrounds
  app/components/sidebars/main/channels_list/switch_teams_button/__snapshots__/switch_teams_button.test.js.snap
  app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
  app/components/team_icon/__snapshots__/team_icon.test.js.snap
  app/components/team_icon/team_icon.js
Labels: 4: Reviews Complete, release-note-none

#5661 Do not resize images to upload
  app/components/attachment_button/index.js
  app/components/post_draft/quick_actions/image_quick_action/index.tsx
Labels: 4: Reviews Complete, release-note

#5660 Upgrade iOS minimum version to 12.1 and ESR to 5.37
  README.md
  app/constants/view.js
  app/init/global_event_handler.test.js
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/Mattermost.xcscheme
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/MattermostShare.xcscheme
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/NotificationService.xcscheme
  ios/Mattermost/AppDelegate.m
  ios/Mattermost/Mattermost+RCTUITextView.m
  ios/Mattermost/MattermostManaged.m
  ios/Mattermost/UIImage+ImageEffects.m
  ios/MattermostShare/ChannelsViewController.swift
  ios/Podfile
  ios/Podfile.lock
  ios/UploadAttachments/UploadAttachments.xcodeproj/project.pbxproj
  ios/UploadAttachments/UploadAttachments.xcodeproj/xcshareddata/xcschemes/UploadAttachments.xcscheme
  ios/UploadAttachments/UploadAttachments/AttachmentArray.swift
  ios/UploadAttachments/UploadAttachments/UploadSessionManager.swift
Labels: 4: Reviews Complete, release-note

#5656 Properly handle notification snooze on Android
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 4: Reviews Complete, release-note

#5666 Android clear notification preferences on version change
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: release-note-none

#5668 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/hu.json
  assets/base/i18n/nl.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
Labels: release-note-none

#5572 Remove all checks for minimum versions previous to 5.31
  app/actions/views/channel.js
  app/actions/views/session.js
  app/actions/websocket/index.ts
  app/actions/websocket/posts.test.js
  app/actions/websocket/websocket.test.js
  app/client/rest/users.ts
  app/components/autocomplete/at_mention/index.js
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/emoji/index.ts
  app/components/post_draft/draft_input/index.js
  app/components/post_draft/index.js
  app/components/post_draft/index.test.js
  app/components/sidebars/main/channels_list/list/index.js
  app/init/global_event_handler.js
  app/mm-redux/actions/general.test.js
  app/mm-redux/actions/general.ts
  app/mm-redux/actions/helpers.ts
  app/mm-redux/actions/teams.test.js
  app/mm-redux/actions/teams.ts
  app/mm-redux/actions/users.ts
  app/mm-redux/selectors/entities/channels.test.js
  app/mm-redux/selectors/entities/channels.ts
  app/mm-redux/selectors/entities/general.test.js
  app/mm-redux/selectors/entities/general.ts
  app/mm-redux/selectors/entities/teams.test.js
  app/mm-redux/selectors/entities/teams.ts
  app/mm-redux/utils/channel_utils.ts
  app/mm-redux/utils/post_utils.test.js
  app/mm-redux/utils/post_utils.ts
  app/screens/channel_info/archive/index.js
  app/screens/channel_info/convert_private/index.js
  app/screens/channel_info/edit_channel/index.js
  app/screens/edit_profile/index.js
  app/screens/more_channels/index.js
  app/screens/search/index.js
  app/screens/search/search.js
  app/screens/settings/notification_settings/index.js
Labels: 4: Reviews Complete, release-note

#5664 MM-38331: fixes opening notification while in threads
  app/actions/views/root.js
  app/screens/channel/channel_base.js
  app/screens/channel/channel_base.test.js
  app/screens/channel/index.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#5670 Very Minor Change: Updated the way to fetch dependeny from a GIT Repo
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#5675 Translations update from Weblate
  assets/base/i18n/ja.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5676 Detox/E2E: Minor fix to email
  detox/e2e/support/test_config.js
  detox/e2e/support/utils/email.js
Labels: 3: QA Review, release-note-none

#5627 MM-37781: Only evaluates some config settings if the server is less than v6.
  app/actions/helpers/channels.ts
  app/mm-redux/selectors/entities/channels.ts
  app/mm-redux/selectors/entities/preferences.ts
  app/mm-redux/types/config.ts
  app/mm-redux/utils/channel_utils.test.js
  app/mm-redux/utils/channel_utils.ts
  app/mm-redux/utils/post_utils.test.js
  app/mm-redux/utils/post_utils.ts
  app/screens/post_options/index.js
  app/utils/channels.js
  ios/UploadAttachments/UploadAttachments/StoreManager.m
Labels: 4: Reviews Complete, release-note

#5680 Translations update from Weblate
  assets/base/i18n/es.json
  assets/base/i18n/pl.json
Labels: release-note-none

#5683 Bump Version to 1.47.0
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5655 Sync binding filtering with webapp
  app/actions/apps.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
  app/components/post_list/post/body/content/embedded_bindings/embedded_binding.tsx
  app/mm-redux/reducers/entities/__snapshots__/apps.test.js.snap
  app/mm-redux/reducers/entities/apps.ts
  app/screens/apps_form/apps_form_component.tsx
  app/utils/apps.test.ts
  app/utils/apps.ts
Labels: 4: Reviews Complete, Docs/Done, release-note

#5688 Update NOTICE.txt
  NOTICE.txt
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#5689 Automated cherry pick of #5688
  NOTICE.txt
Labels: 4: Reviews Complete, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5691 [Gekidou] update dependencies
  .circleci/config.yml
  .flowconfig
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  app/actions/remote/apps.ts
  app/actions/remote/channel.ts
  app/actions/remote/general.ts
  app/actions/remote/group.ts
  app/actions/remote/post.ts
  app/actions/remote/preference.ts
  app/actions/remote/reactions.ts
  app/actions/remote/role.ts
  app/actions/remote/session.ts
  app/actions/remote/systems.ts
  app/actions/remote/team.ts
  app/actions/remote/user.ts
  app/client/rest/error.ts
  app/components/custom_status/__snapshots__/clear_button.test.tsx.snap
  app/components/markdown/markdown_table/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/files/document_file.tsx
  app/context/theme/index.tsx
  app/database/operator/base_data_operator/index.ts
  app/screens/forgot_password/__snapshots__/forgot_password.test.tsx.snap
  app/screens/forgot_password/index.tsx
  app/screens/home/account/index.tsx
  app/screens/home/recent_mentions/index.tsx
  app/screens/login/__snapshots__/login.test.tsx.snap
  app/screens/login/index.tsx
  app/screens/mfa/__snapshots__/mfa.test.tsx.snap
  app/screens/mfa/index.tsx
  app/screens/server/index.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  babel.config.js
  detox/package-lock.json
  detox/package.json
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.65.1.patch
  patches/react-native-device-info+8.3.3.patch
  patches/react-native-fast-image+8.3.7.patch
  patches/react-native-fast-image+8.5.8.patch
  patches/react-native-keyboard-aware-scroll-view+0.9.4.patch
  patches/react-native-navigation+7.21.0.patch
  patches/react-native-notifications+4.1.2.patch
  types/api/session.d.ts
Labels: 4: Reviews Complete, release-note-none

#5644 Fix warnings on channel info row Formatted Text
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/channel_info_row.js
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#5665 Open forms in bindings on all locations
  app/components/post_list/post/body/content/embedded_bindings/button_binding/button_binding.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/menu_binding.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/post_options/bindings/bindings.tsx
Labels: 4: Reviews Complete, Docs/Done, release-note-none

#5677 [MM-38216] Add multiteam mentions and saved posts
  app/client/rest/posts.ts
  app/mm-redux/actions/search.ts
  app/screens/search/channel_display_name/__snapshots__/channel_display_name.test.js.snap
  app/screens/search/channel_display_name/channel_display_name.js
  app/screens/search/channel_display_name/channel_display_name.test.js
  app/screens/search/channel_display_name/index.js
  app/screens/search/channel_display_name/index.test.js
Labels: 4: Reviews Complete, release-note

#5563 [MM-36041] Ensure post options and app commands always have the bindings for its channel
  app/actions/websocket/apps.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.test.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
  app/components/autocomplete/slash_suggestion/app_slash_suggestion/app_slash_suggestion.test.tsx
  app/mm-redux/action_types/apps.ts
  app/mm-redux/actions/apps.ts
  app/mm-redux/reducers/entities/apps.ts
  app/mm-redux/selectors/entities/apps.ts
  app/mm-redux/types/apps.ts
  app/screens/channel_info/bindings/bindings.tsx
  app/screens/channel_info/bindings/index.ts
  app/screens/post_options/bindings/bindings.tsx
  app/screens/post_options/bindings/index.ts
  app/screens/thread/index.js
  app/screens/thread/thread.ios.test.js
  app/screens/thread/thread_base.js
Labels: 4: Reviews Complete, Docs/Done, release-note

#5631 Sync with App Command Parser with Webapp
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.test.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/tests/app_command_parser_test_data.ts
Labels: 4: Reviews Complete, Docs/Done, release-note

#5395 MM-34811 Add plugin oauth support
  app/components/markdown/markdown_link/markdown_link.js
  app/components/post_list/post_list.tsx
  app/constants/deep_linking.js
  app/mm-redux/actions/integrations.ts
  app/screens/index.js
  app/screens/plugin/index.tsx
  app/utils/url.js
Labels: 4: Reviews Complete, release-note

#5696 Fix android extension crash
  share_extension/screens/channel_list.tsx
  share_extension/screens/team_list.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#5685 [MM-38683] Android Initialisation Bug + BottomSheet Correction
  app/components/post_list/post/body/body.tsx
  app/components/post_list/post/body/failed/failed.tsx
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/screens/options_modal/__snapshots__/options_modal_list.test.js.snap
  app/screens/options_modal/options_modal.js
  app/screens/options_modal/options_modal_list.js
  app/utils/bottom_sheet/bottom_sheet.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5698 Automated cherry pick of #5696
  share_extension/screens/channel_list.tsx
  share_extension/screens/team_list.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5699 Automated cherry pick of #5685
  app/components/post_list/post/body/body.tsx
  app/components/post_list/post/body/failed/failed.tsx
  app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
  app/components/sidebars/main/channels_list/list/list.js
  app/screens/options_modal/__snapshots__/options_modal_list.test.js.snap
  app/screens/options_modal/options_modal.js
  app/screens/options_modal/options_modal_list.js
  app/utils/bottom_sheet/bottom_sheet.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5700 Bump app build number to 370
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5701 Automated cherry pick of #5700
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5702 [Gekidou] Enable wdb-jsi on Android
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
Labels: 2: Dev Review, release-note-none

#5703 Use @mattermost/react-native-paste-input to allow pasting of images & files
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/RNEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditText.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableImageFromUrl.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputManager.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputPackage.java
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost+RCTUITextView.h
  ios/Mattermost/Mattermost+RCTUITextView.m
  ios/Mattermost/MattermostManaged.m
  ios/Mattermost/OnPasteEventManager.h
  ios/Mattermost/OnPasteEventManager.m
  ios/Mattermost/UIPasteboard+GetImageInfo.h
  ios/Mattermost/UIPasteboard+GetImageInfo.m
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.65.1.patch
Labels: CherryPick/Approved, QA Review Done, release-note-none

#5704 Automated cherry pick of #5703
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/RNEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditText.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableImageFromUrl.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputManager.java
  android/app/src/main/java/com/mattermost/rnbeta/RNPasteableTextInputPackage.java
  app/components/pasteable_text_input/__snapshots__/index.test.js.snap
  app/components/pasteable_text_input/index.js
  app/components/pasteable_text_input/index.test.js
  app/components/post_draft/__snapshots__/post_draft.test.js.snap
  app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
  app/components/post_draft/post_input/post_input.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost+RCTUITextView.h
  ios/Mattermost/Mattermost+RCTUITextView.m
  ios/Mattermost/MattermostManaged.m
  ios/Mattermost/OnPasteEventManager.h
  ios/Mattermost/OnPasteEventManager.m
  ios/Mattermost/UIPasteboard+GetImageInfo.h
  ios/Mattermost/UIPasteboard+GetImageInfo.m
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native+0.65.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5694 Translations update from Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#5705 Automated cherry pick of #5694
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none
