Repository mattermost/mattermost-mobile, pull requests merged in 2022-05, with the labels that each got.

#6204 Fix Back button position in Navigation Header
  app/components/navigation_header/header.tsx
Labels: release-note-none

#6180 [Gekidou] [MM-39936] Add Select Team Screen
  app/actions/remote/entry/app.ts
  app/actions/remote/role.ts
  app/actions/remote/team.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/teams.ts
  app/components/illustrations/no_team.tsx
  app/components/loading_error/__snapshots__/index.test.tsx.snap
  app/components/loading_error/index.tsx
  app/components/team_sidebar/add_team/add_team_slide_up.tsx
  app/components/team_sidebar/add_team/no_teams.svg
  app/components/team_sidebar/add_team/team_list.tsx
  app/components/team_sidebar/add_team/team_list_item/team_list_item.tsx
  app/components/team_sidebar/team_list/team_item/team_icon.tsx
  app/constants/screens.ts
  app/init/launch.ts
  app/queries/servers/categories.ts
  app/queries/servers/role.ts
  app/queries/servers/team.ts
  app/screens/browse_channels/index.ts
  app/screens/channel/channel_post_list/intro/index.ts
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/index.tsx
  app/screens/index.tsx
  app/screens/login/form.tsx
  app/screens/navigation.ts
  app/screens/select_team/add_team_item.tsx
  app/screens/select_team/header.tsx
  app/screens/select_team/index.ts
  app/screens/select_team/no_teams.tsx
  app/screens/select_team/select_team.tsx
  app/screens/select_team/team_list.tsx
  app/screens/sso/index.tsx
  app/store/ephemeral_store.ts
  app/utils/buttonStyles.ts
  app/utils/navigation/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6203 [Gekidou] Find channels (remote)
  app/actions/local/channel.test.ts
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/team.ts
  app/actions/remote/user.ts
  app/actions/websocket/channel.ts
  app/client/rest/channels.ts
  app/components/autocomplete/emoji_suggestion/index.ts
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/custom_status/custom_status.tsx
  app/components/custom_status/custom_status_emoji.tsx
  app/components/custom_status/custom_status_expiry.tsx
  app/components/emoji_picker/index.tsx
  app/components/markdown/channel_mention/channel_mention.tsx
  app/components/post_list/post/body/content/opengraph/index.ts
  app/components/post_list/post/header/index.ts
  app/components/post_list/post/index.ts
  app/components/post_list/thread_overview/index.ts
  app/components/system_header/index.tsx
  app/components/team_sidebar/team_list/index.ts
  app/queries/servers/channel.ts
  app/queries/servers/post.ts
  app/queries/servers/user.ts
  app/screens/channel/channel_post_list/index.ts
  app/screens/channel/channel_post_list/intro/public_or_private_channel/index.ts
  app/screens/custom_status_clear_after/components/date_time_selector.tsx
  app/screens/find_channels/filtered_list/filtered_list.tsx
  app/screens/find_channels/filtered_list/index.ts
  app/screens/find_channels/filtered_list/remote_channel_item/index.ts
  app/screens/find_channels/filtered_list/remote_channel_item/remote_channel_item.tsx
  app/screens/find_channels/filtered_list/user_item/index.ts
  app/screens/find_channels/filtered_list/user_item/user_item.tsx
  app/screens/find_channels/index.tsx
  app/screens/find_channels/unfiltered_list/index.ts
  app/screens/find_channels/utils.ts
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/store/ephemeral_store.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6206 [Gekidou] Do not set new line message indicator on own posts
  app/components/post_list/index.ts
  app/components/post_list/post_list.tsx
  app/screens/channel/channel_post_list/channel_post_list.tsx
  app/screens/channel/channel_post_list/index.ts
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/permalink/permalink.tsx
  app/screens/saved_posts/saved_posts.tsx
  app/screens/thread/thread_post_list/index.ts
  app/screens/thread/thread_post_list/thread_post_list.tsx
  app/utils/post_list/index.ts
Labels: 4: Reviews Complete, release-note-none

#6210 MM-43904 - Fix: Calls: "Access to route for non-existent plugin" error log
  app/client/rest/base.ts
  app/client/rest/index.ts
  app/client/rest/plugins.ts
  app/constants/calls.ts
  app/constants/websocket.ts
  app/products/calls/hooks.ts
  app/products/calls/store/action_types/calls.ts
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
  app/products/calls/store/reducers/calls.ts
  app/products/calls/store/selectors/calls.ts
  app/products/calls/store/types/calls.ts
  app/products/calls/websocket.ts
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#6213 Automated cherry pick of #6210
  app/client/rest/base.ts
  app/client/rest/index.ts
  app/client/rest/plugins.ts
  app/constants/calls.ts
  app/constants/websocket.ts
  app/products/calls/hooks.ts
  app/products/calls/store/action_types/calls.ts
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
  app/products/calls/store/reducers/calls.ts
  app/products/calls/store/selectors/calls.ts
  app/products/calls/store/types/calls.ts
  app/products/calls/websocket.ts
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6212 Automated cherry pick of #6210
  app/client/rest/base.ts
  app/client/rest/index.ts
  app/client/rest/plugins.ts
  app/constants/calls.ts
  app/constants/websocket.ts
  app/products/calls/hooks.ts
  app/products/calls/store/action_types/calls.ts
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
  app/products/calls/store/reducers/calls.ts
  app/products/calls/store/selectors/calls.ts
  app/products/calls/store/types/calls.ts
  app/products/calls/websocket.ts
  app/screens/channel/channel.android.js
  app/screens/channel/channel.ios.js
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6214 [Gekidou] Hide archive channels in channel list
  app/components/channel_item/channel_item.tsx
Labels: 4: Reviews Complete, release-note-none

#6217 Dot release 1.51.2
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#6218 Bump app build number to 396
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6219 Automated cherry pick of #6218
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6209 Preserve notifications when tapping or clearing notifications from a channel
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, release-note-none

#6216 Fetch missing custom emojis
  app/actions/remote/custom_emoji.ts
  app/components/emoji/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6211 [Gekidou] Fix alignment of custom status
  app/components/channel_item/custom_status/custom_status.tsx
  app/components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap
  app/components/custom_status/custom_status_emoji.tsx
  app/components/post_list/post/header/header.tsx
  app/screens/custom_status/components/custom_status_emoji.tsx
  app/screens/custom_status/components/custom_status_input.tsx
  app/screens/custom_status/components/custom_status_suggestion.tsx
Labels: 4: Reviews Complete, release-note-none

#6221 Gekidou unreads mention fix
  app/components/channel_item/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
Labels: 4: Reviews Complete, release-note

#6208 [Gekidou] Exclude muted channels from unread badges
  app/components/channel_item/index.ts
  app/components/team_sidebar/team_list/team_item/index.ts
  app/database/subscription/unreads.ts
  app/queries/servers/channel.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/home/tab_bar/home.tsx
Labels: 4: Reviews Complete, release-note-none

#6215 [Gekidou] Fix GM display name
  app/actions/remote/channel.ts
  app/actions/remote/user.ts
  app/components/channel_icon/index.tsx
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.test.tsx
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/index.ts
  app/helpers/database/index.ts
Labels: 4: Reviews Complete, release-note-none

#6226 [Gekidou] Remove jcenter
  android/build.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@nozbe+watermelondb+0.24.0.patch
  patches/@react-native-community+art+1.2.0.patch
  patches/react-native-youtube+2.0.2.patch
Labels: 4: Reviews Complete, release-note-none

#6220 Moves collapse animation to FlatList, updates timings
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.test.tsx
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/index.ts
  app/screens/find_channels/filtered_list/filtered_list.tsx
  app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
  app/screens/home/channel_list/categories_list/categories/body/__snapshots__/category_body.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/category_body.test.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/unreads.tsx
Labels: release-note

#6230 Fixes grouped unread sorting
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
Labels: release-note

#6227 Dismiss post options before executing action
  app/screens/post_options/options/copy_text_option.tsx
  app/screens/post_options/options/delete_post_option.tsx
  app/screens/post_options/options/mark_unread_option.tsx
  app/screens/post_options/options/pin_channel_option.tsx
  app/screens/thread_options/options/mark_as_unread_option.tsx
Labels: 2: UX Review, release-note-none

#6222 Fix channel item with long name and badge
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none

#6224 [Gekidou] Fix create direct message styles
  app/components/user_list_row/index.tsx
  app/screens/create_direct_message/selected_users/selected_user.tsx
Labels: 4: Reviews Complete, release-note-none

#6181 MM-41532 Gekidou Snack Bars
  app/components/common_post_options/copy_permalink_option/copy_permalink_option.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/thread_overview/thread_overview.tsx
  app/components/toast/index.tsx
  app/constants/index.ts
  app/constants/screens.ts
  app/constants/snack_bar.ts
  app/screens/home/tab_bar/index.tsx
  app/screens/index.tsx
  app/screens/navigation.ts
  app/screens/post_options/options/copy_text_option.tsx
  app/screens/post_options/options/mark_unread_option/mark_unread_option.tsx
  app/screens/post_options/post_options.tsx
  app/screens/snack_bar/index.tsx
  app/screens/thread_options/thread_options.tsx
  app/utils/snack_bar/index.ts
  assets/base/i18n/en.json
  package-lock.json
Labels: 4: Reviews Complete, 2: UX Review, release-note-none

#6225 [Gekidou] [MM-43973] Thread footer for recent mentions
  app/actions/remote/search.ts
  app/actions/websocket/posts.ts
  app/components/post_with_channel_info/index.ts
  app/components/post_with_channel_info/post_with_channel_info.tsx
  app/database/operator/server_data_operator/handlers/thread.ts
  app/screens/post_options/post_options.tsx
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note-none

#6229 MM-43904 - Fix: Calls batch actions
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6228 Detox/E2E: Messaging e2e tests in Gekidou
  app/components/jumbo_emoji/index.tsx
  app/components/markdown/markdown.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/edit_post/post_error/index.tsx
  app/screens/global_threads/index.tsx
  app/screens/global_threads/threads_list/header/index.tsx
  app/screens/global_threads/threads_list/threads_list.tsx
  app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/screens/home/channel_list/categories_list/threads_button/threads_button.tsx
  app/screens/thread/thread.tsx
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/support/ui/component/post.ts
  detox/e2e/support/ui/component/post_list.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/edit_post.ts
  detox/e2e/support/ui/screen/global_threads.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/post_options.ts
  detox/e2e/support/ui/screen/server_list.ts
  detox/e2e/support/ui/screen/thread.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/messaging/message_delete.e2e.ts
  detox/e2e/test/messaging/message_draft.e2e.ts
  detox/e2e/test/messaging/message_edit.e2e.ts
  detox/e2e/test/messaging/message_post.e2e.ts
  detox/e2e/test/messaging/message_reply.e2e.ts
  detox/e2e/test/server_login/server_list.e2e.ts
  detox/e2e/test/smoke_test/messaging.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6234 [Gekidou] fix flip of post list
  app/screens/channel/channel_post_list/channel_post_list.tsx
  app/utils/post/index.ts
Labels: 4: Reviews Complete, release-note-none

#6232 Automated cherry pick of #6229
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6233 Automated cherry pick of #6229
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6235 Bump app build number to 397
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6236 Bump app build number to 398
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6237 Automated cherry pick of #6236
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6240 [Gekidou] Updated styling opacities
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/index.ts
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/header/header.tsx
  package-lock.json
Labels: release-note

#6238 [Gekidou] Remove Share Extensions
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/share/ShareActivity.java
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  fastlane/Fastfile
  index.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/MattermostShare.xcscheme
  ios/MattermostShare/Base.lproj/MainInterface.storyboard
  ios/MattermostShare/ChannelsViewController.swift
  ios/MattermostShare/Config.swift
  ios/MattermostShare/GenericPreview.swift
  ios/MattermostShare/GenericPreview.xib
  ios/MattermostShare/Images/generic.png
  ios/MattermostShare/Info.plist
  ios/MattermostShare/Item.swift
  ios/MattermostShare/MattermostShare-Bridging-Header.h
  ios/MattermostShare/MattermostShare.entitlements
  ios/MattermostShare/Section.swift
  ios/MattermostShare/ShareViewController.swift
  ios/MattermostShare/TeamsViewController.swift
  share_extension/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6242 [Gekidou] Dismiss keyboard when a post is pressed
  app/components/post_list/post/post.tsx
Labels: 4: Reviews Complete, release-note-none

#6243 Fix typing
  app/components/post_draft/typing/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6244 Bump app build number to 399
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6239 [Gekidou] Remove react-native-youtube and allow the link to be handled natively
  app/components/post_list/post/body/content/youtube/index.ts
  app/components/post_list/post/body/content/youtube/index.tsx
  app/components/post_list/post/body/content/youtube/youtube.tsx
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  ios/patches/XCDYouTubeVideoOperation.patch
  package-lock.json
  package.json
  patches/react-native-youtube+2.0.2.patch
Labels: 4: Reviews Complete, release-note-none

#6245 Show unread channels when category is collapsed
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/body/index.ts
Labels: 4: Reviews Complete, release-note-none

#6250 [Gekidou] Filter archived channels from channel list
  app/screens/home/channel_list/categories_list/categories/body/index.ts
Labels: 4: Reviews Complete, release-note-none

#6192 [Gekidou] [MM-41837] Add verification for push proxy and related interface
  app/actions/remote/entry/app.ts
  app/actions/remote/general.ts
  app/actions/remote/session.ts
  app/client/rest/general.ts
  app/constants/database.ts
  app/constants/index.ts
  app/constants/push_proxy.ts
  app/queries/app/global.ts
  app/queries/servers/system.ts
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/header.test.tsx
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/categories_list/header/index.ts
  app/screens/home/channel_list/servers/servers_list/server_item/index.ts
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/select_team/header.tsx
  app/screens/server/index.tsx
  app/store/ephemeral_store.ts
  app/utils/push_proxy.ts
  assets/base/i18n/en.json
  test/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#6246 [Gekidou] go back when root post is deleted in thread view
  app/screens/thread/thread.tsx
Labels: 2: Dev Review, QA Review Done, release-note-none

#6248 [Gekidou] Filter to show only unread channels
  app/actions/local/channel.ts
  app/constants/database.ts
  app/queries/servers/system.ts
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/categories/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/home/channel_list/categories_list/subheader/index.ts
  app/screens/home/channel_list/categories_list/subheader/search_field/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/subheader/search_field/index.test.tsx
  app/screens/home/channel_list/categories_list/subheader/search_field/index.tsx
  app/screens/home/channel_list/categories_list/subheader/subheader.tsx
  app/screens/home/channel_list/categories_list/subheader/unread_filter/index.ts
  app/screens/home/channel_list/categories_list/subheader/unread_filter/unread_filter.tsx
Labels: 4: Reviews Complete, release-note-none

#6249 [Gekidou] bug fixes
  app/components/navigation_header/header.tsx
  app/components/post_draft/typing/index.tsx
  app/constants/post_draft.ts
  app/constants/screens.ts
  app/screens/channel/channel_post_list/channel_post_list.tsx
  app/screens/channel/channel_post_list/intro/direct_channel/member/member.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Labels: 4: Reviews Complete, release-note-none

#6247 [Gekidou] Update DM and thread title/subtitle as well as navbar rounded corners
  app/actions/local/thread.ts
  app/components/navigation_header/context.tsx
  app/components/navigation_header/header.tsx
  app/components/navigation_header/index.tsx
  app/components/rounded_header_context/index.tsx
  app/screens/channel/channel.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/index.ts
  app/screens/channel/header/other_mentions_badge/index.tsx
  app/screens/channel/index.tsx
  app/screens/navigation.ts
  app/screens/thread/thread.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6253 [Gekidou[ [MM-43969, MM-44037] global threads crash, mark as read
  app/actions/remote/thread.ts
  app/client/rest/threads.ts
  app/database/models/server/post.ts
  app/database/models/server/thread.ts
  app/database/operator/server_data_operator/handlers/thread.ts
  app/queries/servers/post.ts
  app/screens/thread/thread_post_list/thread_post_list.tsx
  app/screens/thread_options/options/mark_as_unread_option.tsx
  types/api/threads.d.ts
  types/database/models/servers/thread.d.ts
Labels: 2: Dev Review, release-note-none

#6256 Translations update from Mattermost Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/hu.json
  assets/base/i18n/ko.json
  assets/base/i18n/sv.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 2: Dev Review, do-not-merge/release-note-label-needed

#6255 Improvements on team switch performance
  app/actions/remote/team.ts
  app/components/channel_item/channel_item.test.tsx
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/custom_status/custom_status.tsx
  app/components/channel_item/index.ts
  app/components/team_sidebar/team_list/team_item/index.ts
  app/components/team_sidebar/team_list/team_item/team_item.tsx
  app/constants/events.ts
  app/hooks/team_switch.ts
  app/queries/servers/channel.ts
  app/screens/channel/channel.tsx
  app/screens/global_threads/index.tsx
  app/screens/home/channel_list/additional_tablet_view/additional_tablet_view.tsx
  app/screens/home/channel_list/additional_tablet_view/index.ts
  app/screens/home/channel_list/categories_list/categories/categories.test.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/categories/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/unreads.tsx
  app/screens/home/channel_list/categories_list/header/index.ts
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/home/channel_list/categories_list/load_channels_error/index.ts
  app/screens/home/channel_list/categories_list/load_channels_error/load_channel_error.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
Labels: 2: Dev Review, release-note-none

#6258 [Gekidou] Team icon style
  app/components/team_sidebar/add_team/index.tsx
  app/components/team_sidebar/team_list/team_item/team_icon.tsx
Labels: 4: Reviews Complete, release-note-none

#6264 Fix autocomplete position on tablets
  app/components/autocomplete/autocomplete.tsx
  app/constants/autocomplete.ts
Labels: 4: Reviews Complete, release-note-none

#6265 Remove unneeded actions on team switch
  app/actions/remote/team.ts
Labels: 4: Reviews Complete, release-note-none

#6266 [Gekidou] Replace lottie loading spinner for activity indicator
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/settings.gradle
  app/components/loading/__snapshots__/index.test.tsx.snap
  app/components/loading/index.tsx
  app/components/loading/spinner.json
  app/components/post_list/post/body/content/message_attachments/action_button/index.tsx
  app/screens/browse_channels/browse_channels.tsx
  app/screens/browse_channels/channel_list.tsx
  app/screens/create_direct_message/user_list.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/edit_server/form.tsx
  app/screens/find_channels/filtered_list/filtered_list.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/login/form.tsx
  app/screens/mfa/index.tsx
  app/screens/saved_posts/saved_posts.tsx
  app/screens/server/form.tsx
  app/utils/theme/index.ts
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  types/api/preferences.d.ts
Labels: 4: Reviews Complete, release-note-none

#6267 Fixes channel muting inside category
  app/components/channel_item/index.ts
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
Labels: 4: Reviews Complete, release-note

#6268 [Gekidou] Various fixes
  app/components/channel_item/channel_item.tsx
  app/components/floating_text_input_label/index.tsx
  app/components/markdown/channel_mention/channel_mention.tsx
  app/components/post_list/post/post.tsx
  app/components/server_icon/__snapshots__/server_icon.test.tsx.snap
  app/components/server_icon/index.tsx
  app/components/team_sidebar/team_list/team_item/team_item.tsx
  app/constants/events.ts
  app/screens/channel/channel.tsx
  app/screens/channel/channel_post_list/channel_post_list.tsx
  app/screens/channel/channel_post_list/intro/intro.tsx
  app/screens/find_channels/filtered_list/filtered_list.tsx
  app/screens/find_channels/index.tsx
  app/screens/gallery/footer/footer.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/home/index.tsx
  app/screens/server/form.tsx
  app/screens/server/index.tsx
Labels: 2: Dev Review, release-note-none

#6254 MM-42484 - Gekidou - Update DM/GM display name when teammate name display changes
  app/actions/local/channel.ts
  app/actions/websocket/preferences.ts
  app/actions/websocket/system.ts
  app/queries/servers/preference.ts
  app/utils/user/index.ts
Labels: 4: Reviews Complete, release-note-none

#6271 [Gekidou] Set 5s as default timeout for ping action
  app/actions/remote/general.ts
  app/client/rest/base.ts
  app/client/rest/general.ts
  types/api/client.d.ts
Labels: 2: Dev Review, release-note-none

#6270 [Gekidou] Bump app build number to 400
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6273 [Gekidou] Bump app build number to 401
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6282 Translations update from Mattermost Weblate
  assets/base/i18n/nl.json
  assets/base/i18n/sv.json
  assets/base/i18n/zh-CN.json
Labels: 2: Dev Review

#6280 [Gekidou MM-44308] CRT Android unable to read/follow the thread
  app/client/rest/threads.ts
  app/screens/thread_options/thread_options.tsx
Labels: 4: Reviews Complete

#6269 Use local users for At Mention Autocomplete
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/at_mention/index.ts
Labels: 4: Reviews Complete, release-note-none

#6274 Gekidou fixes
  app/actions/local/channel.ts
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/markdown/error_boundary.tsx
  app/components/markdown/markdown_latex_block/index.tsx
  app/components/markdown/markdown_latex_inline/index.tsx
  app/components/post_draft/index.ts
  app/components/post_list/post/body/files/files.tsx
  app/components/post_list/post/body/files/video_file.tsx
  app/managers/network_manager.ts
  app/queries/servers/post.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/screens/home/channel_list/categories_list/threads_button/index.ts
  app/screens/home/channel_list/categories_list/threads_button/threads_button.test.tsx
  app/screens/home/channel_list/categories_list/threads_button/threads_button.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6241 MM-43584 - Gekidou Mute Channel SnackBar
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/constants/snack_bar.ts
  app/screens/snack_bar/index.tsx
  app/utils/channel/index.ts
  app/utils/snack_bar/index.ts
  types/api/channels.d.ts
Labels: 2: Dev Review, release-note-none

#6262 Better handle go to location
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/command.ts
  app/actions/websocket/channel.ts
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/post_draft/send_handler/send_handler.tsx
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/screens/apps_form/apps_form_component.tsx
  types/api/channels.d.ts
Labels: 4: Reviews Complete, release-note-none

#6272 Use local channels on channel autocomplete
  app/components/autocomplete/channel_mention/channel_mention.tsx
Labels: 4: Reviews Complete, release-note-none

#6251 [Gekidou] Groups + group membership schema
  app/constants/database.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/models/server/group.ts
  app/database/models/server/group_channel.ts
  app/database/models/server/group_membership.ts
  app/database/models/server/group_team.ts
  app/database/models/server/index.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/group.ts
  app/database/schema/server/table_schemas/group_channel.ts
  app/database/schema/server/table_schemas/group_membership.ts
  app/database/schema/server/table_schemas/group_team.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/test.ts
  docs/database/server/server-v1.pdf
  docs/database/server/server-v1.png
  docs/database/server/server-v1.rtf
  docs/database/server/server-v1.sql
  docs/database/server/server.md
  types/api/groups.d.ts
  types/database/models/servers/group.d.ts
  types/database/models/servers/group_channel.d.ts
  types/database/models/servers/group_membership.d.ts
  types/database/models/servers/group_team.d.ts
  types/database/raw_values.d.ts
Labels: 4: Reviews Complete, release-note

#6231 Unify entry functions
  app/actions/local/thread.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/team.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/screens/home/index.tsx
  app/utils/navigation/index.ts
Labels: 2: Dev Review, release-note-none

#6291 Observe CRT preference with values
  app/queries/servers/thread.ts
Labels: 4: Reviews Complete, release-note-none

#6285 MM-39711 Gekidou Settings - Notification Main Screen
  app/constants/screens.ts
  app/screens/index.tsx
  app/screens/settings/constant.ts
  app/screens/settings/index.tsx
  app/screens/settings/notifications/index.tsx
  app/screens/settings/notifications/notifications.tsx
  app/screens/settings/setting_option.tsx
  app/screens/settings/settings.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6287 MM-39711 Gekidou Settings - Display Main Screen
  app/constants/screens.ts
  app/queries/servers/system.ts
  app/screens/index.tsx
  app/screens/settings/constant.ts
  app/screens/settings/display/display.tsx
  app/screens/settings/display/index.tsx
  app/screens/settings/setting_option.tsx
  app/screens/settings/settings.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6292 [Gekidou - MM-44258] Modifies post padding to 16
  app/components/post_list/date_separator/index.tsx
  app/components/post_list/new_message_line/index.tsx
  app/components/post_list/post/body/content/youtube/index.tsx
  app/components/post_list/post/body/files/files.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
  app/components/post_list/thread_overview/thread_overview.tsx
  app/components/post_with_channel_info/channel_info/channel_info.tsx
  app/components/post_with_channel_info/post_with_channel_info.tsx
Labels: 4: Reviews Complete, release-note-none

#6288 [Gekidou] channel quick actions
  app/actions/local/category.ts
  app/actions/local/channel.ts
  app/actions/local/thread.ts
  app/actions/remote/category.ts
  app/actions/remote/channel.ts
  app/actions/remote/preference.ts
  app/actions/websocket/channel.ts
  app/client/rest/categories.ts
  app/components/channel_actions/add_people_box/index.tsx
  app/components/channel_actions/copy_channel_link_box/copy_channel_link_box.tsx
  app/components/channel_actions/copy_channel_link_box/index.ts
  app/components/channel_actions/favorite_box/favorite_box.tsx
  app/components/channel_actions/favorite_box/index.ts
  app/components/channel_actions/info_box/index.tsx
  app/components/channel_actions/leave_channel_label/index.ts
  app/components/channel_actions/leave_channel_label/leave_channel_label.tsx
  app/components/channel_actions/mute_box/index.ts
  app/components/channel_actions/mute_box/mute_box.tsx
  app/components/channel_actions/set_header_box/index.ts
  app/components/channel_actions/set_header_box/set_header.tsx
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/index.ts
  app/components/navigation_header/header.tsx
  app/components/option_box/animated.tsx
  app/components/option_box/index.tsx
  app/components/slide_up_panel_item/index.tsx
  app/constants/categories.ts
  app/constants/events.ts
  app/constants/screens.ts
  app/constants/snack_bar.ts
  app/database/models/server/category.ts
  app/queries/servers/categories.ts
  app/queries/servers/channel.ts
  app/queries/servers/system.ts
  app/screens/channel/channel_post_list/intro/direct_channel/direct_channel.tsx
  app/screens/channel/channel_post_list/intro/intro.tsx
  app/screens/channel/channel_post_list/intro/options/favorite/favorite.tsx
  app/screens/channel/channel_post_list/intro/options/favorite/index.ts
  app/screens/channel/channel_post_list/intro/options/index.tsx
  app/screens/channel/channel_post_list/intro/options/item.tsx
  app/screens/channel/channel_post_list/intro/public_or_private_channel/public_or_private_channel.tsx
  app/screens/channel/channel_post_list/intro/townsquare/index.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/quick_actions/index.ts
  app/screens/channel/header/quick_actions/quick_actions.tsx
  app/screens/find_channels/quick_options/quick_options.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/header/header.tsx
  app/screens/home/index.tsx
  app/screens/snack_bar/index.tsx
  app/store/ephemeral_store.ts
  app/utils/categories.ts
  app/utils/navigation/index.ts
  app/utils/snack_bar/index.ts
  assets/base/i18n/en.json
  types/database/models/servers/category.d.ts
Labels: 4: Reviews Complete, release-note-none

#6295 CRT fixes for MM-44210 & MM-44156
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/common.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.ts
  app/queries/servers/post.ts
  app/queries/servers/thread.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/utils/thread/index.ts
  types/database/database.d.ts
Labels: release-note-none

#6297 Properly handle deleted system posts
  app/utils/post_list/index.ts
Labels: 4: Reviews Complete, release-note-none

#6298 MM-44423 : Gekidou - event screenDidDisappear called twice
  app/screens/snack_bar/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6293 [Gekidou] retry post
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/actions/remote/post.ts
  app/components/post_list/post/body/failed/index.tsx
  app/components/post_list/post/post.tsx
  app/constants/post.ts
  app/database/models/server/post.ts
  app/utils/file/file_picker/index.ts
  app/utils/post/index.ts
  package-lock.json
  types/database/models/servers/post.d.ts
Labels: 4: Reviews Complete, release-note-none

#6299 Wait until bottom sheet closes before adding the reaction
  app/screens/post_options/reaction_bar/reaction_bar.tsx
Labels: 4: Reviews Complete, release-note-none

#6296 [Gekidou MM-44209] Markdown heading style updates
  app/utils/markdown/index.ts
Labels: release-note-none

#6301 Bump app build number to 402
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6300 Detox/E2E: Global threads e2e tests in Gekidou
  app/components/common_post_options/copy_permalink_option/copy_permalink_option.tsx
  app/components/common_post_options/follow_thread_option/follow_thread_option.tsx
  app/components/common_post_options/reply_option.tsx
  app/components/common_post_options/save_option.tsx
  app/components/post_list/post/footer/footer.tsx
  app/components/post_list/post/header/reply/index.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/post/unread_dot.tsx
  app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
  app/components/post_list/thread_overview/thread_overview.tsx
  app/screens/global_threads/threads_list/empty_state.tsx
  app/screens/global_threads/threads_list/header/index.tsx
  app/screens/global_threads/threads_list/thread/thread.tsx
  app/screens/permalink/permalink.tsx
  app/screens/post_options/options/copy_text_option.tsx
  app/screens/post_options/options/delete_post_option.tsx
  app/screens/post_options/options/edit_option.tsx
  app/screens/post_options/options/mark_unread_option/mark_unread_option.tsx
  app/screens/post_options/options/pin_channel_option.tsx
  app/screens/thread/thread_follow_button/thread_follow_button.tsx
  app/screens/thread_options/options/mark_as_unread_option.tsx
  app/screens/thread_options/options/open_in_channel_option.tsx
  app/screens/thread_options/thread_options.tsx
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/support/ui/component/post.ts
  detox/e2e/support/ui/component/post_list.ts
  detox/e2e/support/ui/screen/global_threads.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/permalink.ts
  detox/e2e/support/ui/screen/post_options.ts
  detox/e2e/support/ui/screen/thread.ts
  detox/e2e/support/ui/screen/thread_options.ts
  detox/e2e/test/smoke_test/threads.e2e.ts
  detox/e2e/test/threads/follow_and_unfollow_thread.e2e.ts
  detox/e2e/test/threads/global_threads.e2e.ts
  detox/e2e/test/threads/mark_thread_as_read_and_unread.e2e.ts
  detox/e2e/test/threads/open_thread_in_channel.e2e.ts
  detox/e2e/test/threads/reply_to_thread.e2e.ts
  detox/e2e/test/threads/save_and_unsave_thread.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6302 [Gekidou] perf improvement & fix upgrade path
  app/actions/remote/channel.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/notifications.ts
  app/actions/remote/retry.ts
  app/actions/remote/user.ts
  app/actions/websocket/channel.ts
  app/components/formatted_date/index.tsx
  app/hooks/team_switch.ts
  app/screens/home/channel_list/additional_tablet_view/additional_tablet_view.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  package-lock.json
  types/database/models/servers/channel.d.ts
Labels: 4: Reviews Complete, release-note-none

#6305 [Gekidou] Update dependencies
  android/app/build.gradle
  android/build.gradle
  detox/package-lock.json
  detox/package.json
  fastlane/Gemfile.lock
  ios/Podfile.lock
  jest.config.js
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+8.3.0.patch
  patches/@stream-io+flat-list-mvcp+0.10.2.patch
  patches/@types+react-syntax-highlighter+15.5.1.patch
  patches/react-native+0.68.2.patch
  patches/react-native-device-info+8.7.1.patch
  patches/react-native-navigation+7.27.1.patch
  patches/react-native-reanimated+2.8.0.patch
  test/file_transformer.js
Labels: QA Review Done, release-note-none

#6261 [Gekidou] Groups are included in the @metion auto-complete
  app/actions/remote/groups.ts
  app/client/rest/groups.ts
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/at_mention/index.ts
  app/components/autocomplete/at_mention_group/at_mention_group.tsx
  app/components/autocomplete/autocomplete_section_header.tsx
  app/components/user_item/user_item.tsx
Labels: 2: Dev Review, release-note

#6311 Update en.json to show proper message on threads tab
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6310 Comment out create team options until we have a create team screen
  app/components/team_sidebar/add_team/add_team_slide_up.tsx
  app/components/team_sidebar/add_team/index.tsx
  app/components/team_sidebar/index.ts
  app/components/team_sidebar/team_sidebar.tsx
  app/screens/select_team/index.ts
  app/screens/select_team/no_teams.tsx
  app/screens/select_team/select_team.tsx
  app/screens/select_team/team_list.tsx
Labels: 4: Reviews Complete, release-note-none

#6279 [Gekidou - MM-44258] Search Screen - Results Empty State
  app/components/navigation_header/context.tsx
  app/components/navigation_header/header.tsx
  app/components/navigation_header/index.tsx
  app/components/navigation_header/large.tsx
  app/components/navigation_header/search.tsx
  app/components/navigation_header/search_context.tsx
  app/components/no_results_with_term/index.tsx
  app/components/no_results_with_term/search_files_illustration.tsx
  app/constants/view.ts
  app/hooks/header.ts
  app/screens/channel/header/quick_actions/quick_actions.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/search/index.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/header_button.tsx
  app/screens/home/search/results/results.tsx
  app/screens/settings/display/display.tsx
  app/screens/settings/notifications/notifications.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, 2: UX Review, release-note

#6277 [Gekidou] Groups API Calls
  app/actions/remote/groups.ts
  app/client/rest/groups.ts
  app/components/autocomplete/at_mention/at_mention.tsx
Labels: 4: Reviews Complete, release-note

#6304 [Gekiodu - MM-44156] Channel ordering is different between web and mobile
  app/actions/remote/post.ts
  app/actions/remote/search.ts
  app/actions/websocket/posts.ts
  app/queries/servers/categories.ts
  app/queries/servers/channel.ts
  app/screens/home/channel_list/categories_list/categories/body/category_body.test.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  types/api/channels.d.ts
Labels: 4: Reviews Complete, release-note, Contributor

#6303 [Gekidou] commonmark feature parity
  app/components/markdown/markdown.tsx
  app/components/markdown/transform.test.ts
  app/components/markdown/transform.ts
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post/body/message/message.tsx
  app/components/post_list/post/post.tsx
  app/utils/markdown/index.ts
  package-lock.json
  package.json
  patches/@types+commonmark+0.27.5.patch
  types/global/markdown.ts
Labels: release-note-none

#6320 [Gekidou] Bump app build number to 403
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6313 MM-39711 - Gekidou Notification - Auto Responder main screen
  app/constants/screens.ts
  app/screens/index.tsx
  app/screens/settings/constant.ts
  app/screens/settings/notification_auto_responder/index.ts
  app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
  app/screens/settings/notification_push/push_send.tsx
  app/screens/settings/notification_push/push_thread.tsx
  app/screens/settings/notifications/notifications.tsx
  app/utils/user/index.ts
  assets/base/i18n/en.json
  types/api/users.d.ts
Labels: 2: Dev Review, Do Not Merge/Awaiting PR, release-note-none

#6317 Remove ts-expect-error regarding legacy refs
  app/components/emoji_picker/sections/index.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/edit_server/form.tsx
  app/screens/edit_server/index.tsx
  app/screens/forgot_password/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/interactive_dialog/index.tsx
  app/screens/login/form.tsx
  app/screens/login/index.tsx
  app/screens/mfa/index.tsx
  app/screens/server/form.tsx
  app/screens/server/index.tsx
Labels: 4: Reviews Complete, release-note-none
