Repository mattermost/mattermost-mobile, pull requests merged in 2022-07, with the labels that each got.

#6452 Bump app build number to 411
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6450 Detox/E2E: Messaging markdown e2e tests in Gekidou
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_code_block/index.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_latex_block/index.tsx
  app/components/markdown/markdown_latex_inline/index.tsx
  app/components/markdown/markdown_link/markdown_link.tsx
  app/components/markdown/markdown_list_item/index.tsx
  app/components/markdown/markdown_table_cell/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/components/markdown/markdown_table_row/index.tsx
  app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap
  detox/e2e/support/ui/component/post.ts
  detox/e2e/support/ui/component/post_list.ts
  detox/e2e/test/messaging/markdown_block_quote.e2e.ts
  detox/e2e/test/messaging/markdown_code.e2e.ts
  detox/e2e/test/messaging/markdown_heading.e2e.ts
  detox/e2e/test/messaging/markdown_image.e2e.ts
  detox/e2e/test/messaging/markdown_latex.e2e.ts
  detox/e2e/test/messaging/markdown_list.e2e.ts
  detox/e2e/test/messaging/markdown_separator.e2e.ts
  detox/e2e/test/messaging/markdown_table.e2e.ts
  detox/e2e/test/smoke_test/messaging.e2e.ts
Labels: QA Review Done, release-note-none

#6458 Fix at mention that triggers ephemeral message
  app/actions/remote/post.ts
  app/actions/websocket/posts.ts
  app/components/post_list/post/body/index.tsx
  app/database/operator/server_data_operator/handlers/posts_in_channel.ts
Labels: release-note

#6382 MM-37110: handle toggling of CRT feature
  app/actions/remote/entry/common.ts
  app/actions/websocket/preferences.ts
  app/constants/events.ts
  app/queries/servers/entry.ts
  app/queries/servers/preference.ts
  app/screens/home/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6370 [Gekidou] Groups + group-memberships deferred fetch
  app/actions/local/group.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/groups.ts
  app/client/rest/groups.ts
  app/components/markdown/at_mention/at_mention.tsx
  app/components/markdown/at_mention/index.ts
  app/database/operator/server_data_operator/handlers/group.ts
  app/database/operator/server_data_operator/transformers/group.ts
  app/queries/servers/group.ts
  app/utils/groups.ts
  types/api/groups.d.ts
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note

#6453 MM-45456 - Gekidou LoadingUnreads component keeps spinning
  app/actions/remote/entry/common.ts
  app/actions/remote/post.ts
  app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note-none

#6461 Gekidou Minor Fixes
  app/database/operator/server_data_operator/handlers/category.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/handlers/group.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/database/operator/server_data_operator/handlers/reaction.ts
  app/database/operator/server_data_operator/handlers/team.ts
  app/database/operator/server_data_operator/handlers/thread.ts
  app/database/operator/server_data_operator/handlers/user.ts
  app/hooks/navigation_button_pressed.tsx
  docs/database/server/server.md
Labels: 2: Dev Review, release-note-none

#6412 MM-39711 - Gekidou Advanced Settings
  app/actions/local/file.ts
  app/components/menu_item/index.tsx
  app/components/option_item/index.tsx
  app/constants/screens.ts
  app/screens/index.tsx
  app/screens/settings/advanced/index.tsx
  app/screens/settings/display_clock/display_clock.tsx
  app/screens/settings/index.tsx
  app/screens/settings/settings.tsx
  app/utils/file/index.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note-none

#6464 [Gekidou] Bump app build number to 412
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6462 Detox/E2E: Recent Mentions and Saved Messages e2e tests in Gekidou
  app/components/post_with_channel_info/channel_info/channel_info.tsx
  app/components/post_with_channel_info/post_with_channel_info.tsx
  app/screens/home/recent_mentions/components/empty.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/results/results.tsx
  detox/e2e/support/ui/component/index.ts
  detox/e2e/support/ui/component/navigation_header.ts
  detox/e2e/support/ui/component/post_channel_info.ts
  detox/e2e/support/ui/component/post_list.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/edit_post.ts
  detox/e2e/support/ui/screen/emoji_picker.ts
  detox/e2e/support/ui/screen/home.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/recent_mentions.ts
  detox/e2e/support/ui/screen/saved_messages.ts
  detox/e2e/support/ui/screen/thread.ts
  detox/e2e/test/channels/channel_post_list.e2e.ts
  detox/e2e/test/messaging/markdown_code.e2e.ts
  detox/e2e/test/messaging/markdown_latex.e2e.ts
  detox/e2e/test/messaging/markdown_table.e2e.ts
  detox/e2e/test/messaging/message_delete.e2e.ts
  detox/e2e/test/messaging/message_edit.e2e.ts
  detox/e2e/test/messaging/message_post.e2e.ts
  detox/e2e/test/messaging/message_reply.e2e.ts
  detox/e2e/test/search/recent_mentions.e2e.ts
  detox/e2e/test/search/saved_messages.e2e.ts
  detox/e2e/test/smoke_test/channels.e2e.ts
  detox/e2e/test/smoke_test/messaging.e2e.ts
  detox/e2e/test/smoke_test/search.e2e.ts
Labels: release-note-none

#6456 Translations update from Mattermost Weblate
  assets/base/i18n/ko.json
Labels: release-note-none, Do Not Merge/Mattermod

#6467 Translations update from Mattermost Weblate
  assets/base/i18n/hu.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#6465 [Gekidou MM-45521] Remove show results button
  app/components/option_item/index.tsx
  app/screens/bottom_sheet/content.tsx
  app/screens/browse_channels/channel_dropdown.tsx
  app/screens/home/search/results/filter.tsx
  app/screens/home/search/results/header.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note

#6459 Detox/E2E: Find channels, Edit channel, etc e2e tests in Gekidou
  app/screens/channel_info/extra/extra.tsx
  app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
  detox/e2e/support/ui/screen/channel_dropdown_menu.ts
  detox/e2e/support/ui/screen/channel_info.ts
  detox/e2e/support/ui/screen/create_or_edit_channel.ts
  detox/e2e/test/autocomplete/channel_post_draft.e2e.ts
  detox/e2e/test/autocomplete/create_channel.e2e.ts
  detox/e2e/test/autocomplete/thread_post_draft.e2e.ts
  detox/e2e/test/channels/browse_channels.e2e.ts
  detox/e2e/test/channels/create_channel_and_edit_channel_header.e2e.ts
  detox/e2e/test/channels/edit_channel.e2e.ts
  detox/e2e/test/channels/find_channels.e2e.ts
  detox/e2e/test/smoke_test/channels.e2e.ts
Labels: release-note-none

#6425 [Gekidou - MM-44930] Use File component for showing files in search.
  app/actions/remote/search.ts
  app/client/rest/files.ts
  app/components/autocomplete_selector/index.tsx
  app/components/files/document_file.tsx
  app/components/files/file.tsx
  app/components/files/file_icon.tsx
  app/components/files/file_info.tsx
  app/components/files/file_options_icon.tsx
  app/components/files/files.tsx
  app/components/files/image_file.tsx
  app/components/files/image_file_overlay.tsx
  app/components/files/index.ts
  app/components/files/video_file.tsx
  app/components/no_results_with_term/index.tsx
  app/components/post_draft/uploads/upload_item/index.tsx
  app/components/post_list/post/body/content/image_preview/image_preview.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_image/index.tsx
  app/components/post_list/post/body/files/file.tsx
  app/components/post_list/post/body/files/file_info.tsx
  app/components/post_list/post/body/index.tsx
  app/components/post_with_channel_info/channel_info/channel_info.tsx
  app/hooks/files.ts
  app/screens/gallery/document_renderer/document_renderer.tsx
  app/screens/home/search/results/fileCard.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/index.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
  app/utils/search/index.ts
  types/api/files.d.ts
  types/api/search.d.ts
Labels: 2: Dev Review, release-note

#6454 [Gekidou MM-44927] Add Recent Searches Component
  app/actions/local/team.ts
  app/components/loading/index.tsx
  app/components/post_with_channel_info/channel_info/channel_info.tsx
  app/queries/servers/team.ts
  app/screens/home/search/modifiers/index.tsx
  app/screens/home/search/recent_searches/index.tsx
  app/screens/home/search/recent_searches/recent_item.tsx
  app/screens/home/search/recent_searches/recent_searches.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
  app/utils/file/index.ts
Labels: 2: Dev Review, release-note

#6468 [Gekidou] [Migration] Adds member_count to groups table
  app/database/migration/server/index.ts
  app/database/models/server/group.ts
  app/database/operator/server_data_operator/transformers/group.test.ts
  app/database/operator/server_data_operator/transformers/group.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/group.ts
  app/database/schema/server/test.ts
  types/api/groups.d.ts
  types/database/models/servers/group.d.ts
Labels: 4: Reviews Complete, release-note

#6357 [Gekidou] Saves groups + groupTeams for constrained teams
  app/actions/remote/groups.ts
  app/actions/remote/team.ts
  app/database/operator/server_data_operator/handlers/group.ts
  app/database/operator/server_data_operator/transformers/group.ts
  app/queries/servers/group.ts
  types/api/groups.d.ts
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note

#6474 [Gekidou] Open User avatar in gallery
  app/components/profile_picture/image.tsx
  app/components/profile_picture/index.tsx
  app/screens/gallery/footer/details/index.tsx
  app/screens/gallery/footer/footer.tsx
  app/screens/gallery/lightbox_swipeout/index.tsx
  app/screens/gallery/viewer/index.tsx
  app/screens/user_profile/title/avatar.tsx
  app/screens/user_profile/title/index.tsx
  types/screens/gallery.d.ts
Labels: 4: Reviews Complete, release-note-none

#6473 Gekidou bugs fixes
  app/components/markdown/markdown_latex_block/index.tsx
  app/components/post_draft/post_input/post_input.tsx
  app/context/theme/index.tsx
  app/screens/create_direct_message/user_list.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/latex/index.tsx
  app/screens/settings/display_timezone/display_timezone.tsx
  app/screens/settings/display_timezone_select/index.tsx
  app/screens/settings/display_timezone_select/timezone_row.tsx
  app/screens/user_profile/user_profile.tsx
Labels: 4: Reviews Complete, release-note-none

#6455 [Gekidou MM-44943] Add team picker to the search screen and results screens
  app/actions/remote/search.ts
  app/actions/remote/team.ts
  app/components/markdown/at_mention/at_mention.tsx
  app/components/no_results_with_term/index.tsx
  app/components/team_sidebar/add_team/add_team_slide_up.tsx
  app/components/team_sidebar/add_team/index.tsx
  app/components/team_sidebar/add_team/team_list.tsx
  app/components/team_sidebar/add_team/team_list_item/team_list_item.tsx
  app/components/team_sidebar/team_list/team_item/team_icon.tsx
  app/screens/home/search/modifiers/index.tsx
  app/screens/home/search/recent_searches/index.tsx
  app/screens/home/search/recent_searches/recent_searches.tsx
  app/screens/home/search/results/filter.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/header_button.tsx
  app/screens/home/search/search.tsx
  app/screens/home/search/team_picker_icon/index.ts
  app/screens/home/search/team_picker_icon/search_team_slideup.tsx
  app/screens/home/search/team_picker_icon/team_picker_icon.tsx
  app/screens/navigation.ts
  app/screens/select_team/team_list.tsx
  app/screens/user_profile/title/index.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, 2: UX Review, release-note

#6477 Gekidou - Fix recent item component
  app/screens/home/search/recent_searches/recent_item.tsx
Labels: 2: Dev Review, release-note-none

#6478 [Gekidou] Bump app build number to 413
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#6469 Add minor fixes and performance improvements on channel switch
  app/actions/remote/channel.ts
  app/components/autocomplete/at_mention/index.ts
  app/components/channel_actions/set_header_box/index.ts
  app/components/markdown/at_mention/at_mention.tsx
  app/components/post_draft/post_input/index.ts
  app/components/post_list/combined_user_activity/index.ts
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post/body/reactions/index.ts
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/constants/events.ts
  app/hooks/channel_switch.ts
  app/queries/servers/role.ts
  app/screens/channel/channel.tsx
  app/screens/channel/header/index.ts
  app/screens/find_channels/quick_options/index.ts
  app/screens/home/channel_list/categories_list/header/index.ts
  app/screens/post_options/index.ts
Labels: 4: Reviews Complete, release-note

#6479 MM-44102 - Fix for: Crash on peer destroyed error
  app/products/calls/connection.ts
Labels: 4: Reviews Complete, release-note

#6488 Detox/E2E: Fix broken iOS e2e tests in Gekidou
  detox/e2e/support/server_api/default_config.json
  detox/e2e/test/autocomplete/channel_mention.e2e.ts
  detox/e2e/test/channels/archive_channel.e2e.ts
  detox/e2e/test/channels/browse_channels.e2e.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/channels/find_channels.e2e.ts
  detox/e2e/test/messaging/markdown_latex.e2e.ts
  detox/e2e/test/server_login/server_list.e2e.ts
  detox/e2e/test/smoke_test/channels.e2e.ts
  detox/e2e/test/smoke_test/server_login.e2e.ts
  detox/e2e/test/smoke_test/threads.e2e.ts
  detox/e2e/test/threads/follow_and_unfollow_thread.e2e.ts
  detox/e2e/test/threads/global_threads.e2e.ts
  detox/e2e/test/threads/mark_thread_as_read_and_unread.e2e.ts
  detox/e2e/test/threads/open_thread_in_channel.e2e.ts
  detox/e2e/test/threads/reply_to_thread.e2e.ts
  detox/e2e/test/threads/save_and_unsave_thread.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6487 Detox/E2E: Channel Info and Quick Actions e2e tests in Gekidou
  app/components/channel_actions/channel_actions.tsx
  app/components/channel_actions/favorite_box/favorite_box.tsx
  app/components/channel_actions/mute_box/mute_box.tsx
  app/components/post_draft/archived/index.tsx
  app/components/toast/index.tsx
  app/screens/channel/channel_post_list/intro/options/index.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/quick_actions/index.tsx
  app/screens/channel_info/destructive_options/archive/archive.tsx
  detox/e2e/support/server_api/default_config.json
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/support/ui/component/post_draft.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/channel_info.ts
  detox/e2e/support/ui/screen/create_or_edit_channel.ts
  detox/e2e/test/autocomplete/channel_mention.e2e.ts
  detox/e2e/test/channels/archive_channel.e2e.ts
  detox/e2e/test/channels/browse_channels.e2e.ts
  detox/e2e/test/channels/channel_info.e2e.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/channels/channel_post_list.e2e.ts
  detox/e2e/test/channels/create_channel_and_edit_channel_header.e2e.ts
  detox/e2e/test/channels/create_direct_message.e2e.ts
  detox/e2e/test/channels/favorite_and_unfavorite_channel.e2e.ts
  detox/e2e/test/channels/find_channels.e2e.ts
  detox/e2e/test/channels/leave_channel.e2e.ts
  detox/e2e/test/channels/mute_and_unmute_channel.e2e.ts
  detox/e2e/test/messaging/emojis_and_reactions.e2e.ts
  detox/e2e/test/messaging/markdown_latex.e2e.ts
  detox/e2e/test/server_login/server_list.e2e.ts
  detox/e2e/test/smoke_test/channels.e2e.ts
  detox/e2e/test/smoke_test/server_login.e2e.ts
  detox/e2e/test/smoke_test/threads.e2e.ts
  detox/e2e/test/threads/follow_and_unfollow_thread.e2e.ts
  detox/e2e/test/threads/global_threads.e2e.ts
  detox/e2e/test/threads/mark_thread_as_read_and_unread.e2e.ts
  detox/e2e/test/threads/open_thread_in_channel.e2e.ts
  detox/e2e/test/threads/reply_to_thread.e2e.ts
  detox/e2e/test/threads/save_and_unsave_thread.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6499 [Gekidou] Fix rounding numbers with different locale
  package-lock.json
Labels: 2: Dev Review, release-note-none

#6489 [Gekidou MM-40089 MM-39318] CRT New Messages Line
  app/actions/local/thread.ts
  app/actions/remote/thread.ts
  app/actions/websocket/threads.ts
  app/components/post_list/more_messages/index.ts
  app/components/post_list/more_messages/more_messages.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/post_list.tsx
  app/init/push_notifications.ts
  app/screens/thread/thread.tsx
  app/screens/thread/thread_post_list/index.ts
  app/screens/thread/thread_post_list/thread_post_list.tsx
  app/store/ephemeral_store.ts
  types/api/threads.d.ts
Labels: 4: Reviews Complete, release-note-none

#6494 [Gekidou MM-40096] Permalink view for replies when CRT is enabled
  app/actions/remote/post.ts
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/post_list.tsx
  app/screens/permalink/index.ts
  app/screens/permalink/permalink.tsx
Labels: 4: Reviews Complete, release-note-none

#6500 [Gekidou] - New Messages banner condition fix for the channel screen
  app/components/post_list/more_messages/more_messages.tsx
Labels: 4: Reviews Complete, release-note-none

#6501 [Gekidou] Bump app build number to 414
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6504 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: release-note-none, kind/chore

#6497 [MM-43838] Calls: WebSocket reconnection support
  app/products/calls/connection.ts
  app/products/calls/websocket.ts
Labels: 4: Reviews Complete, release-note

#6507 Translations update from Mattermost Weblate
  assets/base/i18n/fr.json
Labels: release-note-none, Do Not Merge/Mattermod

#6509 Update README to point to gekidou
  README.md
Labels: 4: Reviews Complete, release-note-none

#6508 importing the translated strings from v1, removing obsolete translated strings
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fa.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#6513 [Gekidou] RN patch
  app/components/post_list/config.ts
  patches/react-native+0.68.2.patch
Labels: 2: Dev Review, release-note-none

#6517 Add observeWithColumns where needed in CombinedUserActivity Post
  app/components/post_list/combined_user_activity/index.ts
Labels: 4: Reviews Complete, release-note

#6512 [Gekidou] gallery footer and video
  app/components/post_draft/typing/index.tsx
  app/screens/gallery/footer/copy_public_link/index.tsx
  app/screens/gallery/footer/download_with_action/index.tsx
  app/screens/gallery/video_renderer/index.tsx
Labels: 2: Dev Review, release-note-none

#6491 MM-45221 - Gekidou Settings fixes - part 2
  app/components/menu_item/__snapshots__/index.test.tsx.snap
  app/components/menu_item/index.tsx
  app/components/option_item/index.tsx
  app/components/option_item/radio_item.tsx
  app/screens/about/index.tsx
  app/screens/index.tsx
  app/screens/settings/about/about.tsx
  app/screens/settings/about/index.tsx
  app/screens/settings/about/learn_more.tsx
  app/screens/settings/about/subtitle.tsx
  app/screens/settings/about/title.tsx
  app/screens/settings/about/tos_privacy.tsx
  app/screens/settings/advanced/index.tsx
  app/screens/settings/display/display.tsx
  app/screens/settings/display_clock/display_clock.tsx
  app/screens/settings/display_theme/custom_theme.tsx
  app/screens/settings/display_theme/display_theme.tsx
  app/screens/settings/display_theme/theme_tiles.tsx
  app/screens/settings/display_timezone/display_timezone.tsx
  app/screens/settings/display_timezone_select/index.tsx
  app/screens/settings/display_timezone_select/timezone_row.tsx
  app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
  app/screens/settings/notification_mention/mention_settings.tsx
  app/screens/settings/notification_push/notification_push.tsx
  app/screens/settings/notification_push/push_send.tsx
  app/screens/settings/notification_push/push_status.tsx
  app/screens/settings/notification_push/push_thread.tsx
  app/screens/settings/setting_block.tsx
  app/screens/settings/setting_container.tsx
  app/screens/settings/setting_option.tsx
  app/screens/settings/setting_row_label.tsx
  app/screens/settings/settings.tsx
  app/screens/settings/settings_separator.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, 2: UX Review, release-note-none

#6485 [Gekidou] Get theme from useTheme
  app/components/files/document_file.tsx
  app/components/files/file.tsx
  app/components/files/file_info.tsx
  app/components/files/files.tsx
  app/components/files/image_file_overlay.tsx
  app/components/post_list/date_separator/index.tsx
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post_list.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/results/results.tsx
  app/screens/pinned_messages/pinned_messages.tsx
Labels: 4: Reviews Complete, release-note

#6515 Detox/E2E: Channel Info Unarchive e2e tests in Gekidou
  detox/e2e/test/channels/unarchive_channel.e2e.ts
  env.d.ts
Labels: 4: Reviews Complete, release-note-none

#6484 [Gekidou MM-45792] Remove recent searches title if there are no recent searches for the team.
  app/screens/home/search/initial/index.tsx
  app/screens/home/search/initial/initial.tsx
  app/screens/home/search/initial/modifiers/index.tsx
  app/screens/home/search/initial/modifiers/modifier.tsx
  app/screens/home/search/initial/modifiers/show_more.tsx
  app/screens/home/search/initial/recent_searches/index.tsx
  app/screens/home/search/initial/recent_searches/recent_item.tsx
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, 2: UX Review, release-note

#6518 Gekidou moment locales
  app/i18n/index.ts
Labels: 3: QA Review, release-note-none

#6519 Remove unused INDICATOR_BAR_HEIGHT
  app/components/post_list/config.ts
  app/constants/view.ts
Labels: 4: Reviews Complete, release-note-none

#6490 MM-45744 - Calls mobile: Implement banner spacing
  app/components/post_list/more_messages/more_messages.tsx
  app/components/post_list/post_list.tsx
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/screens/channel/channel.tsx
  app/screens/channel/channel_post_list/channel_post_list.tsx
Labels: 4: Reviews Complete, release-note-none

#6024 Graph QL POC
  app/actions/local/group.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/websocket/index.ts
  app/client/graphQL/constants.ts
  app/client/graphQL/entry.ts
  app/components/custom_status/custom_status_emoji.test.tsx
  app/components/profile_picture/image.tsx
  app/constants/custom_status.ts
  app/constants/graphql.ts
  app/constants/index.ts
  app/database/operator/server_data_operator/transformers/user.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.ts
  app/screens/custom_status/components/clear_after.tsx
  app/screens/custom_status/components/custom_status_suggestion.tsx
  app/screens/custom_status/components/custom_status_suggestions.tsx
  app/screens/custom_status/index.tsx
  app/screens/custom_status_clear_after/components/clear_after_menu_item.tsx
  app/screens/custom_status_clear_after/index.tsx
  app/utils/graphql.ts
  app/utils/user/index.ts
  types/api/config.d.ts
  types/api/graphql.d.ts
  types/api/users.d.ts
Labels: 4: Reviews Complete, release-note-none

#6502 MM-45745 - Calls channel info screen options
  app/actions/websocket/index.ts
  app/components/channel_actions/channel_actions.tsx
  app/components/channel_actions/copy_channel_link_option/copy_channel_link_option.tsx
  app/components/channel_actions/copy_channel_link_option/index.ts
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/index.ts
  app/components/option_box/index.tsx
  app/constants/screens.ts
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/actions/index.ts
  app/products/calls/actions/permissions.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/components/channel_info_enable_calls/index.tsx
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/products/calls/components/channel_info_start/index.ts
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/components/current_call_bar/index.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/components/leave_and_join_alert.tsx
  app/products/calls/connection/connection.ts
  app/products/calls/connection/websocket_client.ts
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/hooks.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/screens/call_screen/index.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/state/calls_config.ts
  app/products/calls/state/calls_state.ts
  app/products/calls/state/channels_with_calls.ts
  app/products/calls/state/current_call.ts
  app/products/calls/state/index.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  app/queries/servers/user.ts
  app/screens/channel/channel.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/quick_actions/index.tsx
  app/screens/channel/index.tsx
  app/screens/channel_info/channel_info.tsx
  app/screens/channel_info/index.ts
  app/screens/channel_info/options/index.tsx
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#6324 Accept text shared with image on Android
  android/app/src/main/java/com/mattermost/share/ShareModule.java
Labels: 4: Reviews Complete, release-note, Contributor

#6523 [Gekidou] Bump app build number to 415
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#6358 [Gekidou] Saves groups + group-channel for constrained channels
  app/actions/remote/channel.ts
  app/actions/remote/groups.ts
  app/database/operator/server_data_operator/handlers/group.ts
  app/database/operator/server_data_operator/transformers/group.ts
  app/queries/servers/group.ts
  types/api/groups.d.ts
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note

#6460 [Gekidou] Autocomplete Group Member Count
  app/actions/remote/groups.ts
  app/client/rest/groups.ts
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/at_mention_group/at_mention_group.tsx
Labels: 2: Dev Review, release-note
