Repository mattermost/mattermost-mobile, pull requests merged in 2022-12, with the labels that each got.

#6808 Fix categories where a previously deleted category was not removed
  app/actions/local/category.ts
  app/actions/remote/retry.ts
  app/actions/remote/team.ts
  app/actions/websocket/teams.ts
  app/queries/servers/categories.ts
  app/queries/servers/entry.ts
Labels: 2: Dev Review, release-note-none

#6809 update turbo-mailer
  android/app/src/main/res/xml/provider_paths.xml
  app/screens/settings/report_problem/report_problem.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#6811 Fix Android edit profile keyboard aware scroll view
  app/screens/edit_profile/edit_profile.tsx
Labels: 4: Reviews Complete, release-note-none

#6806 New User List for Integration selector
  app/components/server_user_list/index.tsx
  app/screens/integration_selector/custom_list/index.test.tsx
  app/screens/integration_selector/custom_list/index.tsx
  app/screens/integration_selector/index.ts
  app/screens/integration_selector/integration_selector.tsx
Labels: release-note

#6629 Required changes to the CI automation for e2e-testing
  .circleci/config.yml
  fastlane/Fastfile
Labels: 4: Reviews Complete, release-note

#6810 Fix the color for no results when there are no more channels to join
  app/screens/browse_channels/channel_list.tsx
  app/screens/create_direct_message/create_direct_message.tsx
Labels: 4: Reviews Complete, release-note-none

#6815 Start spinner on websocket reconnect
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/websocket/index.ts
Labels: 4: Reviews Complete, release-note

#6798 Add connection banner
  app/components/connection_banner/connection_banner.tsx
  app/components/connection_banner/index.ts
  app/managers/websocket_manager.ts
  app/queries/servers/system.ts
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/websocket/index.ts
  app/screens/home/channel_list/servers/servers_list/server_item/websocket/websocket.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#6813 [MM-48547] Fix potential crash by accessing the team directly from another model
  app/actions/local/team.ts
  app/components/post_with_channel_info/channel_info/index.ts
  app/components/team_sidebar/team_list/team_item/index.ts
Labels: 4: Reviews Complete, release-note-none

#6814 MM-48753 - Calls: GA requirements
  app/actions/remote/channel.ts
  app/products/calls/actions/calls.ts
  app/products/calls/alerts.ts
  app/products/calls/observers/index.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  app/screens/channel/channel.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/index.ts
  app/screens/channel/index.tsx
  app/screens/channel_info/channel_info.tsx
  app/screens/channel_info/index.ts
Labels: 4: Reviews Complete, release-note

#6699 [Gekidou MM-47652] Add Create DM Add Bottom Panel
  app/components/selected_users/index.tsx
  app/components/selected_users/selected_user.tsx
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/components/user_list/index.tsx
  app/components/user_list_row/index.tsx
  app/hooks/device.ts
  app/screens/bottom_sheet/button.tsx
  app/screens/create_direct_message/create_direct_message.tsx
  app/screens/create_direct_message/selected_users/index.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, 2: UX Review, release-note

#6819 MM-48753 - Calls: New GA cloud limits
  app/products/calls/alerts.ts
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/products/calls/components/channel_info_start/index.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/observers/index.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note-none

#6820 [Gekidou] Bump app build number to 441
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6821 Create DM/GM Screen - fix extra space in selected users bottom panel
  app/components/selected_users/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6824 fix Mark as unread a post on non-crt
  app/screens/post_options/options/mark_unread_option/index.ts
  app/screens/post_options/options/mark_unread_option/mark_unread_option.tsx
Labels: 4: Reviews Complete, release-note-none

#6823 Update icon badge on Notification
  app/screens/home/tab_bar/home.tsx
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, release-note-none

#6822 Refactor how keyboard tracking is resumed & paused
  app/constants/events.ts
  app/hooks/keyboard_tracking.ts
  app/init/app.ts
  app/screens/channel/channel.tsx
  app/screens/find_channels/index.tsx
  app/screens/navigation.ts
  app/screens/thread/thread.tsx
Labels: 4: Reviews Complete, release-note-none

#6826 Fix multiselect on users list integration selector
  app/components/server_user_list/index.tsx
  app/screens/integration_selector/integration_selector.tsx
Labels: release-note, kind/bug

#6832 Fix fastlane simulator lane
  fastlane/Fastfile
Labels: 4: Reviews Complete, release-note-none

#6835 Fix inline code blocks in thread preview
  app/components/markdown/markdown.tsx
  app/components/post_list/post/body/message/message.tsx
  app/components/remove_markdown/index.tsx
  app/screens/global_threads/threads_list/thread/thread.tsx
  app/utils/markdown/index.ts
Labels: 2: Dev Review, release-note-none

#6834 set mentionHighlightBg background for mention keywords
  app/components/markdown/markdown.tsx
Labels: 4: Reviews Complete, release-note-none

#6837 Close autocomplete when search input is not in focus
  app/screens/home/search/search.tsx
Labels: release-note-none

#6836 center highlighted post in permalink view
  app/components/post_list/post_list.tsx
Labels: 4: Reviews Complete, release-note-none

#6828 Place cursor position in between the phrase modifier
  app/components/search/index.tsx
  app/screens/home/search/initial/initial.tsx
  app/screens/home/search/initial/modifiers/index.tsx
  app/screens/home/search/initial/modifiers/modifier.tsx
  app/screens/home/search/search.tsx
  patches/react-native-elements+3.4.2.patch
Labels: 3: QA Review, release-note-none

#6841 [MM-47516] Persist globalThreadsTab to System Table
  app/actions/local/systems.ts
  app/constants/database.ts
  app/queries/servers/system.ts
  app/screens/global_threads/global_threads.tsx
  app/screens/global_threads/index.tsx
Labels: 4: Reviews Complete, release-note

#6818 Improve entry logic to manage user interaction while fetching
  app/actions/remote/channel.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/team.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/actions/websocket/teams.ts
Labels: 4: Reviews Complete, release-note

#6842 Refactor NavigationStore
  app/actions/remote/entry/common.ts
  app/actions/websocket/posts.ts
  app/components/option_item/index.tsx
  app/components/post_draft/post_input/post_input.tsx
  app/constants/navigation.ts
  app/constants/screens.ts
  app/hooks/android_back_handler.ts
  app/hooks/keyboard_tracking.ts
  app/init/app.ts
  app/init/push_notifications.ts
  app/products/calls/alerts.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/screens/channel/channel.tsx
  app/screens/custom_status/index.tsx
  app/screens/custom_status_clear_after/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/index.tsx
  app/screens/navigation.ts
  app/store/navigation_store.ts
  app/utils/theme/index.ts
Labels: 4: Reviews Complete, release-note-none

#6840 update dependencies
  android/build.gradle
  detox/package-lock.json
  detox/package.json
  fastlane/Gemfile.lock
  ios/Gekidou/Package.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Channels.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Users.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database.swift
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+9.3.7.patch
  patches/react-native+0.70.6.patch
  patches/react-native-navigation+7.30.3.patch
  patches/react-native-reanimated+2.13.0.patch
  patches/react-native-svg+13.6.0.patch
Labels: 4: Reviews Complete, release-note-none

#6843 V2 unsigned build fix for ios
  fastlane/Fastfile
Labels: release-note-none

#6850 MM-48949 - Calls: Displayname not showing correctly in call screen
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
Labels: 4: Reviews Complete, release-note-none

#6851 MM-48664 - Calls: Profiles cut off sometimes
  app/products/calls/screens/call_screen/call_screen.tsx
Labels: 4: Reviews Complete, release-note-none

#6848 [MM-48855] Remove CRT feature flag from 7.6
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/queries/servers/thread.ts
  app/utils/thread/index.ts
Labels: 4: Reviews Complete, release-note-none

#6844 [MM-48926] Fetch new thread posts on websocket reconnect
  app/actions/local/thread.ts
  app/actions/remote/entry/common.ts
  app/actions/websocket/index.ts
  app/queries/servers/post.ts
  app/screens/global_threads/threads_list/index.ts
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note-none

#6856 Fix foldable devices by not allowing tablet mode on android
  app/constants/device.ts
  app/managers/analytics.ts
  app/screens/bottom_sheet/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/tab_bar/index.tsx
Labels: 4: Reviews Complete, release-note

#6833 [MM-48192, MM-48279] Search - don't reset file filter when a user changes teams.
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, release-note

#6855 Fix issues when removing a user from a team
  app/actions/remote/channel.ts
  app/actions/remote/team.ts
  app/actions/websocket/channel.ts
  app/components/team_sidebar/team_list/team_item/team_item.tsx
  app/queries/servers/channel.ts
  app/queries/servers/team.ts
Labels: 4: Reviews Complete, release-note

#6852 [MM-48328] Use the width as a dependency instead of dimensions reference
  app/screens/home/search/results/results.tsx
Labels: 4: Reviews Complete, release-note

#6854 Combine fastlane for iOS unsigned and simulator and enable build of iOS simulator both in release and PR
  detox/.detoxrc.json
  detox/package.json
  fastlane/Fastfile
Labels: 4: Reviews Complete, release-note-none

#6859 Fix ios keyboard tracking and profile status theme
  app/components/profile_picture/status.tsx
  app/hooks/keyboard_tracking.ts
Labels: 4: Reviews Complete, release-note-none

#6861 Fix caret position on search phrase
  app/screens/home/search/initial/modifiers/modifier.tsx
Labels: 2: Dev Review, release-note-none

#6862 [Gekidou] Bump app build number to 443
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6864 Detox/E2E: Fix android detox build and upgrade simulator to iPhone 14
  android/app/src/androidTest/java/com/mattermost/rnbeta/DetoxTest.java
  detox/.detoxrc.json
Labels: 4: Reviews Complete, release-note-none

#6868 Improve cold start
  app/components/emoji/emoji.tsx
  app/components/emoji/index.tsx
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_code_block/index.tsx
  app/components/syntax_highlight/index.tsx
  types/components/emoji.ts
  types/components/syntax_highlight.ts
Labels: 4: Reviews Complete, release-note-none

#6866 standardize user-agent
  NOTICE.txt
  app/managers/network_manager.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  test/setup.ts
Labels: 2: Dev Review, release-note-none

#6870 remove unused scripts from package.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#6874 Resume keyboard tracking on mount
  app/hooks/keyboard_tracking.ts
Labels: 2: Dev Review, release-note-none

#6876 [Gekidou] Bump app build number to 444
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, release-note-none

#6875 Fix message id
  app/products/calls/screens/call_screen/call_screen.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#6865 [MM-47483] Activity Indicator while loading thread posts
  app/actions/remote/post.ts
  app/components/post_list/post_list.tsx
  app/components/post_list/thread_overview/thread_overview.test.tsx
  app/components/post_list/thread_overview/thread_overview.tsx
  app/hooks/fetching_thread.ts
  app/screens/thread/thread_post_list/thread_post_list.tsx
  app/store/fetching_thread_store.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6796 Fix MM46418
  app/queries/servers/user.ts
Labels: 2: Dev Review, release-note

#6872 Show loading only when team channels are being loaded
  app/actions/remote/channel.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/post.ts
  app/actions/remote/team.ts
  app/actions/websocket/index.ts
  app/actions/websocket/teams.ts
  app/constants/events.ts
  app/hooks/teams_loading.ts
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/error.tsx
  app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
  app/screens/home/channel_list/categories_list/load_channels_error/load_channel_error.tsx
  app/screens/home/channel_list/categories_list/load_teams_error/index.tsx
  app/screens/navigation.ts
  app/store/team_load_store.ts
Labels: 4: Reviews Complete, release-note

#6871 Restyle video playback error
  app/components/files/files.tsx
  app/components/files/video_file.tsx
  app/screens/gallery/document_renderer/document_renderer.tsx
  app/screens/gallery/footer/download_with_action/index.tsx
  app/screens/gallery/video_renderer/error.tsx
  app/screens/gallery/video_renderer/index.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, 2: UX Review, release-note-none

#6879 Fix terms of service
  app/actions/remote/terms_of_service.ts
  app/database/operator/server_data_operator/transformers/user.ts
  app/queries/servers/terms_of_service.ts
  app/screens/home/channel_list/index.ts
  app/screens/terms_of_service/index.ts
  app/screens/terms_of_service/terms_of_service.tsx
Labels: 4: Reviews Complete, release-note

#6881 Do not show favorites category if it only contain archived channels
  app/database/models/server/category.ts
  app/screens/home/channel_list/categories_list/categories/header/index.ts
  types/database/models/servers/category.ts
Labels: 4: Reviews Complete, release-note-none

#6885 iOS notifications badge and posts in channel/thread
  ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Posts.swift
Labels: 4: Reviews Complete, release-note-none

#6887 Badges should include thread mentions from the undeleted channels
  app/queries/servers/thread.ts
Labels: 4: Reviews Complete, release-note-none

#6880 MM-49219: fixes post priority
  app/components/post_draft/draft_input/index.tsx
  app/components/post_draft/quick_actions/post_priority_action/index.tsx
  app/components/post_draft/quick_actions/quick_actions.tsx
  app/components/post_draft/send_handler/send_handler.tsx
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/post.tsx
  app/components/post_priority/post_priority_label.tsx
  app/components/post_priority/post_priority_picker/index.tsx
  types/api/posts.d.ts
Labels: 4: Reviews Complete, release-note

#6889 Trigger tab bar animation earlier
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note-none

#6890 Fix server unreachable message showing too often
  app/actions/websocket/index.ts
  app/components/connection_banner/connection_banner.tsx
  app/components/connection_banner/index.ts
  app/managers/websocket_manager.ts
  app/screens/home/channel_list/servers/servers_list/server_item/websocket/index.ts
  app/screens/home/channel_list/servers/servers_list/server_item/websocket/websocket.tsx
  types/global/websocket.d.ts
Labels: 4: Reviews Complete, release-note

#6895 use correct syntax highlight styles for github code theme
  app/components/syntax_highlight/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6830 Sentry fixes
  app/init/push_notifications.ts
  app/screens/sso/sso_with_redirect_url.tsx
  app/utils/error_handling.ts
  app/utils/general/index.ts
  app/utils/sentry.ts
  fastlane/Fastfile
  ios/ErrorReporting/Sentry.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/MattermostShare/Info.plist
  ios/MattermostShare/ShareViewController.swift
  ios/NotificationService/Info.plist
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, release-note-none

#6893 Perform search when hashtag is pressed
  app/components/markdown/hashtag/index.tsx
  app/screens/home/search/search.tsx
Labels: release-note-none

#6825 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none, kind/chore

#6888 Show the current channel when category is collapsed on tablets
  app/queries/servers/system.ts
  app/screens/home/channel_list/categories_list/categories/body/index.ts
Labels: 2: Dev Review, release-note-none

#6896 Detox/E2E: Upgrade detox android emulator to api 31
  .gitignore
  detox/.detoxrc.json
  detox/android_emulator/config.ini
  detox/create_android_emulator.sh
Labels: 4: Reviews Complete, release-note-none

#6901 Allow to select text from tables on full view
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_table_cell/index.tsx
  app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap
  app/components/syntax_highlight/renderer.tsx
  app/screens/code/index.tsx
Labels: 4: Reviews Complete, release-note

#6902 Fix race condition for keyboard tracker
  app/hooks/keyboard_tracking.ts
Labels: 4: Reviews Complete, release-note-none

#6873 Detox/E2E Maintenance: Fix broken iOS e2e tests
  app/components/selected_users/index.tsx
  app/components/tutorial_highlight/long_press.tsx
  app/components/tutorial_highlight/swipe_left.tsx
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/screens/channel_info/options/index.tsx
  app/screens/create_direct_message/create_direct_message.tsx
  app/screens/settings/advanced/index.tsx
  detox/e2e/support/ui/screen/browse_channels.ts
  detox/e2e/support/ui/screen/channel_info.ts
  detox/e2e/support/ui/screen/channel_list.ts
  detox/e2e/support/ui/screen/create_direct_message.ts
  detox/e2e/support/ui/screen/create_or_edit_channel.ts
  detox/e2e/support/ui/screen/login.ts
  detox/e2e/support/ui/screen/server_list.ts
  detox/e2e/test/autocomplete/create_channel.e2e.ts
  detox/e2e/test/autocomplete/edit_channel.e2e.ts
  detox/e2e/test/channels/channel_info.e2e.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/channels/create_direct_message.e2e.ts
  detox/e2e/test/channels/favorite_and_unfavorite_channel.e2e.ts
  detox/e2e/test/channels/leave_channel.e2e.ts
  detox/e2e/test/channels/mute_and_unmute_channel.e2e.ts
  detox/e2e/test/messaging/save_and_unsave_message.e2e.ts
  detox/e2e/test/server_login/connect_to_server.e2e.ts
  detox/e2e/test/server_login/server_list.e2e.ts
  detox/e2e/test/smoke_test/messaging.e2e.ts
  detox/e2e/test/smoke_test/server_login.e2e.ts
  detox/e2e/test/smoke_test/threads.e2e.ts
  detox/e2e/test/teams/invite_people.e2e.ts
  detox/e2e/test/threads/mark_thread_as_read_and_unread.e2e.ts
Labels: release-note-none

#6634 [Gekidou MM-46365] fix reaction bar space and update bottom sheet styles
  app/components/option_item/index.tsx
  app/components/post_draft/quick_actions/camera_quick_action/camera_type.tsx
  app/components/post_draft/quick_actions/camera_quick_action/index.tsx
  app/components/post_priority/post_priority_picker/index.tsx
  app/components/user_avatars_stack/index.tsx
  app/components/user_item/user_item.tsx
  app/constants/reaction_picker.ts
  app/screens/bottom_sheet/button.tsx
  app/screens/bottom_sheet/content.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/custom_status/components/custom_status_input.tsx
  app/screens/custom_status/index.tsx
  app/screens/edit_profile/components/profile_image_picker.tsx
  app/screens/home/account/components/options/custom_status/custom_label/custom_status_text.tsx
  app/screens/home/account/components/options/custom_status/index.tsx
  app/screens/home/account/components/options/user_presence/index.tsx
  app/screens/home/channel_list/servers/servers_list/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/home/search/results/filter.tsx
  app/screens/post_options/reaction_bar/pick_reaction/index.tsx
  app/screens/post_options/reaction_bar/reaction/index.tsx
  app/screens/post_options/reaction_bar/reaction_bar.tsx
  app/screens/reactions/emoji_bar/index.tsx
  app/screens/reactions/reactors_list/reactor/reactor.tsx
  app/screens/thread_options/thread_options.tsx
  assets/base/i18n/en.json
Labels: release-note

#6900 Align latex with text
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_latex_inline/index.tsx
  app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap
  app/screens/permalink/permalink_error.tsx
  app/utils/markdown/index.ts
Labels: 2: Dev Review, 3: QA Review, release-note

#6899 Refactor CustomStatus to functional component
  app/screens/custom_status/custom_status.tsx
  app/screens/custom_status/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6886 update dependencies
  .solidarity
  detox/package-lock.json
  detox/package.json
  fastlane/Gemfile.lock
  ios/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/jail-monkey+2.7.0.patch
  patches/react-native-navigation+7.30.6.patch
  scripts/postinstall.sh
  scripts/preinstall.sh
Labels: 4: Reviews Complete, release-note-none

#6612 [MM-46562] Add show/hide password function for login screen
  app/components/floating_text_input_label/index.tsx
  app/components/floating_text_input_label/utils.ts
  app/screens/login/form.tsx
  app/screens/settings/notification_mention/mention_settings.tsx
Labels: 4: Reviews Complete, release-note, Contributor, kind/feature

#6894 Fix webhook picture on notifications
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
Labels: 3: QA Review, release-note

#6904 Notifications profile images
  app/actions/remote/notifications.ts
  app/actions/websocket/index.ts
  app/store/ephemeral_store.ts
  ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift
  ios/Mattermost/Info.plist
  ios/Mattermost/Mattermost.entitlements
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, release-note-none

#6905 Bump app build number to 445
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6910 Remove Bundler check from Solidarity
  .solidarity
Labels: 2: Dev Review, release-note-none

#6911 Revert "Align latex with text (#6900)"
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_latex_inline/index.tsx
  app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap
  app/screens/permalink/permalink_error.tsx
  app/utils/markdown/index.ts
Labels: 4: Reviews Complete, release-note-none

#6912 Translations update from Mattermost Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fa.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#6914 Bump app build number to 446
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6913 Do not display the favorites category when it has no channels
  app/database/models/server/category.ts
  app/screens/home/channel_list/categories_list/categories/header/index.ts
  types/database/models/servers/category.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#6916 Fix floating input style
  app/components/floating_text_input_label/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6917 Detox/E2E Maintenance: Fix broken iOS e2e tests
  app/screens/settings/report_problem/report_problem.tsx
  detox/e2e/support/ui/screen/settings.ts
  detox/e2e/test/account/custom_status.e2e.ts
  detox/e2e/test/account/settings.e2e.ts
  detox/e2e/test/channels/channel_info.e2e.ts
  detox/e2e/test/channels/channel_post_list.e2e.ts
  detox/e2e/test/smoke_test/account.e2e.ts
Labels: 4: Reviews Complete, release-note-none
