Repository mattermost/mattermost-mobile, pull requests merged in 2022-04, with the labels that each got.

#6115 Fix Detox reporting
  detox/.detoxrc.json
  detox/e2e/config.js
  detox/e2e/config.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#6120 Automated cherry pick of #6107
  app/actions/websocket/index.ts
  app/constants/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/__snapshots__/enable_disable_calls.test.js.snap
  app/products/calls/components/channel_info/calls_channel_info.tsx
  app/products/calls/components/channel_info/enable_disable_calls.tsx
  app/products/calls/components/channel_info/start_call.tsx
  app/products/calls/components/enable_disable_calls.test.js
  app/products/calls/components/start_call/__snapshots__/start_call.test.js.snap
  app/products/calls/components/start_call/index.ts
  app/products/calls/components/start_call/start_call.test.js
  app/products/calls/hooks.ts
  app/products/calls/store/action_types/calls.ts
  app/products/calls/store/actions/calls.test.js
  app/products/calls/store/actions/calls.ts
  app/products/calls/store/reducers/calls.test.js
  app/products/calls/store/reducers/calls.ts
  app/products/calls/store/selectors/calls.test.js
  app/products/calls/store/selectors/calls.ts
  app/products/calls/store/types/calls.ts
  app/screens/channel/channel_base.js
  app/screens/channel/index.js
  app/screens/channel_info/__snapshots__/channel_info.test.js.snap
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6116 Gekidou - removed SlashCommands from the Server database schema
  app/constants/database.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/models/server/index.ts
  app/database/models/server/slash_command.ts
  app/database/models/server/team.ts
  app/database/operator/server_data_operator/handlers/team.test.ts
  app/database/operator/server_data_operator/handlers/team.ts
  app/database/operator/server_data_operator/transformers/team.test.ts
  app/database/operator/server_data_operator/transformers/team.ts
  app/database/operator/utils/general.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/table_schemas/slash_command.ts
  app/database/schema/server/test.ts
  app/queries/servers/team.ts
  types/database/models/servers/team.d.ts
Labels: 4: Reviews Complete, release-note-none

#6117 removed TOS from Server DB schema
  app/constants/database.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/models/server/index.ts
  app/database/models/server/terms_of_service.ts
  app/database/operator/server_data_operator/comparators/index.ts
  app/database/operator/server_data_operator/handlers/index.test.ts
  app/database/operator/server_data_operator/handlers/index.ts
  app/database/operator/server_data_operator/transformers/general.test.ts
  app/database/operator/server_data_operator/transformers/general.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/table_schemas/terms_of_service.ts
  app/database/schema/server/test.ts
Labels: 4: Reviews Complete, release-note-none

#6113 [Gekidou] Add performance and code improvements around post_list
  app/components/autocomplete/at_mention/index.ts
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/channel_list/header/index.ts
  app/components/channel_list/index.test.tsx
  app/components/post_draft/index.ts
  app/components/post_draft/send_handler/index.ts
  app/components/post_draft/uploads/index.tsx
  app/components/post_list/combined_user_activity/index.ts
  app/components/post_list/index.tsx
  app/components/post_list/post/body/reactions/index.ts
  app/components/post_list/post/index.ts
  app/queries/servers/role.ts
  app/queries/servers/team.ts
  app/screens/post_options/index.ts
  app/utils/role/index.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.m
  ios/Podfile
  ios/Podfile.lock
  patches/react-native+0.67.4.patch
  patches/react-native-reanimated+2.5.0.patch
  types/database/models/servers/channel.d.ts
Labels: 4: Reviews Complete, release-note-none

#6075 [Gekidou MM-41093] CRT - WS Events, Actions, Queries, Thread Follow, Post Query
  app/actions/local/post.ts
  app/actions/local/thread.ts
  app/actions/remote/post.ts
  app/actions/remote/search.ts
  app/actions/remote/thread.ts
  app/actions/websocket/index.ts
  app/actions/websocket/posts.ts
  app/actions/websocket/threads.ts
  app/client/rest/base.ts
  app/client/rest/index.ts
  app/client/rest/posts.ts
  app/client/rest/threads.ts
  app/constants/config.ts
  app/constants/general.ts
  app/constants/index.ts
  app/constants/preferences.ts
  app/constants/screens.ts
  app/database/models/server/thread.ts
  app/database/operator/server_data_operator/handlers/thread.ts
  app/database/operator/server_data_operator/transformers/thread.ts
  app/database/operator/utils/thread.ts
  app/database/schema/server/table_schemas/thread.ts
  app/database/schema/server/test.ts
  app/queries/servers/post.ts
  app/queries/servers/thread.ts
  app/screens/channel/channel_post_list/index.ts
  app/screens/index.tsx
  app/screens/thread/thread.tsx
  app/screens/thread/thread_follow_button/index.ts
  app/screens/thread/thread_follow_button/thread_follow_button.tsx
  app/screens/thread/thread_post_list/index.ts
  app/screens/thread/thread_post_list/thread_post_list.tsx
  app/utils/post/index.ts
  app/utils/thread/index.ts
  assets/base/i18n/en.json
  types/api/channels.d.ts
  types/api/threads.d.ts
  types/api/websocket.d.ts
  types/database/database.d.ts
  types/database/models/servers/thread.d.ts
Labels: release-note-none

#6121 Apply patch for minSdkVersion
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@rudderstack+rudder-sdk-react-native+1.2.1.patch
  patches/@stream-io+flat-list-mvcp+0.10.1.patch
  patches/react-native-hw-keyboard-event+0.0.4.patch
Labels: 4: Reviews Complete, release-note-none

#6038 [Gekidou MM-39728] - Websocket Events - Channels
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/post.ts
  app/actions/remote/retry.ts
  app/actions/remote/search.ts
  app/actions/remote/team.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/actions/websocket/roles.ts
  app/actions/websocket/teams.ts
  app/components/autocomplete/channel_mention_item/channel_mention_item.tsx
  app/components/channel_list/categories/body/category_body.tsx
  app/components/channel_list/categories/body/index.ts
  app/components/navigation_header/header.tsx
  app/constants/categories.ts
  app/constants/index.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/queries/servers/categories.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.ts
  app/queries/servers/post.ts
  app/queries/servers/preference.ts
  app/queries/servers/role.ts
  app/queries/servers/system.ts
  app/queries/servers/team.ts
  app/queries/servers/user.ts
  app/utils/categories.ts
  app/utils/channel/index.ts
  types/database/database.d.ts
Labels: release-note-none

#6123 [Gekidou] ci updates
  .circleci/config.yml
  android/gradle.properties
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
Labels: 4: Reviews Complete, release-note-none

#6127 [Gekidou] Use delta for mark as unread
  app/actions/websocket/posts.ts
Labels: 4: Reviews Complete, release-note-none

#6114 Detox/E2E: Channel List, Browse Channels, Create Direct Message e2e tests in Gekidou
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/channel_list/categories/body/__snapshots__/category_body.test.tsx.snap
  app/components/channel_list/categories/body/category_body.tsx
  app/components/channel_list/categories/body/channel/__snapshots__/channel_list_item.test.tsx.snap
  app/components/channel_list/categories/body/channel/channel_list_item.test.tsx
  app/components/channel_list/categories/body/channel/channel_list_item.tsx
  app/components/channel_list/categories/header/__snapshots__/header.test.tsx.snap
  app/components/channel_list/categories/header/header.tsx
  app/components/channel_list/header/__snapshots__/header.test.tsx.snap
  app/components/channel_list/header/header.tsx
  app/components/channel_list/header/plus_menu/item.tsx
  app/components/channel_list/search/__snapshots__/index.test.tsx.snap
  app/components/channel_list/search/index.tsx
  app/components/channel_list/threads/__snapshots__/index.test.tsx.snap
  app/components/channel_list/threads/index.tsx
  app/components/user_list_row/index.tsx
  app/screens/browse_channels/channel_list.tsx
  app/screens/browse_channels/channel_list_row.tsx
  app/screens/channel/channel.tsx
  app/screens/channel/channel_post_list/intro/direct_channel/direct_channel.tsx
  app/screens/channel/channel_post_list/intro/options/index.tsx
  app/screens/channel/channel_post_list/intro/options/item.tsx
  app/screens/channel/channel_post_list/intro/public_or_private_channel/public_or_private_channel.tsx
  app/screens/channel/channel_post_list/intro/townsquare/index.tsx
  app/screens/create_direct_message/create_direct_message.tsx
  app/screens/create_direct_message/selected_users/index.tsx
  app/screens/create_direct_message/selected_users/selected_user.tsx
  app/screens/create_direct_message/user_list.tsx
  detox/e2e/support/ui/component/index.ts
  detox/e2e/support/ui/component/navigation_header.ts
  detox/e2e/support/ui/component/plus_menu.ts
  detox/e2e/support/ui/screen/browse_channels.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/channel_list.ts
  detox/e2e/support/ui/screen/create_direct_message.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/login.ts
  detox/e2e/support/ui/screen/server.ts
  detox/e2e/test/channels/browse_channels.e2e.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/channels/create_direct_message.e2e.ts
  detox/e2e/test/server_login/connect_to_server.e2e.ts
  detox/e2e/test/server_login/login_by_email.e2e.ts
  detox/e2e/test/server_login/server_list.e2e.ts
  detox/e2e/test/smoke_test/server_login.e2e.ts
  test/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#6132 [Gekidou HOTFIX] fixes saving threads in the DB
  app/actions/local/thread.ts
  app/actions/remote/thread.ts
  app/database/models/server/team.ts
  app/database/models/server/thread.ts
  app/database/models/server/thread_in_team.ts
  app/database/operator/server_data_operator/handlers/thread.test.ts
  app/database/operator/server_data_operator/handlers/thread.ts
  app/database/operator/server_data_operator/handlers/thread_in_team.ts
  app/database/operator/server_data_operator/transformers/thread.ts
  types/api/threads.d.ts
  types/database/database.d.ts
Labels: release-note-none

#6136 [Gekidou] operator handlers improvements
  app/actions/app/global.ts
  app/actions/local/channel.ts
  app/actions/local/thread.ts
  app/actions/remote/channel.ts
  app/actions/remote/custom_emoji.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/post.ts
  app/actions/remote/reactions.ts
  app/actions/remote/role.ts
  app/actions/remote/search.ts
  app/actions/remote/team.ts
  app/actions/remote/user.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/posts.ts
  app/actions/websocket/roles.ts
  app/actions/websocket/teams.ts
  app/database/exceptions/data_operator_exception.ts
  app/database/operator/app_data_operator/index.test.ts
  app/database/operator/app_data_operator/index.ts
  app/database/operator/base_data_operator/index.ts
  app/database/operator/server_data_operator/handlers/category.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/handlers/index.test.ts
  app/database/operator/server_data_operator/handlers/index.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/database/operator/server_data_operator/handlers/posts_in_channel.ts
  app/database/operator/server_data_operator/handlers/posts_in_thread.ts
  app/database/operator/server_data_operator/handlers/reaction.ts
  app/database/operator/server_data_operator/handlers/team.ts
  app/database/operator/server_data_operator/handlers/thread.ts
  app/database/operator/server_data_operator/handlers/thread_in_team.ts
  app/database/operator/server_data_operator/handlers/user.ts
  app/database/operator/utils/post.ts
  app/queries/servers/categories.ts
  app/queries/servers/preference.ts
  app/queries/servers/thread.ts
  app/queries/servers/user.ts
  package-lock.json
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note-none

#6133 Gekidou - Updated App Database Diagrams/Schema/Models
  app/database/schema/app/index.ts
  app/database/schema/app/table_schemas/index.ts
  app/database/schema/app/table_schemas/info.ts
  app/database/schema/app/table_schemas/servers.ts
  app/database/schema/app/test.ts
  docs/database/app_database/app-database-v1.pdf
  docs/database/app_database/app-database-v1.png
  docs/database/app_database/app-database-v1.rtf
  docs/database/app_database/app-database-v1.sql
  docs/database/app_database/app-database.md
Labels: 4: Reviews Complete, release-note-none

#6130 [Gekidou] bug fixes found with e2e tests
  app/components/channel_list/header/plus_menu/index.tsx
  app/components/user_list_row/index.tsx
  app/constants/general.ts
  app/screens/channel/channel_post_list/intro/options/index.tsx
  app/screens/create_direct_message/create_direct_message.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/create_or_edit_channel/create_or_edit_channel.tsx
  app/screens/thread/thread_follow_button/thread_follow_button.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#6119 Gekidou - Updated Server Database Diagrams/Schema/Models
  app/actions/local/category.ts
  app/components/channel_list/categories/body/channel/index.ts
  app/database/models/server/category.ts
  app/database/models/server/channel.ts
  app/database/models/server/my_channel.ts
  app/database/models/server/my_channel_settings.ts
  app/database/models/server/my_team.ts
  app/database/models/server/posts_in_thread.ts
  app/database/models/server/team.ts
  app/database/models/server/team_channel_history.ts
  app/database/models/server/user.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/database/operator/server_data_operator/transformers/post.ts
  app/database/operator/server_data_operator/transformers/user.ts
  app/database/schema/server/table_schemas/category.ts
  app/database/schema/server/table_schemas/custom_emoji.ts
  app/database/schema/server/table_schemas/file.ts
  app/database/schema/server/table_schemas/my_channel.ts
  app/database/schema/server/table_schemas/post.ts
  app/database/schema/server/table_schemas/posts_in_thread.ts
  app/database/schema/server/table_schemas/reaction.ts
  app/database/schema/server/table_schemas/role.ts
  app/database/schema/server/table_schemas/team.ts
  app/database/schema/server/table_schemas/team_search_history.ts
  app/database/schema/server/table_schemas/thread.ts
  app/database/schema/server/table_schemas/thread_in_team.ts
  app/database/schema/server/table_schemas/user.ts
  app/database/schema/server/test.ts
  app/queries/servers/channel.ts
  docs/database/server/server-v1.pdf
  docs/database/server/server-v1.png
  docs/database/server/server-v1.rtf
  docs/database/server/server-v1.sql
  docs/database/server/server.md
  types/database/models/servers/channel.d.ts
  types/database/models/servers/file.d.ts
  types/database/models/servers/my_channel.d.ts
  types/database/models/servers/my_channel_settings.d.ts
Labels: 4: Reviews Complete, release-note-none

#6147 Automated cherry pick of #6145
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6138 [Gekidou] upgrade to RN 68 (old arch)
  .flowconfig
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/rn/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mattermost/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/com/mattermost/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/com/mattermost/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/share/SharePackage.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/settings.gradle
  app/actions/local/channel.ts
  app/components/post_list/post/body/files/document_file.tsx
  app/components/post_list/post/body/files/video_file.tsx
  app/constants/device.ts
  app/context/theme/index.tsx
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/screens/gallery/footer/download_with_action/index.tsx
  app/utils/file/index.ts
  app/utils/theme/index.ts
  detox/package-lock.json
  detox/package.json
  fastlane/Fastfile
  fastlane/Gemfile.lock
  index.ts
  ios/GekidouWrapper.swift
  ios/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.h
  ios/Mattermost/AppDelegate.mm
  ios/Mattermost/Mattermost-Bridging-Header.h
  ios/Mattermost/main.m
  ios/Podfile
  ios/Podfile.lock
  ios/UploadAttachments/UploadAttachments.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  patches/@rudderstack+rudder-sdk-react-native+1.3.0.patch
  patches/expo-video-thumbnails+6.2.0.patch
  patches/react-native+0.68.0.patch
  patches/react-native-device-info+8.7.0.patch
  patches/react-native-reanimated+2.5.0.patch
  patches/react-native-reanimated+2.6.0.patch
  test/setup.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note-none

#6146 Fix floating container using a hook inside the styles
  app/products/calls/components/floating_call_container.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6148 Automated cherry pick of #6146
  app/products/calls/components/floating_call_container.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6149 Bump app build number to 390
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6150 Automated cherry pick of #6149
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6144 Fix add DM screen and some other database related issues
  app/actions/local/category.ts
  app/actions/local/channel.ts
  app/actions/local/draft.ts
  app/actions/local/post.ts
  app/actions/local/team.ts
  app/actions/local/thread.ts
  app/actions/local/user.ts
  app/actions/remote/channel.ts
  app/actions/remote/command.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/post.ts
  app/actions/remote/reactions.ts
  app/actions/remote/retry.ts
  app/actions/remote/team.ts
  app/actions/remote/user.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/constants/websocket.ts
  app/database/operator/base_data_operator/index.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/handlers/index.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.ts
  app/queries/servers/preference.ts
  app/queries/servers/system.ts
  app/queries/servers/team.ts
  app/queries/servers/user.ts
  app/screens/create_direct_message/create_direct_message.tsx
  app/store/ephemeral_store.ts
Labels: 4: Reviews Complete, release-note-none

#6154 [Gekidou] Fix update lastPostAt
  app/actions/local/channel.ts
  app/actions/remote/post.ts
Labels: 2: Dev Review, release-note-none

#6158 Automated cherry pick of #6143
  app/products/calls/connection.ts
  app/products/calls/simple-peer.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  types/modules/react-native-webrtc.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6151 Fix float input label initial position
  app/components/floating_text_input_label/animation_utils.ts
  app/components/floating_text_input_label/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6159 Bump app build number to 391
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6160 Automated cherry pick of #6159
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6126 [Gekidou CRT] thread mention counts
  app/actions/local/thread.ts
  app/actions/remote/post.ts
  app/actions/websocket/posts.ts
  app/components/team_sidebar/team_list/team_item/index.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/subscription/unreads.ts
  app/queries/servers/channel.ts
  app/queries/servers/team.ts
  app/queries/servers/thread.ts
  app/screens/channel/other_mentions_badge/index.tsx
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/home/tab_bar/home.tsx
  types/api/channels.d.ts
Labels: 4: Reviews Complete, release-note-none

#6135 MM-40093 [Gekidou]: adds remote action to sync threads
  app/actions/remote/entry/common.ts
  app/actions/remote/thread.ts
  app/actions/websocket/index.ts
  app/client/rest/threads.ts
  app/queries/servers/thread.ts
  app/utils/thread/index.ts
Labels: 2: Dev Review, release-note-none

#6156 [Gekidou] Code syntax highlight
  app/components/markdown/markdown_code_block/index.tsx
  app/components/syntax_highlight/index.tsx
  app/components/syntax_highlight/renderer.tsx
  app/constants/screens.ts
  app/screens/code/index.tsx
  app/screens/index.tsx
  app/utils/markdown/index.ts
  jest.config.js
  package-lock.json
  package.json
  patches/@types+react-syntax-highlighter+13.5.2.patch
  patches/react-syntax-highlighter+15.5.0.patch
Labels: 4: Reviews Complete, release-note-none

#6161 [Gekidou] Fix bottom sheet initial animation
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/components/post_list/post/body/reactions/reactions.tsx
  app/components/post_list/post/post.tsx
  app/components/post_list/thread_overview/thread_overview.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note-none

#6162 [Gekidou] Fix create DM when searching profile
  app/screens/create_direct_message/create_direct_message.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#6164 [Gekidou] Fix initial Channel list width on iPad
  app/components/channel_list/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6167 Gekidou - Removed redundant getConfig call
  app/queries/servers/thread.ts
Labels: 4: Reviews Complete, release-note-none

#6139 Gekidou CRT - User avatar stack
  app/actions/remote/post.ts
  app/components/user_avatars_stack/index.tsx
  app/components/user_avatars_stack/user_avatar/index.ts
  app/components/user_avatars_stack/user_avatar/user_avatar.tsx
  app/components/user_avatars_stack/users_list/index.tsx
  app/queries/servers/thread.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#6166 [Gekidou] Update bottom sheet style for title and button
  app/components/team_sidebar/add_team/team_list.tsx
  app/components/team_sidebar/add_team/team_list_item/team_list_item.tsx
  app/screens/bottom_sheet/button.tsx
  app/screens/bottom_sheet/content.tsx
Labels: 4: Reviews Complete, release-note-none

#6170 [Gekidou] unreads category section
  app/components/channel_list/categories/categories.tsx
  app/components/channel_list/categories/index.ts
  app/queries/servers/channel.ts
Labels: 2: Dev Review, release-note-none

#6163 Active State for selected Channel
  app/actions/local/channel.test.ts
  app/actions/local/channel.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/team.ts
  app/actions/websocket/index.ts
  app/actions/websocket/posts.ts
  app/components/channel_icon/index.tsx
  app/components/channel_list/categories/body/__snapshots__/category_body.test.tsx.snap
  app/components/channel_list/categories/body/channel/__snapshots__/channel_list_item.test.tsx.snap
  app/components/channel_list/categories/body/channel/channel_list_item.tsx
  app/components/channel_list/categories/categories.tsx
  app/components/channel_list/categories/header/__snapshots__/header.test.tsx.snap
  app/components/channel_list/categories/header/header.tsx
  app/components/channel_list/categories/index.ts
  app/components/channel_list/categories/unreads.test.tsx
  app/components/channel_list/categories/unreads.tsx
  app/components/channel_list/index.tsx
  app/constants/database.ts
  app/queries/servers/system.ts
  app/screens/home/channel_list/channel_list.tsx
Labels: 4: Reviews Complete, release-note

#6169 [Gekidou] bottomSheet snapPoint helper
  app/components/channel_list/header/header.test.tsx
  app/components/channel_list/header/header.tsx
  app/components/channel_list/header/plus_menu/item.tsx
  app/components/channel_list/index.test.tsx
  app/components/markdown/at_mention/at_mention.tsx
  app/components/markdown/markdown_code_block/index.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_link/markdown_link.tsx
  app/components/post_list/post/body/failed/index.tsx
  app/screens/edit_profile/components/profile_image_picker.tsx
  app/screens/home/account/components/options/user_presence/index.tsx
  app/utils/helpers.ts
  test/intl-test-helper.tsx
Labels: 4: Reviews Complete, release-note-none

#6175 [Gekidou] Fix new DM issue
  app/actions/websocket/channel.ts
  app/queries/servers/channel.ts
Labels: 2: Dev Review, release-note-none

#6174 Performance improvements in the area of home and channel switch.
  app/actions/remote/channel.ts
  app/actions/websocket/channel.ts
  app/components/channel_list/categories/body/category_body.test.tsx
  app/components/channel_list/categories/body/category_body.tsx
  app/components/channel_list/categories/body/channel/channel_list_item.test.tsx
  app/components/channel_list/categories/body/channel/channel_list_item.tsx
  app/components/channel_list/categories/body/channel/index.ts
  app/components/channel_list/categories/body/index.ts
  app/components/channel_list/categories/categories.tsx
  app/components/channel_list/categories/index.ts
  app/components/channel_list/categories/unreads/index.ts
  app/components/channel_list/categories/unreads/unreads.test.tsx
  app/components/channel_list/categories/unreads/unreads.tsx
  index.ts
Labels: release-note-none

#6171 [Gekidou] Move managers
  .eslintrc.json
  app/actions/remote/apps.ts
  app/actions/remote/category.ts
  app/actions/remote/channel.ts
  app/actions/remote/command.ts
  app/actions/remote/custom_emoji.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/file.ts
  app/actions/remote/general.ts
  app/actions/remote/groups.ts
  app/actions/remote/post.ts
  app/actions/remote/preference.ts
  app/actions/remote/reactions.ts
  app/actions/remote/retry.ts
  app/actions/remote/role.ts
  app/actions/remote/search.ts
  app/actions/remote/session.ts
  app/actions/remote/systems.ts
  app/actions/remote/team.ts
  app/actions/remote/thread.ts
  app/actions/remote/user.ts
  app/actions/websocket/users.ts
  app/client/rest/base.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_slash_suggestion/app_slash_suggestion.tsx
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/emoji/index.tsx
  app/components/post_draft/draft_handler/draft_handler.tsx
  app/components/post_draft/send_handler/send_handler.tsx
  app/components/post_draft/uploads/index.tsx
  app/components/post_draft/uploads/upload_item/index.tsx
  app/components/post_draft/uploads/upload_item/upload_remove.tsx
  app/components/post_list/post/avatar/avatar.tsx
  app/components/post_list/post/body/files/document_file.tsx
  app/components/profile_picture/image.tsx
  app/components/team_sidebar/team_list/team_item/team_icon.tsx
  app/init/credentials.ts
  app/managers/analytics.ts
  app/managers/draft_upload_manager/index.test.ts
  app/managers/draft_upload_manager/index.ts
  app/managers/global_event_handler.ts
  app/managers/integrations_manager.ts
  app/managers/network_manager.ts
  app/managers/websocket_manager.ts
  app/screens/channel/channel_post_list/intro/direct_channel/group/group.tsx
  app/screens/edit_profile/components/edit_profile_picture.tsx
  app/screens/edit_profile/components/profile_image_picker.tsx
  app/screens/in_app_notification/icon.tsx
  app/screens/server/index.tsx
  app/screens/sso/sso_with_redirect_url.tsx
  babel.config.js
  tsconfig.json
Labels: 4: Reviews Complete, release-note-none

#6176 [Gekidou] Attach device token on App Entry
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/session.ts
  app/queries/app/global.ts
Labels: 4: Reviews Complete, release-note-none

#6177 [Gekidou] optimizations, fix & moved files
  app/components/autocomplete/autocomplete.tsx
  app/components/freeze_screen/index.tsx
  app/components/loading_error/__snapshots__/index.test.tsx.snap
  app/components/loading_error/index.test.tsx
  app/components/loading_error/index.tsx
  app/components/syntax_highlight/renderer.tsx
  app/hooks/freeze.ts
  app/screens/channel/channel.tsx
  app/screens/home/account/account.tsx
  app/screens/home/account/index.ts
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/__snapshots__/category_body.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/category_body.test.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/body/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/channel_item/channel_item.test.tsx
  app/screens/home/channel_list/categories_list/categories/body/channel_item/channel_item.tsx
  app/screens/home/channel_list/categories_list/categories/body/channel_item/index.ts
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/screens/home/channel_list/categories_list/categories/categories.test.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/categories/error.tsx
  app/screens/home/channel_list/categories_list/categories/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/header/header.test.tsx
  app/screens/home/channel_list/categories_list/categories/header/header.tsx
  app/screens/home/channel_list/categories_list/categories/header/index.ts
  app/screens/home/channel_list/categories_list/categories/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/unreads.test.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/unreads.tsx
  app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/header.test.tsx
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/categories_list/header/index.ts
  app/screens/home/channel_list/categories_list/header/plus_menu/index.tsx
  app/screens/home/channel_list/categories_list/header/plus_menu/item.tsx
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/home/channel_list/categories_list/load_channels_error/index.ts
  app/screens/home/channel_list/categories_list/load_channels_error/load_channel_error.tsx
  app/screens/home/channel_list/categories_list/load_teams_error/index.tsx
  app/screens/home/channel_list/categories_list/search/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/search/index.test.tsx
  app/screens/home/channel_list/categories_list/search/index.tsx
  app/screens/home/channel_list/categories_list/threads/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/threads/index.test.tsx
  app/screens/home/channel_list/categories_list/threads/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/index.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/search/index.tsx
  app/screens/thread/thread.tsx
Labels: 4: Reviews Complete, release-note-none

#6173 Detox/E2E: Create Channel and Channel Post List e2e in Gekidou
  app/components/post_draft/send_action/index.tsx
  app/components/post_list/index.tsx
  app/components/section_item/index.tsx
  app/components/team_sidebar/add_team/add_team_slide_up.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/browse_channels/dropdown_slideup.tsx
  app/screens/channel/channel.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/create_or_edit_channel/create_or_edit_channel.tsx
  app/screens/post_options/options/copy_permalink_option/copy_permalink_option.tsx
  app/screens/post_options/options/copy_text_option.tsx
  app/screens/post_options/options/delete_post_option.tsx
  app/screens/post_options/options/edit_option.tsx
  app/screens/post_options/options/follow_option.tsx
  app/screens/post_options/options/mark_unread_option.tsx
  app/screens/post_options/options/pin_channel_option.tsx
  app/screens/post_options/options/reply_option.tsx
  app/screens/post_options/options/save_option.tsx
  app/screens/post_options/post_options.tsx
  app/screens/post_options/reaction_bar/pick_reaction/index.tsx
  app/screens/post_options/reaction_bar/reaction/index.tsx
  app/screens/post_options/reaction_bar/reaction_bar.tsx
  app/screens/reactions/reactions.tsx
  app/screens/thread/thread.tsx
  babel.config.js
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/support/ui/component/camera_quick_action.ts
  detox/e2e/support/ui/component/file_quick_action.ts
  detox/e2e/support/ui/component/image_quick_action.ts
  detox/e2e/support/ui/component/index.ts
  detox/e2e/support/ui/component/input_quick_action.ts
  detox/e2e/support/ui/component/post.ts
  detox/e2e/support/ui/component/post_draft.ts
  detox/e2e/support/ui/component/post_list.ts
  detox/e2e/support/ui/component/profile_picture.ts
  detox/e2e/support/ui/component/send_button.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/channel_list.ts
  detox/e2e/support/ui/screen/create_or_edit_channel.ts
  detox/e2e/support/ui/screen/home.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/post_options.ts
  detox/e2e/support/ui/screen/thread.ts
  detox/e2e/test/channels/browse_channels.e2e.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/channels/channel_post_list.e2e.ts
  detox/e2e/test/channels/create_and_edit_header.e2e.ts
  detox/e2e/test/channels/create_direct_message.e2e.ts
  detox/e2e/test/smoke_test/channels.e2e.ts
  index.ts
  package-lock.json
  package.json
Labels: release-note-none

#6051 feat: add .m4a file preview
  app/utils/file.js
Labels: Lifecycle/1:stale, 3: QA Review, release-note, Contributor

#5651 Latex rendering with react-native-math-view
  app/components/markdown/index.js
  app/components/markdown/latex_code_block/__snapshots__/latex_code_block.test.js.snap
  app/components/markdown/latex_code_block/index.js
  app/components/markdown/latex_code_block/latex_code_block.js
  app/components/markdown/latex_code_block/latex_code_block.test.js
  app/components/markdown/latex_inline/__snapshots__/latex_inline.test.js.snap
  app/components/markdown/latex_inline/index.js
  app/components/markdown/latex_inline/latex_inline.js
  app/components/markdown/latex_inline/latex_inline.test.js
  app/components/markdown/markdown.js
  app/mm-redux/types/config.ts
  app/screens/index.js
  app/screens/latex/__snapshots__/latex.test.js.snap
  app/screens/latex/index.js
  app/screens/latex/latex.js
  app/screens/latex/latex.test.js
  app/utils/latex.test.ts
  app/utils/latex.ts
  ios/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest.config.js
  package-lock.json
  package.json
Labels: QA Review Done, release-note

#6141 In-Channel experience
  app/actions/remote/thread.ts
  app/client/rest/channels.ts
  app/components/common_post_options/base_option/index.tsx
  app/components/common_post_options/copy_permalink_option/copy_permalink_option.tsx
  app/components/common_post_options/copy_permalink_option/index.tsx
  app/components/common_post_options/follow_thread_option/follow_thread_option.tsx
  app/components/common_post_options/follow_thread_option/index.ts
  app/components/common_post_options/index.ts
  app/components/common_post_options/reply_option.tsx
  app/components/common_post_options/save_option.tsx
  app/components/post_list/index.tsx
  app/components/post_list/post/footer/footer.tsx
  app/components/post_list/post/footer/index.ts
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/header/index.ts
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/components/post_list/post/unread_dot.tsx
  app/queries/servers/post.ts
  app/queries/servers/thread.ts
  app/screens/channel/channel_post_list/channel_post_list.tsx
  app/screens/post_options/index.ts
  app/screens/post_options/options/copy_text_option.tsx
  app/screens/post_options/options/delete_post_option.tsx
  app/screens/post_options/options/edit_option.tsx
  app/screens/post_options/options/mark_unread_option.tsx
  app/screens/post_options/options/pin_channel_option.tsx
  app/screens/post_options/post_options.tsx
  app/screens/thread/thread_follow_button/thread_follow_button.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6184 [Gekidou] bugs squash
  app/components/jumbo_emoji/index.tsx
  app/components/post_list/more_messages/more_messages.tsx
  app/components/post_list/post/body/files/files.tsx
  app/screens/bottom_sheet/index.tsx
Labels: 2: PM Review, release-note-none

#6185 Show login options when using multiple SSO login methods
  app/screens/select_server/select_server.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#6186 Automated cherry pick of #6185
  app/screens/select_server/select_server.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6187 Bump version 1.51.1 build 392
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6190 [Gekidou] Show login screen when selecting a previous server
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/login/index.tsx
  app/screens/navigation.ts
  app/screens/server/index.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso.test.tsx
  app/utils/server/index.ts
  test/setup.ts
Labels: 4: Reviews Complete, release-note-none

#6191 [Gekidou] find channels (default state)
  app/actions/remote/user.ts
  app/components/channel_icon/dm_avatar/dm_avatar.tsx
  app/components/channel_icon/index.tsx
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.test.tsx
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/custom_status/custom_status.tsx
  app/components/channel_item/custom_status/index.ts
  app/components/channel_item/index.ts
  app/components/option_box/index.tsx
  app/components/search/index.tsx
  app/components/user_item/user_item.tsx
  app/constants/screens.ts
  app/queries/servers/channel.ts
  app/screens/custom_status/index.tsx
  app/screens/find_channels/filtered_list/filtered_list.tsx
  app/screens/find_channels/filtered_list/index.ts
  app/screens/find_channels/index.tsx
  app/screens/find_channels/quick_options/index.ts
  app/screens/find_channels/quick_options/quick_options.tsx
  app/screens/find_channels/unfiltered_list/header.tsx
  app/screens/find_channels/unfiltered_list/index.ts
  app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/__snapshots__/category_body.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/category_body.test.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/body/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/body/channel_item/channel_item.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/unreads.test.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/unreads.tsx
  app/screens/home/channel_list/categories_list/search/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/search/index.tsx
  app/screens/index.tsx
  app/utils/user/index.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, 4: Reviews Complete, release-note-none

#6193 Remove logError remote action
  app/actions/remote/error.ts
  app/actions/remote/session.ts
  app/actions/remote/systems.ts
Labels: 4: Reviews Complete, release-note-none

#6194 Use device locale to display the untrusted device alert
  app/init/managed_app.ts
Labels: 4: Reviews Complete, release-note-none

#6140 Gekidou CRT - Global threads screen
  app/actions/local/channel.ts
  app/actions/local/post.ts
  app/actions/local/thread.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/team.ts
  app/actions/remote/thread.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/threads.ts
  app/components/channel_item/channel_item.tsx
  app/components/friendly_date/friendly_date.test.tsx
  app/components/friendly_date/index.tsx
  app/components/navigation_header/header.tsx
  app/components/post_list/date_separator/index.tsx
  app/components/remove_markdown/index.tsx
  app/constants/datetime.ts
  app/constants/index.ts
  app/constants/screens.ts
  app/queries/servers/team.ts
  app/screens/global_threads/index.tsx
  app/screens/global_threads/threads_list/empty_state.tsx
  app/screens/global_threads/threads_list/end_of_list.tsx
  app/screens/global_threads/threads_list/header/index.tsx
  app/screens/global_threads/threads_list/illustrations/empty_state.tsx
  app/screens/global_threads/threads_list/illustrations/search_hint.svg
  app/screens/global_threads/threads_list/index.ts
  app/screens/global_threads/threads_list/thread/index.ts
  app/screens/global_threads/threads_list/thread/thread.tsx
  app/screens/global_threads/threads_list/thread/thread_footer/index.ts
  app/screens/global_threads/threads_list/thread/thread_footer/thread_footer.tsx
  app/screens/global_threads/threads_list/threads_list.tsx
  app/screens/home/channel_list/additional_tablet_view/index.tsx
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/home/channel_list/categories_list/threads/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/threads/index.tsx
  app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/screens/home/channel_list/categories_list/threads_button/index.ts
  app/screens/home/channel_list/categories_list/threads_button/threads_button.test.tsx
  app/screens/home/channel_list/categories_list/threads_button/threads_button.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
  app/screens/index.tsx
  app/screens/thread_options/index.ts
  app/screens/thread_options/options/mark_as_unread_option.tsx
  app/screens/thread_options/options/open_in_channel_option.tsx
  app/screens/thread_options/thread_options.tsx
  app/utils/datetime.ts
  assets/base/i18n/en.json
  types/crt/index.d.ts
Labels: 2: Dev Review, release-note-none

#6189 [Gekidou] set badge count on cancel notifications
  app/actions/local/channel.ts
  app/database/subscription/unreads.ts
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, Do Not Merge, release-note-none

#6142 Add AppsForm and Interactive Dialogs
  app/actions/remote/apps.ts
  app/actions/remote/command.ts
  app/actions/remote/integrations.ts
  app/actions/remote/post.ts
  app/actions/websocket/index.ts
  app/actions/websocket/integrations.ts
  app/actions/websocket/teams.ts
  app/client/rest/apps.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete_selector/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/embedded_binding.tsx
  app/components/post_list/post/body/content/embedded_bindings/embedded_sub_bindings.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_button/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_menu/index.tsx
  app/components/settings/bool_setting.tsx
  app/components/settings/footer.tsx
  app/components/settings/label.tsx
  app/components/settings/radio_setting/index.tsx
  app/components/settings/radio_setting/radio_entry.tsx
  app/components/settings/text_setting.tsx
  app/constants/apps.ts
  app/constants/database.ts
  app/constants/index.ts
  app/constants/integrations.ts
  app/constants/screens.ts
  app/constants/view.ts
  app/managers/integrations_manager.ts
  app/queries/app/servers.ts
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_field.tsx
  app/screens/apps_form/index.tsx
  app/screens/index.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/interactive_dialog/dialog_introduction_text.tsx
  app/screens/interactive_dialog/index.tsx
  app/screens/navigation.ts
  app/utils/apps.ts
  app/utils/integrations.ts
  app/utils/opengraph.js
  assets/base/i18n/en.json
  types/api/apps.d.ts
  types/api/integrations.d.ts
Labels: 2: Dev Review, release-note-none

#6195 [Gekidou] Add Latex support
  app/components/markdown/at_mention/at_mention.tsx
  app/components/markdown/channel_mention/channel_mention.tsx
  app/components/markdown/index.ts
  app/components/markdown/index.tsx
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_code_block/index.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_latex_block/index.tsx
  app/components/markdown/markdown_latex_inline/index.tsx
  app/components/markdown/markdown_link/markdown_link.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/constants/screens.ts
  app/screens/index.tsx
  app/screens/latex/index.tsx
  app/utils/markdown/latex.test.ts
  app/utils/markdown/latex.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest.config.js
  package-lock.json
  package.json
  types/api/config.d.ts
  types/global/markdown.ts
  types/modules/react-native-math-view.d.ts
Labels: 4: Reviews Complete, release-note-none

#6198 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6201 Bump version 1.52.0 build 394
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6202 Automated cherry pick of #6201
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none
