Repository mattermost/mattermost-mobile, pull requests merged in 2022-10, with the labels that each got.

#6662 MM-47003 - Calls - Fix for: peer connection timeout (v1)
  app/products/calls/connection.ts
Labels: 4: Reviews Complete, release-note

#6658 MM-47003 - Calls - Fix for: peer connection timeout
  app/products/calls/connection/connection.ts
  app/products/calls/state/actions.ts
Labels: 4: Reviews Complete, release-note

#6653 Fix permissions defaulting to true
  app/queries/servers/channel.ts
  app/queries/servers/role.ts
  app/screens/browse_channels/index.ts
  app/screens/channel/channel_post_list/intro/public_or_private_channel/public_or_private_channel.tsx
  app/screens/channel/channel_post_list/intro/townsquare/index.tsx
  app/utils/channel/index.ts
  app/utils/role/index.ts
Labels: 4: Reviews Complete, release-note

#6659 Improve wiring after test with the recording library
  app/actions/local/draft.ts
  app/components/files/voice_recording_file.tsx
  app/components/post_draft/draft_input/message_input.tsx
  app/components/post_draft/draft_input/voice_input.tsx
  app/components/post_draft/send_handler/send_handler.tsx
  app/components/post_list/post/body/body.tsx
  app/queries/servers/system.ts
  types/api/config.d.ts
Labels: 2: Dev Review, release-note-none

#6671 [Gekidou] Bump app build number to 427
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#6670 [Gekidou] Add custom status to user profile sheet
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/header/index.ts
  app/screens/channel/header/header.tsx
  app/screens/channel/header/index.ts
  app/screens/channel_info/extra/extra.tsx
  app/screens/channel_info/extra/index.ts
  app/screens/user_profile/custom_status.tsx
  app/screens/user_profile/index.ts
  app/screens/user_profile/user_profile.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note-none

#6676 [Gekidou] Fix iOS keyboard tracking when paused
  patches/react-native-keyboard-tracking-view+5.7.0.patch
Labels: 2: Dev Review, release-note-none

#6675 [Gekidou] Fix switch to channel when notification is dismissed
  app/constants/screens.ts
  app/init/push_notifications.ts
  app/screens/navigation.ts
  index.ts
Labels: 2: Dev Review, release-note-none

#6661 Voice message recording UI
  app/components/files/voice_recording_file.tsx
  app/components/files/voice_recording_file/index.tsx
  app/components/files/voice_recording_file/playback.tsx
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/draft_input/message_input.tsx
  app/components/post_draft/draft_input/voice_input.tsx
  app/components/post_draft/draft_input/voice_input/animated_microphone.tsx
  app/components/post_draft/draft_input/voice_input/index.tsx
  app/components/post_draft/draft_input/voice_input/sound_wave.tsx
  app/components/post_draft/draft_input/voice_input/time_elapsed.tsx
  app/components/post_draft/record_action/index.tsx
  app/components/post_draft/send_action/index.tsx
  app/components/post_draft/uploads/index.tsx
  app/components/post_draft/uploads/upload_item/index.tsx
  app/components/post_draft/uploads/upload_item/upload_remove.tsx
  app/constants/view.ts
Labels: 2: Dev Review, release-note-none

#6681 [Voice message] add react-native-audio-recorder-player mp3 fork
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: release-note-none

#6678 [Gekidou] Fix navbar theme in share extension
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/MattermostShare.xcscheme
  ios/MattermostShare/Views/InitialView.swift
Labels: 4: Reviews Complete, release-note-none

#6663 Detox/E2E: Update reporting to accommodate sharding
  detox/e2e/config.js
  detox/e2e/test/autocomplete/create_channel.e2e.ts
  detox/package-lock.json
  detox/package.json
  detox/save_report.js
  detox/utils/artifacts.js
  detox/utils/jest_stare.js
  detox/utils/report.js
  detox/utils/test_cases.js
Labels: 4: Reviews Complete, release-note-none

#6679 Translations update from Mattermost Weblate
  assets/base/i18n/uk.json
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Do Not Merge/Mattermod

#6684 [Gekidou] Bump app build number to 428
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6664 Detox/E2E: Verification fixes and added a step to post message on direct messages
  detox/e2e/test/autocomplete/channel_mention.e2e.ts
  detox/e2e/test/autocomplete/edit_channel_header.e2e.ts
  detox/e2e/test/channels/create_direct_message.e2e.ts
  detox/e2e/test/channels/favorite_and_unfavorite_channel.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6685 CI Build fix
  .circleci/config.yml
  android/gradle.properties
Labels: 4: Reviews Complete, release-note-none

#6687 Updated CodeQL to use latest version
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: release-note-none

#6693 iOS: Perform the split view check in main queue. (Some call paths caused the check to be done in a background thread)
  ios/Mattermost/MattermostManaged.m
Labels: 4: Reviews Complete, release-note-none

#6694 adding current translations to gekidou
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fa.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#6688 Remove not member teams on startup
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
Labels: 4: Reviews Complete, release-note

#6683 [Gekidou MM-47486] Clear the search input after selecting a user
  app/components/search/index.tsx
Labels: 4: Reviews Complete, release-note

#6690 [Gekidou] Upgrade to RN 0.70
  .flowconfig
  .gitignore
  android/app/build.gradle
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  detox/package-lock.json
  detox/package.json
  index.ts
  ios/Mattermost/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+9.3.5.patch
  patches/react-native+0.69.3.patch
  patches/react-native+0.70.3.patch
  patches/react-native-navigation+7.29.0.patch
  patches/react-native-reanimated+2.10.0.patch
  patches/react-native-svg+13.4.0.patch
Labels: 4: Reviews Complete, release-note-none

#6691 [Gekidou] auto update timezone when device changes its location
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/session.ts
  app/actions/remote/user.ts
  app/managers/global_event_handler.ts
Labels: 4: Reviews Complete, release-note-none

#6695 Fix gallery header & footer as well as download video toast
  app/screens/gallery/footer/footer.tsx
  app/screens/gallery/header/index.tsx
  app/screens/gallery/video_renderer/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6692 Hide autocomplete when the input is blurred.
  app/components/post_draft/draft_handler/draft_handler.tsx
  app/components/post_draft/draft_input/index.tsx
  app/components/post_draft/post_draft.tsx
  app/components/post_draft/post_input/post_input.tsx
  app/components/post_draft/send_handler/send_handler.tsx
Labels: 4: Reviews Complete, release-note

#6594 Use always first the local channels
  app/actions/remote/channel.ts
  app/actions/remote/user.ts
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/at_mention/index.ts
  app/components/autocomplete/autocomplete.tsx
  app/components/autocomplete/channel_mention/channel_mention.tsx
  app/components/autocomplete/channel_mention/index.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/mentions.ts
  app/queries/servers/channel.ts
  app/screens/browse_channels/search_handler.tsx
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, release-note

#6705 [Gekidou] Bump app build number to 429
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6677 [Gekidou MM-46229] Add hideAndLock, showAndUnlock callbacks for Search
  app/components/navigation_header/header.tsx
  app/components/navigation_header/index.tsx
  app/components/navigation_header/large.tsx
  app/components/navigation_header/search.tsx
  app/components/post_draft/post_draft.tsx
  app/constants/view.ts
  app/hooks/header.ts
  app/products/calls/components/floating_call_container.tsx
  app/screens/channel/channel.tsx
  app/screens/channel/header/header.tsx
  app/screens/gallery/header/index.tsx
  app/screens/global_threads/index.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/initial/initial.tsx
  app/screens/home/search/initial/modifiers/index.tsx
  app/screens/home/search/search.tsx
Labels: 2: Dev Review, 2: UX Review, release-note

#6711 update team sidebar's background color to match with the theme color …
  app/components/team_sidebar/team_sidebar.tsx
Labels: release-note-none

#6710 [Gekidou] apply heading style to hashtags
  app/components/markdown/hashtag/index.tsx
  app/components/markdown/markdown.tsx
Labels: 4: Reviews Complete, release-note-none

#6709 [Gekidou MM-47999, MM-48005] Remove unusable modifiers, default team picker to current team
  app/screens/home/search/initial/modifiers/index.tsx
  app/screens/home/search/search.tsx
Labels: 2: UX Review, release-note

#6704 [Gekidou MM-47224] Don’t show in app notifications for the active thread
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, release-note-none

#6713 [MM-47498] Don't bold muted channels
  app/components/channel_icon/index.tsx
  app/components/channel_item/channel_item.tsx
Labels: 4: Reviews Complete, release-note

#6712 [Gekidou] Bump app build number to 430
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6660 Fetch and store bindings
  app/actions/local/post.ts
  app/actions/remote/channel.ts
  app/actions/remote/command.ts
  app/actions/remote/thread.ts
  app/actions/websocket/index.ts
  app/components/autocomplete/autocomplete.tsx
  app/components/autocomplete/index.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/autocomplete/slash_suggestion/app_slash_suggestion/app_slash_suggestion.tsx
  app/components/autocomplete/slash_suggestion/index.ts
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/post_draft/post_draft.tsx
  app/components/post_list/post/avatar/avatar.tsx
  app/components/post_list/post/avatar/index.ts
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/content/index.tsx
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/header/index.ts
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/managers/apps_manager.ts
  app/managers/integrations_manager.ts
  app/queries/servers/post.ts
  app/screens/apps_form/index.tsx
  app/screens/edit_post/edit_post.tsx
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note

#6613 Make so Autocomplete opens when we use the at quick action
  app/components/post_draft/draft_handler/draft_handler.tsx
  app/components/post_draft/draft_input/index.tsx
  app/components/post_draft/post_input/post_input.tsx
  app/components/post_draft/quick_actions/input_quick_action/index.tsx
  app/components/post_draft/quick_actions/quick_actions.tsx
  app/components/post_draft/send_handler/send_handler.tsx
Labels: 4: Reviews Complete, release-note
