Repository mattermost/mattermost-mobile, pull requests merged in 2022-08, with the labels that each got.

#6524 [Gekidou] Handle Group Received WebSocket Event
  app/actions/remote/groups.ts
  app/actions/websocket/group.ts
  app/actions/websocket/index.ts
  app/client/rest/groups.ts
  app/constants/websocket.ts
Labels: 4: Reviews Complete, release-note

#6480 [Gekidou MM-45552] Replace Recent Search Item From MenuItem To OptionItem
  app/components/option_item/index.tsx
  app/screens/home/search/initial/recent_searches/recent_item.tsx
Labels: 4: Reviews Complete, release-note

#6527 Translations update from Mattermost Weblate
  assets/base/i18n/ca.json
Labels: release-note-none, Do Not Merge/Mattermod

#6533 Automated cherry pick of #6324
  android/app/src/main/java/com/mattermost/share/ShareModule.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6532 Fix other name showing on typing
  app/components/post_draft/typing/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6528 Detox/E2E: Fix global threads and unarchive channel tests
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/test/threads/global_threads.e2e.ts
Labels: release-note-none

#6534 Remove copy link from DMs and GMs
  app/components/channel_actions/channel_actions.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/quick_actions/index.tsx
  app/screens/channel_info/options/index.tsx
  app/utils/channel/index.ts
Labels: 4: Reviews Complete, release-note

#6536 Substitue rn-device-info by rn-user-agent when fetching the user agent
  app/managers/network_manager.ts
  package-lock.json
  package.json
  test/setup.ts
Labels: 4: Reviews Complete, release-note-none

#6538 Bump version to 1.55.0 and build to 416
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6539 Automated cherry pick of #6538
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6526 Fix permalink not entering loading status after join channel and fix button functionality after joining the channel.
  app/screens/permalink/permalink.tsx
Labels: 4: Reviews Complete, release-note

#6522 MM-45344 Gekidou Remove <MenuItem/>
  app/components/common_post_options/base_option/index.tsx
  app/components/menu_item/__snapshots__/index.test.tsx.snap
  app/components/menu_item/index.test.tsx
  app/components/menu_item/index.tsx
  app/components/option_item/index.tsx
  app/components/status_label/index.tsx
  app/database/operator/base_data_operator/index.ts
  app/database/operator/server_data_operator/handlers/group.ts
  app/screens/about/server_version.tsx
  app/screens/home/account/components/options/custom_status/custom_label.tsx
  app/screens/home/account/components/options/custom_status/custom_status_emoji.tsx
  app/screens/home/account/components/options/custom_status/custom_status_text.tsx
  app/screens/home/account/components/options/custom_status/index.tsx
  app/screens/home/account/components/options/index.tsx
  app/screens/home/account/components/options/logout/index.tsx
  app/screens/home/account/components/options/settings/index.tsx
  app/screens/home/account/components/options/user_presence/index.tsx
  app/screens/home/account/components/options/your_profile/index.tsx
  app/screens/home/search/initial/modifiers/show_more.tsx
  app/screens/post_options/post_options.tsx
  app/screens/settings/about/tos_privacy.tsx
  app/screens/settings/config.ts
  app/screens/settings/display/display.tsx
  app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
  app/screens/settings/notifications/notifications.tsx
  app/screens/settings/setting_item.tsx
  app/screens/settings/setting_row_label.tsx
  app/screens/settings/settings.tsx
  app/screens/snack_bar/index.tsx
  app/screens/thread_options/thread_options.tsx
Labels: 4: Reviews Complete, release-note-none

#6535 [Gekidou MM-42242 MM-46043] Paginating Threads
  app/actions/local/thread.ts
  app/actions/remote/post.ts
  app/actions/remote/thread.ts
  app/client/rest/posts.ts
  app/components/post_list/post_list.tsx
  app/init/push_notifications.ts
  app/screens/permalink/permalink.tsx
  app/screens/thread/thread_post_list/index.ts
  app/screens/thread/thread_post_list/thread_post_list.tsx
  types/api/posts.d.ts
Labels: 4: Reviews Complete, release-note-none

#6545 Automated cherry pick of #6503
  app/mattermost.js
  app/store/ephemeral_store.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6546 Fix channel added websocket message
  app/actions/websocket/channel.ts
Labels: 4: Reviews Complete, release-note

#5640 [MM-38103] initialize select fields with the value
  app/screens/apps_form/apps_form_field.tsx
Labels: 3: QA Review, release-note

#6530 [Gekidou] Handles Group Channel WebSocket Events
  app/actions/websocket/group.ts
  app/actions/websocket/index.ts
  app/constants/websocket.ts
  app/queries/servers/group.ts
  types/database/database.d.ts
Labels: 2: Dev Review, Do Not Merge/Awaiting PR, release-note

#6548 Automated cherry pick of #5640
  app/screens/apps_form/apps_form_field.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6449 [Gekidou MM-45178] Improve wording about url not being a valid one
  app/managers/network_manager.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#6542 MM-45746 - Handle call_end ws event and '/call end' slash command
  app/actions/websocket/index.ts
  app/components/post_draft/send_handler/send_handler.tsx
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/leave_and_join_alert.tsx
  app/products/calls/connection/connection.ts
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#6529 [Gekidou] GroupTeams WebSocket Handling
  app/actions/websocket/group.ts
  app/actions/websocket/index.ts
  app/constants/websocket.ts
  app/queries/servers/group.ts
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note

#6516 [Gekidou MM-44940] Add autocomplete to navigation search
  app/actions/remote/channel.ts
  app/components/autocomplete/autocomplete.tsx
  app/components/autocomplete/channel_mention/channel_mention.tsx
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, 2: UX Review, release-note

#6550 fix podfile lock missing user-agent
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
Labels: 4: Reviews Complete, release-note-none

#6553 [Gekidou] Bump app build number to 417
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6481 [Gekidou - MM-45791] Use the same handler for search clear and cancel actions
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, release-note

#6551 [Gekidou MM-46237] Correct spelling for log messages
  app/actions/remote/session.ts
  app/actions/remote/systems.ts
  app/init/launch.ts
  app/utils/sentry.ts
Labels: 4: Reviews Complete, release-note

#6555 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none, kind/chore

#6557 Gekidou cold start
  app/utils/emoji/emoji.json
  index.ts
Labels: 4: Reviews Complete, release-note-none

#6556 Pass down client custom headers to native
  app/client/rest/base.ts
  app/client/rest/users.ts
  types/api/client.d.ts
Labels: 4: Reviews Complete, release-note-none

#6554 [Gekidou MM-46195] Fix team picker height
  app/components/team_sidebar/add_team/add_team_slide_up.tsx
  app/components/team_sidebar/add_team/index.tsx
  app/components/team_sidebar/add_team/team_list_item/team_list_item.tsx
  app/screens/bottom_sheet/content.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/team_picker_icon/team_picker_icon.tsx
  app/screens/navigation.ts
  app/utils/team_list/index.ts
Labels: 2: Dev Review, release-note

#6558 Fix load channels animation
  app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
Labels: 4: Reviews Complete, release-note-none

#6543 Calls: WebSocket reconnection support (v2)
  app/products/calls/connection/connection.ts
  app/products/calls/connection/websocket_client.ts
Labels: 4: Reviews Complete, release-note

#6544 [MM-45749] Support for advanced ICE server configs and TURN credentials
  app/products/calls/client/rest.ts
  app/products/calls/connection/connection.ts
  app/products/calls/connection/simple-peer.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
  types/modules/react-native-webrtc.d.ts
Labels: 4: Reviews Complete, release-note

#6561 MM-46252 : Gekidou - Settings - Fixes Advanced Settings
  app/screens/settings/advanced/index.tsx
  app/utils/file/index.ts
Labels: 4: Reviews Complete, release-note-none

#6564 Bump app build number to 418
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6562 Fix convert to private
  app/client/rest/channels.ts
Labels: 4: Reviews Complete, release-note

#6569 MM-46050 MM-46302 - Fix for call screen popping errors
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/screens/call_screen/call_screen.tsx
Labels: 4: Reviews Complete, release-note-none

#6547 MM-45945 - Calls: finish i18n of calls components and messages
  app/components/post_draft/send_handler/send_handler.tsx
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/components/channel_info_enable_calls/index.tsx
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/components/leave_and_join_alert.tsx
  app/products/calls/hooks.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/utils/file/file_picker/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#6571 MM-46301 MM-45973: Refactor currentCall logic; fix CurrentCallBar bug
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
Labels: 4: Reviews Complete, release-note

#6573 Fix graphQL error
  app/client/graphQL/entry.ts
Labels: 4: Reviews Complete, release-note

#6574 MM-46325: Improve Calls mobile state sync
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/state/actions.ts
Labels: 4: Reviews Complete, release-note-none

#6568 Fix convert channel to private
  app/client/rest/channels.ts
  app/mm-redux/actions/channels.test.js
Labels: 4: Reviews Complete, release-note

#6559 Improve autocomplete behaviour
  app/components/autocomplete/autocomplete.tsx
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.tsx
  app/components/option_item/index.tsx
  app/components/post_draft/post_draft.tsx
  app/constants/autocomplete.ts
  app/hooks/device.ts
  app/screens/channel/channel.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/edit_post/edit_post.tsx
  app/screens/home/search/search.tsx
  app/screens/thread/thread.tsx
  types/modules/react-native-keyboard-tracking-view.d.ts
Labels: 4: Reviews Complete, release-note

#6560 Detox/E2E: Scripts to run tests and save report
  detox/e2e/config.js
  detox/e2e/support/test_config.ts
  detox/package-lock.json
  detox/package.json
  detox/save_report.js
  detox/utils/artifacts.js
  detox/utils/constants.js
  detox/utils/report.js
  detox/utils/test_cases.js
Labels: 3: QA Review, release-note-none

#6576 Gekidou bump build to 419
  android/app/build.gradle
  app/screens/edit_profile/components/edit_profile_picture.tsx
  app/screens/edit_profile/components/panel_item.tsx
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6567 Fix MM-46309
  app/actions/remote/entry/app.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/utils/file/index.ts
  app/utils/mattermost_managed.ts
  app/utils/security.ts
  ios/Mattermost/MattermostManaged.m
Labels: 4: Reviews Complete, release-note-none

#6563 Detox/E2E: Convert to private channel e2e tests in Gekidou
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/support/ui/screen/channel_info.ts
  detox/e2e/test/channels/convert_to_private_channel.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6580 MM-46228 - Calls: endcall should not send the slash command
  app/components/post_draft/send_handler/send_handler.tsx
Labels: 4: Reviews Complete, release-note-none

#6577 Translations update from Mattermost Weblate
  assets/base/i18n/ca.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#6581 [Gekidou] Fix mimeType undefined in isImage utility
  app/utils/file/index.ts
Labels: 2: Dev Review, release-note-none

#6584 Detox/E2E: Account e2e tests in Gekidou
  app/components/tablet_title/index.tsx
  app/components/user_status/__snapshots__/user_status.test.js.snap
  app/components/user_status/index.tsx
  app/screens/channel_info/channel_info.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/custom_status/index.tsx
  app/screens/edit_profile/components/edit_profile_picture.tsx
  app/screens/edit_profile/components/email_field.tsx
  app/screens/edit_profile/components/field.tsx
  app/screens/edit_profile/components/form.tsx
  app/screens/edit_profile/components/user_profile_picture.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/home/account/components/options/custom_status/index.tsx
  app/screens/home/account/components/options/logout/index.tsx
  app/screens/home/account/components/options/settings/index.tsx
  app/screens/home/account/components/options/user_presence/index.tsx
  app/screens/home/account/components/options/your_profile/index.tsx
  app/screens/home/account/components/user_info/index.tsx
  app/screens/settings/about/about.tsx
  app/screens/settings/advanced/index.tsx
  app/screens/settings/display/display.tsx
  app/screens/settings/display_clock/display_clock.tsx
  app/screens/settings/display_theme/display_theme.tsx
  app/screens/settings/display_timezone/display_timezone.tsx
  app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
  app/screens/settings/notification_email/notification_email.tsx
  app/screens/settings/notification_mention/notification_mention.tsx
  app/screens/settings/notification_push/notification_push.tsx
  app/screens/settings/notifications/notifications.tsx
  app/screens/settings/setting_container.tsx
  app/screens/settings/settings.tsx
  detox/e2e/support/server_api/common.ts
  detox/e2e/support/server_api/default_config.json
  detox/e2e/support/test_config.ts
  detox/e2e/support/ui/screen/account.ts
  detox/e2e/support/ui/screen/channel_info.ts
  detox/e2e/support/ui/screen/create_or_edit_channel.ts
  detox/e2e/support/ui/screen/custom_status.ts
  detox/e2e/support/ui/screen/edit_profile.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/settings.ts
  detox/e2e/test/account/account_menu.e2e.ts
  detox/e2e/test/smoke_test/autocomplete.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#6566 [Gekidou] refactor clean notifications
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
  android/app/src/main/java/com/mattermost/helpers/KeysReadableArray.java
  android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
  android/app/src/main/java/com/mattermost/helpers/RandomId.kt
  android/app/src/main/java/com/mattermost/helpers/ReadableArrayUtils.java
  android/app/src/main/java/com/mattermost/helpers/ReadableMapUtils.java
  android/app/src/main/java/com/mattermost/helpers/RealPathUtil.java
  android/app/src/main/java/com/mattermost/helpers/ResolvePromise.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationDrawer.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationsModule.java
  app/actions/local/channel.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/notifications.ts
  app/actions/remote/thread.ts
  app/database/subscription/unreads.ts
  app/init/push_notifications.ts
  app/managers/global_event_handler.ts
  app/notifications/index.ts
  app/notifications/notifications.android.ts
  app/notifications/notifications.ios.ts
  app/screens/home/tab_bar/home.tsx
  ios/Gekidou/Sources/Gekidou/Networking/Network+Mentions.swift
  ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Channels.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Team.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.mm
  ios/Mattermost/NotificationHelper.swift
  ios/Mattermost/NotificationsModule.h
  ios/Mattermost/NotificationsModule.m
  ios/NotificationService/NotificationService.swift
  patches/react-native-notifications+4.3.1.patch
  test/setup.ts
  types/global/native_notifications.d.ts
Labels: 2: Dev Review, release-note-none

#6585 MM-46465 - Calls: Fix for unable to see >1 participant speaking at same time
  app/products/calls/screens/call_screen/call_screen.tsx
Labels: 4: Reviews Complete, release-note

#6578 MM-45747 - Cloud freemium limits & Max participants limits
  android/app/src/main/AndroidManifest.xml
  app/components/post_list/post/post.tsx
  app/constants/index.ts
  app/constants/license.ts
  app/products/calls/actions/calls.ts
  app/products/calls/alerts.ts
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/products/calls/components/channel_info_start/index.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/components/leave_and_join_alert.tsx
  app/products/calls/hooks.ts
  app/products/calls/observers/index.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.test.ts
  app/queries/servers/user.ts
  app/screens/channel/channel.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/index.ts
  app/screens/channel_info/channel_info.tsx
  app/screens/channel_info/index.ts
  app/utils/user/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#6586 Gekidou - fix about screen - wrong i18n key
  app/screens/settings/about/about.tsx
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: 2: Dev Review, release-note-none

#6575 [Gekidou MM-46342] Search screen - handle loading spinner in results screen
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
Labels: release-note

#6587 Bump app build number to 420
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6394 [Gekidou] Solidarity poc
  .solidarity
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note, Contributor

#6589 Make it so a space after autocomplete channels and users closes the autocomplete
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/channel_mention/channel_mention.tsx
  app/utils/helpers.ts
Labels: 4: Reviews Complete, release-note

#5398 MM-33993 Allow apps form and interactive dialogs to clear select fields
  app/components/autocomplete_selector/autocomplete_selector.tsx
  app/components/post_list/post/body/content/message_attachments/action_menu/action_menu.tsx
  app/mm-redux/types/apps.ts
  app/screens/apps_form/apps_form_field.tsx
  app/screens/interactive_dialog/dialog_element.js
Labels: 3: QA Review, release-note

#6592 Gekidou: MM-46531 - CRT observe post and load new threads on load
  app/screens/global_threads/threads_list/thread/index.ts
  app/screens/global_threads/threads_list/thread/thread.tsx
  app/screens/global_threads/threads_list/threads_list.tsx
Labels: 4: Reviews Complete, release-note-none

#6583 MM-46443 : Gekidou - removes save button on settings screens
  app/hooks/android_back_handler.ts
  app/hooks/navigate_back.ts
  app/hooks/navigation_button_pressed.ts
  app/screens/settings/config.ts
  app/screens/settings/display/display.tsx
  app/screens/settings/display_clock/display_clock.tsx
  app/screens/settings/display_theme/display_theme.tsx
  app/screens/settings/display_timezone/display_timezone.tsx
  app/screens/settings/display_timezone_select/index.tsx
  app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
  app/screens/settings/notification_email/notification_email.tsx
  app/screens/settings/notification_mention/mention_settings.tsx
  app/screens/settings/notification_mention/notification_mention.tsx
  app/screens/settings/notification_mention/reply_settings.tsx
  app/screens/settings/notification_push/notification_push.tsx
  app/screens/settings/notification_push/push_send.tsx
  app/screens/settings/notification_push/push_status.tsx
  app/screens/settings/notification_push/push_thread.tsx
  app/screens/settings/notifications/notifications.tsx
  types/screens/settings.d.ts
Labels: 4: Reviews Complete, release-note-none

#6588 fix option box minHeight so that it fits on iPhone SE
  app/components/option_box/animated.tsx
  app/components/option_box/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6595 Fix bottom sheet backdrop
  app/screens/bottom_sheet/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6579 [Gekidou MM-46370] Fix slow response time which switching between files and messages tabs
  app/actions/local/post.ts
  app/components/files/files.tsx
  app/screens/home/search/results/file_results.tsx
  app/screens/home/search/results/index.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
Labels: release-note

#6599 Fix MFA when introducing wrong token or having no teams
  app/screens/mfa/index.tsx
Labels: 4: Reviews Complete, release-note

#6601 Fix loading unreads not stopping with GraphQL
  app/actions/remote/entry/gql_common.ts
Labels: 4: Reviews Complete, release-note

#6603 Gekidou: Create patches for node modules failing on android build
  patches/jail-monkey+2.7.0.patch
  patches/react-native-hw-keyboard-event+0.0.4.patch
Labels: 4: Reviews Complete, release-note-none

#6604 Bump app build number to 421
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6606 MM-46685 MM-45753 - Fix voice activity indicator and Android speakerphone
  android/app/src/main/AndroidManifest.xml
  app/products/calls/screens/call_screen/call_screen.tsx
  ios/Podfile.lock
  package-lock.json
Labels: 4: Reviews Complete, release-note
