Repository mattermost/mattermost-mobile, pull requests merged in 2022-09, with the labels that each got.

#6607 Added missing field to gql query
  app/client/graphQL/entry.ts
Labels: 4: Reviews Complete, release-note

#6609 Automated cherry pick of #5398
  app/components/autocomplete_selector/autocomplete_selector.tsx
  app/components/post_list/post/body/content/message_attachments/action_menu/action_menu.tsx
  app/mm-redux/types/apps.ts
  app/screens/apps_form/apps_form_field.tsx
  app/screens/interactive_dialog/dialog_element.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6610 Automated cherry pick of #6568
  app/client/rest/channels.ts
  app/mm-redux/actions/channels.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6611 Detox/E2E: Add custom test sequencer
  detox/e2e/config.js
  detox/e2e/custom_sequencer.js
  detox/package-lock.json
  detox/package.json
Labels: 4: Reviews Complete, release-note-none

#6608 Fix notification entry on graphQL
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/entry/notification.ts
Labels: 4: Reviews Complete, release-note

#6582 MM-46300 Clear cached images on logout
  app/managers/global_event_handler.ts
  app/utils/file/index.ts
Labels: 4: Reviews Complete, release-note-none

#6605 Fix login crash when ExtendedSessionLengthWithActivity === false
  patches/react-native-notifications+4.3.1.patch
Labels: release-note

#6615 [Gekidou] Patch RNNotification Android
  app/init/push_notifications.ts
  patches/react-native-notifications+4.3.1.patch
Labels: 2: Dev Review, release-note-none

#6616 Add missing GQL fields
  app/client/graphQL/entry.ts
  app/utils/graphql.ts
Labels: 4: Reviews Complete, release-note

#6614 Gekidou fix unsigned builds
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/bundleReactNative.sh
  ios/react-native-xcode.sh
  scripts/build.sh
Labels: 2: Dev Review, release-note-none

#6617 Bump app build number to 422
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6618 [Gekidou] add file logger
  app/utils/log.ts
  babel.config.js
  index.ts
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#6623 Receiving multiple In-app notifications is blocking the navigation
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, release-note

#6621 [Gekidou] Adjust bottomSheet height for iOS devices without insets
  app/constants/view.ts
  app/utils/helpers.ts
Labels: 4: Reviews Complete, release-note-none

#6624 Add fallback to rest on websocket reconnect
  app/actions/websocket/index.ts
Labels: 4: Reviews Complete, release-note

#6622 [Gekidou] Fix account screen scrollable options
  app/screens/home/account/account.tsx
  app/screens/home/account/components/options/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6625 Bump version to 1.55.1 build 423
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6626 Automated cherry pick of #6625
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6602 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/nl.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#6596 Fix autocomplete not scrolling in search in Android
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/autocomplete.tsx
  app/components/autocomplete/channel_mention/channel_mention.tsx
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.tsx
  app/components/autocomplete/slash_suggestion/app_slash_suggestion/app_slash_suggestion.tsx
  app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
  app/components/post_draft/post_draft.tsx
  app/hooks/autocomplete.ts
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/edit_post/edit_post.tsx
  app/screens/home/search/search.tsx
  patches/react-native-reanimated+2.9.1.patch
Labels: 4: Reviews Complete, release-note

#6627 MM-45755 - Calls: Unmute automatically in DM or GM channels
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/alerts.ts
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/products/calls/components/channel_info_start/index.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/components/leave_and_join_alert.tsx
  app/products/calls/connection/connection.ts
  app/products/calls/types/calls.ts
Labels: 4: Reviews Complete, release-note

#6632 [Gekidou] Bump app build number to 424
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#6620 [Gekidou MM-43992] Display message priority labels for the posts
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/header/reply/index.tsx
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/components/post_priority/post_priority_label.tsx
  app/constants/post.ts
  app/queries/servers/system.ts
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: 4: Reviews Complete, release-note

#6637 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none, kind/chore

#6638 Refactor entry to better share between rest and GQL
  app/actions/local/systems.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/groups.ts
  app/actions/remote/systems.ts
  app/actions/websocket/index.ts
  app/client/graphQL/entry.ts
Labels: 4: Reviews Complete, release-note

#6641 [Gekidou] Bump app build number to 425
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#6642 [Gekidou MM-46899 MM-45205] Thread sync issue
  app/actions/websocket/threads.ts
Labels: 4: Reviews Complete, release-note-none

#6640 Translations update from Mattermost Weblate
  assets/base/i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#6635 [Gekidou MM-45046] Always show threads button when filtered and unfiltered
  app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/screens/home/channel_list/categories_list/threads_button/index.ts
  app/screens/home/channel_list/categories_list/threads_button/threads_button.test.tsx
  app/screens/home/channel_list/categories_list/threads_button/threads_button.tsx
Labels: 4: Reviews Complete, release-note

#6630 [Gekidou MM-45506] Do not include empty DM and GMs in Channel List
  app/queries/servers/channel.ts
  app/screens/home/channel_list/categories_list/categories/body/index.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#6644 [Gekidou] Fix for crash caused due to accessing "priority" property
  app/components/post_list/post/post.tsx
Labels: 4: Reviews Complete, release-note-none

#6639 Gekidou session expired notification
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  app/actions/remote/entry/login.ts
  app/actions/remote/session.ts
  app/constants/database.ts
  app/constants/events.ts
  app/constants/index.ts
  app/constants/push_notification.ts
  app/init/launch.ts
  app/init/push_notifications.ts
  app/managers/global_event_handler.ts
  app/managers/session_manager.ts
  app/queries/servers/system.ts
  app/screens/home/account/account.tsx
  app/screens/navigation.ts
  app/utils/notification/index.ts
  assets/base/i18n/en.json
  index.ts
  patches/react-native-navigation+7.29.0.patch
  patches/react-native-notifications+4.3.1.patch
  types/api/session.d.ts
  types/database/raw_values.d.ts
Labels: 4: Reviews Complete, release-note-none

#6648 [Gekidou] Bump app build number to 426
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6649 Translations update from Mattermost Weblate
  assets/base/i18n/ko.json
Labels: release-note-none, Do Not Merge/Mattermod

#6650 Update to xcode 14
  .circleci/config.yml
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/Mattermost.xcscheme
  ios/Mattermost.xcodeproj/xcshareddata/xcschemes/NotificationService.xcscheme
  ios/Podfile
  ios/Podfile.lock
Labels: 2: Dev Review, release-note-none

#6651 Voice Messages
  app/components/files/voice_recording_file.tsx
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/draft_input/index.ts
  app/components/post_draft/draft_input/message_input.tsx
  app/components/post_draft/draft_input/voice_input.tsx
  app/components/post_draft/uploads/upload_item/index.tsx
  app/components/post_list/post/body/body.tsx
  app/components/post_list/post/body/index.ts
  app/constants/post.ts
  app/queries/servers/system.ts
  types/api/config.d.ts
  types/api/files.d.ts
Labels: release-note-none

#6652 Fix login not showing the usernames
  app/actions/remote/systems.ts
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
Labels: 4: Reviews Complete, release-note
