Repository mattermost/mattermost-mobile, pull requests merged in 2022-01, with the labels that each got.

#5886 update v1 dependencies
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-community+netinfo+7.1.7.patch
  patches/react-native-file-viewer+2.1.4.patch
  patches/react-native-file-viewer+2.1.5.patch
  patches/react-native-navigation+7.24.3.patch
  patches/react-native-notifications+4.1.3.patch
  test/setup.js
Labels: 4: Reviews Complete, release-note-none

#5890 [Gekidou] dependency updates
  .env
  detox/package-lock.json
  detox/package.json
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#5891 [Gekidou] downgrade from expo 44 to 43
  assets/base/i18n/en.json
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/expo-file-system+13.1.0.patch
Labels: release-note-none

#5889 Update NOTICE.txt
  NOTICE.txt
Labels: 2: Dev Review, release-note-none

#5894 Fix re-login and hot reload crash
  ios/Mattermost/MattermostManaged.m
  patches/@nozbe+watermelondb+0.24.0.patch
Labels: 4: Reviews Complete, release-note-none

#5895 Automated cherry pick of #5881
  app/actions/views/custom_status.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#5896 Version 1.48.2 build 382
  android/app/build.gradle
  assets/base/i18n/en.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#5907 V2 dependency updates
  .flowconfig
  android/app/build.gradle
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  app/actions/remote/reactions.ts
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/channel_list/search/__snapshots__/index.test.tsx.snap
  app/components/channel_list/search/index.tsx
  app/components/custom_status/__snapshots__/clear_button.test.tsx.snap
  app/components/loading/__snapshots__/index.test.tsx.snap
  app/components/team_sidebar/add_team/team_list.tsx
  app/database/manager/index.ts
  app/database/operator/server_data_operator/handlers/user.ts
  app/screens/in_app_notification/index.tsx
  app/screens/index.tsx
  index.ts
  ios/Gemfile
  ios/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/expo+43.0.5.patch
  patches/expo-file-system+13.0.3.patch
  patches/expo-modules-core+0.4.10.patch
  patches/react-native+0.66.4.patch
  patches/react-native+0.67.1.patch
  patches/react-native-navigation+7.25.1.patch
  types/database/database.d.ts
Labels: 4: Reviews Complete, release-note-none

#5862 [Gekidou] Manage user websocket events
  app/actions/local/channel.ts
  app/actions/remote/post.ts
  app/actions/remote/user.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/actions/websocket/teams.ts
  app/actions/websocket/users.ts
  app/database/operator/server_data_operator/comparators/index.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/queries/servers/channel.ts
  app/utils/user/index.ts
  types/api/channels.d.ts
  types/database/database.d.ts
  types/database/raw_values.d.ts
Labels: 2: Dev Review, release-note-none

#5851 [Gekidou] Handle post related websocket events
  app/actions/local/channel.ts
  app/actions/local/post.ts
  app/actions/remote/channel.ts
  app/actions/remote/post.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/actions/websocket/posts.ts
  app/actions/websocket/teams.ts
  app/components/post_list/post/avatar/index.tsx
  app/components/post_list/post/body/add_members/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/message/message.tsx
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/post.tsx
  app/constants/events.ts
  app/constants/post.ts
  app/queries/servers/channel.ts
  app/screens/channel/channel_post_list/index.ts
  app/utils/post/index.ts
  types/api/posts.d.ts
Labels: 2: Dev Review, release-note-none

#5911 Translations update from Mattermost Weblate
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#5913 [Gekidou] Handle gracefully teams or channels are fetch errors out
  app/components/channel_list/__snapshots__/index.test.tsx.snap
  app/components/channel_list/header/header.tsx
  app/components/channel_list/header/index.ts
  app/components/channel_list/index.tsx
  app/components/channel_list/load_channels_error/index.ts
  app/components/channel_list/load_channels_error/load_channel_error.tsx
  app/components/channel_list/load_teams_error/index.tsx
  app/components/channel_list/loading_error/__snapshots__/index.test.tsx.snap
  app/components/channel_list/loading_error/index.test.tsx
  app/components/channel_list/loading_error/index.tsx
  app/components/failed_action/cloud_svg.tsx
  app/components/failed_action/index.tsx
  app/screens/channel/channel.tsx
  app/screens/channel/failed_channels/index.tsx
  app/screens/channel/failed_teams/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note-none

#5875 Update Calls
  NOTICE.txt
  app/actions/websocket/index.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/__snapshots__/enable_disable_calls.test.js.snap
  app/products/calls/components/call_avatar.tsx
  app/products/calls/components/call_message/__snapshots__/call_message.test.js.snap
  app/products/calls/components/call_message/call_message.tsx
  app/products/calls/components/current_call/__snapshots__/current_call.test.js.snap
  app/products/calls/components/current_call/current_call.tsx
  app/products/calls/components/current_call/index.ts
  app/products/calls/components/enable_disable_calls.tsx
  app/products/calls/components/join_call/__snapshots__/join_call.test.js.snap
  app/products/calls/components/join_call/join_call.tsx
  app/products/calls/components/leave_and_join_alert.tsx
  app/products/calls/components/start_call/__snapshots__/start_call.test.js.snap
  app/products/calls/components/start_call/start_call.tsx
  app/products/calls/connection.ts
  app/products/calls/screens/call/__snapshots__/call_screen.test.js.snap
  app/products/calls/screens/call/call_screen.test.js
  app/products/calls/screens/call/call_screen.tsx
  app/products/calls/screens/call/index.ts
  app/products/calls/screens/call_other_actions/call_other_actions.tsx
  app/products/calls/simple-peer.ts
  app/products/calls/store/actions/calls.ts
  app/products/calls/store/actions/websockets.ts
  app/products/calls/store/reducers/calls.test.js
  app/products/calls/store/reducers/calls.ts
  app/products/calls/store/types/calls.ts
  app/products/calls/websocket.ts
  app/screens/channel_info/channel_info.js
  app/screens/channel_info/index.js
  assets/base/i18n/en.json
  ios/Podfile.lock
  package-lock.json
  package.json
  types/modules/react-native-webrtc.d.ts
Labels: 4: Reviews Complete, release-note-none

#5901 MM-40364 [Gekidou] - Image Picker for Edit Profile
  app/actions/remote/user.ts
  app/components/error_text/index.tsx
  app/components/post_list/post/body/files/file_info.tsx
  app/components/profile_picture/image.tsx
  app/components/profile_picture/index.tsx
  app/components/profile_picture/status.tsx
  app/constants/index.ts
  app/constants/profile.ts
  app/screens/edit_profile/components/disabled_fields.tsx
  app/screens/edit_profile/components/edit_profile_picture.tsx
  app/screens/edit_profile/components/form.tsx
  app/screens/edit_profile/components/panel_item.tsx
  app/screens/edit_profile/components/profile_image_picker.tsx
  app/screens/edit_profile/components/updating.tsx
  app/screens/edit_profile/components/user_profile_picture.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/home/account/components/options/your_profile/index.tsx
  app/screens/home/account/index.tsx
  app/screens/navigation.ts
  app/utils/file/file_picker/index.ts
  app/utils/file/index.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  types/api/files.d.ts
  types/screens/edit_profile.d.ts
  types/utils/file.d.ts
  types/utils/index.d.ts
Labels: 4: Reviews Complete, release-note-none

#5917 Add scorecards analysis
  .github/workflows/scorecards-analysis.yml
Labels: release-note-none

#5909 [Gekidou] Sidebar Categories (Database only)
  app/constants/database.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/models/server/category.ts
  app/database/models/server/category_channel.ts
  app/database/models/server/channel.ts
  app/database/models/server/index.ts
  app/database/models/server/my_channel.ts
  app/database/operator/server_data_operator/comparators/index.ts
  app/database/operator/server_data_operator/handlers/category.test.ts
  app/database/operator/server_data_operator/handlers/category.ts
  app/database/operator/server_data_operator/index.ts
  app/database/operator/server_data_operator/transformers/category.test.ts
  app/database/operator/server_data_operator/transformers/category.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/category.ts
  app/database/schema/server/table_schemas/category_channel.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/test.ts
  types/api/category.d.ts
  types/database/database.d.ts
  types/database/models/servers/category.d.ts
  types/database/models/servers/category_channel.d.ts
  types/database/raw_values.d.ts
Labels: release-note
