Repository mattermost/mattermost-mobile, pull requests merged in 2023-07, with the labels that each got.

#7436 Bump version to 2.6.0 and build to 477
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7437 Automated cherry pick of #7436
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7432 fix open code block when keyboard is opened
  app/components/markdown/markdown_code_block/index.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#7392 Add `.node-version` and `.ruby-version`
  .node-version
  .nvmrc
  .ruby-version
Labels: 4: Reviews Complete, release-note

#7412 Fix ios cache
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/managers/session_manager.ts
  app/utils/mattermost_managed.ts
  ios/Gekidou/Sources/Gekidou/Keychain.swift
  ios/GekidouWrapper.swift
  ios/Mattermost/MattermostManaged.m
Labels: CherryPick/Approved, release-note

#7439 Automated cherry pick of #7412
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/managers/session_manager.ts
  app/utils/mattermost_managed.ts
  ios/Gekidou/Sources/Gekidou/Keychain.swift
  ios/GekidouWrapper.swift
  ios/Mattermost/MattermostManaged.m
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7441 Bump app build number to 478
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7442 Automated cherry pick of #7441
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7433 Remove Post Priority Feature Flag
  app/queries/servers/post.ts
Labels: 4: Reviews Complete, release-note

#7438 14 day data cleanup and vacuum
  app/actions/local/systems.ts
  package-lock.json
  patches/@nozbe+watermelondb+0.26.0.patch
Labels: 4: Reviews Complete, release-note-none

#7448 fix: crash when reactor is missing
  app/components/user_item/user_item.tsx
  app/screens/reactions/reactors_list/reactor/reactor.tsx
  app/utils/user/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7449 Automated cherry pick of #7448
  app/components/user_item/user_item.tsx
  app/screens/reactions/reactors_list/reactor/reactor.tsx
  app/utils/user/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7451 Bump app build number to 479
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7452 Automated cherry pick of #7451
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7447 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/fr.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: 2: Dev Review, release-note-none, Do Not Merge/Mattermod

#7457 Translations update from Mattermost Weblate
  assets/base/i18n/zh-CN.json
Labels: 2: Dev Review, release-note-none, Do Not Merge/Mattermod

#7455 use useAndroidHardwareBackHnd on Files and Members
  app/screens/channel_files/channel_files.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7459 Fix search hashtag
  app/components/markdown/hashtag/index.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note

#7446 MM-53343 - save button not grayed out when edit message is too long
  app/screens/edit_post/edit_post.tsx
Labels: 4: Reviews Complete, release-note-none

#7445 match desktop search and highlight results
  app/actions/remote/search.ts
  app/client/rest/posts.ts
  app/components/markdown/transform.ts
  app/components/post_with_channel_info/post_with_channel_info.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
  app/utils/markdown/index.ts
  types/api/posts.d.ts
  types/api/search.d.ts
Labels: 4: Reviews Complete, release-note

#7429 [MM-53249] Allow server to hide or customize the Forgot Password link
  app/screens/login/form.tsx
  types/api/config.d.ts
Labels: 4: Reviews Complete, release-note-none

#7460 Do not show archived teams when browsing available teams
  app/screens/index.tsx
  app/screens/join_team/join_team.tsx
  app/screens/select_team/select_team.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#7434 added Remember last viewed channel or thread on cold start feature
  app/actions/app/global.ts
  app/constants/database.ts
  app/init/launch.ts
  app/queries/app/global.ts
  app/screens/channel/channel.tsx
  app/screens/thread/thread.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7430 [MM-48225] Reduce Padding/Margins from Files Tab and moving the Search Results to the FlatList
  app/components/files/file.tsx
  app/components/files/files.tsx
  app/components/files_search/file_results.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/header_button.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
  app/screens/home/search/team_picker_icon.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Lifecycle/1:stale, release-note, Contributor

#7464 Added status on profile picture in bottom tab
  app/screens/home/tab_bar/account.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7134 Feat: add copy to clipboard button in "about" mattermost page
  app/screens/settings/about/about.tsx
  assets/base/i18n/en.json
  detox/e2e/support/ui/screen/about.ts
  detox/e2e/test/account/about.e2e.ts
Labels: 4: Reviews Complete, release-note, Contributor

#7469 Automated cherry pick of #7134
  app/screens/settings/about/about.tsx
  assets/base/i18n/en.json
  detox/e2e/support/ui/screen/about.ts
  detox/e2e/test/account/about.e2e.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7470 Fix re-selection of custom theme
  app/screens/settings/display_theme/custom_theme.tsx
  app/screens/settings/display_theme/display_theme.tsx
Labels: CherryPick/Approved, 3: QA Review, release-note

#7471 Automated cherry pick of #7470
  app/screens/settings/display_theme/custom_theme.tsx
  app/screens/settings/display_theme/display_theme.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7465 Fix keyboard overlap with recent search items in the search tab
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7474 Automated cherry pick of #7465
  app/screens/home/search/search.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7475 Bump Version to 2.7.0 build 480
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7476 Automated cherry pick of #7475
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none
