Repository mattermost/mattermost-mobile, pull requests merged in 2023-06, with the labels that each got.

#7383 conditionally set the current user status
  app/actions/remote/user.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7381 Fix bad use of updatelocaluser on fetchChannelMember
  app/actions/remote/channel.ts
  app/client/rest/channels.ts
Labels: 4: Reviews Complete, release-note

#7386 Automated cherry pick of #7379
  app/actions/local/user.ts
  app/actions/websocket/index.ts
  app/actions/websocket/users.ts
  app/managers/websocket_manager.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7385 Remove double text for SSO login method
  app/screens/login/sso_options.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7382 Native fetch users on attachments
  android/app/src/main/java/com/mattermost/helpers/push_notification/Post.kt
  ios/Gekidou/Sources/Gekidou/DataTypes/Post.swift
  ios/Gekidou/Sources/Gekidou/Networking/Network+Posts.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Posts.swift
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7387 Automated cherry pick of #7385
  app/screens/login/sso_options.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7390 Automated cherry pick of #7389
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7087 Migrate to GitHub actions
  .circleci/config.yml
  .github/actions/prepare-android-build/action.yaml
  .github/actions/prepare-ios-build/action.yaml
  .github/actions/prepare-mobile-build/action.yaml
  .github/actions/prepare-node-deps/action.yaml
  .github/actions/test/action.yaml
  .github/workflows/build-android-beta.yml
  .github/workflows/build-android-release.yml
  .github/workflows/build-ios-beta.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-pr.yml
  .github/workflows/ci.yml
  .github/workflows/github-release.yml
  .gitignore
  fastlane/.env.android.beta
  fastlane/.env.android.pr
  fastlane/.env.android.release
  fastlane/.env.default
  fastlane/.env.ios.beta
  fastlane/.env.ios.pr
  fastlane/.env.ios.release
  fastlane/.env.ios.simulator
  fastlane/Fastfile
  fastlane/Gemfile
  fastlane/Gemfile.lock
Labels: 2: Dev Review, release-note-none

#7394 feat: Migrate to Github Actions
  .circleci/config.yml
  .github/actions/prepare-android-build/action.yaml
  .github/actions/prepare-ios-build/action.yaml
  .github/actions/prepare-mobile-build/action.yaml
  .github/actions/prepare-node-deps/action.yaml
  .github/actions/test/action.yaml
  .github/workflows/build-android-beta.yml
  .github/workflows/build-android-release.yml
  .github/workflows/build-ios-beta.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-pr.yml
  .github/workflows/ci.yml
  .github/workflows/github-release.yml
  .gitignore
  fastlane/.env.android.beta
  fastlane/.env.android.pr
  fastlane/.env.android.release
  fastlane/.env.default
  fastlane/.env.ios.beta
  fastlane/.env.ios.pr
  fastlane/.env.ios.release
  fastlane/.env.ios.simulator
  fastlane/Fastfile
  fastlane/Gemfile
  fastlane/Gemfile.lock
Labels: release-note, kind/feature

#7396 Bump build to 474
  android/app/build.gradle
  fastlane/Gemfile
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: CherryPick/Approved, release-note-none

#7397 Automated cherry pick of #7396
  android/app/build.gradle
  fastlane/Gemfile
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7398 fix env var for sentry project android
  fastlane/.env.android.beta
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7399 Automated cherry pick of #7398
  fastlane/.env.android.beta
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7400 Fix onViewableItemsChanged item id
  app/components/post_list/post_list.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/pinned_messages/pinned_messages.tsx
  package-lock.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7401 Automated cherry pick of #7400
  app/components/post_list/post_list.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/pinned_messages/pinned_messages.tsx
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7402 Bump app build number to 475
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7403 Automated cherry pick of #7402
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7338 MM-52653 - Calls: Attach call to existing thread on `/call start`
  app/components/post_draft/send_handler/send_handler.tsx
  app/products/calls/actions/calls.ts
  app/products/calls/alerts.ts
  app/products/calls/connection/connection.ts
Labels: 4: Reviews Complete, release-note

#7407 fix: fastlane working dir
  .github/workflows/github-release.yml
Labels: CherryPick/Approved, release-note, kind/bug

#7408 Automated cherry pick of #7407
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7410 fix: Fix expected names for releases
  .github/workflows/github-release.yml
Labels: CherryPick/Approved, release-note, kind/bug

#7411 Automated cherry pick of #7410
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7413 set path and name for unsigned builds
  .github/workflows/github-release.yml
Labels: CherryPick/Approved, release-note-none, kind/bug

#7414 Automated cherry pick of #7413
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7417 Fix MarkThreadAsRead on notifications
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7416 Fix image attachment overlap
  app/components/files/image_file.tsx
  app/components/progressive_image/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#7419 Automated cherry pick of #7416
  app/components/files/image_file.tsx
  app/components/progressive_image/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7406 Fix fetching unreads from archived channels, fetching groups on unlicensed servers and logs
  app/actions/remote/groups.ts
  app/actions/remote/post.ts
  app/utils/errors.ts
Labels: 4: Reviews Complete, release-note

#7418 Automated cherry pick of #7417
  app/init/push_notifications.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7351 Added localization into iOS share extension
  app/utils/file/index.ts
  assets/base/i18n/en.json
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/i18n/ar.lproj/Localizable.strings
  ios/Mattermost/i18n/bg.lproj/Localizable.strings
  ios/Mattermost/i18n/de.lproj/Localizable.strings
  ios/Mattermost/i18n/en.lproj/Localizable.strings
  ios/Mattermost/i18n/en_AU.lproj/Localizable.strings
  ios/Mattermost/i18n/es.lproj/Localizable.strings
  ios/Mattermost/i18n/fa.lproj/Localizable.strings
  ios/Mattermost/i18n/fr.lproj/Localizable.strings
  ios/Mattermost/i18n/hu.lproj/Localizable.strings
  ios/Mattermost/i18n/it.lproj/Localizable.strings
  ios/Mattermost/i18n/ja.lproj/Localizable.strings
  ios/Mattermost/i18n/ko.lproj/Localizable.strings
  ios/Mattermost/i18n/nl.lproj/Localizable.strings
  ios/Mattermost/i18n/pl.lproj/Localizable.strings
  ios/Mattermost/i18n/pt-BR.lproj/Localizable.strings
  ios/Mattermost/i18n/ro.lproj/Localizable.strings
  ios/Mattermost/i18n/ru.lproj/Localizable.strings
  ios/Mattermost/i18n/sv.lproj/Localizable.strings
  ios/Mattermost/i18n/tr.lproj/Localizable.strings
  ios/Mattermost/i18n/uk.lproj/Localizable.strings
  ios/Mattermost/i18n/zh-CN.lproj/Localizable.strings
  ios/Mattermost/i18n/zh-TW.lproj/Localizable.strings
  ios/MattermostShare/Extensions/Int64.swift
  ios/MattermostShare/Extensions/NumberFormatter.swift
  ios/MattermostShare/Info.plist
  ios/MattermostShare/Views/ContentViews/AttachmentsViews/AttachmentsView.swift
  ios/MattermostShare/Views/ContentViews/AttachmentsViews/MultipleAttachmentView.swift
  ios/MattermostShare/Views/ContentViews/ChannelListView/ChannelListView.swift
  ios/MattermostShare/Views/ContentViews/ChannelListView/SearchBarView.swift
  ios/MattermostShare/Views/ContentViews/ContentView.swift
  ios/MattermostShare/Views/ContentViews/FloatingTextField.swift
  ios/MattermostShare/Views/ErrorViews/ErrorSharingView.swift
  ios/MattermostShare/Views/ErrorViews/NoMembershipView.swift
  ios/MattermostShare/Views/ErrorViews/NoServersView.swift
  ios/MattermostShare/Views/InitialView.swift
  share_extension/screens/channels.tsx
  share_extension/screens/share.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7420 Bump react-native-network-client to 1.3.4
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7422 Automated cherry pick of #7420
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7421 Bump version to 2.5.1 build 476
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7409 Update Dependencies
  android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
  android/app/src/main/java/com/mattermost/helpers/database_extension/General.kt
  app/database/operator/base_data_operator/index.ts
  app/managers/global_event_handler.ts
  app/screens/bottom_sheet/index.tsx
  app/screens/custom_status_clear_after/index.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/home/index.tsx
  app/screens/index.tsx
  babel.config.js
  detox/package-lock.json
  detox/package.json
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@nozbe+watermelondb+0.25.5.patch
  patches/@nozbe+watermelondb+0.26.0.patch
  patches/@react-native-community+netinfo+9.3.10.patch
  patches/@rudderstack+rudder-sdk-react-native+1.7.1.patch
  patches/@sentry+utils+7.54.0.patch
  patches/@stream-io+flat-list-mvcp+0.10.2.patch
  patches/@types+react-syntax-highlighter+15.5.7.patch
  patches/react-native+0.71.11.patch
  patches/react-native-button+3.0.1.patch
  patches/react-native-button+3.1.0.patch
  patches/react-native-navigation+7.33.4.patch
  patches/react-native-notifications+4.3.5.patch
  patches/react-native-reanimated+3.3.0.patch
  test/setup.ts
Labels: 3: QA Review, release-note-none

#7415 Updated text in post priority popover
  app/screens/post_priority_picker/index.ts
  app/screens/post_priority_picker/post_priority_picker.tsx
  app/screens/post_priority_picker/utils.ts
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: 4: Reviews Complete, release-note-none

#7366 Fix edit post input height and looks
  app/screens/edit_post/edit_post.tsx
  app/screens/edit_post/edit_post_input/index.tsx
Labels: 4: Reviews Complete, release-note

#7393 Remove output redirection to resolve stuck behavior in pod-install
  scripts/build.sh
  scripts/postinstall.sh
Labels: 2: Dev Review, release-note

#7427 CLD-5901 Fix: iOS simulator download link
  fastlane/Fastfile
Labels: 4: Reviews Complete, release-note-none

#7428 Automated cherry pick of #7426
  android/app/src/main/java/com/mattermost/helpers/Network.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7405 Fix problems related to closing react but keeping other state
  app/actions/remote/notifications.ts
  app/init/app.ts
  app/init/launch.ts
  app/screens/navigation.ts
  app/store/ephemeral_store.ts
  app/store/navigation_store.ts
  index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7431 Automated cherry pick of #7405
  app/actions/remote/notifications.ts
  app/init/app.ts
  app/init/launch.ts
  app/screens/navigation.ts
  app/store/ephemeral_store.ts
  app/store/navigation_store.ts
  index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7425 Remove guest tags based on config
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/header/index.ts
  app/components/post_list/post/header/tag/index.tsx
  app/components/post_list/post/system_message/index.tsx
  app/components/post_list/post/system_message/system_message.tsx
  app/components/user_item/index.ts
  app/components/user_item/user_item.tsx
  app/screens/channel_info/title/direct_message/direct_message.tsx
  app/screens/channel_info/title/direct_message/index.ts
  app/screens/user_profile/index.ts
  app/screens/user_profile/title/index.tsx
  app/screens/user_profile/title/tag.tsx
  app/screens/user_profile/user_profile.tsx
  types/api/config.d.ts
Labels: 4: Reviews Complete, release-note
