Repository mattermost/mattermost-mobile, pull requests merged in 2023-03, with the labels that each got.

#7171 Fix iOS push notification when set as generic message with sender name
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, release-note

#7173 ignore leading and trailing spaces when editing profile
  app/screens/edit_profile/edit_profile.tsx
Labels: 2: Dev Review, release-note-none

#7172 Fix potential reaction crash
  app/components/post_list/post/body/reactions/reactions.tsx
  app/utils/emoji/helpers.ts
Labels: 4: Reviews Complete, release-note-none

#7174 trigger Search when hardware keyboard enter key is pressed
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, release-note-none

#7176 use sourceScreen instead of location in post options
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/screens/post_options/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7179 fix entry for tablets
  app/actions/remote/entry/common.ts
  app/actions/websocket/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7181 Fix display name when open own DM
  app/components/selected_users/index.tsx
  app/screens/create_direct_message/create_direct_message.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#7182 support WS connection over TLS1.3
  app/components/post_draft/post_input/post_input.tsx
  ios/Podfile
  ios/Podfile.lock
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7183 Fix push notification token registration race/missing
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7170 Refactor category channels to react to setting changes and apply the correct order
  android/app/src/main/java/com/mattermost/helpers/push_notification/Channel.kt
  app/constants/preferences.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/queries/servers/categories.ts
  app/queries/servers/channel.ts
  app/screens/home/channel_list/categories_list/categories/body/category_body.test.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/utils/categories.ts
  types/database/models/servers/category.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7184 Bump app build number to 460
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note

#7185 Fix race condition when the same websocket gets initialized twice
  app/client/websocket/index.ts
  app/utils/config.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7190 Performance fixes and fix manual sort
  app/components/team_sidebar/team_sidebar.tsx
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/screens/home/channel_list/categories_list/header/index.ts
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
  app/utils/categories.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#7192 Bump app build number to 461
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#7191 Consider ExperimentalGroupUnreadChannels for unreads on top
  app/screens/home/channel_list/categories_list/categories/index.ts
Labels: 4: Reviews Complete, release-note

#7198 MM-51226 - Calls: Emojis not showing in reaction stream
  app/products/calls/components/call_avatar.tsx
  app/products/calls/components/emoji_list.tsx
  app/products/calls/components/emoji_pill.tsx
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  ios/Podfile.lock
Labels: 4: Reviews Complete, release-note

#7197 Fix guest badge not appearing on member list
  app/components/user_list/index.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
Labels: 4: Reviews Complete, release-note

#7203 [Release 2.2 cherrypick] Add missing podfile change
  ios/Podfile.lock
Labels: 4: Reviews Complete, release-note-none

#7210 Fix muted channels not being filtered out on the categories list
  app/utils/categories.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7217 Bump app version number to 2.2.0 and build number to 462
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: release-note-none

#7205 MM-51362 - Fix proximity notice engaging after call ended
  app/products/calls/actions/calls.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  types/modules/react-native-incall-manager.d.ts
Labels: 4: Reviews Complete, release-note-none

#7213 MM-51469 - Calls: Fix for app crashes when screen presenter leaves
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
Labels: 4: Reviews Complete, release-note

#7211 MM-50010 - Share common calls code between web and mobile
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/call_avatar.tsx
  app/products/calls/connection/connection.ts
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/rtcpeer/index.ts
  app/products/calls/rtcpeer/types.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/state/calls_config.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
  jest.config.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#7225 Add debug logs
  app/actions/remote/general.ts
  app/actions/remote/post.ts
  app/screens/home/tab_bar/home.tsx
Labels: 4: Reviews Complete, release-note

#7224 Consider unread when mentions are present regardless of muted state
  app/utils/categories.ts
Labels: 4: Reviews Complete, release-note

#7229 MM-50533 - Calls: Prioritize raised hand when ordering participants
  app/products/calls/utils.ts
Labels: 4: Reviews Complete, release-note

#7228 photo permission alert is not displayed properly
  app/utils/file/file_picker/index.ts
Labels: 2: Dev Review, release-note, Contributor

#7231 Prevent in-app notification and snackbar from blocking gestures
  package-lock.json
  patches/react-native-navigation+7.32.1.patch
Labels: 3: QA Review, release-note-none

#7232 Bump app build number to 463
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#7233 Translations update from Mattermost Weblate
  assets/base/i18n/zh-CN.json
Labels: release-note-none

#7199 Tapping on a custom status in the message list opens the users profile card
  app/components/post_list/post/header/display_name/index.tsx
  app/components/post_list/post/header/header.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7226 MM-51227 - Calls: Landscape mode optimizations for screensharing
  app/products/calls/components/reaction_bar.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
Labels: 4: Reviews Complete, release-note

#7227 [MM-44655 ]: Add files_count column in ChannelInfo table and DB migration
  app/actions/remote/channel.ts
  app/database/migration/server/index.ts
  app/database/models/server/channel_info.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/transformers/channel.test.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/channel_info.ts
  app/database/schema/server/test.ts
  app/queries/servers/channel.ts
  app/utils/graphql.ts
  docs/database/server/server.md
  types/api/channels.d.ts
  types/api/graphql.d.ts
  types/database/models/servers/channel_info.ts
  types/database/raw_values.d.ts
Labels: 4: Reviews Complete, release-note

#7222 Update members count on remove users
  app/components/channel_actions/manage_members_label/manage_members_label.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7214 [MM-50324]: Increase nickname field on UI from 22 to 64 characters
  app/screens/edit_profile/components/form.tsx
Labels: 4: Reviews Complete, release-note

#7245 Automated cherry pick of #7222
  app/components/channel_actions/manage_members_label/manage_members_label.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7237 Fix iOS Push notification crashes
  app/init/launch.ts
  app/init/push_notifications.ts
  app/screens/in_app_notification/index.tsx
  ios/Gekidou/Sources/Gekidou/Networking/Network+Users.swift
  ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+ProfileImage.swift
  ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7248 use xcode 14.2.0 on circleCI
  .circleci/config.yml
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7247 Enable flipper on iOS
  ios/Mattermost/AppDelegate.mm
Labels: 4: Reviews Complete, release-note-none

#7241 Update NOTICE.txt
  NOTICE.txt
Labels: CherryPick/Approved, release-note-none

#7244 Handle undefined metadata all over the app
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/components/post_list/post/body/content/image_preview/image_preview.tsx
  app/components/post_list/post/body/content/image_preview/index.ts
  app/components/post_list/post/body/content/index.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_fields.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_pretext.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_text.tsx
  app/components/post_list/post/body/content/message_attachments/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/post_list/post/body/content/opengraph/opengraph.tsx
  app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx
  app/components/post_list/post/body/content/youtube/index.tsx
  app/utils/images/index.ts
  app/utils/url/index.ts
  types/api/posts.d.ts
Labels: CherryPick/Approved, release-note

#7249 Bump react-native-network-client to version 1.3.3
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: CherryPick/Approved, release-note

#7253 Cherry pick - Handle undefined metadata all over the app (#7244)
  app/components/markdown/markdown.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/components/post_list/post/body/content/image_preview/image_preview.tsx
  app/components/post_list/post/body/content/image_preview/index.ts
  app/components/post_list/post/body/content/index.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_fields.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_pretext.tsx
  app/components/post_list/post/body/content/message_attachments/attachment_text.tsx
  app/components/post_list/post/body/content/message_attachments/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/post_list/post/body/content/opengraph/opengraph.tsx
  app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx
  app/components/post_list/post/body/content/youtube/index.tsx
  app/utils/images/index.ts
  app/utils/url/index.ts
  types/api/posts.d.ts
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#7255 revert changes made to in_app_notifications
  app/screens/in_app_notification/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7251 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none

#7256 Bump version to 2.3.0 and build number to 464
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7257 Bump version to 2.3.0 and build number to 464 (#7256)
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: release-note
