Repository mattermost/mattermost-mobile, pull requests merged in 2023-12, with the labels that each got.

#7697 MM-55621 fix layout for tablets and foldables
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/FoldableObserver.kt
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  android/app/src/main/java/com/mattermost/rnbeta/SplitViewModule.kt
  app/actions/local/channel.ts
  app/actions/local/thread.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/team.ts
  app/actions/websocket/index.ts
  app/actions/websocket/posts.ts
  app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/constants/device.ts
  app/context/device/index.test.tsx
  app/context/device/index.tsx
  app/database/components/index.tsx
  app/hooks/device.ts
  app/init/push_notifications.ts
  app/managers/analytics.ts
  app/products/calls/components/audio_device_button.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
  app/screens/navigation.ts
  app/utils/helpers.ts
  ios/Mattermost/Modules/SplitViewModule.m
  ios/Mattermost/Modules/SplitViewModule.swift
  test/setup.ts
  types/global/device.d.ts
Labels: release-note-none

#7700 Bump build version to 498
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#7698 MM-54575 fix server & user list tutorials
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/components/user_list_row/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Labels: 3: QA Review, release-note

#7701 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none

#7705 Bump to version 2.12.0 build 499
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7706 Automated cherry pick of #7705
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7685 CLD-6707 Automate weekly build
  scripts/bump.sh
  scripts/get_latest_build_number.sh
Labels: release-note-none

#7711 CLD-6707 Followup fixes
  scripts/bump.sh
Labels: release-note-none

#7688 [MM-51088] fix: height for multiple line floating text input
  app/components/floating_text_input_label/index.tsx
  app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7707 Translations update from Mattermost Weblate
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#7720 Fix typo: use correct base branch in PR creation
  scripts/bump.sh
Labels: release-note-none

#7718 feat: Enable true labeled trigger and deprecate mattermod
  .github/workflows/build-pr.yml
Labels: release-note, kind/feature

#7726 Translations update from Mattermost Weblate
  assets/base/i18n/ko.json
Labels: release-note-none, Do Not Merge/Mattermod

#7704 MM-54866 - Calls: Transcription notifications
  app/products/calls/alerts.ts
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#7650 Improves get roles by names requests to batch them following the new endpoint limit
  app/actions/remote/role.ts
  app/constants/general.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#7735 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/vi.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: release-note-none
