Repository mattermost/mattermost-mobile, pull requests merged in 2023-04, with the labels that each got.

#7268 Use `bash` to run scripts
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7269 Automated cherry pick of #7268
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7270 Automated cherry pick of #7249
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7271 Bump app build number to 465
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#7206 Check server identifier before login
  app/components/floating_text_input_label/index.tsx
  app/screens/server/form.tsx
  app/screens/server/index.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#7284 Automated cherry pick of #7271
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7280 Fix file attachment limited to one file
  app/components/post_draft/quick_actions/file_quick_action/index.tsx
Labels: 4: Reviews Complete, release-note

#7267 [MM-42565] Toast - Follow/Unfollow thread with undo functionality
  app/actions/remote/thread.ts
  app/components/common_post_options/follow_thread_option/follow_thread_option.tsx
  app/components/post_list/post/footer/footer.tsx
  app/components/toast/index.tsx
  app/constants/snack_bar.ts
  app/screens/thread/thread_follow_button/thread_follow_button.tsx
  app/utils/snack_bar/index.ts
Labels: 2: Dev Review, release-note, Contributor

#7223 [MM-44655] : Add channel files screen
  app/components/files/file_filter.tsx
  app/components/files_search/file_options/header.tsx
  app/components/files_search/file_options/icon.tsx
  app/components/files_search/file_options/mobile_options.tsx
  app/components/files_search/file_options/option_menus/index.tsx
  app/components/files_search/file_options/option_menus/option_menus.tsx
  app/components/files_search/file_options/tablet_options.tsx
  app/components/files_search/file_options/toasts.tsx
  app/components/files_search/file_result.tsx
  app/components/files_search/file_results.tsx
  app/components/files_search/no_results.tsx
  app/constants/screens.ts
  app/screens/channel_files/channel_files.tsx
  app/screens/channel_files/header.tsx
  app/screens/channel_files/index.ts
  app/screens/channel_info/options/channel_files/channel_files.tsx
  app/screens/channel_info/options/channel_files/index.ts
  app/screens/channel_info/options/index.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/index.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note

#7285 Bump app build number to 466
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, release-note-none

#7291 Fix channels showing empty
  app/client/rest/posts.ts
  app/screens/channel/channel_post_list/channel_post_list.tsx
Labels: 4: Reviews Complete, release-note

#7292 Request missing write to storage permission to use the camera on Android 9 and below
  app/utils/file/file_picker/index.ts
Labels: 4: Reviews Complete, release-note

#7289 Fix channel not marked as unread on notification entry
  app/actions/websocket/posts.ts
Labels: 4: Reviews Complete, release-note-none

#7230 Added support for self-hosted Sentry
  fastlane/Fastfile
  fastlane/env_vars_example
  ios/bundleReactNative.sh
  ios/makeSentryProperties.sh
  ios/uploadDebugSymbols.sh
Labels: release-note, Contributor

#7290 Fix out of order websocket events for posts
  app/actions/websocket/posts.ts
  app/store/ephemeral_store.ts
  patches/@nozbe+watermelondb+0.25.5.patch
Labels: 2: Dev Review, release-note

#7302 Fix the query undefined comparison when threadId prop is not set by the nav library
  app/actions/local/thread.ts
  app/actions/remote/channel.ts
  app/actions/remote/team.ts
  app/components/channel_actions/leave_channel_label/leave_channel_label.tsx
  app/components/markdown/hashtag/index.tsx
  app/queries/servers/thread.ts
  app/screens/navigation.ts
  app/screens/thread/thread_follow_button/index.ts
  app/utils/error_handling.ts
Labels: 4: Reviews Complete, release-note

#7303 Added localization for iOS plist files
  app/constants/permissions.ts
  assets/base/i18n/en.json
  fastlane/Fastfile
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/Mattermost/i18n/ar.lproj/InfoPlist.strings
  ios/Mattermost/i18n/bg.lproj/InfoPlist.strings
  ios/Mattermost/i18n/de.lproj/InfoPlist.strings
  ios/Mattermost/i18n/en.lproj/InfoPlist.strings
  ios/Mattermost/i18n/en_AU.lproj/InfoPlist.strings
  ios/Mattermost/i18n/es.lproj/InfoPlist.strings
  ios/Mattermost/i18n/fa.lproj/InfoPlist.strings
  ios/Mattermost/i18n/fr.lproj/InfoPlist.strings
  ios/Mattermost/i18n/hu.lproj/InfoPlist.strings
  ios/Mattermost/i18n/it.lproj/InfoPlist.strings
  ios/Mattermost/i18n/ja.lproj/InfoPlist.strings
  ios/Mattermost/i18n/ko.lproj/InfoPlist.strings
  ios/Mattermost/i18n/nl.lproj/InfoPlist.strings
  ios/Mattermost/i18n/pl.lproj/InfoPlist.strings
  ios/Mattermost/i18n/pt-BR.lproj/InfoPlist.strings
  ios/Mattermost/i18n/ro.lproj/InfoPlist.strings
  ios/Mattermost/i18n/ru.lproj/InfoPlist.strings
  ios/Mattermost/i18n/sv.lproj/InfoPlist.strings
  ios/Mattermost/i18n/tr.lproj/InfoPlist.strings
  ios/Mattermost/i18n/uk.lproj/InfoPlist.strings
  ios/Mattermost/i18n/zh-CN.lproj/InfoPlist.strings
  ios/Mattermost/i18n/zh-TW.lproj/InfoPlist.strings
Labels: 4: Reviews Complete, release-note

#7305 Bump app build number to 467
  android/app/build.gradle
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#7298 Reduce minimum NPM version to match web app
  .solidarity
Labels: 4: Reviews Complete, release-note-none

#7312 Update README.md
  README.md
Labels: release-note-none

#7293 MM-43737 - Calls: Follow call thread on user joining a call
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/queries/servers/thread.ts
Labels: 4: Reviews Complete, release-note

#7142 [MM-49540] Message Priority Phase 3
  app/actions/local/draft.ts
  app/actions/local/post.ts
  app/actions/remote/post.ts
  app/actions/websocket/index.ts
  app/actions/websocket/posts.ts
  app/client/rest/posts.ts
  app/components/channel_item/index.ts
  app/components/option_item/index.tsx
  app/components/post_draft/draft_input/header.tsx
  app/components/post_draft/draft_input/index.tsx
  app/components/post_draft/index.ts
  app/components/post_draft/quick_actions/index.ts
  app/components/post_draft/quick_actions/post_priority_action/index.tsx
  app/components/post_draft/quick_actions/quick_actions.tsx
  app/components/post_draft/send_handler/index.ts
  app/components/post_draft/send_handler/send_handler.tsx
  app/components/post_list/index.ts
  app/components/post_list/post/body/acknowledgements/acknowledgements.tsx
  app/components/post_list/post/body/acknowledgements/index.ts
  app/components/post_list/post/body/acknowledgements/users_list/index.ts
  app/components/post_list/post/body/acknowledgements/users_list/user_list_item.tsx
  app/components/post_list/post/body/acknowledgements/users_list/users_list.tsx
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post/body/reactions/reactions.tsx
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/components/post_list/post_list.tsx
  app/components/post_priority/post_priority_label.tsx
  app/components/post_priority/post_priority_picker/index.tsx
  app/components/post_priority/post_priority_picker/post_priority_picker_item.tsx
  app/components/user_item/user_item.tsx
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/constants/autocomplete.test.ts
  app/constants/autocomplete.ts
  app/constants/screens.ts
  app/constants/websocket.ts
  app/database/operator/server_data_operator/transformers/post.ts
  app/helpers/api/user.ts
  app/queries/servers/drafts.ts
  app/queries/servers/post.ts
  app/queries/servers/system.ts
  app/screens/index.tsx
  app/screens/post_priority_picker/components/picker_option.tsx
  app/screens/post_priority_picker/footer.tsx
  app/screens/post_priority_picker/index.ts
  app/screens/post_priority_picker/post_priority_picker.tsx
  app/screens/post_priority_picker/utils.ts
  app/store/ephemeral_store.ts
  app/utils/post/index.test.ts
  app/utils/post/index.ts
  assets/base/i18n/en.json
  types/api/config.d.ts
  types/api/posts.d.ts
  types/database/raw_values.d.ts
Labels: 2: UX Review, release-note

#7286 MM-51776 - Calls: Audio device selections, & fix bluetooth
  app/products/calls/actions/calls.ts
  app/products/calls/actions/permissions.ts
  app/products/calls/alerts.ts
  app/products/calls/components/audio_device_button.ios.tsx
  app/products/calls/components/audio_device_button.tsx
  app/products/calls/connection/connection.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  assets/base/i18n/en.json
  package-lock.json
  package.json
  types/modules/react-native-incall-manager.d.ts
Labels: 4: Reviews Complete, release-note

#7314 small refactor to include thread follow button
  app/actions/local/thread.ts
  app/screens/thread/index.tsx
  app/screens/thread/thread.tsx
  app/screens/thread/thread_follow_button/index.ts
Labels: 4: Reviews Complete, release-note-none

#7316 Update supported ESR version
  README.md
  app/constants/supported_server.ts
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
Labels: 4: Reviews Complete, release-note-none

#7297 MM-52173 Add setting to delay channel autocomplete
  app/components/autocomplete/channel_mention/index.ts
  app/constants/autocomplete.ts
  types/api/config.d.ts
Labels: QA Review Done, release-note

#7317 Fixed exception on accessing 'payload' of undefined in InAppNotification
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#7318 MM-52342 - Use CallState and CallChannelState from @mattermost/calls
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/types/calls.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#7310 fix small images style
  app/components/files/file.tsx
  app/components/files/image_file.tsx
Labels: 2: Dev Review, release-note-none

#7319 Bump app build number to 468
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none
