Repository mattermost/mattermost-mobile, pull requests merged in 2023-01, with the labels that each got.

#6920 Fix unarchive action
  app/actions/remote/channel.ts
Labels: 4: Reviews Complete, release-note-none

#6919 Dismiss correct bottom sheet screen for post / thread options
  app/components/common_post_options/copy_permalink_option/copy_permalink_option.tsx
  app/components/common_post_options/follow_thread_option/follow_thread_option.tsx
  app/components/common_post_options/reply_option.tsx
  app/components/common_post_options/save_option.tsx
  app/screens/post_options/options/app_bindings_post_option.tsx
  app/screens/post_options/options/copy_text_option.tsx
  app/screens/post_options/options/delete_post_option.tsx
  app/screens/post_options/options/edit_option.tsx
  app/screens/post_options/options/mark_unread_option/mark_unread_option.tsx
  app/screens/post_options/options/pin_channel_option.tsx
  app/screens/post_options/post_options.tsx
  app/screens/post_options/reaction_bar/reaction_bar.tsx
  app/screens/thread_options/options/mark_as_unread_option.tsx
  app/screens/thread_options/options/open_in_channel_option.tsx
  app/screens/thread_options/thread_options.tsx
Labels: 4: Reviews Complete, release-note-none

#6915 Android Fixes
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  patches/react-native-navigation+7.30.6.patch
Labels: 2: Dev Review, release-note-none

#6927 Reduce the amount of queries to display the PostList
  app/components/post_list/index.ts
  app/components/post_list/more_messages/more_messages.tsx
  app/components/post_list/new_message_line/index.tsx
  app/components/post_list/post/index.ts
  app/components/post_list/post/post.tsx
  app/components/post_list/post_list.tsx
  app/components/post_with_channel_info/index.ts
  app/components/post_with_channel_info/post_with_channel_info.tsx
  app/queries/servers/post.ts
  app/screens/global_threads/threads_list/threads_list.tsx
  app/screens/home/recent_mentions/index.ts
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/index.ts
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/results/file_results.tsx
  app/screens/home/search/results/index.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/pinned_messages/index.ts
  app/screens/pinned_messages/pinned_messages.tsx
  app/utils/emoji/helpers.ts
  app/utils/post_list/index.ts
  types/components/post_list.ts
Labels: 2: Dev Review, release-note-none

#6921 Use Promise.allSettle when fetching emojis
  app/actions/remote/custom_emoji.ts
  app/components/emoji/emoji.tsx
  app/init/app.ts
Labels: 2: Dev Review, release-note-none

#6923 update dependencies
  detox/package-lock.json
  detox/package.json
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-elements+3.4.3.patch
Labels: 4: Reviews Complete, release-note-none

#6926 [MM-47406] Exclude muted channel's mentions count
  app/database/models/server/my_channel.ts
  app/queries/servers/channel.ts
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/home/tab_bar/home.tsx
  ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift
Labels: 4: Reviews Complete, release-note-none

#6929 Detox Report: Add commit hash to report
  detox/save_report.js
  detox/utils/artifacts.js
  detox/utils/report.js
  detox/utils/test_cases.js
Labels: 4: Reviews Complete, release-note-none

#6924 Display own DM avatar in channel intro
  app/screens/channel/channel_post_list/intro/direct_channel/direct_channel.tsx
Labels: 4: Reviews Complete, release-note-none

#6907 BottomSheet migration to react-native-bottom-sheet
  NOTICE.txt
  app/components/announcement_banner/announcement_banner.tsx
  app/components/announcement_banner/expanded_announcement_banner.tsx
  app/components/channel_actions/channel_actions.tsx
  app/components/markdown/at_mention/at_mention.tsx
  app/components/markdown/markdown_code_block/index.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_latex_block/index.tsx
  app/components/markdown/markdown_link/markdown_link.tsx
  app/components/post_draft/quick_actions/camera_quick_action/index.tsx
  app/components/post_draft/quick_actions/post_priority_action/index.tsx
  app/components/post_list/post/body/failed/index.tsx
  app/components/post_priority/post_priority_picker/index.tsx
  app/components/team_list/index.tsx
  app/components/user_avatars_stack/index.tsx
  app/components/user_avatars_stack/users_list/index.tsx
  app/constants/reaction_picker.ts
  app/constants/view.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/screens/bottom_sheet/button.tsx
  app/screens/bottom_sheet/content.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/bottom_sheet/indicator.tsx
  app/screens/browse_channels/channel_dropdown.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/quick_actions/index.tsx
  app/screens/edit_profile/components/profile_image_picker.tsx
  app/screens/home/account/components/options/user_presence/index.tsx
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/channel_list/servers/servers_list/add_server_button.tsx
  app/screens/home/channel_list/servers/servers_list/index.tsx
  app/screens/home/search/bottom_sheet_team_list.tsx
  app/screens/home/search/results/file_options/mobile_options.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/team_picker_icon.tsx
  app/screens/navigation.ts
  app/screens/post_options/post_options.tsx
  app/screens/reactions/reactions.tsx
  app/screens/reactions/reactors_list/index.tsx
  app/screens/thread_options/thread_options.tsx
  app/screens/user_profile/user_profile.tsx
  app/utils/helpers.ts
  app/utils/team_list/index.ts
  package-lock.json
  package.json
  types/components/bottom_sheet.d.ts
Labels: release-note-none

#6932 Cache push notification profile image and add logs
  app/screens/settings/advanced/index.tsx
  app/utils/file/index.ts
  ios/Gekidou/Sources/Gekidou/FileCache.swift
  ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift
  ios/NotificationService/NotificationService.swift
Labels: 2: Dev Review, release-note-none

#6922 Generate video thumb from file url instead of public url
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  app/components/files/video_file.tsx
  ios/GekidouWrapper.swift
  ios/Mattermost/MattermostManaged.m
  patches/react-native-create-thumbnail+1.6.4.patch
Labels: 2: Dev Review, release-note-none

#6931 Detox Maintenance: Skip tests that are unstable and cleanup known issues
  detox/e2e/support/server_api/default_config.json
  detox/e2e/support/server_api/plugin.ts
  detox/e2e/test/autocomplete/at_mention.e2e.ts
  detox/e2e/test/messaging/at_mention.e2e.ts
  detox/e2e/test/messaging/markdown_latex.e2e.ts
  detox/e2e/test/messaging/markdown_list.e2e.ts
  detox/e2e/test/threads/global_threads.e2e.ts
  detox/save_report.js
  detox/utils/report.js
Labels: 4: Reviews Complete, release-note-none

#6934 Preserve new message line on WS reconnect
  app/actions/local/channel.ts
  app/actions/websocket/channel.ts
  app/actions/websocket/index.ts
  app/actions/websocket/posts.ts
  app/init/push_notifications.ts
Labels: 4: Reviews Complete, release-note-none

#6935 Fix crashes found in NotificationService
  ios/Gekidou/Sources/Gekidou/Networking/Network+Mentions.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+Posts.swift
Labels: 2: Dev Review, release-note-none

#6936 CI fixes
  .circleci/config.yml
  fastlane/Fastfile
Labels: 4: Reviews Complete, release-note-none

#6937 Bump app build number to 447
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6938 update deps
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@types+react-syntax-highlighter+15.5.6.patch
Labels: 4: Reviews Complete, release-note-none

#6939 Bump app build number to 448
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6940 Bump app build number to 449
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#6946 Fix navigation theming
  app/constants/screens.ts
  app/screens/navigation.ts
  app/utils/theme/index.ts
Labels: CherryPick/Approved, release-note-none

#6951 Weblate 6947
  assets/base/i18n/ko.json
  assets/base/i18n/tr.json
Labels: 4: Reviews Complete, release-note-none

#6944 [MM-49616] Fix code syntax highlight on full screen view
  app/components/markdown/markdown_code_block/index.tsx
Labels: 4: Reviews Complete, release-note

#6950 Bump build number to 450
  .circleci/config.yml
  android/app/build.gradle
  app/actions/remote/entry/app.ts
  app/database/manager/index.ts
  app/database/migration/server/index.ts
  app/database/schema/server/index.ts
  app/helpers/database/upgrade.ts
  app/init/app.ts
  app/init/launch.ts
  app/queries/app/info.ts
  app/utils/mattermost_managed.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  types/database/manager.ts
Labels: 4: Reviews Complete, release-note-none

#6953 Automated cherry pick of #6948
  app/client/websocket/index.ts
  app/components/connection_banner/connection_banner.tsx
  app/managers/websocket_manager.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6954 Automated cherry pick of #6944
  app/components/markdown/markdown_code_block/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6955 Automated cherry pick of #6950
  .circleci/config.yml
  android/app/build.gradle
  app/actions/remote/entry/app.ts
  app/database/manager/index.ts
  app/database/migration/server/index.ts
  app/database/schema/server/index.ts
  app/helpers/database/upgrade.ts
  app/init/app.ts
  app/init/launch.ts
  app/queries/app/info.ts
  app/utils/mattermost_managed.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  types/database/manager.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6945 Detox Reporting: Fix artifact link
  detox/utils/report.js
Labels: 4: Reviews Complete, release-note-none

#6959 Add back wrongly removed Ephemeral.theme assignment
  app/utils/theme/index.ts
Labels: 4: Reviews Complete, release-note-none

#6961 Add String description in log arguments
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, release-note-none

#6962 Fix some issues found by Sentry
  app/actions/remote/post.ts
  app/managers/session_manager.ts
  app/screens/navigation.ts
Labels: 4: Reviews Complete, release-note-none

#6963 Automated cherry pick of #6959
  app/utils/theme/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6964 Automated cherry pick of #6961
  ios/NotificationService/NotificationService.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6965 Automated cherry pick of #6962
  app/actions/remote/post.ts
  app/managers/session_manager.ts
  app/screens/navigation.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6960 [MM-49619] Channel doesn't show the posts
  app/actions/websocket/posts.ts
  app/actions/websocket/threads.ts
Labels: 4: Reviews Complete, release-note-none

#6966 Automated cherry pick of #6960
  app/actions/websocket/posts.ts
  app/actions/websocket/threads.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6967 Bump app build number to 451
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6968 Automated cherry pick of #6967
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6933 New UI for Emoji picker
  app/actions/app/global.ts
  app/actions/remote/preference.ts
  app/components/emoji_picker/sections/icons_bar/index.tsx
  app/components/emoji_picker/sections/touchable_emoji.tsx
  app/components/post_list/post/body/reactions/reactions.tsx
  app/components/post_list/post/post.tsx
  app/components/touchable_emoji/index.tsx
  app/components/touchable_emoji/skinned_emoji.tsx
  app/components/user_avatars_stack/index.tsx
  app/constants/database.ts
  app/constants/index.ts
  app/constants/tutorial.ts
  app/hooks/emoji_category_bar.ts
  app/queries/app/global.ts
  app/screens/bottom_sheet/index.tsx
  app/screens/create_direct_message/index.ts
  app/screens/custom_status/custom_status.tsx
  app/screens/emoji_picker/index.tsx
  app/screens/emoji_picker/picker/emoji_category_bar/icon.tsx
  app/screens/emoji_picker/picker/emoji_category_bar/index.tsx
  app/screens/emoji_picker/picker/filtered/emoji_item.tsx
  app/screens/emoji_picker/picker/filtered/filtered.tsx
  app/screens/emoji_picker/picker/filtered/index.ts
  app/screens/emoji_picker/picker/footer/index.tsx
  app/screens/emoji_picker/picker/header/bottom_sheet_search.tsx
  app/screens/emoji_picker/picker/header/header.tsx
  app/screens/emoji_picker/picker/header/index.ts
  app/screens/emoji_picker/picker/header/skintone_selector/close_button.tsx
  app/screens/emoji_picker/picker/header/skintone_selector/index.ts
  app/screens/emoji_picker/picker/header/skintone_selector/skin_selector.tsx
  app/screens/emoji_picker/picker/header/skintone_selector/skintone_selector.tsx
  app/screens/emoji_picker/picker/header/skintone_selector/tooltip.tsx
  app/screens/emoji_picker/picker/index.ts
  app/screens/emoji_picker/picker/picker.tsx
  app/screens/emoji_picker/picker/sections/index.tsx
  app/screens/emoji_picker/picker/sections/section_footer.tsx
  app/screens/emoji_picker/picker/sections/section_header.tsx
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/index.ts
  app/screens/home/search/team_picker_icon.tsx
  app/screens/post_options/post_options.tsx
  app/screens/post_options/reaction_bar/reaction_bar.tsx
  app/screens/reactions/reactions.tsx
  app/utils/emoji/helpers.ts
  app/utils/emoji/index.ts
  assets/base/i18n/en.json
  package-lock.json
  package.json
  patches/react-native-section-list-get-item-layout+2.2.3.patch
  patches/react-native-walkthrough-tooltip+1.4.0.patch
  types/screens/emoji_selector.d.ts
Labels: 2: UX Review, release-note-none

#6972 Fix the caret position when using the search phrase modifier
  app/screens/home/search/initial/modifiers/modifier.tsx
Labels: release-note-none

#6974 Bump app build number to 452
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#6973 Automated cherry pick of #6972
  app/screens/home/search/initial/modifiers/modifier.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6975 Automated cherry pick of #6974
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6978 Fix e2e login error
  app/screens/login/index.tsx
Labels: 4: Reviews Complete, release-note-none

#6956 [MM-48282] When user selects open in channel, dismiss the bottom sheet
  app/screens/home/search/results/file_options/option_menus/option_menus.tsx
Labels: 3: QA Review, release-note

#6971 Add webhook image to notification in missing scenarios
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
Labels: 4: Reviews Complete, release-note

#6985 Remove uneeded database migrations
  app/constants/database.ts
  app/database/manager/index.ts
  app/utils/file/index.ts
  app/utils/security.ts
Labels: 4: Reviews Complete, release-note-none

#6943 MM-44652 - Fix long team name
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap
  app/screens/home/channel_list/categories_list/header/header.tsx
Labels: 4: Reviews Complete, release-note

#6995 Bump app build number to 453
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, release-note-none

#6732 [MM-47548 Gekidou] Data Retention Implementation
  app/actions/local/post.ts
  app/actions/local/systems.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/post.ts
  app/actions/remote/session.ts
  app/actions/remote/systems.ts
  app/client/rest/base.ts
  app/client/rest/general.ts
  app/constants/database.ts
  app/queries/servers/system.ts
  types/global/data_retention.d.ts
Labels: 1: Dev Testing, release-note

#6992 MM-49746 - Calls: Show call thread title in root calls post
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
Labels: 4: Reviews Complete, release-note

#6980 MM-48836 - Calls: handle slash commands
  app/components/post_draft/send_handler/send_handler.tsx
  app/products/calls/actions/calls.ts
  app/products/calls/actions/index.ts
  app/products/calls/alerts.ts
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/components/channel_info_start/channel_info_start_button.tsx
  app/products/calls/components/channel_info_start/index.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/connection/connection.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note

#6877 MM-42835_Invite People - add email+user invites
  app/actions/remote/team.ts
  app/client/rest/teams.ts
  app/components/illustrations/alert.tsx
  app/components/illustrations/error.tsx
  app/components/illustrations/success.tsx
  app/components/selected_chip/index.tsx
  app/components/selected_users/index.tsx
  app/components/selected_users/selected_user.tsx
  app/components/user_item/user_item.tsx
  app/constants/screens.ts
  app/constants/server_errors.ts
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/categories_list/header/index.ts
  app/screens/home/channel_list/categories_list/header/plus_menu/index.tsx
  app/screens/index.tsx
  app/screens/invite/index.ts
  app/screens/invite/invite.tsx
  app/screens/invite/selection.tsx
  app/screens/invite/selection_search_bar.tsx
  app/screens/invite/selection_team_bar.tsx
  app/screens/invite/summary.tsx
  app/screens/invite/summary_report.tsx
  app/screens/invite/text_item.tsx
  assets/base/i18n/en.json
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/support/ui/screen/invite.ts
  detox/e2e/support/ui/screen/server.ts
  detox/e2e/test/teams/invite_people.e2e.ts
  types/api/teams.d.ts
Labels: 2: Dev Review, 3: QA Review, release-note

#7005 Remove mock locations from jailbrake detection
  app/init/managed_app.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#7006 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#7012 [MM-49927] Calls: Fix recording message
  app/constants/post.ts
  app/products/calls/utils.ts
Labels: 4: Reviews Complete, release-note

#7007 iPad: enable rotation in all directions
  app/components/tutorial_highlight/index.tsx
  app/components/tutorial_highlight/item.tsx
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/components/user_list_row/index.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  ios/Mattermost/Info.plist
Labels: 2: UX Review, release-note

#6999 [MM-49652] Setting to enable/disable CRT
  app/constants/screens.ts
  app/queries/servers/thread.ts
  app/screens/index.tsx
  app/screens/settings/config.ts
  app/screens/settings/display/display.tsx
  app/screens/settings/display/index.tsx
  app/screens/settings/display_crt/display_crt.tsx
  app/screens/settings/display_crt/index.ts
  app/utils/thread/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, release-note-none

#7010 Fix matchDeepLink when server is on a subpath
  app/utils/deep_link/index.ts
  app/utils/url/test.ts
Labels: 4: Reviews Complete, release-note

#7026 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none

#7025 Support for Android Tablets & Foldable
  android/app/build.gradle
  android/app/src/main/java/com/mattermost/rnbeta/FoldableObserver.kt
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
  android/app/src/main/java/com/mattermost/rnbeta/SplitViewModule.kt
  app/constants/device.ts
  app/hooks/device.ts
  app/managers/global_event_handler.ts
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
  app/queries/servers/channel.ts
  app/screens/gallery/index.tsx
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/categories.test.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/navigation.ts
  app/utils/gallery/index.ts
  app/utils/helpers.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Mattermost-Bridging-Header.h
  ios/Mattermost/MattermostManaged.m
  ios/Mattermost/Modules/SplitViewModule.m
  ios/Mattermost/Modules/SplitViewModule.swift
  ios/Podfile.lock
  package-lock.json
  package.json
  test/setup.ts
  types/global/device.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7017 Automated cherry pick of #7005
  app/init/managed_app.ts
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7018 Automated cherry pick of #7010
  app/utils/deep_link/index.ts
  app/utils/url/test.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6898 MM-46312 - Calls: Replace simple-peer with RTCPeer; use up-to-date upstream react-native-webrtc
  app/products/calls/client/rest.ts
  app/products/calls/connection/connection.ts
  app/products/calls/connection/simple-peer.ts
  app/products/calls/rtcpeer/index.ts
  app/products/calls/rtcpeer/types.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.test.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  types/modules/react-native-webrtc.d.ts
Labels: 4: Reviews Complete, release-note

#6984 Fix pdf upload and pdf download from search results
  app/screens/home/search/results/file_options/option_menus/option_menus.tsx
  app/screens/home/search/results/file_options/toasts.tsx
  app/utils/file/file_picker/index.ts
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Docs/Needed, CherryPick/Approved, release-note

#7029 Fix crash when dismissing notification on android
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7035 Automated cherry pick of #7029
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7036 Automated cherry pick of #7028
  app/components/channel_item/index.ts
  app/components/common_post_options/copy_permalink_option/index.tsx
  app/components/common_post_options/follow_thread_option/index.ts
  app/components/files/index.ts
  app/components/post_draft/post_input/index.ts
  app/components/post_draft/send_handler/index.ts
  app/components/post_list/post/body/add_members/index.ts
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/reactions/index.ts
  app/components/post_list/post/footer/index.ts
  app/components/post_list/post/header/index.ts
  app/components/post_list/post/index.ts
  app/components/post_list/post/system_message/index.tsx
  app/components/post_with_channel_info/channel_info/index.ts
  app/queries/servers/channel.ts
  app/queries/servers/file.ts
  app/queries/servers/reaction.ts
  app/queries/servers/thread.ts
  app/screens/channel/channel_post_list/intro/direct_channel/index.ts
  app/screens/channel/channel_post_list/intro/direct_channel/member/index.ts
  app/screens/channel_info/title/group_message/index.ts
  app/screens/edit_post/index.tsx
  app/screens/gallery/footer/index.ts
  app/screens/permalink/index.ts
  app/screens/post_options/index.ts
  app/screens/reactions/index.ts
  app/screens/thread_options/index.ts
  share_extension/components/channel_item/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7037 Automated cherry pick of #7029
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7038 Automated cherry pick of #7028
  app/components/channel_item/index.ts
  app/components/common_post_options/copy_permalink_option/index.tsx
  app/components/common_post_options/follow_thread_option/index.ts
  app/components/files/index.ts
  app/components/post_draft/post_input/index.ts
  app/components/post_draft/send_handler/index.ts
  app/components/post_list/post/body/add_members/index.ts
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/reactions/index.ts
  app/components/post_list/post/footer/index.ts
  app/components/post_list/post/header/index.ts
  app/components/post_list/post/index.ts
  app/components/post_list/post/system_message/index.tsx
  app/components/post_with_channel_info/channel_info/index.ts
  app/queries/servers/channel.ts
  app/queries/servers/file.ts
  app/queries/servers/reaction.ts
  app/queries/servers/thread.ts
  app/screens/channel/channel_post_list/intro/direct_channel/index.ts
  app/screens/channel/channel_post_list/intro/direct_channel/member/index.ts
  app/screens/channel_info/title/group_message/index.ts
  app/screens/edit_post/index.tsx
  app/screens/gallery/footer/index.ts
  app/screens/permalink/index.ts
  app/screens/post_options/index.ts
  app/screens/reactions/index.ts
  app/screens/thread_options/index.ts
  share_extension/components/channel_item/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7016 Allow user to mark post as unread that was posted by a webhook
  app/screens/post_options/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7027 catch exceptions in Android Database helper
  android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#7039 Automated cherry pick of #7016
  app/screens/post_options/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7040 Automated cherry pick of #7027
  android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7041 Automated cherry pick of #7027
  android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#6952 Use more verbose message on archive and don't make help link lowercase
  app/screens/channel_info/destructive_options/archive/archive.tsx
  app/screens/settings/settings.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#7043 Fix CI to include postinstall script of react-native-webrtc
  .circleci/config.yml
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#7044 Automated cherry pick of #7043
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7045 disable top domain level verification
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#7046 Automated cherry pick of #7045
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7032 Fixes crashes and errors in iOS Share Extension and Notification Service
  ios/Gekidou/.swiftpm/xcode/xcshareddata/xcschemes/Gekidou.xcscheme
  ios/Gekidou/Sources/Gekidou/FileCache.swift
  ios/Gekidou/Sources/Gekidou/Keychain.swift
  ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/MattermostShare/Extensions/Color.swift
  ios/MattermostShare/ShareViewController.swift
  ios/MattermostShare/ViewModels/ShareViewModel.swift
  ios/MattermostShare/Views/ErrorViews/ErrorSharingView.swift
  ios/MattermostShare/Views/InitialView.swift
  ios/MattermostShare/Views/NavigationButtons/PostButton.swift
  ios/NotificationService/NotificationService.swift
Labels: 2: Dev Review, CherryPick/Approved, release-note

#7047 Automated cherry pick of #7032
  ios/Gekidou/.swiftpm/xcode/xcshareddata/xcschemes/Gekidou.xcscheme
  ios/Gekidou/Sources/Gekidou/FileCache.swift
  ios/Gekidou/Sources/Gekidou/Keychain.swift
  ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/MattermostShare/Extensions/Color.swift
  ios/MattermostShare/ShareViewController.swift
  ios/MattermostShare/ViewModels/ShareViewModel.swift
  ios/MattermostShare/Views/ErrorViews/ErrorSharingView.swift
  ios/MattermostShare/Views/InitialView.swift
  ios/MattermostShare/Views/NavigationButtons/PostButton.swift
  ios/NotificationService/NotificationService.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7048 Automated cherry pick of #7032
  ios/Gekidou/.swiftpm/xcode/xcshareddata/xcschemes/Gekidou.xcscheme
  ios/Gekidou/Sources/Gekidou/FileCache.swift
  ios/Gekidou/Sources/Gekidou/Keychain.swift
  ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/MattermostShare/Extensions/Color.swift
  ios/MattermostShare/ShareViewController.swift
  ios/MattermostShare/ViewModels/ShareViewModel.swift
  ios/MattermostShare/Views/ErrorViews/ErrorSharingView.swift
  ios/MattermostShare/Views/InitialView.swift
  ios/MattermostShare/Views/NavigationButtons/PostButton.swift
  ios/NotificationService/NotificationService.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7042 Bump app build number to 454
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 2: Dev Review, release-note-none

#7049 Automated cherry pick of #7042
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7011 [MM-49006] Handle Plugin related events
  app/actions/websocket/index.ts
  app/constants/websocket.ts
Labels: 4: Reviews Complete, release-note

#7055 Fix the animation that occurs in login flow
  app/screens/forgot_password/index.tsx
  app/screens/login/index.tsx
  app/screens/mfa/index.tsx
  app/screens/onboarding/index.tsx
  app/screens/server/index.tsx
  app/screens/sso/index.tsx
Labels: 4: Reviews Complete, release-note

#7054 Fix the animation that occurs in login flow
  app/screens/onboarding/index.tsx
  app/screens/server/index.tsx
Labels: CherryPick/Approved, release-note-none

#7056 Automated cherry pick of #7054
  app/screens/onboarding/index.tsx
  app/screens/server/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7015 Filter unused preferences
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/gql_common.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/preference.ts
  app/actions/remote/retry.ts
  app/actions/websocket/preferences.ts
  app/actions/websocket/users.ts
  app/components/autocomplete/emoji_suggestion/index.ts
  app/components/custom_status/custom_status_expiry.tsx
  app/components/post_list/post/body/content/opengraph/index.ts
  app/components/post_list/post/header/index.ts
  app/components/post_list/thread_overview/index.ts
  app/components/system_header/index.tsx
  app/components/team_sidebar/team_list/index.ts
  app/components/threads_button/index.ts
  app/constants/preferences.ts
  app/context/theme/index.tsx
  app/database/operator/server_data_operator/handlers/user.test.ts
  app/database/operator/server_data_operator/handlers/user.ts
  app/helpers/api/preference.ts
  app/products/calls/actions/calls.ts
  app/products/calls/components/calls_custom_message/index.ts
  app/queries/servers/post.ts
  app/queries/servers/preference.ts
  app/queries/servers/team.ts
  app/queries/servers/thread.ts
  app/queries/servers/user.ts
  app/screens/channel/channel_post_list/index.ts
  app/screens/custom_status_clear_after/components/date_time_selector.tsx
  app/screens/emoji_picker/picker/filtered/index.ts
  app/screens/emoji_picker/picker/header/index.ts
  app/screens/home/channel_list/categories_list/categories/body/index.ts
  app/screens/home/channel_list/categories_list/categories/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
  app/screens/home/channel_list/categories_list/subheader/index.ts
  app/screens/home/saved_messages/index.ts
  app/screens/settings/display/index.tsx
  app/screens/settings/display_clock/display_clock.tsx
  app/screens/settings/display_clock/index.tsx
  app/screens/settings/display_crt/display_crt.tsx
  app/screens/settings/display_theme/display_theme.tsx
  app/screens/settings/display_theme/theme_tiles.tsx
  app/screens/settings/notification_email/index.tsx
  app/screens/settings/notification_email/notification_email.tsx
  app/screens/settings/notifications/index.tsx
  app/screens/user_profile/index.ts
  app/utils/thread/index.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#7064 Automated cherry pick of #7057
  app/actions/local/category.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7066 Fix add to default category code for dms and gms (#7057)
  app/actions/local/category.ts
Labels: 4: Reviews Complete, release-note-none

#7059 Request permissions for Android push notifications and refactor
  android/app/src/main/java/com/mattermost/helpers/BitmapCache.kt
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/Network.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/init/push_notifications.ts
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7068 Automated cherry pick of #7059
  android/app/src/main/java/com/mattermost/helpers/BitmapCache.kt
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/Network.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/init/push_notifications.ts
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7060 Only fetchMissingDirectChannelsInfo when no display name is set
  app/actions/remote/channel.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7069 Automated cherry pick of #7060
  app/actions/remote/channel.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none
