Repository mattermost/mattermost-mobile, pull requests merged in 2023-11, with the labels that each got.

#7645 Bump app build number to 492
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#7643 Bump build and version number to 2.9.1 (491)
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#7644 Bump app build number to 492
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#7629 Session timeout notification incorrectly says "Days" on iOS
  app/utils/notification/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#7611 MM-54278 - Calls banners redesign
  app/components/user_avatars_stack/index.tsx
  app/constants/view.ts
  app/products/calls/components/call_avatar.tsx
  app/products/calls/components/call_notification/call_notification.tsx
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/components/floating_call_container.tsx
  app/products/calls/components/incoming_calls_container.tsx
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/components/join_call_banner/rounded_header_calls.tsx
  app/products/calls/components/message_bar.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
  app/screens/channel/channel.tsx
  app/screens/thread/thread.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#7620 MM-55010 - Calls: more messages bar adjustments
  app/components/post_list/more_messages/more_messages.tsx
  app/components/post_list/post_list.tsx
  app/products/calls/components/floating_call_container.tsx
  app/products/calls/hooks.ts
  app/screens/channel/channel.tsx
  app/screens/channel/channel_post_list/channel_post_list.tsx
Labels: 4: Reviews Complete, release-note

#7651 Bump app build number to 493
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: 4: Reviews Complete, release-note-none

#7610 Update supported ESR version
  README.md
  app/constants/supported_server.ts
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
Labels: QA Review Done, release-note

#7661 Allow connecting to a previous server if credentials are not in the keychain
  app/screens/server/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7662 Automated cherry pick of #7661
  app/screens/server/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7646 MM-54323 - Calls: Incoming call from different server
  app/products/calls/components/call_notification/call_notification.tsx
  app/products/calls/components/call_notification/index.ts
  app/products/calls/hooks.ts
Labels: 4: Reviews Complete, release-note

#7665 Maintenance fixes
  app/components/post_list/more_messages/more_messages.tsx
  app/products/calls/hooks.ts
  app/screens/channel_info/options/auto_follow_threads/auto_follow_threads.tsx
  app/screens/channel_info/options/ignore_mentions/ignore_mentions.tsx
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#7623 MM-55036 - Calls: Fix: Receiving in-app notifications for calls notifications while active
  app/constants/push_notification.ts
  app/init/push_notifications.ts
  app/products/calls/utils.ts
  app/utils/notification/index.ts
  types/global/push_notifications.d.ts
Labels: 4: Reviews Complete, release-note

#7668 Bump build main 494 and v2.11.0
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: CherryPick/Approved, release-note-none

#7669 Manual cherrypick of PR #7668
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: release-note-none

#7647 MM-54865 - Calls: Multisession support
  app/actions/websocket/index.ts
  app/constants/calls.ts
  app/constants/websocket.ts
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/current_call_bar/current_call_bar.tsx
  app/products/calls/components/current_call_bar/index.ts
  app/products/calls/components/join_call_banner/index.ts
  app/products/calls/components/join_call_banner/join_call_banner.tsx
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/observers/index.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/screens/call_screen/index.ts
  app/products/calls/screens/call_screen/raised_hand_banner.tsx
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#7664 Show at mentions in RemoveMarkdown renderer
  app/components/markdown/at_mention/at_mention.tsx
  app/components/remove_markdown/at_mention/at_mention.tsx
  app/components/remove_markdown/at_mention/index.ts
  app/components/remove_markdown/index.tsx
  app/hooks/markdown.ts
Labels: 4: Reviews Complete, release-note

#7670 MM-55592 - Add ci checks to main and release branches
  .github/workflows/ci.yml
Labels: 4: Reviews Complete, release-note-none

#7671 MM-54351 - Calls: Improve logging
  app/products/calls/connection/connection.ts
  app/products/calls/connection/websocket_client.ts
Labels: 4: Reviews Complete, release-note-none

#7667 Displayed channel related error with name field
  app/constants/server_errors.ts
  app/screens/convert_gm_to_channel/convert_gm_to_channel_form/convert_gm_to_channel_form.tsx
Labels: release-note-none

#7654 GM to channel conversion
  app/actions/local/category.ts
  app/actions/remote/channel.ts
  app/actions/websocket/channel.ts
  app/client/rest/channels.ts
  app/components/button/index.tsx
  app/components/channel_actions/convert_to_channel/convert_to_channel_label.tsx
  app/components/loading/index.tsx
  app/components/option_item/index.tsx
  app/constants/screens.ts
  app/constants/server_errors.ts
  app/i18n/index.ts
  app/queries/servers/categories.ts
  app/queries/servers/system.ts
  app/screens/channel_info/channel_info.tsx
  app/screens/channel_info/index.ts
  app/screens/convert_gm_to_channel/channel_name_input.tsx
  app/screens/convert_gm_to_channel/convert_gm_to_channel.tsx
  app/screens/convert_gm_to_channel/convert_gm_to_channel_form/convert_gm_to_channel_form.tsx
  app/screens/convert_gm_to_channel/convert_gm_to_channel_form/index.ts
  app/screens/convert_gm_to_channel/convert_gm_to_channel_form/no_common_teams_form.tsx
  app/screens/convert_gm_to_channel/index.tsx
  app/screens/convert_gm_to_channel/message_box/message_box.tsx
  app/screens/convert_gm_to_channel/team_selector.tsx
  app/screens/convert_gm_to_channel/team_selector_list/index.tsx
  app/screens/index.tsx
  assets/base/i18n/en.json
  index.ts
  package-lock.json
  package.json
Labels: 2: Dev Review, 2: UX Review, release-note

#7674 [MM-42586] Reaction toggle behavior
  app/actions/remote/reactions.ts
  app/components/post_list/post/body/reactions/reactions.tsx
  app/screens/post_options/reaction_bar/reaction_bar.tsx
Labels: 3: QA Review, release-note, Contributor

#7681 resolve weblate merge conflicts
  assets/base/i18n/de.json
  assets/base/i18n/hu.json
  assets/base/i18n/ja.json
  assets/base/i18n/pl.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Contributor

#7673 MM-54277 - Calls: Add incoming banners to channel_list screen
  app/products/calls/components/floating_call_container.tsx
  app/products/calls/components/incoming_calls_container.tsx
  app/products/calls/observers/index.ts
  app/screens/channel/index.tsx
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/index.ts
  app/screens/thread/index.tsx
Labels: 4: Reviews Complete, release-note

#7683 Added one important test
  app/actions/local/category.test.ts
  app/actions/local/category.ts
Labels: release-note-none

#7666 Fix issue when logout is called several times for the same server
  app/managers/session_manager.ts
Labels: 3: QA Review, release-note

#7613 MM-53902-cont'd: include encoded when checking invalid deeplinks
  app/actions/remote/command.ts
  app/components/markdown/markdown_link/markdown_link.tsx
  app/utils/deep_link/index.ts
  app/utils/url/path.ts
  app/utils/url/test.ts
  package-lock.json
  package.json
  types/launch/index.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#7689 MM-53902: deep link validation
  app/actions/remote/command.ts
  app/components/markdown/markdown_link/markdown_link.tsx
  app/utils/deep_link/index.ts
  app/utils/url/path.ts
  app/utils/url/test.ts
  package-lock.json
  package.json
  types/launch/index.ts
Labels: release-note

#7690 MM-53902: deep link validation
  app/actions/remote/command.ts
  app/components/markdown/markdown_link/markdown_link.tsx
  app/utils/deep_link/index.ts
  app/utils/url/path.ts
  app/utils/url/test.ts
  package-lock.json
  package.json
  types/launch/index.ts
Labels: release-note

#7682 [MM-55463] GM conversion reconnect handler
  app/actions/remote/entry/common.ts
  app/actions/websocket/index.ts
Labels: release-note-none

#7691 Bump to version 2.10.1 build 496
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: release-note-none

#7692 Bump build 497
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: CherryPick/Approved, release-note-none

#7693 Cherrypick bump build 497 for 2.11
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none

#7648 [MM-54529] Prevent Persistent Notifications Error Message for DM Channel
  app/components/post_draft/draft_input/index.tsx
  app/utils/post/index.ts
Labels: 4: Reviews Complete, release-note, Contributor
