Repository mattermost/mattermost-mobile, pull requests merged in 2024-02, with the labels that each got.

#7801 revert change to allow arbitrary loads
  ios/Mattermost/Info.plist
Labels: 2: Dev Review, CherryPick/Approved, release-note

#7802 Automated cherry pick of #7801
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7803 Automated cherry pick of #7801
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7795 Fix multi-server icon mention badge
  app/screens/home/channel_list/servers/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#7805 Update iOS permissions texts
  app/constants/permissions.ts
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#7807 Automated cherry pick of #7805
  app/constants/permissions.ts
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7806 Automated cherry pick of #7805
  app/constants/permissions.ts
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7804 Automated cherry pick of #7795
  app/screens/home/channel_list/servers/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7826 MacOS-latest-xlarge for m1 github runners
  .github/workflows/build-ios-beta.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-pr.yml
  .github/workflows/github-release.yml
Labels: Build Apps for PR, release-note-none

#7825 Cherry-picking translations
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/pl.json
  assets/base/i18n/ru.json
  assets/base/i18n/zh-CN.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#7653 chore: migrate AWS SDK for JavaScript v2 APIs to v3
  detox/package-lock.json
  detox/package.json
  detox/utils/artifacts.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#7796 MM-56391: fixed search bar moving up in ios
  app/components/navigation_header/index.tsx
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7828 CLD-7165 Bump MacOS runner version
  .github/actions/prepare-ios-build/action.yaml
  .github/actions/prepare-mobile-build/action.yaml
  .github/workflows/build-ios-beta.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-pr.yml
  .github/workflows/github-release.yml
  .ruby-version
  .solidarity
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#7815 Add handling of posts with unsafe links.
  app/components/markdown/markdown.tsx
  app/components/post_list/post/body/message/message.tsx
Labels: release-note-none

#7847 Translations update from Mattermost Weblate
  assets/base/i18n/en_AU.json
Labels: release-note-none, Do Not Merge/Mattermod
