Repository mattermost/mattermost-mobile, pull requests merged in 2024-12, with the labels that each got.

#8389 Translations update from Mattermost Weblate
  assets/base/i18n/nb_NO.json
Labels: release-note-none, Do Not Merge/Mattermod

#8344 Fix 60879
  app/components/document/index.tsx
  app/components/files/file_info.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/screens/channel_bookmark/components/bookmark_file/bookmark_file.tsx
  app/screens/channel_bookmark/index.tsx
  app/screens/gallery/footer/download_with_action/index.tsx
  app/utils/file/file_picker/index.ts
  app/utils/file/index.ts
  app/utils/url/index.test.ts
  app/utils/url/index.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note-none

#8347 Fix Thai search keywords not properly hi-lighted in the search results.
  app/utils/markdown/index.test.ts
  app/utils/markdown/index.ts
Labels: Lifecycle/1:stale, do-not-merge/release-note-label-needed, Contributor, QA Deferred

#8391 Surround text on file info for searches
  app/components/files/file_info.tsx
Labels: Build Apps for PR, 3: QA Review, release-note-none

#8392 Automated cherry pick of #8391
  app/components/files/file_info.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8393 Automated cherry pick of #8344
  app/components/document/index.tsx
  app/components/files/file_info.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/screens/channel_bookmark/components/bookmark_file/bookmark_file.tsx
  app/screens/channel_bookmark/index.tsx
  app/screens/gallery/footer/download_with_action/index.tsx
  app/utils/file/file_picker/index.ts
  app/utils/file/index.ts
  app/utils/url/index.test.ts
  app/utils/url/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8283 MM-56899 - prevent app block when setting custom status if no internet
  app/hooks/navigation_button_pressed.ts
  app/screens/custom_status/components/custom_status_input.tsx
  app/screens/custom_status/custom_status.tsx
  app/screens/home/account/components/options/custom_status/custom_label/custom_label.tsx
Labels: Build Apps for PR, release-note

#8396 Fix join/leave messages not showing
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/utils/post_list/index.ts
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, 3: QA Review, release-note-none

#8395 MM-59779 Add tests for queries/server/channel
  app/queries/servers/channel.test.ts
  app/queries/servers/channel.ts
Labels: 2: Dev Review, release-note

#8361 fix: fixed image overflow in message attachments
  app/components/post_list/post/body/content/message_attachments/attachment_image/index.tsx
  app/constants/image.ts
  app/utils/images/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note, Contributor

#8397 Automated cherry pick of #8396
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/utils/post_list/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8398 Automated cherry pick of #8361
  app/components/post_list/post/body/content/message_attachments/attachment_image/index.tsx
  app/constants/image.ts
  app/utils/images/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8401 Translations update from Mattermost Weblate
  assets/base/i18n/fr.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod

#8362 Fix: Android build for Detox e2e
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  detox/README.md
  detox/e2e/support/ui/screen/login.ts
  detox/e2e/support/ui/screen/server.ts
  detox/inject-detox-settings.js
  detox/package.json
Labels: release-note, Build App for Android

#8404 Remove end user message for unsupported servers
  app/utils/server/index.ts
  app/utils/server/server.test.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, release-note

#8409 Automated cherry pick of #8404
  app/utils/server/index.ts
  app/utils/server/server.test.ts
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8356 fix(MM-49742): broken user avatar
  app/constants/view.ts
  app/screens/home/tab_bar/account.test.tsx
  app/screens/home/tab_bar/account.tsx
Labels: Build Apps for PR, QA Review Done, release-note, kind/bug

#8410 Update supported ESR version
  app/constants/supported_server.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8413 Automated cherry pick of #8410
  app/constants/supported_server.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8384 Android native logs
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.kt
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.kt
  android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  package-lock.json
  package.json
Labels: 2: Dev Review, QA Review Done, release-note, Build App for Android

#8390 Network metrics
  app/actions/remote/channel.ts
  app/actions/remote/channel_bookmark.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/groups.ts
  app/actions/remote/notifications.test.ts
  app/actions/remote/post.ts
  app/actions/remote/preference.ts
  app/actions/remote/role.ts
  app/actions/remote/systems.ts
  app/actions/remote/team.ts
  app/actions/remote/thread.ts
  app/actions/remote/user.ts
  app/actions/websocket/index.ts
  app/client/rest/apps.ts
  app/client/rest/base.ts
  app/client/rest/categories.ts
  app/client/rest/channel_bookmark.ts
  app/client/rest/channels.ts
  app/client/rest/general.ts
  app/client/rest/groups.ts
  app/client/rest/posts.ts
  app/client/rest/preferences.ts
  app/client/rest/teams.ts
  app/client/rest/threads.ts
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
  app/client/rest/users.ts
  app/helpers/database/index.ts
  app/init/launch.ts
  app/managers/apps_manager.ts
  app/managers/network_manager.ts
  app/managers/websocket_manager.ts
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/call_notification/call_notification.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/utils/deep_link/index.test.ts
  app/utils/deep_link/index.ts
  assets/base/config.json
  package-lock.json
  package.json
  types/api/client.d.ts
Labels: 2: Dev Review, release-note-none

#8417 MM-59652 Add unit tests to actions/websocket/channel
  app/actions/websocket/channel.test.ts
  app/actions/websocket/channel.ts
Labels: 4: Reviews Complete, release-note-none

#8425 chore: add .aider* to gitignore
  .gitignore
Labels: release-note, kind/chore

#8427 Fix interactive dialogs not showing
  app/components/settings/bool_setting.tsx
  app/components/settings/radio_setting/index.tsx
  app/components/settings/text_setting.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/interactive_dialog/index.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note

#8429 Automated cherry pick of #8427
  app/components/settings/bool_setting.tsx
  app/components/settings/radio_setting/index.tsx
  app/components/settings/text_setting.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/interactive_dialog/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8428 Automated cherry pick of #8427
  app/components/settings/bool_setting.tsx
  app/components/settings/radio_setting/index.tsx
  app/components/settings/text_setting.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/interactive_dialog/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8431 Fix interactive dialog number handling
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/interactive_dialog/index.tsx
  app/utils/integrations.ts
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, release-note

#8432 Automated cherry pick of #8431
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/interactive_dialog/index.tsx
  app/utils/integrations.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8438 Translations update from Mattermost Weblate
  assets/base/i18n/nb_NO.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ru.json
Labels: release-note-none, Do Not Merge/Mattermod

#8436 feat(MM-61865): send network request telemetry data to the server
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
  app/managers/performance_metrics_manager/constant.ts
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
  app/managers/performance_metrics_manager/performance_metrics_batcher.ts
  app/managers/performance_metrics_manager/types.d.ts
  app/utils/file/file_picker/index.test.ts
Labels: release-note, kind/feature

#8441 Translations update from Mattermost Weblate
  assets/base/i18n/ko.json
Labels: release-note-none, Do Not Merge/Mattermod
