Repository mattermost/mattermost-mobile, pull requests merged in 2024-09, with the labels that each got.

#8198 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/hr.json
  assets/base/i18n/ja.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#8026 fix: MM-58164 Search text is behind the textbox while searching
  app/components/navigation_header/header.tsx
  app/components/navigation_header/index.tsx
  app/hooks/header.ts
  app/hooks/useCollapsibleHeader.test.tsx
  app/screens/home/search/search.tsx
Labels: 2: Dev Review, 3: QA Review, release-note, kind/bug

#8201 Remove unneeded permissions
  android/app/src/main/AndroidManifest.xml
Labels: Build Apps for PR, 3: QA Review, release-note

#8209 MM-60312- rename ssoOffice 365 to sso EntraId
  app/screens/edit_profile/components/email_field.tsx
  app/screens/login/sso_options.tsx
  assets/base/i18n/en.json
  assets/base/images/Icon_EntraID.png
  assets/base/images/Icon_EntraID@2x.png
  assets/base/images/Icon_EntraID@3x.png
  assets/base/images/Icon_Office.png
  assets/base/images/Icon_Office@2x.png
  assets/base/images/Icon_Office@3x.png
Labels: 2: Dev Review, Build Apps for PR, QA Review Done, release-note

#8210 Translations update from Mattermost Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fa.json
  assets/base/i18n/fr.json
  assets/base/i18n/hr.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/vi.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#8060 Send notification status information to the server
  app/actions/remote/entry/common.ts
  app/actions/websocket/index.ts
  app/client/rest/users.ts
Labels: 4: Reviews Complete, CherryPick/Done, release-note

#8217 Automated cherry pick of #8060
  app/actions/remote/entry/common.ts
  app/actions/websocket/index.ts
  app/client/rest/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8212 Various Fixes
  app/components/channel_bookmarks/channel_bookmark/channel_bookmark.tsx
  app/hooks/device.ts
  app/screens/gallery/index.tsx
  app/screens/gallery/video_renderer/index.tsx
  app/screens/gallery/viewer/index.tsx
  app/utils/deep_link/index.ts
  fastlane/Gemfile.lock
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/RNUtilsModuleImpl.kt
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/enums/Events.kt
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/helpers/FoldableObserver.kt
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/helpers/SplitView.kt
  libraries/@mattermost/rnutils/android/src/newarch/RNUtilsModule.kt
  libraries/@mattermost/rnutils/android/src/oldarch/RNUtilsModule.kt
  libraries/@mattermost/rnutils/ios/Extensions/RNUtilsWrapper+Events.swift
  libraries/@mattermost/rnutils/ios/RNUtils.mm
  libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift
  libraries/@mattermost/rnutils/src/NativeRNUtils.ts
  libraries/@mattermost/rnutils/src/index.tsx
  package-lock.json
  package.json
  patches/expo-video-thumbnails+8.0.0.patch
Labels: 2: Dev Review, release-note-none

#8199 Fix iPad split view
  libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift
  types/global/device.d.ts
Labels: 2: Dev Review, Build Apps for PR, 3: QA Review, release-note

#8219 Remove axios and detox from package.json in the root folder
  detox/e2e/support/server_api/common.ts
  detox/package-lock.json
  detox/package.json
  package-lock.json
  package.json
Labels: release-note-none, E2E iOS tests for PR

#8222 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/ru.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#8220 open an external browser when the server config for MobileExternalBrowse is set to true
  app/screens/sso/components/auth_error.tsx
  app/screens/sso/components/auth_redirect.tsx
  app/screens/sso/components/auth_success.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso_authentication.tsx
  app/screens/sso/sso_authentication_with_external_browser.tsx
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, Build App for Android

#8223 Automated cherry pick of #8220
  app/screens/sso/components/auth_error.tsx
  app/screens/sso/components/auth_redirect.tsx
  app/screens/sso/components/auth_success.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso_authentication.tsx
  app/screens/sso/sso_authentication_with_external_browser.tsx
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8224 feat(test): Mobile message drafts: Remove outdated reference to fixed issue
  detox/e2e/test/messaging/message_draft.e2e.ts
Labels: 4: Reviews Complete, release-note-none

#8225 feat(test): Mobile reply: Remove outdated note about fixed issue
  detox/e2e/test/messaging/message_reply.e2e.ts
Labels: 4: Reviews Complete, release-note

#8230 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
Labels: release-note-none, Do Not Merge/Mattermod

#8231 feat(test): Update test case to remove known issue that has been fixed
  detox/e2e/test/smoke_test/autocomplete.e2e.ts
Labels: do-not-merge/release-note-label-needed

#8238 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/ru.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#8232 MM-60534 -fix rate my app broken styles
  app/components/button/index.tsx
  app/screens/review_app/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note

#8239 Automated cherry pick of #8232
  app/components/button/index.tsx
  app/screens/review_app/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none
