Repository mattermost/mattermost-mobile, pull requests merged in 2024-11, with the labels that each got.

#8303 MM-59436 Add tests to actions/remote/groups
  app/actions/remote/groups.test.ts
Labels: 4: Reviews Complete, release-note

#8304 MM-59422 Add tests to actions/remote/search
  app/actions/remote/search.test.ts
Labels: 4: Reviews Complete, release-note

#8302 MM-59423 Add tests to actions/remote/notifications
  app/actions/remote/notifications.test.ts
  app/actions/remote/notifications.ts
Labels: 4: Reviews Complete, release-note

#8301 MM-59449 Add tests for actions/remote/post
  app/actions/remote/post.test.ts
  app/actions/remote/post.ts
Labels: 4: Reviews Complete, release-note

#8311 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/pl.json
  assets/base/i18n/sv.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#8313 feat:proper badge theme use for server list
  app/components/badge/index.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Labels: Build Apps for PR, release-note, QA Deferred, kind/feature

#8316 MM-53775: Hide Thread Overview until there are replies
  app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
  app/components/post_list/thread_overview/thread_overview.test.tsx
  app/components/post_list/thread_overview/thread_overview.tsx
  assets/base/i18n/en.json
  detox/e2e/test/smoke_test/messaging.e2e.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note, E2E Android tests for PR

#8317 Fix iPad split screen
  libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift
Labels: 4: Reviews Complete, release-note

#8314 Remove app alias for imports
  app/actions/local/category.test.ts
  app/actions/local/channel.test.ts
  app/actions/local/post.test.ts
  app/actions/local/reactions.test.ts
  app/actions/local/systems.test.ts
  app/actions/local/team.test.ts
  app/actions/local/thread.test.ts
  app/actions/local/user.test.ts
  app/actions/remote/post.test.ts
  app/actions/remote/preference.test.ts
  app/actions/remote/reactions.test.ts
  app/actions/remote/search.ts
  app/actions/remote/thread.test.ts
  app/components/channel_bookmarks/channel_bookmark/bookmark_document.tsx
  app/components/post_list/post/header/header.tsx
  app/products/calls/components/call_notification/index.ts
  app/screens/channel_bookmark/components/bookmark_file/bookmark_file.tsx
  app/screens/channel_bookmark/components/bookmark_link.tsx
  app/screens/code/index.tsx
  app/screens/gallery/footer/avatar/index.tsx
  app/screens/home/tab_bar/home.tsx
  app/utils/deep_link/index.ts
  babel.config.js
  tsconfig.json
Labels: 4: Reviews Complete, release-note-none

#8315 Bump Ruby to v3.2.0
  .ruby-version
  .solidarity
Labels: Build Apps for PR, release-note-none, QA Deferred

#8294 fix(MM-60638): Provider Paths
  android/app/src/main/res/xml/file_viewer_provider_paths.xml
  android/app/src/main/res/xml/provider_paths.xml
  patches/react-native-share+10.2.1.patch
Labels: Build Apps for PR, QA Review Done, 3: Security Review, release-note, kind/bug

#8324 Automated cherry pick of #8294
  android/app/src/main/res/xml/file_viewer_provider_paths.xml
  android/app/src/main/res/xml/provider_paths.xml
  patches/react-native-share+10.2.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8271 Add test notification tool
  app/actions/remote/notifications.test.ts
  app/actions/remote/notifications.ts
  app/client/rest/posts.test.ts
  app/client/rest/posts.ts
  app/components/section_notice/__snapshots__/index.test.tsx.snap
  app/components/section_notice/index.test.tsx
  app/components/section_notice/index.tsx
  app/components/section_notice/section_notice_button.tsx
  app/components/section_notice/types.d.ts
  app/components/settings/container.tsx
  app/hooks/use_external_link.test.ts
  app/hooks/use_external_link.ts
  app/screens/settings/notifications/index.tsx
  app/screens/settings/notifications/notifications.tsx
  app/screens/settings/notifications/send_test_notification_notice/__snapshots__/send_test_notification_notice.test.tsx.snap
  app/screens/settings/notifications/send_test_notification_notice/index.ts
  app/screens/settings/notifications/send_test_notification_notice/send_test_notification_notice.test.tsx
  app/screens/settings/notifications/send_test_notification_notice/send_test_notification_notice.tsx
  assets/base/i18n/en.json
  package-lock.json
  package.json
  types/api/config.d.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8329 Translations update from Mattermost Weblate
  assets/base/i18n/bg.json
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fa.json
  assets/base/i18n/fr.json
  assets/base/i18n/hr.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/vi.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#8326 MM-59444 Add tests for actions/remote/command
  app/actions/remote/command.test.ts
  app/actions/remote/command.ts
Labels: 4: Reviews Complete, release-note

#8332 remove warning due to patch version missmatch
  patches/@mattermost+react-native-network-client+1.7.2.patch
Labels: 4: Reviews Complete, release-note-none

#8333 Automated cherry pick of #8306
  app/actions/remote/channel.test.ts
  app/actions/remote/channel.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/post.ts
  app/actions/remote/team.test.ts
  app/actions/remote/team.ts
  app/actions/remote/thread.test.ts
  app/actions/remote/thread.ts
  app/actions/websocket/channel.ts
  app/client/rest/threads.ts
  app/components/team_sidebar/team_list/index.ts
  app/database/operator/server_data_operator/transformers/thread.ts
  app/helpers/database/index.ts
  app/managers/network_manager.ts
  ios/Podfile.lock
  libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8334 remove patch warning
  patches/@mattermost+react-native-network-client+1.7.3.patch
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#8336 Automated cherry pick of #8332
  patches/@mattermost+react-native-network-client+1.7.2.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8338 Automated cherry pick of #8334
  patches/@mattermost+react-native-network-client+1.7.3.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8335 update fastlane
  fastlane/Gemfile.lock
Labels: 2: Dev Review, release-note-none

#8341 Automated cherry pick of #8339
  app/components/progressive_image/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8342 Automated cherry pick of #8339
  app/components/progressive_image/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8345 chore: patch getBuildSettings to allow run ios from cli
  patches/@react-native-community+cli-platform-apple+13.6.9.patch
Labels: release-note, kind/chore, Build App for iOS

#8330 Update README.md
  README.md
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
Labels: CherryPick/Approved, release-note

#8351 Automated cherry pick of #8330
  README.md
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8300 MM-61148 Rewrite table parsing and improve error handling around Markdown code
  app/components/markdown/error_boundary.tsx
  app/components/markdown/markdown.test.tsx
  app/components/markdown/markdown.tsx
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8352 Automated cherry pick of #8300
  app/components/markdown/error_boundary.tsx
  app/components/markdown/markdown.test.tsx
  app/components/markdown/markdown.tsx
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8327 include EMM/MDM integration in the arch diagram
  docs/architecture-diagram.monopic
  docs/architecture-diagram.png
Labels: 2: Dev Review, release-note-none

#8349 fix entry logic to not re-fetch data for the initial team
  app/actions/remote/entry/common.ts
  app/actions/remote/thread.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#8354 Automated cherry pick of #8349
  app/actions/remote/entry/common.ts
  app/actions/remote/thread.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8355 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/ko.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod

#8340 fix screen position for server / login / forgot password & mfa
  app/hooks/device.ts
  app/screens/forgot_password/index.tsx
  app/screens/index.tsx
  app/screens/login/form.tsx
  app/screens/login/index.tsx
  app/screens/mfa/index.tsx
  app/screens/server/form.tsx
  app/screens/server/index.tsx
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none

#8322 prevent overlap of clear button, fix font, reduce space on recent statuses
  app/screens/custom_status/components/custom_status_input.tsx
  app/screens/custom_status/components/custom_status_suggestion/custom_status_suggestion.tsx
  app/screens/custom_status/custom_status.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note

#8366 Increase branch test coverage to over 80% for actions/local
  app/actions/local/category.test.ts
  app/actions/local/draft.test.ts
  app/actions/local/file.test.ts
  app/actions/local/group.test.ts
  app/actions/local/post.test.ts
  app/actions/local/systems.test.ts
  app/actions/local/thread.test.ts
Labels: 4: Reviews Complete, release-note-none

#8371 MM-59450 Add tests for actions/remote/category
  app/actions/remote/category.test.ts
Labels: 4: Reviews Complete, release-note

#8372 MM-59432 Add tests for actions/remote/custom_emoji
  app/actions/remote/custom_emoji.test.ts
  app/actions/remote/custom_emoji.ts
Labels: 4: Reviews Complete, release-note

#8373 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/ja.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#8375 Ensure myTeam.id is not undefined
  app/components/team_sidebar/team_list/index.test.tsx
  app/components/team_sidebar/team_list/index.ts
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, release-note-none

#8376 Automated cherry pick of #8375
  app/components/team_sidebar/team_list/index.test.tsx
  app/components/team_sidebar/team_list/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8368 Fix MM-61710
  app/components/autocomplete_selector/index.tsx
  app/components/formatted_text/index.tsx
  app/components/markdown/channel_mention/channel_mention.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/components/post_list/combined_user_activity/last_users.tsx
  app/components/post_list/post/body/content/image_preview/image_preview.tsx
  app/components/post_list/post/body/content/message_attachments/action_button/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx
  app/components/post_list/post/system_message/system_message.tsx
  app/components/selected_users/index.tsx
  app/database/components/index.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/emoji_picker/picker/header/skintone_selector/skin_selector.tsx
  app/screens/emoji_picker/picker/header/skintone_selector/skintone_selector.tsx
  app/screens/in_app_notification/index.tsx
  app/screens/integration_selector/integration_selector.tsx
  app/screens/interactive_dialog/index.tsx
  app/screens/invite/invite.tsx
  app/screens/invite/summary_report.tsx
  app/screens/permalink/permalink.tsx
  app/utils/types.ts
Labels: Build Apps for PR, 3: QA Review, release-note-none

#8323 Add post props validation
  app/actions/local/post.ts
  app/actions/remote/post.ts
  app/actions/remote/search.ts
  app/components/files/files.tsx
  app/components/markdown/channel_mention/channel_mention.tsx
  app/components/markdown/channel_mention/index.ts
  app/components/markdown/markdown.tsx
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/components/post_list/combined_user_activity/index.ts
  app/components/post_list/post/avatar/avatar.tsx
  app/components/post_list/post/body/add_members/add_members.tsx
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/index.tsx
  app/components/post_list/post/body/content/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_button/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post/body/message/message.tsx
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/system_message/system_message.tsx
  app/helpers/api/user.ts
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
  app/screens/gallery/footer/footer.tsx
  app/utils/apps.ts
  app/utils/gallery/index.ts
  app/utils/message_attachment.ts
  app/utils/message_attachment_colors.test.ts
  app/utils/message_attachment_colors.ts
  app/utils/post/index.test.ts
  app/utils/post/index.ts
  app/utils/post_list/index.test.ts
  app/utils/post_list/index.ts
  app/utils/types.ts
  package-lock.json
  package.json
  types/api/files.d.ts
  types/api/posts.d.ts
  types/database/models/servers/post.ts
  types/screens/gallery.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none

#8383 Automated cherry pick of #8323
  app/actions/local/post.ts
  app/actions/remote/post.ts
  app/actions/remote/search.ts
  app/components/files/files.tsx
  app/components/markdown/channel_mention/channel_mention.tsx
  app/components/markdown/channel_mention/index.ts
  app/components/markdown/markdown.tsx
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/components/post_list/combined_user_activity/index.ts
  app/components/post_list/post/avatar/avatar.tsx
  app/components/post_list/post/body/add_members/add_members.tsx
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/index.tsx
  app/components/post_list/post/body/content/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_button/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/post_list/post/body/index.tsx
  app/components/post_list/post/body/message/message.tsx
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/system_message/system_message.tsx
  app/helpers/api/user.ts
  app/products/calls/components/calls_custom_message/index.ts
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
  app/screens/gallery/footer/footer.tsx
  app/utils/apps.ts
  app/utils/gallery/index.ts
  app/utils/message_attachment.ts
  app/utils/message_attachment_colors.test.ts
  app/utils/message_attachment_colors.ts
  app/utils/post/index.test.ts
  app/utils/post/index.ts
  app/utils/post_list/index.test.ts
  app/utils/post_list/index.ts
  app/utils/types.ts
  package-lock.json
  package.json
  types/api/files.d.ts
  types/api/posts.d.ts
  types/database/models/servers/post.ts
  types/screens/gallery.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8348 Extra keyboard
  app/components/post_draft/post_draft.tsx
  app/components/post_draft/post_input/post_input.tsx
  app/components/post_list/post/post.tsx
  app/constants/post_draft.ts
  app/context/extra_keyboard/index.tsx
  app/hooks/device.ts
  app/hooks/keyboard_tracking.ts
  app/screens/channel/channel.tsx
  app/screens/channel/channel_post_list/channel_post_list.tsx
  app/screens/home/index.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/permalink/permalink.tsx
  app/screens/pinned_messages/pinned_messages.tsx
  app/screens/thread/thread.tsx
  app/screens/thread/thread_post_list/thread_post_list.tsx
  app/store/navigation_store.ts
  ios/Podfile.lock
  libraries/@mattermost/keyboard-tracker/ios/Extensions/UIResponder+FirstResponder.h
  libraries/@mattermost/keyboard-tracker/ios/Extensions/UIResponder+FirstResponder.m
  libraries/@mattermost/keyboard-tracker/ios/MattermostKeyboardTrackerView.h
  libraries/@mattermost/keyboard-tracker/ios/MattermostKeyboardTrackerView.mm
  libraries/@mattermost/keyboard-tracker/ios/ViewManagers/MattermostKeyboardTrackerViewManager.mm
  libraries/@mattermost/keyboard-tracker/ios/Views/KeyboardTrackingView.h
  libraries/@mattermost/keyboard-tracker/ios/Views/KeyboardTrackingView.m
  libraries/@mattermost/keyboard-tracker/ios/Views/ObservingInputAccessoryView.h
  libraries/@mattermost/keyboard-tracker/ios/Views/ObservingInputAccessoryView.m
  libraries/@mattermost/keyboard-tracker/mattermost-keyboard-tracker.podspec
  libraries/@mattermost/keyboard-tracker/package.json
  libraries/@mattermost/keyboard-tracker/src/MattermostKeyboardTrackerViewNativeComponent.ts
  libraries/@mattermost/keyboard-tracker/src/index.tsx
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/RNUtilsModuleImpl.kt
  libraries/@mattermost/rnutils/android/src/newarch/RNUtilsModule.kt
  libraries/@mattermost/rnutils/android/src/oldarch/RNUtilsModule.kt
  libraries/@mattermost/rnutils/ios/RNUtils.mm
  libraries/@mattermost/rnutils/src/NativeRNUtils.ts
  package-lock.json
  package.json
  patches/react-native-navigation+7.40.1.patch
  test/intl-test-helper.tsx
Labels: 2: Dev Review, Build Apps for PR, 2: UX Review, release-note-none

#8331 Fix bottomSheet bottom insets
  app/components/announcement_banner/announcement_banner.tsx
  app/components/channel_bookmarks/add_bookmark.tsx
  app/components/channel_bookmarks/channel_bookmark/channel_bookmark.tsx
  app/components/channel_bookmarks/channel_bookmarks.tsx
  app/components/files_search/file_options/mobile_options.tsx
  app/components/files_search/file_results.tsx
  app/components/markdown/at_mention/at_mention.tsx
  app/components/markdown/markdown_code_block/index.tsx
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_latex_block/index.tsx
  app/components/markdown/markdown_link/markdown_link.tsx
  app/components/post_draft/quick_actions/camera_quick_action/index.tsx
  app/components/post_draft/quick_actions/post_priority_action/index.tsx
  app/components/post_list/post/body/acknowledgements/acknowledgements.tsx
  app/components/post_list/post/body/acknowledgements/users_list/user_list_item.tsx
  app/components/post_list/post/body/failed/index.tsx
  app/components/post_list/post/body/reactions/reactions.tsx
  app/components/post_list/post/footer/footer.tsx
  app/components/selected_users/index.tsx
  app/components/team_list/index.tsx
  app/components/user_avatars_stack/index.tsx
  app/components/user_list/index.tsx
  app/products/calls/components/audio_device_button.tsx
  app/products/calls/hooks.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/screens/host_controls/host_controls.tsx
  app/products/calls/screens/participants_list/participants_list.tsx
  app/screens/bottom_sheet/button.tsx
  app/screens/bottom_sheet/index.tsx
  app/screens/browse_channels/channel_dropdown.tsx
  app/screens/channel/channel_post_list/intro/direct_channel/member/member.tsx
  app/screens/channel/header/bookmarks.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel_bookmark/components/bookmark_detail.tsx
  app/screens/channel_files/header.tsx
  app/screens/channel_info/extra/extra.tsx
  app/screens/channel_info/title/public_private/public_private.tsx
  app/screens/create_direct_message/create_direct_message.tsx
  app/screens/custom_status/custom_status.tsx
  app/screens/edit_profile/components/profile_image_picker.tsx
  app/screens/emoji_picker/picker/footer/index.tsx
  app/screens/home/account/components/options/user_presence/index.tsx
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/servers/index.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/team_picker_icon.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
  app/screens/post_options/post_options.tsx
  app/screens/post_options/reaction_bar/reaction_bar.tsx
  app/screens/post_priority_picker/footer.tsx
  app/screens/post_priority_picker/post_priority_picker.tsx
  app/screens/thread_options/thread_options.tsx
  app/screens/user_profile/user_profile.tsx
  app/utils/helpers.test.ts
  app/utils/helpers.ts
  patches/@gorhom+bottom-sheet+4.6.4.patch
Labels: Build Apps for PR, 2: UX Review, release-note-none

#8367 Fix: Env variabled to pick up right simulator device for tests
  .github/workflows/e2e-detox-template.yml
  detox/.detoxrc.json
  detox/utils/generate_detox_config_ci.js
Labels: release-note-none
