Repository mattermost/mattermost-mobile, pull requests merged in 2024-10, with the labels that each got.

#8241 MM-59434 Add tests to actions/remote/team
  app/actions/remote/team.test.ts
  app/actions/remote/team.ts
Labels: 4: Reviews Complete, release-note

#8215 MM-60425 Making clickable images work inside Markdown
  app/components/markdown/markdown.tsx
Labels: 4: Reviews Complete, release-note, Contributor, kind/bug

#8247 Automated cherry pick of #8220
  app/screens/sso/components/auth_error.tsx
  app/screens/sso/components/auth_redirect.tsx
  app/screens/sso/components/auth_success.tsx
  app/screens/sso/index.tsx
  app/screens/sso/sso_authentication.tsx
  app/screens/sso/sso_authentication_with_external_browser.tsx
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8246 [MM-45894] Calls: support for signaling media tracks using data channels
  app/products/calls/connection/connection.ts
  app/products/calls/types/calls.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#8205 Fix: render channel links in threads list
  app/components/remove_markdown/index.tsx
  app/screens/global_threads/threads_list/thread/thread.tsx
Labels: 4: Reviews Complete, release-note, Contributor, kind/bug

#8254 Add fixes for xCode 16 changes
  ios/Gekidou/Sources/Gekidou/Storage/Database.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@sentry+utils+7.119.1.patch
Labels: 4: Reviews Complete, release-note-none

#8255 Update calls-common
  app/products/calls/connection/connection.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8257 Automated cherry pick of #8255
  app/products/calls/connection/connection.ts
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8202 test: mitmproxy + low bandwidth + automated QA using detox
  .github/actions/bandwidth-throttling/action.yml
  .github/actions/prepare-low-bandwidth/action.yml
  .github/actions/start-proxy/action.yml
  .github/workflows/e2e-detox-pr.yml
  .github/workflows/e2e-detox-template.yml
  detox/e2e/support/utils/index.ts
  scripts/mitmdump-flow-parsing.py
Labels: 2: Dev Review, release-note

#8242 Native set load measured
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/RNUtilsModuleImpl.kt
  libraries/@mattermost/rnutils/android/src/newarch/RNUtilsModule.kt
  libraries/@mattermost/rnutils/android/src/oldarch/RNUtilsModule.kt
  libraries/@mattermost/rnutils/ios/RNUtils.mm
  libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift
  libraries/@mattermost/rnutils/src/NativeRNUtils.ts
  test/setup.ts
Labels: 4: Reviews Complete, release-note

#8256 fix: (MM-59973) emoji count 0 update
  app/components/animated_number/index.tsx
Labels: release-note, kind/bug

#8263 Automated cherry pick of #8258
  NOTICE.txt
Labels: release-note-none

#8264 fix bookmarks sort order when WS does not bump update_at
  app/database/operator/server_data_operator/handlers/channel.ts
  app/queries/servers/channel_bookmark.ts
Labels: 4: Reviews Complete, release-note

#8244 feat: Add copy button on code view
  app/constants/snack_bar.ts
  app/screens/code/index.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor, E2E iOS tests for PR

#8267 Add utils/search unit tests
  app/utils/search/index.test.ts
Labels: 2: Dev Review, release-note-none

#8266 Add utils/role unit tests
  app/utils/role/index.test.ts
Labels: 2: Dev Review, release-note-none

#8265 Add utils/post_list unit tests
  app/utils/post_list/index.test.ts
  app/utils/post_list/index.ts
Labels: 2: Dev Review, release-note-none

#8277 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/sv.json
  assets/base/i18n/zh-TW.json
Labels: Hacktoberfest, release-note-none, Do Not Merge/Mattermod

#8272 chore: exhaustive-deps eslint rules from 'off' to 'warn'
  .eslintrc.json
Labels: release-note, kind/chore

#8273 MM-59447 Add tests to actions/remote/user
  app/actions/remote/user.test.ts
  app/actions/remote/user.ts
Labels: 4: Reviews Complete, release-note

#8261 Add support for Auth Scheme customization on build time
  app/constants/sso.ts
  app/screens/sso/sso.test.tsx
  assets/base/config.json
  fastlane/Fastfile
Labels: 2: Dev Review, release-note-none

#8146 MM-59973: fix the emoji count 0 issue when archive and unarchive chan…
  app/components/animated_number/index.tsx
Labels: 2: Dev Review, Build Apps for PR, 3: QA Review, release-note

#8279 [MM-61166] Ensure full validation of Calls post props
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
Labels: 4: Reviews Complete, release-note-none

#8287 Automated cherry pick of #8279
  app/products/calls/components/calls_custom_message/calls_custom_message.tsx
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8278 Add Index to 'type' column in 'Post' table
  app/database/migration/server/index.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/post.ts
  app/database/schema/server/test.ts
  docs/database/server/server-v3.pdf
  docs/database/server/server-v3.rtf
  docs/database/server/server-v3.sql
  docs/database/server/server.md
Labels: Hacktoberfest, 3: QA Review, release-note, Contributor

#8282 Add logs when notification device tokens is registered or fails to do so
  app/init/push_notifications.ts
Labels: 2: Dev Review, release-note-none

#8292 Translations update from Mattermost Weblate
  assets/base/i18n/nb_NO.json
  assets/base/i18n/pl.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/zh-CN.json
Labels: Hacktoberfest, release-note-none, Do Not Merge/Mattermod

#8034 Reconnect the network when we switch network types
  app/managers/websocket_manager.ts
  patches/@mattermost+react-native-network-client+1.6.0.patch
Labels: Build Apps for PR, 3: QA Review, release-note

#8296 MM-59438 Add tests to actions/remote/session
  app/actions/remote/session.test.ts
  app/actions/remote/session.ts
  app/managers/session_manager.ts
Labels: 4: Reviews Complete, release-note

#8245 feat: Add visible to you text on ephemeral posts
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/post.tsx
  app/components/system_header/index.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#8281 Fix sidebar teams order
  app/components/team_sidebar/team_list/index.ts
Labels: 2: Dev Review, Build Apps for PR, 3: QA Review, release-note

#8299 MM-59448 Add tests to actions/remote/preference
  app/actions/remote/preference.test.ts
Labels: 4: Reviews Complete, release-note

#8284 fix(MM-53762): missing file and reaction
  app/database/operator/server_data_operator/handlers/post.test.ts
  app/database/operator/server_data_operator/handlers/post.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note, kind/bug
