Repository mattermost/mattermost-mobile, pull requests merged in 2024-04, with the labels that each got.

#7890 Fix id error when moving to a channel
  app/components/post_list/post_list.tsx
Labels: 4: Reviews Complete, release-note-none

#7897 Update sentry to fix error with the Privacy files
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@sentry+utils+7.100.1.patch
Labels: release-note-none

#7902 Add missing privacy requirements
  ios/NotificationService/PrivacyInfo.xcprivacy
  ios/PrivacyInfo.xcprivacy
Labels: CherryPick/Approved, release-note-none

#7906 Automated cherry pick of #7902
  ios/NotificationService/PrivacyInfo.xcprivacy
  ios/PrivacyInfo.xcprivacy
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7896 Fix channel members list not fully loaded
  app/screens/manage_channel_members/manage_channel_members.tsx
Labels: 3: QA Review, release-note, Contributor, kind/bug

#7790 [MM-56585]Show only unreads filter stays active after changing the 'Group unreads' setting
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/components/threads_button/index.ts
  app/components/threads_button/threads_button.test.tsx
  app/components/threads_button/threads_button.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
Labels: 4: Reviews Complete, Build Apps for PR, release-note, Contributor

#7909 Automated cherry pick of #7790
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/components/threads_button/index.ts
  app/components/threads_button/threads_button.test.tsx
  app/components/threads_button/threads_button.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7908 Automated cherry pick of #7896
  app/screens/manage_channel_members/manage_channel_members.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7916 Manual cherrypick of PR #7915
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#7904 fix: use polyfill-force to improve startup time
  index.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note, Contributor, kind/bug

#7911 Fix erratic behavior of pull to refresh on threads
  app/components/post_list/post_list.tsx
Labels: 4: Reviews Complete, release-note

#7863 Push react native to 0.73.6
  .husky/pre-commit
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/mattermost/flipper/ReactNativeFlipper.java
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
  android/app/src/main/java/com/mattermost/rnbeta/MainActivity.kt
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
  android/app/src/main/java/com/mattermost/rnbeta/MainApplication.kt
  android/app/src/main/java/com/mattermost/share/ShareActivity.java
  android/app/src/main/java/com/mattermost/share/ShareModule.java
  android/app/src/release/java/com/mattermost/flipper/ReactNativeFlipper.java
  android/build.gradle
  android/buildscript-gradle.lockfile
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/settings-gradle.lockfile
  app/components/post_list/post/body/content/message_attachments/__snapshots__/attachment_author.test.tsx.snap
  app/components/post_list/post/body/content/message_attachments/__snapshots__/attachment_footer.test.tsx.snap
  app/components/post_list/post/system_message/system_message_helpers.test.js
  app/components/profile_picture/image.tsx
  app/components/progressive_image/index.tsx
  app/components/progressive_image/thumbnail.tsx
  app/hooks/gallery.ts
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/permissions.ts
  app/products/calls/state/actions.test.ts
  app/screens/gallery/gallery.tsx
  app/screens/gallery/lightbox_swipeout/index.tsx
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/search/search.tsx
  app/screens/sso/sso_with_webview.tsx
  app/screens/user_profile/title/avatar.tsx
  app/utils/buttonStyles.ts
  app/utils/file/file_picker/index.ts
  app/utils/file/index.ts
  babel.config.js
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@gorhom+bottom-sheet+4.6.1.patch
  patches/@react-native-community+netinfo+11.3.1.patch
  patches/@types+react-syntax-highlighter+15.5.11.patch
  patches/react-native-device-info+10.13.1.patch
  patches/react-native-fast-image+8.6.3.patch
  patches/react-native-keychain+8.2.0.patch
  patches/react-native-navigation+7.39.1.patch
  patches/react-native-reanimated+3.5.4.patch
  patches/react-native-safe-area-context+4.9.0.patch
  patches/react-native-svg+15.1.0.patch
  patches/react-native-svg-transformer+1.1.0.patch
  patches/react-native-video+5.2.1.patch
  patches/react-native-walkthrough-tooltip+1.6.0.patch
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#7912 [MM-52675] Use message_source in copy text action (#26674)
  app/screens/post_options/post_options.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#7907 MM-37809 Update Default Themes
  app/components/post_list/post/body/content/message_attachments/__snapshots__/attachment_author.test.tsx.snap
  app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
  app/components/server_icon/__snapshots__/server_icon.test.tsx.snap
  app/constants/preferences.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#7883 Fix MM 56723
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
  android/app/src/main/java/com/mattermost/helpers/database_extension/General.kt
  android/app/src/main/java/com/mattermost/helpers/database_extension/System.kt
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
  app/constants/push_notification.ts
  app/init/push_notifications.ts
  assets/base/i18n/en.json
  ios/Gekidou/Package.swift
  ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+Signature.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database+System.swift
  ios/Gekidou/Sources/Gekidou/Storage/Database.swift
  ios/GekidouWrapper.swift
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Mattermost/AppDelegate.mm
  ios/NotificationService/NotificationService.swift
Labels: 4: Reviews Complete, release-note-none

#7905 [MM-57707] - Calls: Add host controls menu
  app/constants/calls.ts
  app/constants/screens.ts
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/hooks.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/screens/call_screen/participant_card.tsx
  app/products/calls/screens/host_controls/host_controls.tsx
  app/products/calls/screens/host_controls/index.ts
  app/products/calls/screens/participants_list/participant.tsx
  app/products/calls/screens/participants_list/participants_list.tsx
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  app/screens/index.tsx
  assets/base/i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note
