Repository mattermost/mattermost-mobile, pull requests merged in 2024-03, with the labels that each got.

#7743 [MM-55988]: alert message in DM of persistent notification changed
  app/components/post_draft/draft_input/index.tsx
  app/components/post_draft/send_handler/index.ts
  app/components/post_draft/send_handler/send_handler.tsx
  app/utils/post/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#7856 CLD-7296 Fix watchman installation after dependency changes
  .github/actions/prepare-ios-build/action.yaml
Labels: release-note-none, Build App for iOS

#7871 Automated cherry pick of #7870
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7868 Translations update from Mattermost Weblate
  assets/base/i18n/pl.json
  assets/base/i18n/tr.json
Labels: release-note-none

#7854 [MM-57019] Calls: Live captions support for mobile
  app/actions/websocket/index.ts
  app/constants/calls.ts
  app/constants/websocket.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/captions.tsx
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/screens/call_screen/call_screen.tsx
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
  assets/base/i18n/en.json
  ios/Mattermost/Info.plist
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#7879 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
  assets/base/i18n/th.json
  assets/base/i18n/tr.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#7875 Add gradle lockfile
  android/build.gradle
  android/buildscript-gradle.lockfile
Labels: 4: Reviews Complete, release-note-none

#7886 Automated cherry pick of #7877
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
Labels: release-note-none
