Repository mattermost/mattermost-mobile, pull requests merged in 2024-07, with the labels that each got.

#8053 Translations update from Mattermost Weblate
  assets/base/i18n/ja.json
  assets/base/i18n/ru.json
Labels: release-note-none, Do Not Merge/Mattermod

#8049 Fix User Agent issue in some device
  app/managers/network_manager.ts
Labels: release-note, Contributor

#8040 More utils unit tests
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/utils/apps.test.ts
  app/utils/apps.ts
  app/utils/font_family.test.ts
  app/utils/font_family.ts
  app/utils/groups.test.ts
  app/utils/helpers.test.ts
  app/utils/helpers.ts
  app/utils/integrations.test.ts
  app/utils/key_mirror.test.ts
  app/utils/log.test.ts
  app/utils/mattermost_managed.test.ts
  app/utils/message_attachment_colors.test.ts
  app/utils/mix.test.ts
  app/utils/opengraph.test.ts
  app/utils/opengraph.ts
  app/utils/push_proxy.test.ts
  app/utils/reviews.test.ts
  app/utils/security.test.ts
  app/utils/sentry.test.ts
  app/utils/strings.test.ts
  app/utils/strings.ts
  app/utils/timezone.test.ts
  app/utils/typography.test.ts
  app/utils/typography.ts
  test/setup.ts
Labels: 2: Dev Review, release-note-none

#8052 Graciously handle load measure when there is no mark
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
  app/managers/performance_metrics_manager/performance_metrics_batcher.test.ts
  app/managers/performance_metrics_manager/performance_metrics_batcher.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, Build App for iOS

#8058 Add unit tests for app/actions/local/category
  app/actions/local/category.test.ts
Labels: 2: Dev Review, release-note

#8063 Add unit tests for app/actions/local/channel
  app/actions/local/channel.test.ts
  app/actions/local/channel.ts
Labels: 2: Dev Review, release-note-none

#8064 Automated cherry pick of #8052
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
  app/managers/performance_metrics_manager/performance_metrics_batcher.test.ts
  app/managers/performance_metrics_manager/performance_metrics_batcher.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8065 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/nl.json
  assets/base/i18n/ru.json
  assets/base/i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#8056 Fix button ui when disabled
  app/screens/edit_server/form.tsx
  app/screens/forgot_password/index.tsx
  app/screens/login/form.tsx
  app/screens/mfa/index.tsx
  app/screens/server/form.tsx
Labels: 2: Dev Review, release-note-none

#8050 Restore out of channel and some cleanup
  app/components/autocomplete/at_mention/at_mention.tsx
  app/components/autocomplete/at_mention/constants.ts
  app/components/autocomplete/at_mention/types.ts
  app/components/autocomplete/at_mention/utils.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note, Build App for Android

#8069 Update jest config to show coverage for correct folders
  jest.config.js
Labels: 2: Dev Review, release-note-none

#8071 Add Amy as a reviewer for the weekly build number bump PRs
  scripts/bump.sh
Labels: release-note-none

#8070 fix: add mkdir of "android/app/src/main/res/raw/" in postinstall
  scripts/postinstall.sh
Labels: release-note, kind/bug

#8076 chore: Place common beforeeach/aftereach top of file
  app/actions/local/draft.test.ts
Labels: release-note-none

#8068 Add more utils unit test coverage
  app/utils/channel/index.test.ts
  app/utils/channel/index.ts
  app/utils/deep_link/index.test.ts
  app/utils/document/index.test.ts
  app/utils/draft/index.test.ts
  app/utils/emoji/helpers.test.ts
  app/utils/emoji/helpers.ts
Labels: 4: Reviews Complete, release-note-none

#8077 Add unit tests for app/actions/local/file and app/actions/local/group
  app/actions/local/file.test.ts
  app/actions/local/group.test.ts
Labels: 4: Reviews Complete, release-note-none

#8080 fix: saving test report
  detox/save_report.js
Labels: 2: Dev Review, release-note-none

#8083 Add unit tests for app/actions/local/post
  app/actions/local/post.test.ts
Labels: 4: Reviews Complete, release-note-none

#8079 add file utils unit tests
  app/utils/file/index.test.ts
  app/utils/file/index.ts
Labels: 4: Reviews Complete, release-note-none

#8057 MM-56933 - password field do not disable autocomplete
  app/screens/login/form.tsx
Labels: release-note-none, Build App for Android

#8084 Add unit test cases for reactions.ts
  app/actions/local/reactions.test.ts
Labels: release-note-none

#8090 Automated cherry pick of #8057
  app/screens/login/form.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8094 Fix server list bottom sheet on tablet
  app/screens/home/channel_list/servers/index.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note

#8097 Automated cherry pick of #8094
  app/screens/home/channel_list/servers/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8096 Automated cherry pick of #8094
  app/screens/home/channel_list/servers/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8095 fix issues found by sonarqube
  app/actions/remote/post.ts
  app/products/calls/actions/calls.ts
  app/products/calls/alerts.ts
  app/utils/apps.test.ts
  app/utils/apps.ts
  app/utils/helpers.ts
  app/utils/url/test.ts
Labels: 4: Reviews Complete, release-note-none

#8101 update fastlane
  fastlane/Gemfile.lock
Labels: 4: Reviews Complete, release-note-none

#8106 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/ru.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#8055 SSL Pinned Certificate
  android/app/src/main/assets/certs/.gitignore
  app/client/websocket/index.ts
  app/managers/network_manager.ts
  assets/base/i18n/en.json
  assets/certs/.gitignore
  fastlane/Fastfile
  ios/Gekidou/Sources/Gekidou/Bundle+Extensions.swift
  ios/Gekidou/Sources/Gekidou/Networking/Network+Delegate.swift
  ios/Gekidou/Sources/Gekidou/Networking/Network+Error.swift
  ios/Gekidou/Sources/Gekidou/Networking/Network.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Delegate.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension.swift
  ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification.swift
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Podfile.lock
  libraries/@mattermost/rnshare/android/src/main/java/com/mattermost/rnshare/ShareWorker.kt
  libraries/@mattermost/rnshare/android/src/main/java/com/mattermost/rnshare/helpers/RealPathUtil.kt
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note

#8099 added unit tests for utils/file/file-picker
  app/utils/file/file_picker/index.test.ts
  app/utils/file/file_picker/index.ts
Labels: 4: Reviews Complete, release-note-none

#8107 Avoid registering wrong performance load logs
  app/actions/remote/entry/login.ts
  app/managers/performance_metrics_manager/index.ts
  share_extension/index.tsx
Labels: 4: Reviews Complete, release-note

#8108 Automated cherry pick of #8107
  app/actions/remote/entry/login.ts
  app/managers/performance_metrics_manager/index.ts
  share_extension/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8110 Add an architecture diagram to docs
  docs/architecture-diagram.monopic
  docs/architecture-diagram.png
Labels: 4: Reviews Complete, release-note

#8037 [MM-52657] AV1 support
  app/products/calls/connection/connection.ts
  app/products/calls/types/calls.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, QA Review Done, release-note

#8051 [MM-57698] Implement client ICE candidate pairs metric
  app/products/calls/connection/connection.test.ts
  app/products/calls/connection/connection.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#8114 fix ios and android build
  fastlane/Fastfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: release-note-none, E2E iOS tests for PR

#8112 fix loop counters should not be assigned within the loop body
  app/utils/opengraph.ts
Labels: 4: Reviews Complete, release-note-none

#8109 fix cannot read data when opening a deeplink
  app/constants/deep_linking.ts
  app/init/launch.ts
  app/managers/global_event_handler.ts
  app/screens/home/index.tsx
  app/screens/navigation.ts
  app/screens/server/index.tsx
  app/utils/deep_link/index.test.ts
  app/utils/deep_link/index.ts
  test/setup.ts
  types/launch/index.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#8118 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod
