Repository mattermost/mattermost-mobile, pull requests merged in 2025-07, with the labels that each got.

#8887 Remaining test for draft and Scheduled post
  app/components/draft_scheduled_post/draft_scheduled_post.test.tsx
  app/components/draft_scheduled_post/draft_scheduled_post.tsx
  app/components/draft_scheduled_post/draft_scheduled_post_actions/send_draft/index.test.tsx
  app/components/draft_scheduled_post_header/draft_scheduled_post_header.test.tsx
  app/components/drafts_buttton/index.test.tsx
  app/components/drafts_buttton/index.ts
  app/components/post_draft/send_button/index.test.tsx
  app/components/post_draft/send_button/index.tsx
  app/components/post_draft/send_button/send_button.test.tsx
  app/components/post_draft/send_button/send_button.tsx
  app/queries/servers/scheduled_post.test.ts
  app/queries/servers/scheduled_post.ts
  app/screens/global_drafts/components/global_scheduled_post_list/index.test.tsx
  app/screens/reschedule_draft/indext.test.tsx
  app/screens/scheduled_post_options/core_options/core_options.test.tsx
  app/screens/scheduled_post_options/core_options/index.test.tsx
  app/screens/scheduled_post_options/index.test.tsx
  test/test_helper.ts
Labels: 2: Dev Review, release-note

#8971 [MM-64358] don't save unneeded custom profile attributes
  app/screens/edit_profile/components/form.test.tsx
  app/screens/edit_profile/components/form.tsx
  app/screens/edit_profile/edit_profile.test.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/utils/user/index.ts
  types/api/custom_profile_attributes.d.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note

#8961 MM-64415 Attachment style updated for draft and Edit post screen
  app/components/post_draft/uploads/index.test.tsx
  app/components/post_draft/uploads/index.tsx
  app/components/post_draft/uploads/upload_item/index.test.tsx
  app/components/post_draft/uploads/upload_item/index.tsx
  app/components/post_draft/uploads/upload_item/upload_remove.tsx
  app/components/post_draft/uploads/upload_item/upload_retry.tsx
  app/screens/edit_post/edit_post.test.tsx
  app/screens/edit_post/edit_post.tsx
  app/screens/edit_post/edit_post_input/edit_post_input.test.tsx
  app/screens/edit_post/edit_post_input/edit_post_input.tsx
  app/screens/edit_post/post_error/index.tsx
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note, E2E Android tests for PR

#8984 Edit mode when no text and no attachment on save calls delete post
  app/components/autocomplete/autocomplete.tsx
  app/components/autocomplete/emoji_suggestion/emoji_suggestion.tsx
  app/components/post_draft/post_draft.tsx
  app/screens/create_or_edit_channel/channel_info_form.tsx
  app/screens/edit_post/edit_post.test.tsx
  app/screens/edit_post/edit_post.tsx
  app/screens/edit_post/index.test.tsx
  app/screens/edit_post/index.tsx
  app/screens/home/search/search.tsx
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, 3: QA Review, release-note

#8992 Automated cherry pick of #8985
  app/screens/home/search/search.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8988 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/ja.json
  assets/base/i18n/pt.json
Labels: release-note-none, Do Not Merge/Mattermod

#8989 Purge playbooks data when the plugin gets disabled
  app/products/playbooks/actions/local/version.test.ts
  app/products/playbooks/actions/local/version.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note-none

#8994 Remove playbooks on delete channel
  app/actions/local/channel.ts
  app/actions/local/team.test.ts
  app/actions/local/team.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/team.ts
  app/products/playbooks/database/models/playbook_checklist.test.ts
  app/products/playbooks/database/models/playbook_checklist.ts
  app/products/playbooks/database/models/playbook_run.test.ts
  app/products/playbooks/database/models/playbook_run.ts
  app/products/playbooks/types/database/models/playbook_checklist.ts
  app/products/playbooks/types/database/models/playbook_run.ts
  app/queries/servers/channel.test.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.test.ts
  app/queries/servers/entry.ts
  app/queries/servers/team.test.ts
  app/queries/servers/team.ts
  app/store/ephemeral_store.test.ts
  app/store/ephemeral_store.ts
  test/test_helper.ts
Labels: CherryPick/Approved, Build Apps for PR, QA Review Done, 3: Security Review, release-note-none

#9002 Automated cherry pick of #8989
  app/products/playbooks/actions/local/version.test.ts
  app/products/playbooks/actions/local/version.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9007 Automated cherry pick of #8997
  app/products/playbooks/screens/playbook_run/playbook_run.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8993 Fetch playbooks when we reconnect and we are on a channel
  app/actions/websocket/index.test.ts
  app/actions/websocket/index.ts
  app/managers/websocket_manager.test.ts
  app/managers/websocket_manager.ts
  app/products/playbooks/actions/remote/runs.test.ts
  app/products/playbooks/actions/remote/runs.ts
  app/products/playbooks/actions/websocket/reconnect.test.ts
  app/products/playbooks/actions/websocket/reconnect.ts
  app/products/playbooks/database/queries/version.test.ts
  app/products/playbooks/database/queries/version.ts
  app/screens/channel/header/header.test.tsx
  app/screens/channel/header/header.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, 3: Security Review, release-note-none

#9008 Automated cherry pick of #8993
  app/actions/websocket/index.test.ts
  app/actions/websocket/index.ts
  app/managers/websocket_manager.test.ts
  app/managers/websocket_manager.ts
  app/products/playbooks/actions/remote/runs.test.ts
  app/products/playbooks/actions/remote/runs.ts
  app/products/playbooks/actions/websocket/reconnect.test.ts
  app/products/playbooks/actions/websocket/reconnect.ts
  app/products/playbooks/database/queries/version.test.ts
  app/products/playbooks/database/queries/version.ts
  app/screens/channel/header/header.test.tsx
  app/screens/channel/header/header.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8998 Fix progress numbers on playbook runs
  app/products/playbooks/screens/playbook_run/checklist/checklist.test.tsx
  app/products/playbooks/screens/playbook_run/checklist/checklist.tsx
  app/products/playbooks/screens/playbook_run/checklist/index.test.tsx
  app/products/playbooks/screens/playbook_run/checklist/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note-none

#9015 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/fr.json
  assets/base/i18n/ja.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/pl.json
Labels: release-note-none, Do Not Merge/Mattermod

#9018 Automated cherry pick of #9000
  app/products/playbooks/actions/websocket/runs.test.ts
  app/products/playbooks/components/channel_actions/playbook_runs_option/index.test.tsx
  app/products/playbooks/components/channel_actions/playbook_runs_option/playbook_runs_option.test.tsx
  app/products/playbooks/components/channel_actions/playbook_runs_option/playbook_runs_option.tsx
  app/screens/channel/header/quick_actions/index.test.tsx
  app/screens/channel/header/quick_actions/index.tsx
  app/screens/channel_info/options/index.test.tsx
  app/screens/channel_info/options/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9011 Address plugin changes around incremental websocket
  app/products/playbooks/actions/websocket/events.ts
  app/products/playbooks/actions/websocket/runs.test.ts
  app/products/playbooks/actions/websocket/runs.ts
  app/products/playbooks/constants/websocket.ts
  app/products/playbooks/types/websocket.d.ts
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, release-note-none

#9024 Automated cherry pick of #9011
  app/products/playbooks/actions/websocket/events.ts
  app/products/playbooks/actions/websocket/runs.test.ts
  app/products/playbooks/actions/websocket/runs.ts
  app/products/playbooks/constants/websocket.ts
  app/products/playbooks/types/websocket.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9025 Automated cherry pick of #9022
  app/products/playbooks/constants/version.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9023 use alertOnlyPDFSupported for document files
  app/components/document/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9041 Automated cherry pick of #8952
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9042 Automated cherry pick of #8953
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9043 Automated cherry pick of #9039
  app/actions/remote/command.test.ts
  app/actions/remote/command.ts
  app/components/post_list/post/body/index.tsx
  app/constants/deep_linking.ts
  app/database/migration/server/index.ts
  app/managers/global_event_handler.ts
  app/products/playbooks/actions/remote/runs.ts
  app/products/playbooks/client/rest.ts
  app/products/playbooks/components/status_update_post/index.tsx
  app/products/playbooks/components/status_update_post/participants/index.ts
  app/products/playbooks/components/status_update_post/participants/participants.tsx
  app/products/playbooks/constants/plugin.ts
  app/screens/channel_info/channel_info.tsx
  app/screens/channel_info/index.ts
  app/screens/channel_info/options/index.test.tsx
  app/screens/channel_info/options/index.tsx
  app/screens/home/index.tsx
  app/utils/deep_link/index.test.ts
  app/utils/deep_link/index.ts
  app/utils/url/links.test.ts
  app/utils/url/links.ts
  assets/base/i18n/en.json
  fastlane/.env.ios.beta
  fastlane/.env.ios.pr
  fastlane/.env.ios.simulator
  types/api/posts.d.ts
  types/launch/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none
