Repository mattermost/mattermost-mobile, pull requests merged in 2025-09, with the labels that each got.

#9093 Automated cherry pick of #9088
  app/products/playbooks/actions/remote/runs.test.ts
  app/products/playbooks/actions/remote/runs.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9094 update react-native-network-client
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@mattermost+react-native-network-client+1.8.3.patch
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9096 Automated cherry pick of #9082
  app/actions/remote/entry/login.ts
  app/actions/remote/general.ts
  app/actions/remote/session.test.ts
  app/actions/remote/session.ts
  app/client/rest/base.ts
  app/client/rest/constants.ts
  app/client/rest/index.ts
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
  app/client/websocket/index.ts
  app/init/credentials.ts
  app/managers/network_manager.ts
  app/managers/websocket_manager.test.ts
  app/managers/websocket_manager.ts
  app/screens/login/sso_options.tsx
  app/screens/server/form.tsx
  app/screens/server/index.tsx
  app/screens/sso/index.tsx
  app/utils/url/index.ts
  assets/base/i18n/en.json
  detox/e2e/support/ui/screen/server.ts
  detox/e2e/test/server_login/preauth_secret_connection.e2e.ts
  ios/Gekidou/Sources/Gekidou/Constants.swift
  ios/Gekidou/Sources/Gekidou/Keychain.swift
  ios/Gekidou/Sources/Gekidou/Networking/Network.swift
  ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
  ios/GekidouWrapper.swift
  ios/Mattermost/Extensions/RNNotificationEventHandler+HandleReplyAction.m
  libraries/@mattermost/rnshare/android/src/main/java/com/mattermost/rnshare/ShareWorker.kt
  libraries/@mattermost/rnshare/src/NativeMattermostShare.ts
  share_extension/components/header/post_button.tsx
  types/credentials/index.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9105 chore: error on react-hooks/exhaustive-deps during pre-commit
  .gitignore
  eslint.precommit.config.mjs
  scripts/clean.sh
  scripts/pre-commit.sh
Labels: release-note, kind/chore

#9052 Typescript support and view component for permalink with user and message
  app/actions/websocket/posts.test.ts
  app/actions/websocket/posts.ts
  app/components/edited_indicator/index.test.tsx
  app/components/edited_indicator/index.tsx
  app/components/jumbo_emoji/index.tsx
  app/components/markdown/markdown.tsx
  app/components/post_list/post/body/content/content.test.tsx
  app/components/post_list/post/body/content/content.tsx
  app/components/post_list/post/body/content/index.tsx
  app/components/post_list/post/body/content/permalink_preview/index.test.tsx
  app/components/post_list/post/body/content/permalink_preview/index.tsx
  app/components/post_list/post/body/content/permalink_preview/permalink_preview.test.tsx
  app/components/post_list/post/body/content/permalink_preview/permalink_preview.tsx
  app/queries/servers/post.test.ts
  app/queries/servers/post.ts
  app/utils/permalink_sync.test.ts
  app/utils/permalink_sync.ts
  assets/base/i18n/en.json
  types/api/config.d.ts
  types/api/posts.d.ts
Labels: 2: Dev Review, Build Apps for PR, QA Review Done, release-note

#9102 feat: show pre-auth secret error on field on server create
  app/actions/remote/general.ts
  app/client/rest/error.ts
  app/client/rest/tracking.ts
  app/screens/server/form.tsx
  app/screens/server/index.tsx
  assets/base/i18n/en.json
  detox/e2e/test/products/channels/server_login/preauth_secret_connection.e2e.ts
  types/api/client.d.ts
Labels: Build Apps for PR, 3: QA Review, release-note, kind/feature

#8959 [GH-25810] fix Slack attachment button color looks wrong color for dark themes problem
  app/components/post_list/post/body/content/message_attachments/action_button/index.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#9146 Automated cherry pick of #9136
  app/components/autocomplete/autocomplete.test.tsx
  app/components/autocomplete/autocomplete.tsx
  app/products/playbooks/screens/edit_command/edit_command.test.tsx
  app/products/playbooks/screens/edit_command/edit_command.tsx
  app/products/playbooks/screens/edit_command/edit_command_form.test.tsx
  app/products/playbooks/screens/edit_command/edit_command_form.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9137 Fix playbooks bottom sheet not scrolling on ipad
  app/screens/bottom_sheet/index.tsx
Labels: 4: Reviews Complete, release-note-none, Build App for iOS

#9144 Add playbooks finish run
  app/products/playbooks/actions/remote/runs.test.ts
  app/products/playbooks/actions/remote/runs.ts
  app/products/playbooks/actions/websocket/reconnect.test.ts
  app/products/playbooks/actions/websocket/reconnect.ts
  app/products/playbooks/client/rest.test.ts
  app/products/playbooks/client/rest.ts
  app/products/playbooks/screens/playbook_run/index.test.tsx
  app/products/playbooks/screens/playbook_run/index.ts
  app/products/playbooks/screens/playbook_run/playbook_run.test.tsx
  app/products/playbooks/screens/playbook_run/playbook_run.tsx
  app/products/playbooks/utils/run.test.ts
  app/products/playbooks/utils/run.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, 3: QA Review, release-note, Build App for iOS

#9167 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
Labels: release-note-none, Do Not Merge/Mattermod
