Repository mattermost/mattermost-mobile, pull requests merged in 2025-04, with the labels that each got.

#8741 Add "APNG4Android" to ignoreDependencies in config.yaml
  build/notice-file/config.yaml
Labels: 4: Reviews Complete, release-note, kind/bug

#8742 feat: Add setup-xcode action to prepare-ios-build workflow
  .github/actions/prepare-ios-build/action.yaml
Labels: 2: Dev Review, release-note, kind/feature, Build App for iOS

#8729 Enabling Autofill on Android in the Login page
  app/screens/login/form.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#8733 channel banner DB migration
  app/database/migration/server/index.ts
  app/database/models/server/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/channel.ts
  app/database/schema/server/test.ts
  docs/database/server/server-v3.pdf
  docs/database/server/server-v3.png
  docs/database/server/server-v3.rtf
  docs/database/server/server-v4.pdf
  docs/database/server/server-v4.png
  docs/database/server/server-v4.rtf
  docs/database/server/server-v4.sql
  docs/database/server/server.md
  types/api/channels.d.ts
  types/database/models/servers/channel.ts
Labels: 2: Dev Review, release-note-none

#8722 upgrade to @mattermost/commonmark@0.31.2-0
  package-lock.json
  package.json
Labels: release-note

#8720 Unify Is Read Only logic to avoid code repetition and improve redability
  app/actions/remote/entry/common.ts
  app/components/channel_actions/leave_channel_label/index.ts
  app/components/post_draft/index.ts
  app/components/post_list/post/body/reactions/index.ts
  app/queries/servers/channel.nomock.test.ts
  app/queries/servers/channel.test.ts
  app/queries/servers/channel.ts
  app/queries/servers/role.ts
  app/screens/channel/channel_post_list/intro/intro.tsx
  app/screens/channel_info/destructive_options/archive/index.ts
  app/screens/channel_info/destructive_options/convert_private/index.ts
  app/screens/post_options/index.ts
  app/screens/user_profile/index.ts
  app/utils/channel/index.test.ts
  app/utils/channel/index.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none

#8745 [MM-62296] Update calls-common to latest
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8749 Fix the issue when click on see all tab in from channel takes to the empty scheduled post screen.
  app/actions/local/draft.test.ts
  app/actions/local/draft.ts
  app/screens/global_drafts/components/tabbed_contents/draftTabsHeader.tsx
  app/screens/global_drafts/components/tabbed_contents/tabbed_contents.test.tsx
  app/screens/global_drafts/components/tabbed_contents/tabbed_contents.tsx
  app/screens/navigation.ts
Labels: 2: Dev Review, Build Apps for PR, 3: QA Review, release-note

#8756 Update calls-common
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note-none

#8735 Channel banner display
  app/components/announcement_banner/expanded_announcement_banner.tsx
  app/components/channel_list_row/index.test.tsx
  app/constants/license.ts
  app/constants/screens.ts
  app/constants/view.ts
  app/products/calls/components/floating_call_container.tsx
  app/screens/channel/channel.tsx
  app/screens/channel/channel_feature_checks.test.tsx
  app/screens/channel/channel_feature_checks.ts
  app/screens/channel/header/channel_banner/channel_banner.test.tsx
  app/screens/channel/header/channel_banner/channel_banner.tsx
  app/screens/channel/header/channel_banner/index.ts
  app/screens/channel/header/header.tsx
  app/screens/channel/index.tsx
  app/utils/general/index.test.ts
  app/utils/general/index.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note

#8740 Refactor chips
  app/components/channel_actions/copy_channel_link_box/index.ts
  app/components/chips/base_chip.test.tsx
  app/components/chips/base_chip.tsx
  app/components/chips/constants.ts
  app/components/chips/selected_chip.test.tsx
  app/components/chips/selected_chip.tsx
  app/components/chips/selected_user_chip.test.tsx
  app/components/chips/selected_user_chip.tsx
  app/components/chips/user_chip.test.tsx
  app/components/chips/user_chip.tsx
  app/components/floating_text_chips_input/index.tsx
  app/components/selected_users/index.tsx
  app/components/selected_users/selected_user.tsx
  app/components/user_avatars_stack/index.tsx
  app/components/user_avatars_stack/users_list/index.tsx
  app/screens/invite/selection.tsx
Labels: Build Apps for PR, 3: QA Review, release-note-none

#8753 Fix SecurityManager flaky test
  app/managers/security_manager/index.test.ts
  app/managers/security_manager/index.ts
Labels: 2: Dev Review, release-note-none

#8739 [MM-62565] DB only custom profile attributes and fields
  app/actions/remote/user.ts
  app/client/rest/custom_profile_attributes.ts
  app/constants/database.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/migration/server/index.ts
  app/database/models/server/custom_profile_attribute.ts
  app/database/models/server/custom_profile_field.ts
  app/database/models/server/index.ts
  app/database/models/server/user.ts
  app/database/operator/base_data_operator/index.ts
  app/database/operator/server_data_operator/handlers/custom_profile.test.ts
  app/database/operator/server_data_operator/handlers/custom_profile.ts
  app/database/operator/server_data_operator/handlers/user.ts
  app/database/operator/server_data_operator/index.ts
  app/database/operator/server_data_operator/transformers/custom_profile.test.ts
  app/database/operator/server_data_operator/transformers/custom_profile.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/custom_profile_attribute.ts
  app/database/schema/server/table_schemas/custom_profile_field.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/test.ts
  app/queries/servers/custom_profile.test.ts
  app/queries/servers/custom_profile.ts
  app/utils/custom_profile_attribute.ts
  docs/database/server/server.md
  test/test_helper.ts
  types/api/custom_profile_attributes.d.ts
  types/database/database.ts
  types/database/models/servers/custom_profile_attribute.ts
  types/database/models/servers/custom_profile_field.ts
  types/database/models/servers/user.ts
  types/database/raw_values.d.ts
Labels: 2: Dev Review, release-note-none, QA Deferred

#8760 Fix build on Xcode 16.3
  android/build.gradle
  android/buildscript-gradle.lockfile
  app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
  app/screens/gallery/video_renderer/index.tsx
  app/screens/home/search/search.test.tsx
  fastlane/Gemfile.lock
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@nozbe+watermelondb+0.28.0.patch
  patches/@shopify+flash-list+1.8.0.patch
  patches/expo-image+2.0.7.patch
  patches/react-intl+7.1.8.patch
  patches/react-native-navigation+7.45.0.patch
  patches/react-native-reanimated+3.17.3.patch
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8763 Automated cherry pick of #8742
  .github/actions/prepare-ios-build/action.yaml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8767 Update calls-common (cherry-pick)
  package-lock.json
  package.json
Labels: release-note-none

#8765 chore(MM-63733): patch expo-image to use the latest version of APNG4Android
  android/settings.gradle
  package-lock.json
  package.json
  patches/expo-image+2.0.7.patch
Labels: release-note, kind/bug, Build App for Android

#8773 MM-63571 Android Sentry Error Checks
  app/screens/navigation.ts
  app/utils/helpers.ts
Labels: 2: Dev Review, release-note

#8769 [MM-63728] Add license load metric to About screen
  app/actions/remote/license.test.ts
  app/actions/remote/license.ts
  app/client/rest/general.test.ts
  app/client/rest/general.ts
  app/screens/settings/about/about.tsx
  assets/base/i18n/en.json
  detox/e2e/support/ui/screen/about.ts
  detox/e2e/test/account/about.e2e.ts
Labels: release-note, QA Deferred

#8777 Remove unused rnshield dependency
  package-lock.json
Labels: release-note-none

#8788 Automated cherry pick of #8787
  android/app/build.gradle
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/Info.plist
  ios/MattermostShare/Info.plist
  ios/NotificationService/Info.plist
  package-lock.json
  package.json
Labels: release-note-none

#8790 Explicitly build the universal apk
  android/app/build.gradle
  fastlane/Fastfile
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#8791 Automated cherry pick of #8790
  android/app/build.gradle
  fastlane/Fastfile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8797 Add watchman watch-del to clean script
  scripts/clean.sh
Labels: release-note-none

#8795 Fix direct message screen showing deactivated accounts
  app/screens/create_direct_message/create_direct_message.tsx
  detox/e2e/test/channels/create_direct_message.e2e.ts
Labels: 4: Reviews Complete, release-note

#8799 [MM-63889] Calls: Add backend version check to enable DC locking
  app/products/calls/client/rest.ts
  app/products/calls/connection/connection.test.ts
  app/products/calls/connection/connection.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#8809 [MM-63889] Cherry-pick to `release-2.27`
  app/products/calls/client/rest.ts
  app/products/calls/connection/connection.test.ts
  app/products/calls/connection/connection.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  package-lock.json
  package.json
Labels: release-note

#8808 Automated cherry pick of #8799
  app/products/calls/client/rest.ts
  app/products/calls/connection/connection.test.ts
  app/products/calls/connection/connection.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.ts
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8806 Unlicensed server should not show the tooltip on channel send button
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/draft_input/index.ts
  app/components/post_draft/send_button/send_button.test.tsx
  app/components/post_draft/send_button/send_button.tsx
  app/queries/servers/scheduled_post.ts
  app/screens/global_drafts/index.ts
  app/screens/home/channel_list/categories_list/index.tsx
Labels: 2: Dev Review, CherryPick/Approved, 3: QA Review, release-note, Build App for Android

#8810 Android: Fix Rescheduling pop back calendar
  app/screens/reschedule_draft/reschedule_draft.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note, Build App for Android

#8818 Automated cherry pick of #8794
  app/components/chips/base_chip.tsx
  app/screens/emoji_picker/picker/header/skintone_selector/skintone_selector.tsx
  app/screens/find_channels/filtered_list/filtered_list.tsx
  app/screens/find_channels/quick_options/quick_options.tsx
  app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
  share_extension/components/search_channels/search_channels.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8784 [MM-63509] Fix: Protect against license can be undefined
  app/screens/settings/about/about.tsx
  app/screens/settings/about/title.tsx
Labels: 4: Reviews Complete, release-note

#8804 [MM-63382] Calls: Fix rendering of long user/channel name in call bar
  app/products/calls/components/current_call_bar/current_call_bar.tsx
Labels: 4: Reviews Complete, release-note
