Repository mattermost/mattermost-mobile, pull requests merged in 2025-03, with the labels that each got.

#8637 Scheduled post typing indicator and user typing indicator UI fix
  app/components/post_list/scroll_to_end_view.tsx
  app/components/scheduled_post_indicator/scheduled_post_indicator.tsx
Labels: release-note-none

#8653 Translations update from Mattermost Weblate
  assets/base/i18n/da.json
  assets/base/i18n/es.json
  assets/base/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod

#8652 Fix more messages indicator on read only channels
  app/components/post_draft/read_only/index.tsx
Labels: 4: Reviews Complete, release-note-none

#8646 MM-62896 Keyboard blocks input
  app/context/extra_keyboard/index.tsx
  app/hooks/device.ts
  app/screens/interactive_dialog/index.tsx
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/RNUtilsModuleImpl.kt
  patches/react-native-keyboard-aware-scroll-view+0.9.5.patch
Labels: CherryPick/Approved, Build Apps for PR, 3: QA Review, release-note

#8651 Do not use extra keyboard on Android
  app/components/post_draft/post_draft.tsx
  app/screens/navigation.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note

#8650 Improve emoji picker performance introducing flashList
  android/app/build.gradle
  app/actions/remote/custom_emoji.test.ts
  app/actions/remote/custom_emoji.ts
  app/components/emoji/emoji.tsx
  app/constants/emoji.ts
  app/screens/emoji_picker/picker/filtered/emoji_item.tsx
  app/screens/emoji_picker/picker/filtered/filtered.tsx
  app/screens/emoji_picker/picker/footer/index.tsx
  app/screens/emoji_picker/picker/sections/emoji_image.tsx
  app/screens/emoji_picker/picker/sections/emoji_row.tsx
  app/screens/emoji_picker/picker/sections/index.tsx
  app/screens/emoji_picker/picker/sections/section_header.tsx
  app/utils/emoji/prefetch.test.ts
  app/utils/emoji/prefetch.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@shopify+flash-list+1.7.3.patch
  types/screens/emoji_selector.d.ts
Labels: 2: Dev Review, release-note

#8633 [MM-62925] introduce websocket client-side ping
  app/client/websocket/index.test.ts
  app/client/websocket/index.ts
  app/constants/websocket.ts
  test/timer_helpers.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note, E2E Android tests for PR

#8661 Automated cherry pick of #8651
  app/components/post_draft/post_draft.tsx
  app/screens/navigation.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8665 Automated cherry pick of #8622
  .github/actions/prepare-node-deps/action.yaml
  package-lock.json
  package.json
  scripts/postinstall.sh
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8648 Fix list scrolling inside bottom sheet
  app/components/announcement_banner/expanded_announcement_banner.tsx
  app/components/files/file_filter.tsx
  app/components/team_list/index.tsx
  app/components/user_avatars_stack/users_list/index.tsx
  app/hooks/bottom_sheet_lists_fix.test.tsx
  app/hooks/bottom_sheet_lists_fix.ts
  app/products/calls/screens/participants_list/participants_list.tsx
  app/queries/servers/team.test.ts
  app/queries/servers/team.ts
  app/screens/home/channel_list/servers/servers_list/index.tsx
  app/screens/home/search/bottom_sheet_team_list.tsx
  app/screens/home/search/index.tsx
  app/screens/home/search/team_picker.tsx
  app/screens/post_options/post_options.tsx
  app/screens/reactions/reactors_list/index.tsx
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#8664 fix keyboard blocking input on mentions notifications settings
  app/screens/settings/notification_mention/mention_settings.tsx
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none, E2E iOS tests for PR

#8634 Error handling for API call fails for Scheduled post
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/components/post_draft/send_handler/send_handler.test.tsx
  app/constants/snack_bar.ts
  app/hooks/handle_send_message.test.tsx
  app/hooks/handle_send_message.ts
  app/screens/draft_scheduled_post_options/delete_draft.test.tsx
  app/screens/draft_scheduled_post_options/delete_draft.tsx
  app/screens/draft_scheduled_post_options/draft_scheduled_post_options.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.tsx
  app/screens/draft_scheduled_post_options/send_draft.test.tsx
  app/screens/draft_scheduled_post_options/send_draft.tsx
  app/screens/global_drafts/constants.ts
  app/screens/reschedule_draft/reschedule_draft.test.tsx
  app/screens/reschedule_draft/reschedule_draft.tsx
  app/utils/scheduled_post/index.ts
  app/utils/scheduled_post/scheduled_post.test.ts
Labels: release-note

#8628 Map error code for scheduled post
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/components/draft_scheduled_post_header/draft_scheduled_post_header.tsx
  app/components/post_draft/send_handler/send_handler.test.tsx
  app/constants/snack_bar.ts
  app/hooks/handle_send_message.test.tsx
  app/hooks/handle_send_message.ts
  app/screens/draft_scheduled_post_options/delete_draft.test.tsx
  app/screens/draft_scheduled_post_options/delete_draft.tsx
  app/screens/draft_scheduled_post_options/draft_scheduled_post_options.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.tsx
  app/screens/draft_scheduled_post_options/send_draft.test.tsx
  app/screens/draft_scheduled_post_options/send_draft.tsx
  app/screens/global_drafts/constants.ts
  app/screens/reschedule_draft/reschedule_draft.test.tsx
  app/screens/reschedule_draft/reschedule_draft.tsx
  app/screens/scheduled_post_options/core_options/core_options.tsx
  app/screens/scheduled_post_options/scheduled_post_picker.tsx
  app/utils/scheduled_post/index.ts
  app/utils/scheduled_post/scheduled_post.test.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, Build Apps for PR, release-note

#8675 Update useExternalLink to match webapp
  app/hooks/use_external_link.test.ts
  app/hooks/use_external_link.ts
Labels: 4: Reviews Complete, release-note-none

#8627 Swipable delete for Schedule post
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/components/draft_scheduled_post_header/draft_scheduled_post_header.tsx
  app/components/post_draft/send_button/scheduled_post_tooltip.tsx
  app/components/post_draft/send_handler/send_handler.test.tsx
  app/constants/snack_bar.ts
  app/hooks/handle_send_message.test.tsx
  app/hooks/handle_send_message.ts
  app/screens/draft_scheduled_post_options/delete_draft.test.tsx
  app/screens/draft_scheduled_post_options/delete_draft.tsx
  app/screens/draft_scheduled_post_options/draft_scheduled_post_options.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.tsx
  app/screens/draft_scheduled_post_options/send_draft.test.tsx
  app/screens/draft_scheduled_post_options/send_draft.tsx
  app/screens/global_drafts/components/draft_and_scheduled_post_swipe_actions.test.tsx
  app/screens/global_drafts/components/draft_and_scheduled_post_swipe_actions.tsx
  app/screens/global_drafts/constants.ts
  app/screens/reschedule_draft/reschedule_draft.test.tsx
  app/screens/reschedule_draft/reschedule_draft.tsx
  app/screens/scheduled_post_options/core_options/core_options.tsx
  app/screens/scheduled_post_options/scheduled_post_picker.tsx
  app/utils/scheduled_post/index.ts
  app/utils/scheduled_post/scheduled_post.test.ts
  assets/base/i18n/en.json
Labels: 2: Dev Review, release-note

#8626 Fixed count, error state and created empty state component for scheduled post and draft
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/components/draft_scheduled_post_header/draft_scheduled_post_header.tsx
  app/components/post_draft/send_handler/send_handler.test.tsx
  app/components/scheduled_post_indicator/index.ts
  app/components/scheduled_post_indicator/scheduled_post_indicator.test.tsx
  app/components/scheduled_post_indicator/scheduled_post_indicator.tsx
  app/components/scheduled_post_indicator_with_datetime/__tests__/scheduled_post_indicator_with_datetime.test.tsx
  app/components/scheduled_post_indicator_with_datetime/index.tsx
  app/components/scheduled_post_indicator_with_datetime/scheduled_post_indicator_with_datetime.tsx
  app/constants/snack_bar.ts
  app/hooks/handle_send_message.test.tsx
  app/hooks/handle_send_message.ts
  app/queries/servers/scheduled_post.ts
  app/screens/channel/channel.tsx
  app/screens/draft_scheduled_post_options/delete_draft.test.tsx
  app/screens/draft_scheduled_post_options/delete_draft.tsx
  app/screens/draft_scheduled_post_options/draft_scheduled_post_options.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.test.tsx
  app/screens/draft_scheduled_post_options/rescheduled_draft.tsx
  app/screens/draft_scheduled_post_options/send_draft.test.tsx
  app/screens/draft_scheduled_post_options/send_draft.tsx
  app/screens/global_drafts/components/draft_and_scheduled_post_swipe_actions.test.tsx
  app/screens/global_drafts/components/draft_and_scheduled_post_swipe_actions.tsx
  app/screens/global_drafts/components/global_scheduled_post_list/global_scheduled_post_list.tsx
  app/screens/global_drafts/components/scheduled_post_empty_component.test.tsx
  app/screens/global_drafts/components/scheduled_post_empty_component.tsx
  app/screens/global_drafts/constants.ts
  app/screens/global_drafts/global_drafts.test.tsx
  app/screens/global_drafts/index.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/reschedule_draft/reschedule_draft.test.tsx
  app/screens/reschedule_draft/reschedule_draft.tsx
  app/screens/scheduled_post_options/core_options/core_options.tsx
  app/screens/scheduled_post_options/scheduled_post_picker.tsx
  app/screens/thread/thread.tsx
  app/utils/scheduled_post/index.ts
  app/utils/scheduled_post/scheduled_post.test.ts
  assets/base/i18n/en.json
  assets/base/images/Scheduled_Message.png
Labels: 2: Dev Review, release-note

#8673 Avoid unnecessary re-renders
  app/components/post_list/post/body/message/message.tsx
  app/context/theme/index.tsx
  app/screens/settings/display_theme/display_theme.tsx
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, 3: QA Review, release-note-none

#8676 Automated cherry pick of #8673
  app/components/post_list/post/body/message/message.tsx
  app/context/theme/index.tsx
  app/screens/settings/display_theme/display_theme.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8659 Updated empty state images
  app/components/no_results_with_term/index.tsx
  app/components/no_results_with_term/search_files_illustration.tsx
  app/components/no_results_with_term/search_illustration.tsx
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/screens/channel/channel_post_list/intro/illustration/private.tsx
  app/screens/channel/channel_post_list/intro/illustration/public.tsx
  app/screens/channel/channel_post_list/intro/illustration/town_square.tsx
  app/screens/global_threads/threads_list/illustrations/empty_state.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/empty_state/empty_unreads.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/empty_state/index.tsx
  app/screens/home/recent_mentions/components/mention_icon.tsx
  app/screens/home/saved_messages/components/saved_posts_icon.tsx
Labels: CherryPick/Approved, Build Apps for PR, 2: UX Review, release-note

#8678 Automated cherry pick of #8659
  app/components/no_results_with_term/index.tsx
  app/components/no_results_with_term/search_files_illustration.tsx
  app/components/no_results_with_term/search_illustration.tsx
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/screens/channel/channel_post_list/intro/illustration/private.tsx
  app/screens/channel/channel_post_list/intro/illustration/public.tsx
  app/screens/channel/channel_post_list/intro/illustration/town_square.tsx
  app/screens/global_threads/threads_list/illustrations/empty_state.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/empty_state/empty_unreads.tsx
  app/screens/home/channel_list/categories_list/categories/unreads/empty_state/index.tsx
  app/screens/home/recent_mentions/components/mention_icon.tsx
  app/screens/home/saved_messages/components/saved_posts_icon.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8570 Make attachments and app bindings more robust yet secure
  app/actions/remote/apps.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/embedded_binding.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_menu/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/settings/radio_setting/index.tsx
  app/hooks/apps.ts
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_field.tsx
  app/screens/channel_info/app_bindings/index.tsx
  app/screens/integration_selector/integration_selector.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/post_options/options/app_bindings_post_option.tsx
  app/utils/apps.ts
  app/utils/message_attachment.test.ts
  app/utils/message_attachment.ts
  assets/base/i18n/en.json
  types/api/apps.d.ts
  types/api/integrations.d.ts
  types/api/posts.d.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8642 ci(MM-63199): code coverage tracking
  .github/actions/test-coverage/action.yml
  .github/actions/test/action.yaml
  .github/workflows/ci.yml
  jest.config.js
  scripts/compare-coverage.sh
  scripts/read-coverage.sh
Labels: release-note, Reset Test Coverage

#8683 Automated cherry pick of #8570
  app/actions/remote/apps.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/embedded_binding.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_menu/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/settings/radio_setting/index.tsx
  app/hooks/apps.ts
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_field.tsx
  app/screens/channel_info/app_bindings/index.tsx
  app/screens/integration_selector/integration_selector.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/post_options/options/app_bindings_post_option.tsx
  app/utils/apps.ts
  app/utils/message_attachment.test.ts
  app/utils/message_attachment.ts
  assets/base/i18n/en.json
  types/api/apps.d.ts
  types/api/integrations.d.ts
  types/api/posts.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8681 update react-native-emm fixes navigation perf degradation on iOS
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#8686 Automated cherry pick of #8681
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8688 Minor CSS and title fixes for Tablet scheduled post
  app/components/draft_scheduled_post/draft_scheduled_post.tsx
  app/screens/global_drafts/components/tabbed_contents/tabbed_contents.tsx
  assets/base/i18n/en.json
Labels: release-note

#8624 Fix team sidebar not showing thread unreads
  app/actions/local/post.test.ts
  app/actions/local/systems.test.ts
  app/actions/local/thread.test.ts
  app/actions/remote/entry/notification.test.ts
  app/actions/remote/notifications.test.ts
  app/actions/remote/post.test.ts
  app/actions/remote/preference.test.ts
  app/actions/remote/reactions.test.ts
  app/actions/remote/search.test.ts
  app/actions/remote/thread.test.ts
  app/components/files/files.test.tsx
  app/components/team_sidebar/team_list/team_item/index.test.tsx
  app/components/team_sidebar/team_list/team_item/index.ts
  app/hooks/files.test.ts
  app/queries/servers/channel.test.ts
  app/queries/servers/channel.ts
  app/queries/servers/team.test.ts
  app/queries/servers/team.ts
  test/api_mocks/file.ts
  test/test_helper.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8690 ci(MM-63199): fix download artifact issue
  .github/actions/test-coverage/action.yml
  .github/workflows/ci.yml
  scripts/compare-coverage.sh
Labels: release-note

#8685 Translations update from Mattermost Weblate
  assets/base/i18n/be.json
  assets/base/i18n/bg.json
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/el.json
  assets/base/i18n/en_AU.json
  assets/base/i18n/es.json
  assets/base/i18n/fa.json
  assets/base/i18n/fr.json
  assets/base/i18n/fy.json
  assets/base/i18n/hu.json
  assets/base/i18n/it.json
  assets/base/i18n/ja.json
  assets/base/i18n/ko.json
  assets/base/i18n/lt.json
  assets/base/i18n/ml.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/ne.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/ro.json
  assets/base/i18n/ru.json
  assets/base/i18n/sq.json
  assets/base/i18n/sv.json
  assets/base/i18n/tr.json
  assets/base/i18n/uk.json
  assets/base/i18n/vi.json
  assets/base/i18n/zh-CN.json
  assets/base/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#8641 Better handle threads sync
  app/actions/remote/thread.ts
  app/utils/thread/index.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8693 fix(MM-63460): HTTPClientError spam
  ios/ErrorReporting/Sentry.swift
Labels: Tests/Not Needed, CherryPick/Approved, release-note, kind/bug

#8698 Automated cherry pick of #8570
  app/actions/remote/apps.ts
  app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
  app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
  app/components/post_list/post/body/content/embedded_bindings/embedded_binding.tsx
  app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
  app/components/post_list/post/body/content/message_attachments/action_menu/index.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
  app/components/settings/radio_setting/index.tsx
  app/hooks/apps.ts
  app/screens/apps_form/apps_form_component.tsx
  app/screens/apps_form/apps_form_field.tsx
  app/screens/channel_info/app_bindings/index.tsx
  app/screens/integration_selector/integration_selector.tsx
  app/screens/interactive_dialog/dialog_element.tsx
  app/screens/post_options/options/app_bindings_post_option.tsx
  app/utils/apps.ts
  app/utils/message_attachment.test.ts
  app/utils/message_attachment.ts
  assets/base/i18n/en.json
  types/api/apps.d.ts
  types/api/integrations.d.ts
  types/api/posts.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8700 Automated cherry pick of #8693
  ios/ErrorReporting/Sentry.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8697 [MM-63481] Don't substract keyboard height in Android as it was already substracted
  app/components/post_draft/post_draft.tsx
  app/hooks/autocomplete.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#8707 Automated cherry pick of #8697
  app/components/post_draft/post_draft.tsx
  app/hooks/autocomplete.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8710 Automated cherry pick of #8697
  app/components/post_draft/post_draft.tsx
  app/hooks/autocomplete.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8657 chore(deps-dev): Bump Node.js to ^22.11.0 (LTS)
  .github/workflows/build-android-beta.yml
  .github/workflows/build-android-release.yml
  .github/workflows/build-ios-beta.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-pr.yml
  .github/workflows/ci.yml
  .node-version
  .nvmrc
  package-lock.json
  package.json
Labels: release-note-none, Contributor

#8719 [MM-62176] fix ordering after edit
  app/screens/edit_profile/edit_profile.test.tsx
  app/screens/edit_profile/edit_profile.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note

#8723 Automated cherry pick of #8719
  app/screens/edit_profile/edit_profile.test.tsx
  app/screens/edit_profile/edit_profile.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8715 Add model mocks to TestHelper
  app/actions/local/post.test.ts
  app/actions/local/user.test.ts
  app/actions/local/user.ts
  app/actions/remote/user.ts
  app/actions/websocket/index.test.ts
  app/actions/websocket/posts.test.ts
  app/actions/websocket/roles.test.ts
  app/actions/websocket/teams.test.ts
  app/actions/websocket/users.test.ts
  app/components/post_list/combined_user_activity/combined_user_activity.tsx
  app/constants/general.ts
  app/constants/post.ts
  app/database/operator/app_data_operator/transformers/index.ts
  app/database/operator/base_data_operator/index.ts
  app/database/operator/server_data_operator/handlers/channel.ts
  app/database/operator/server_data_operator/handlers/index.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/database/operator/server_data_operator/handlers/team_threads_sync.ts
  app/database/operator/server_data_operator/transformers/category.ts
  app/database/operator/server_data_operator/transformers/channel.test.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/operator/server_data_operator/transformers/general.test.ts
  app/database/operator/server_data_operator/transformers/general.ts
  app/database/operator/server_data_operator/transformers/group.ts
  app/database/operator/server_data_operator/transformers/index.ts
  app/database/operator/server_data_operator/transformers/post.test.ts
  app/database/operator/server_data_operator/transformers/post.ts
  app/database/operator/server_data_operator/transformers/reaction.test.ts
  app/database/operator/server_data_operator/transformers/reaction.ts
  app/database/operator/server_data_operator/transformers/team.ts
  app/database/operator/server_data_operator/transformers/thread.ts
  app/database/operator/server_data_operator/transformers/user.ts
  app/database/operator/utils/general.ts
  app/database/operator/utils/reaction.ts
  app/database/operator/utils/thread.ts
  app/hooks/markdown.test.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/utils.test.ts
  app/queries/servers/channel.test.ts
  app/queries/servers/role.test.ts
  app/screens/edit_profile/components/form.test.tsx
  app/screens/home/tab_bar/account.test.tsx
  app/screens/settings/notification_mention/mention_settings.test.tsx
  app/screens/user_profile/user_info.test.tsx
  app/utils/categories.test.ts
  app/utils/post/index.test.ts
  app/utils/post/index.ts
  app/utils/post_list/index.test.ts
  app/utils/post_list/index.ts
  app/utils/types.ts
  app/utils/url/test.ts
  app/utils/user/index.test.ts
  test/test_helper.ts
  types/api/posts.d.ts
  types/database/database.ts
  types/database/models/servers/post.ts
  types/database/raw_values.d.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none
