Repository mattermost/mattermost-mobile, pull requests merged in 2025-05, with the labels that each got.

#8819 Renamed premium SKU to Enterprise Advanced
  app/constants/license.ts
  app/screens/channel/channel_feature_checks.test.tsx
  app/screens/channel/channel_feature_checks.ts
  app/screens/channel/header/channel_banner/channel_banner.test.tsx
Labels: 2: Dev Review, release-note-none

#8827 Fix back button not closing the app
  patches/react-native-navigation+7.45.0.patch
Labels: CherryPick/Approved, 3: QA Review, release-note, Build App for Android

#8833 Automated cherry pick of #8827
  patches/react-native-navigation+7.45.0.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8815 [MM-62874] Fix iPad hw keyboard overlapping input
  app/context/extra_keyboard/index.tsx
Labels: 4: Reviews Complete, release-note

#8837 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/ja.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/pt-BR.json
Labels: release-note-none, Do Not Merge/Mattermod

#8822 Add error boundary to latex code
  app/screens/latex/index.tsx
  app/screens/latex/latex.test.tsx
Labels: release-note, Build App for Android

#8828 Fix category sorting difference between mobile and web
  app/database/operator/server_data_operator/transformers/category.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#8839 [MM-63963] Remove unused constants from SelfHostedProducts
  app/constants/license.ts
Labels: release-note-none

#8842 Add is_blocked to FileModel
  app/actions/local/file.test.ts
  app/actions/local/file.ts
  app/database/migration/server/index.ts
  app/database/models/server/file.ts
  app/database/operator/server_data_operator/transformers/general.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/file.ts
  app/database/schema/server/test.ts
  docs/database/server/server.md
  ios/patches/SessionDelegate.patch
  test/test_helper.ts
  types/database/models/servers/file.ts
Labels: 2: Dev Review, release-note-none

#8466 [MM-62491] Removing exported receivers.
  patches/@voximplant+react-native-foreground-service+3.0.2.patch
Labels: 4: Reviews Complete, release-note

#8816 [MM-63548] Address potential risks
  app/components/post_list/post/body/content/message_attachments/message_attachment.test.tsx
  app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note-none

#8846 Update transitive dependency prismjs
  package-lock.json
  package.json
Labels: release-note-none

#8829 [MM-63808] Calls: Fix scrolling in participants list
  app/products/calls/screens/participants_list/participants_list.tsx
Labels: 4: Reviews Complete, release-note

#8750 Add the channel options to get into playbooks
  app/components/navigation_header/header.test.tsx
  app/components/navigation_header/header.tsx
  app/constants/screens.ts
  app/products/playbooks/components/channel_actions/playbook_runs_option/index.ts
  app/products/playbooks/components/channel_actions/playbook_runs_option/playbook_runs_option.test.tsx
  app/products/playbooks/components/channel_actions/playbook_runs_option/playbook_runs_option.tsx
  app/products/playbooks/queries/playbooks.ts
  app/products/playbooks/screens/navigation.test.ts
  app/products/playbooks/screens/navigation.ts
  app/products/playbooks/screens/playbook_run/index.tsx
  app/products/playbooks/screens/playbooks_runs/index.tsx
  app/screens/channel/header/header.test.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/index.ts
  app/screens/channel/header/quick_actions/index.test.tsx
  app/screens/channel/header/quick_actions/index.tsx
  app/screens/channel_info/options/index.tsx
  app/screens/index.tsx
  assets/base/i18n/en.json
  babel.config.js
  eslint.config.mjs
  test/setup.ts
  test/test_helper.ts
  tsconfig.json
  types/database/models/servers/playbook_run_model.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none

#8811 [MM-63553] Fix for: messages received on the background on iOS lose the props
  app/actions/remote/notifications.test.ts
  app/actions/remote/notifications.ts
Labels: 2: Dev Review, release-note

#8798 [MM-61995] Correct copying instructions when long-pressing an email in messages & headers
  app/components/markdown/markdown_link/markdown_link.tsx
  app/screens/channel_info/extra/extra.tsx
  assets/base/i18n/en.json
Labels: 2: Dev Review, Build Apps for PR, release-note, Contributor

#8854 Automated cherry pick of #8811
  app/actions/remote/notifications.test.ts
  app/actions/remote/notifications.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8849 MM-63935 - abac end user indicators db changes
  app/actions/remote/channel_access_control_attributes.ts
  app/client/rest/channels.ts
  app/components/alert_banner/alert_banner.test.tsx
  app/components/alert_banner/alert_banner.tsx
  app/components/alert_banner/index.tsx
  app/components/alert_banner/tag.test.tsx
  app/components/alert_banner/tag.tsx
  app/database/migration/server/index.ts
  app/database/models/server/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/channel.ts
  app/database/schema/server/test.ts
  app/hooks/access_control_attributes.test.ts
  app/hooks/access_control_attributes.ts
  app/screens/channel_add_members/channel_add_members.tsx
  app/screens/manage_channel_members/index.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
  assets/base/i18n/en.json
  types/api/channels.d.ts
  types/database/models/servers/channel.ts
Labels: 2: Dev Review, Do Not Merge, Build Apps for PR, 2: UX Review, release-note-none

#8859 Revert "MM-63935 - abac end user indicators db changes"
  app/actions/remote/channel_access_control_attributes.ts
  app/client/rest/channels.ts
  app/components/alert_banner/alert_banner.test.tsx
  app/components/alert_banner/alert_banner.tsx
  app/components/alert_banner/index.tsx
  app/components/alert_banner/tag.test.tsx
  app/components/alert_banner/tag.tsx
  app/database/migration/server/index.ts
  app/database/models/server/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/channel.ts
  app/database/schema/server/test.ts
  app/hooks/access_control_attributes.test.ts
  app/hooks/access_control_attributes.ts
  app/screens/channel_add_members/channel_add_members.tsx
  app/screens/manage_channel_members/index.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
  assets/base/i18n/en.json
  types/api/channels.d.ts
  types/database/models/servers/channel.ts
Labels: release-note-none

#8860 Mm 63935 abac end user indicators db isolated changes
  app/database/migration/server/index.ts
  app/database/models/server/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/channel.ts
  app/database/schema/server/test.ts
  types/database/models/servers/channel.ts
Labels: release-note-none

#8862 MM-63935- abac end user indicators db fix
  types/api/channels.d.ts
Labels: release-note-none

#8861 Automated cherry pick of #8860
  app/database/migration/server/index.ts
  app/database/models/server/channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/channel.ts
  app/database/schema/server/test.ts
  types/api/channels.d.ts
  types/database/models/servers/channel.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8838 Fix ephemeral messages disappearing when updating them
  app/actions/websocket/posts.test.ts
  app/actions/websocket/posts.ts
Labels: 4: Reviews Complete, release-note, E2E Android tests for PR

#8747 [MM-63580] Remove long deprecated Calls code
  app/actions/websocket/event.test.ts
  app/actions/websocket/event.ts
  app/constants/calls.ts
  app/constants/websocket.ts
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/connection/websocket_event_handlers.test.ts
  app/products/calls/connection/websocket_event_handlers.ts
  app/products/calls/types/calls.ts
  app/products/calls/utils.test.ts
  app/products/calls/utils.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none

#8835 Update supported ESR version
  README.md
  app/constants/supported_server.ts
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#8863 Automated cherry pick of #8835
  README.md
  app/constants/supported_server.ts
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/changelog
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8867 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt-BR.json
  assets/base/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod

#8848 Mm 63935 abac end user indicators
  app/actions/remote/channel_access_control_attributes.ts
  app/client/rest/channels.ts
  app/components/section_notice/__snapshots__/index.test.tsx.snap
  app/components/section_notice/index.tsx
  app/components/tag/index.tsx
  app/hooks/access_control_attributes.test.ts
  app/hooks/access_control_attributes.ts
  app/screens/channel_add_members/channel_add_members.tsx
  app/screens/manage_channel_members/index.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
  app/screens/settings/notifications/send_test_notification_notice/__snapshots__/send_test_notification_notice.test.tsx.snap
  assets/base/i18n/en.json
  types/api/channels.d.ts
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, 2: UX Review, release-note

#8852 use the actual url in the metadata if there is an image proxy being used
  app/components/markdown/markdown_image/index.tsx
  app/components/markdown/markdown_table_image/index.tsx
  app/utils/markdown/index.test.ts
  app/utils/markdown/index.ts
Labels: 4: Reviews Complete, release-note-none

#8869 Mm 63935 abac end user indicators (#8848)
  app/actions/remote/channel_access_control_attributes.ts
  app/client/rest/channels.ts
  app/components/section_notice/__snapshots__/index.test.tsx.snap
  app/components/section_notice/index.tsx
  app/components/tag/index.tsx
  app/hooks/access_control_attributes.test.ts
  app/hooks/access_control_attributes.ts
  app/screens/channel_add_members/channel_add_members.tsx
  app/screens/manage_channel_members/index.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
  app/screens/settings/notifications/send_test_notification_notice/__snapshots__/send_test_notification_notice.test.tsx.snap
  assets/base/i18n/en.json
  types/api/channels.d.ts
Labels: release-note-none

#8874 Random fixes
  app/context/device/index.tsx
  app/managers/security_manager/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8875 Automated cherry pick of #8874
  app/context/device/index.tsx
  app/managers/security_manager/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8823 feat(MM-63936): add mark function in performance metrics manager
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
Labels: release-note, kind/feature

#8879 [MM-64354] Simplify snappoints based on team numbers
  app/screens/home/search/bottom_sheet_team_list.tsx
  app/screens/home/search/team_picker.tsx
Labels: 2: Dev Review, Build Apps for PR, QA Review Done, release-note

#8877 Fix scheduled messages tooltip entering an infinite resize loop
  app/constants/tooltip.ts
Labels: 4: Reviews Complete, release-note

#8886 Automated cherry pick of #8877
  app/constants/tooltip.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8853 Custom Emojis not updating on application
  app/database/operator/server_data_operator/handlers/index.test.ts
  app/database/operator/server_data_operator/handlers/index.ts
Labels: 4: Reviews Complete, release-note, Contributor, kind/bug, E2E Android tests for PR

#8758 [MM-62565] Custom Profile attributes websocket changes
  app/actions/remote/custom_profile.test.ts
  app/actions/remote/custom_profile.ts
  app/actions/remote/user.test.ts
  app/actions/websocket/event.ts
  app/actions/websocket/users.test.ts
  app/actions/websocket/users.ts
  app/constants/websocket.ts
  app/database/operator/server_data_operator/handlers/custom_profile.test.ts
  app/database/operator/server_data_operator/handlers/custom_profile.ts
  app/queries/servers/custom_profile.test.ts
  app/queries/servers/custom_profile.ts
  app/screens/edit_profile/edit_profile.test.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/edit_profile/index.ts
  app/screens/user_profile/index.ts
  app/screens/user_profile/user_info.test.tsx
  app/screens/user_profile/user_info.tsx
  app/screens/user_profile/user_profile.tsx
  app/utils/user/index.test.ts
  app/utils/user/index.ts
  test/test_helper.ts
  types/screens/edit_profile.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note-none

#8691 Standardize tabs across different components
  app/components/formatted_text/index.tsx
  app/constants/draft.ts
  app/hooks/use_tabs/index.ts
  app/hooks/use_tabs/tab.test.tsx
  app/hooks/use_tabs/tab.tsx
  app/hooks/use_tabs/tabs.test.tsx
  app/hooks/use_tabs/tabs.tsx
  app/hooks/use_tabs/types.ts
  app/hooks/use_tabs/use_tabs.test.tsx
  app/hooks/use_tabs/use_tabs.ts
  app/screens/global_drafts/components/tabbed_contents/draft_tabs_header.test.tsx
  app/screens/global_drafts/components/tabbed_contents/draft_tabs_header.tsx
  app/screens/global_drafts/components/tabbed_contents/tabbed_contents.test.tsx
  app/screens/global_drafts/components/tabbed_contents/tabbed_contents.tsx
  app/screens/global_drafts/global_drafts.test.tsx
  app/screens/global_threads/global_threads.test.tsx
  app/screens/global_threads/global_threads.tsx
  app/screens/global_threads/index.test.tsx
  app/screens/global_threads/index.tsx
  app/screens/global_threads/threads_list/header/index.test.tsx
  app/screens/global_threads/threads_list/header/index.tsx
  app/screens/global_threads/threads_list/index.ts
  app/screens/global_threads/threads_list/threads_list.tsx
  app/screens/home/search/results/header.test.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/header_button.tsx
  app/screens/home/search/search.test.tsx
  app/screens/home/search/search.tsx
  detox/e2e/support/ui/screen/global_threads.ts
  detox/e2e/support/ui/screen/scheduled_message_screen.ts
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none

#8880 feat(MM-64361): categoryChannels update ONLY when necessary
  app/database/operator/server_data_operator/handlers/category.test.ts
  app/database/operator/server_data_operator/handlers/category.ts
Labels: release-note, kind/feature

#8865 Unify buttons
  app/components/announcement_banner/expanded_announcement_banner.tsx
  app/components/button/index.tsx
  app/components/loading/index.tsx
  app/components/loading_error/__snapshots__/index.test.tsx.snap
  app/components/loading_error/index.tsx
  app/components/section_notice/__snapshots__/index.test.tsx.snap
  app/components/selected_users/index.tsx
  app/screens/apps_form/apps_form_component.tsx
  app/screens/bottom_sheet/button.tsx
  app/screens/bottom_sheet/content.tsx
  app/screens/channel_bookmark/index.tsx
  app/screens/channel_notification_preferences/muted_banner.tsx
  app/screens/convert_gm_to_channel/convert_gm_to_channel_form/convert_gm_to_channel_form.tsx
  app/screens/edit_server/form.tsx
  app/screens/forgot_password/index.tsx
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/home/channel_list/categories_list/categories/unreads/empty_state/index.tsx
  app/screens/invite/summary.tsx
  app/screens/login/form.tsx
  app/screens/login/sso_options.tsx
  app/screens/mfa/index.tsx
  app/screens/onboarding/footer_buttons.tsx
  app/screens/permalink/permalink.tsx
  app/screens/permalink/permalink_error.tsx
  app/screens/select_team/no_teams.tsx
  app/screens/server/form.tsx
  app/screens/settings/notifications/send_test_notification_notice/__snapshots__/send_test_notification_notice.test.tsx.snap
  app/screens/sso/components/auth_error.tsx
  app/screens/user_profile/options.tsx
  app/screens/user_profile/user_profile.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, release-note
