Repository mattermost/mattermost-mobile, pull requests merged in 2025-06, with the labels that each got.

#8892 feat(MM-64410): batch write all posts for all channels by team
  app/actions/local/post.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/post.auxiliary.test.ts
  app/actions/remote/post.auxiliary.ts
  app/actions/remote/post.test.ts
  app/actions/remote/post.ts
Labels: 2: Dev Review, Build Apps for PR, release-note, kind/feature

#8902 Translations update from Mattermost Weblate
  assets/base/i18n/cs.json
  assets/base/i18n/de.json
  assets/base/i18n/ja.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/pt.json
  assets/base/i18n/sq.json
  assets/base/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod

#8909 Automated cherry pick of #8877
  app/constants/tooltip.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8895 Add Accept Header on ClientTracking
  app/actions/remote/performance.test.ts
  app/client/rest/constants.ts
  app/client/rest/tracking.ts
  app/managers/performance_metrics_manager/test_utils.ts
Labels: 4: Reviews Complete, release-note, Contributor, E2E iOS tests for PR

#8917 Translations update from Mattermost Weblate
  assets/base/i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#8916 Add lastPlaybookFetchAt to channel table
  app/database/migration/server/index.ts
  app/database/models/server/my_channel.ts
  app/database/operator/server_data_operator/transformers/channel.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/my_channel.ts
  app/database/schema/server/test.ts
  app/products/playbooks/actions/local/channel.ts
  app/products/playbooks/database/queries/run.ts
  app/queries/servers/channel.test.ts
  test/test_helper.ts
  types/database/models/servers/my_channel.ts
Labels: 2: Dev Review, release-note-none

#8905 Fix GM/DM unread threads highlighting all teams as unreads
  app/actions/local/thread.ts
  app/components/threads_button/index.ts
  app/database/subscription/unreads.ts
  app/queries/servers/team.test.ts
  app/queries/servers/team.ts
  app/queries/servers/thread.ts
  app/screens/global_threads/index.tsx
  app/screens/global_threads/threads_list/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#8856 Standardize tags and chips through the app
  app/components/chips/base_chip.test.tsx
  app/components/chips/base_chip.tsx
  app/components/chips/constants.ts
  app/components/chips/user_chip.tsx
  app/components/floating_text_chips_input/index.tsx
  app/components/post_list/post/header/display_name/index.tsx
  app/components/post_list/post/header/header.tsx
  app/components/post_list/post/header/reply/index.tsx
  app/components/post_list/post/header/tag/index.tsx
  app/components/post_priority/post_priority_label.test.tsx
  app/components/post_priority/post_priority_label.tsx
  app/components/section_notice/__snapshots__/index.test.tsx.snap
  app/components/section_notice/index.tsx
  app/components/selected_users/index.tsx
  app/components/tag/base_tag.test.tsx
  app/components/tag/base_tag.tsx
  app/components/tag/bot_tag.test.tsx
  app/components/tag/bot_tag.tsx
  app/components/tag/guest_tag.test.tsx
  app/components/tag/guest_tag.tsx
  app/components/tag/index.tsx
  app/components/user_item/user_item.tsx
  app/components/user_list/__snapshots__/index.test.tsx.snap
  app/products/calls/screens/participants_list/participant.tsx
  app/screens/channel/channel_post_list/intro/direct_channel/direct_channel.tsx
  app/screens/channel_add_members/channel_add_members.tsx
  app/screens/channel_info/title/direct_message/direct_message.tsx
  app/screens/component_library/button.cl.tsx
  app/screens/component_library/chip.cl.tsx
  app/screens/component_library/index.tsx
  app/screens/component_library/section_notice.cl.tsx
  app/screens/component_library/tag.cl.tsx
  app/screens/invite/selection.tsx
  app/screens/manage_channel_members/manage_channel_members.tsx
  app/screens/settings/notifications/send_test_notification_notice/__snapshots__/send_test_notification_notice.test.tsx.snap
  app/screens/user_profile/title/index.tsx
  app/screens/user_profile/title/tag.tsx
  app/utils/buttonStyles.ts
  assets/base/i18n/en.json
Labels: Build Apps for PR, 3: QA Review, 2: UX Review, release-note-none

#8903 [MM-62700] User Attribute types
  app/actions/remote/custom_profile.test.ts
  app/actions/remote/custom_profile.ts
  app/actions/remote/user.test.ts
  app/actions/remote/user.ts
  app/components/autocomplete_selector/index.tsx
  app/database/models/server/custom_profile_field.ts
  app/screens/edit_profile/components/form.test.tsx
  app/screens/edit_profile/components/form.tsx
  app/screens/edit_profile/components/select_field.test.tsx
  app/screens/edit_profile/components/select_field.tsx
  app/screens/edit_profile/edit_profile.test.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/edit_profile/index.ts
  app/screens/integration_selector/integration_selector.tsx
  app/screens/user_profile/custom_attributes.test.tsx
  app/screens/user_profile/custom_attributes.tsx
  app/screens/user_profile/index.ts
  app/screens/user_profile/label.test.tsx
  app/screens/user_profile/label.tsx
  app/screens/user_profile/label_link.test.tsx
  app/screens/user_profile/label_link.tsx
  app/screens/user_profile/user_info.test.tsx
  app/screens/user_profile/user_info.tsx
  app/utils/user/index.test.ts
  app/utils/user/index.ts
  assets/base/i18n/en.json
  types/api/custom_profile_attributes.d.ts
  types/database/models/servers/custom_profile_field.ts
  types/screens/edit_profile.ts
Labels: Build Apps for PR, QA Review Done, release-note

#8932 Translations update from Mattermost Weblate
  assets/base/i18n/de.json
  assets/base/i18n/nb_NO.json
  assets/base/i18n/nl.json
  assets/base/i18n/pl.json
  assets/base/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod

#8933 MANUAL CHERRYPICK: Fix GM/DM unread threads highlighting all teams as unreads (#8905)
  app/actions/local/thread.ts
  app/components/threads_button/index.ts
  app/database/subscription/unreads.ts
  app/queries/servers/team.test.ts
  app/queries/servers/team.ts
  app/queries/servers/thread.ts
  app/screens/global_threads/threads_list/index.ts
  app/screens/home/channel_list/categories_list/categories/unreads/index.ts
Labels: release-note

#8801 Urgent mentions do not get the properly coloured mention badge
  app/actions/local/channel.test.ts
  app/actions/local/channel.ts
  app/actions/remote/post.ts
  app/actions/websocket/posts.test.ts
  app/actions/websocket/posts.ts
  app/components/channel_item/channel_item.tsx
  app/components/channel_item/index.ts
Labels: 2: Dev Review, 3: QA Review, release-note, Build App for Android

#8878 [MM-63385] Derive connection state for current call from RTC peer
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/connection/connection.test.ts
  app/products/calls/connection/connection.ts
  app/products/calls/connection/websocket_client.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/state/actions.ts
  app/products/calls/types/calls.ts
Labels: 4: Reviews Complete, release-note-none

#8924 Make the React Native App aware of the minimum hashtag length configuration
  app/components/markdown/index.ts
Labels: 4: Reviews Complete, release-note, Contributor

#8897 First implementation of playbooks API
  app/actions/websocket/event.ts
  app/actions/websocket/index.ts
  app/actions/websocket/plugins.ts
  app/client/rest/index.ts
  app/constants/database.ts
  app/constants/websocket.ts
  app/managers/websocket_manager.ts
  app/products/playbooks/actions/local/version.ts
  app/products/playbooks/actions/remote/runs.ts
  app/products/playbooks/actions/remote/version.ts
  app/products/playbooks/actions/websocket/version.ts
  app/products/playbooks/client/rest.ts
  app/products/playbooks/components/channel_actions/playbook_runs_option/index.ts
  app/products/playbooks/constants/plugin.ts
  app/products/playbooks/database/models/playbook_checklist_item.ts
  app/products/playbooks/database/operators/comparators/index.test.ts
  app/products/playbooks/database/operators/transformers/index.test.ts
  app/products/playbooks/database/queries/checklist.ts
  app/products/playbooks/database/queries/run.test.ts
  app/products/playbooks/database/queries/run.ts
  app/products/playbooks/database/queries/version.ts
  app/products/playbooks/queries/playbooks.ts
  app/products/playbooks/types/api.d.ts
  app/products/playbooks/types/client.d.ts
  app/products/playbooks/types/database/models/playbook_checklist_item.ts
  app/products/playbooks/types/database/transformers/index.d.ts
  app/screens/channel/header/header.test.tsx
  app/screens/channel/header/header.tsx
  app/screens/channel/header/index.ts
  app/store/ephemeral_store.ts
  tsconfig.json
Labels: 2: Dev Review, release-note-none

#8939 Fix commit hashes for download artifacts
  .github/workflows/github-release.yml
Labels: release-note-none

#8940 Automated cherry pick of #8939
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8945 fix typo on curl command of cyclonedx
  .github/workflows/github-release.yml
Labels: release-note

#8927 Add sort_order, update_at and previousReminder columns
  app/database/migration/server/index.ts
  app/database/schema/server/index.ts
  app/database/schema/server/test.ts
  app/products/playbooks/database/models/playbook_checklist.ts
  app/products/playbooks/database/models/playbook_checklist_item.ts
  app/products/playbooks/database/models/playbook_run.ts
  app/products/playbooks/database/operators/comparators/index.test.ts
  app/products/playbooks/database/operators/comparators/index.ts
  app/products/playbooks/database/operators/transformers/index.test.ts
  app/products/playbooks/database/operators/transformers/index.ts
  app/products/playbooks/database/queries/item.test.ts
  app/products/playbooks/database/queries/item.ts
  app/products/playbooks/database/schema/playbook_checklist.ts
  app/products/playbooks/database/schema/playbook_checklist_item.ts
  app/products/playbooks/database/schema/playbook_run.ts
  app/products/playbooks/types/api.d.ts
  app/products/playbooks/types/database/models/playbook_checklist.ts
  app/products/playbooks/types/database/models/playbook_checklist_item.ts
  app/products/playbooks/types/database/models/playbook_run.ts
  app/products/playbooks/types/database/transformers/index.d.ts
  app/products/playbooks/utils/sort_order.test.ts
  app/products/playbooks/utils/sort_order.ts
  test/test_helper.ts
Labels: 2: Dev Review, release-note-none

#8948 Automated cherry pick of #8944
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8950 Automated cherry pick of #8945
  .github/workflows/github-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8918 Viewing Files in Edit mode in mobile with ability to delete and save
  app/actions/remote/post.test.ts
  app/actions/remote/post.ts
  app/components/files/index.ts
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/uploads/index.tsx
  app/components/post_draft/uploads/upload_item/index.tsx
  app/components/post_draft/uploads/upload_item/upload_remove.tsx
  app/constants/events.ts
  app/context/edit_post/index.tsx
  app/queries/servers/file.ts
  app/screens/edit_post/edit_post.test.tsx
  app/screens/edit_post/edit_post.tsx
  app/screens/edit_post/edit_post_input/edit_post_input.test.tsx
  app/screens/edit_post/edit_post_input/edit_post_input.tsx
  app/screens/edit_post/edit_post_input/index.tsx
  app/screens/post_options/options/edit_option/edit_option.tsx
  app/screens/post_options/options/edit_option/index.test.tsx
  app/screens/post_options/options/edit_option/index.ts
  app/utils/file/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#8672 Update additional images branding
  app/components/illustrations/draft_empty.tsx
  app/components/illustrations/loading_error.tsx
  app/components/illustrations/review_app.tsx
  app/components/loading_error/__snapshots__/index.test.tsx.snap
  app/components/loading_error/index.tsx
  app/screens/global_drafts/components/draft_empty_component.tsx
  app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap
  app/screens/review_app/index.tsx
  assets/base/images/Draft_Message.png
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8947 Add websockets for playbooks
  app/actions/websocket/event.ts
  app/actions/websocket/plugins.ts
  app/products/playbooks/actions/local/run.ts
  app/products/playbooks/actions/remote/runs.ts
  app/products/playbooks/actions/websocket/events.ts
  app/products/playbooks/actions/websocket/runs.ts
  app/products/playbooks/constants/websocket.ts
  app/store/ephemeral_store.ts
Labels: release-note-none

#8957 Update NOTICE.txt
  NOTICE.txt
Labels: release-note-none
