Repository mattermost/mattermost-mobile, pull requests merged in 2025-02, with the labels that each got.

#8547 MM-59764 Add tests for launch.ts initialization logic
  app/init/launch.test.ts
  app/init/launch.ts
Labels: 4: Reviews Complete, release-note

#8541 MM-59799 Add tests for NavigationStore
  app/store/navigation_store.test.ts
Labels: 4: Reviews Complete, release-note

#8545 MM-59767 Add tests for AppsManager
  app/managers/apps_manager.test.ts
  app/managers/apps_manager.ts
Labels: 4: Reviews Complete, release-note

#8549 Check file id instead of metadata for file removal
  app/database/operator/server_data_operator/handlers/post.test.ts
  app/database/operator/server_data_operator/handlers/post.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, release-note-none

#8551 Automated cherry pick of #8549
  app/database/operator/server_data_operator/handlers/post.test.ts
  app/database/operator/server_data_operator/handlers/post.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8522 Scheduled post indicator
  app/components/post_list/scroll_to_end_view.tsx
  app/components/scheduled_post_indicator/index.ts
  app/components/scheduled_post_indicator/scheduled_post_indicator.test.tsx
  app/components/scheduled_post_indicator/scheduled_post_indicator.tsx
  app/screens/channel/channel.tsx
  assets/base/i18n/en.json
  ios/Gekidou/Package.resolved
Labels: release-note-none

#8519 Create scheduled post api integration
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/components/post_draft/draft_input/draft_input.test.tsx
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/send_action/index.tsx
  app/components/post_draft/send_action/send_action.test.tsx
  app/components/post_draft/uploads/index.tsx
  app/components/post_list/scroll_to_end_view.tsx
  app/components/scheduled_post_indicator/index.ts
  app/components/scheduled_post_indicator/scheduled_post_indicator.test.tsx
  app/components/scheduled_post_indicator/scheduled_post_indicator.tsx
  app/components/toast/index.tsx
  app/constants/snack_bar.ts
  app/hooks/handle_send_message.test.tsx
  app/hooks/handle_send_message.ts
  app/screens/channel/channel.tsx
  app/screens/convert_gm_to_channel/convert_gm_to_channel_form/convert_gm_to_channel_form.tsx
  app/screens/scheduled_post_options/core_options/core_options.tsx
  app/screens/scheduled_post_options/footer/scheduled_post_footer.test.tsx
  app/screens/scheduled_post_options/footer/scheduled_post_footer.tsx
  app/screens/scheduled_post_options/index.ts
  app/screens/scheduled_post_options/scheduled_post_picker.test.tsx
  app/screens/scheduled_post_options/scheduled_post_picker.tsx
  app/screens/snack_bar/index.tsx
  app/screens/snack_bar/snack_bar.test.tsx
  app/utils/post/index.test.ts
  app/utils/post/index.ts
  app/utils/snack_bar/index.ts
  assets/base/i18n/en.json
  ios/Gekidou/Package.resolved
  types/api/scheduled_post.d.ts
  types/database/raw_values.d.ts
Labels: release-note-none

#8319 Add the Component Library to the app
  app/constants/screens.ts
  app/context/theme/index.tsx
  app/screens/component_library/button.cl.tsx
  app/screens/component_library/hooks.tsx
  app/screens/component_library/index.tsx
  app/screens/component_library/utils.tsx
  app/screens/index.tsx
  app/screens/settings/advanced/advanced.tsx
  app/screens/settings/advanced/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, release-note

#8503 Added Migration to add SchedulePost table in local db for mobile
  app/constants/action_type.ts
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/database/migration/server/index.ts
  app/database/models/server/index.ts
  app/database/models/server/scheduled_post.ts
  app/database/operator/server_data_operator/comparators/scheduled_post.ts
  app/database/operator/server_data_operator/handlers/post.test.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/database/operator/server_data_operator/transformers/post.test.ts
  app/database/operator/server_data_operator/transformers/post.ts
  app/database/schema/server/index.ts
  app/database/schema/server/table_schemas/index.ts
  app/database/schema/server/table_schemas/scheduled_post.ts
  app/database/schema/server/test.ts
  app/queries/servers/scheduled_post.ts
  types/database/database.ts
  types/database/models/servers/scheduled_post.ts
  types/database/raw_values.d.ts
Labels: 2: Dev Review, release-note-none

#8554 Fix android keyboard area when switching apps
  app/hooks/android_adjust_soft_keyboard/index.test.ts
  app/hooks/android_adjust_soft_keyboard/index.ts
  app/screens/channel/channel.tsx
  app/screens/thread/thread.tsx
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note

#8559 Automated cherry pick of #8554
  app/hooks/android_adjust_soft_keyboard/index.test.ts
  app/hooks/android_adjust_soft_keyboard/index.ts
  app/screens/channel/channel.tsx
  app/screens/thread/thread.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8560 Fix plus menu on home screen
  app/screens/home/channel_list/categories_list/header/header.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note-none

#8561 Automated cherry pick of #8560
  app/screens/home/channel_list/categories_list/header/header.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8411 [MM-60405] Crossteam search
  app/components/team_list/index.test.tsx
  app/components/team_list/index.tsx
  app/components/team_list/team_list_item/team_list_item.test.tsx
  app/components/team_list/team_list_item/team_list_item.tsx
  app/constants/index.ts
  app/constants/team.ts
  app/screens/home/search/bottom_sheet_team_list.tsx
  app/screens/home/search/index.tsx
  app/screens/home/search/initial/index.tsx
  app/screens/home/search/initial/initial.tsx
  app/screens/home/search/initial/modifiers/index.test.tsx
  app/screens/home/search/initial/modifiers/index.tsx
  app/screens/home/search/results/header.test.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/search.tsx
  app/screens/home/search/team_picker.test.tsx
  app/screens/home/search/team_picker.tsx
  assets/base/i18n/en.json
  types/api/config.d.ts
Labels: 4: Reviews Complete, Build Apps for PR, 3: QA Review, release-note

#8565 Fix Android keyboard gap using navigation events
  app/constants/screens.ts
  app/hooks/android_adjust_soft_keyboard/index.test.ts
  app/hooks/android_adjust_soft_keyboard/index.ts
  app/screens/channel/channel.tsx
  app/screens/navigation.ts
  app/screens/thread/thread.tsx
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note-none

#8566 Automated cherry pick of #8565
  app/constants/screens.ts
  app/hooks/android_adjust_soft_keyboard/index.test.ts
  app/hooks/android_adjust_soft_keyboard/index.ts
  app/screens/channel/channel.tsx
  app/screens/navigation.ts
  app/screens/thread/thread.tsx
Labels: release-note-none

#8526 Added rest client and local/remote/WebSocket handling for Scheduled Post
  app/actions/local/scheduled_post.test.ts
  app/actions/local/scheduled_post.ts
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/actions/websocket/event.test.ts
  app/actions/websocket/event.ts
  app/actions/websocket/scheduled_post.test.ts
  app/actions/websocket/scheduled_post.ts
  app/client/rest/base.ts
  app/client/rest/index.ts
  app/client/rest/scheduled_post.test.ts
  app/client/rest/scheduled_post.ts
  app/constants/websocket.ts
  types/api/config.d.ts
  types/api/scheduled_post.d.ts
Labels: 2: Dev Review, release-note-none

#8558 MM-59445 + others - Add tests for channel bookmarks, systems, apps and tos files in remote/actions
  app/actions/remote/apps.test.ts
  app/actions/remote/channel_bookmark.test.ts
  app/actions/remote/systems.test.ts
  app/actions/remote/terms_of_service.test.ts
Labels: 2: Dev Review, release-note

#8568 MM-62915 and MM-62919
  android/app/src/main/java/com/mattermost/helpers/Network.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.kt
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/screens/home/account/account.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
  app/screens/home/tab_bar/index.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@mattermost+react-native-network-client+1.8.1.patch
Labels: CherryPick/Approved, 3: QA Review, release-note-none, Build App for iOS

#8572 Automated cherry pick of #8568
  android/app/src/main/java/com/mattermost/helpers/Network.java
  android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.kt
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/screens/home/account/account.tsx
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/results/header.tsx
  app/screens/home/search/results/post_results.tsx
  app/screens/home/search/results/results.tsx
  app/screens/home/search/search.tsx
  app/screens/home/tab_bar/index.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@mattermost+react-native-network-client+1.8.1.patch
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8564 [MM-62898] Reset filter when changing team
  app/screens/home/search/search.test.tsx
  app/screens/home/search/search.tsx
Labels: 4: Reviews Complete, CherryPick/Done, Build Apps for PR, QA Review Done, release-note-none

#8577 Automated cherry pick of #8564
  app/screens/home/search/search.test.tsx
  app/screens/home/search/search.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8578 2.25 fixes
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/search.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note-none

#8580 Automated cherry pick of #8578
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/search.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8581 Automated cherry pick of #8578
  android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
  android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
  app/screens/home/recent_mentions/recent_mentions.tsx
  app/screens/home/saved_messages/saved_messages.tsx
  app/screens/home/search/search.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8573 fix(MM-62375): OOM on gif
  .github/actions/prepare-node-deps/action.yaml
  android/settings.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/expo-image+2.0.4.patch
  scripts/postinstall.sh
Labels: CherryPick/Approved, Build Apps for PR, release-note, kind/bug

#8586 Automated cherry pick of #8573
  .github/actions/prepare-node-deps/action.yaml
  android/settings.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/expo-image+2.0.4.patch
  scripts/postinstall.sh
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8553 Add ability to run detox tests on Android
  .github/actions/generate-specs/split-tests.js
  .github/workflows/e2e-android-detox.yml
  .github/workflows/e2e-android-template.yml
  .github/workflows/e2e-detox-pr.yml
  .github/workflows/e2e-detox-release.yml
  .github/workflows/e2e-detox-scheduled.yml
  .github/workflows/e2e-ios-template.yml
  app/components/floating_text_chips_input/index.tsx
  app/components/option_item/index.tsx
  detox/.detoxrc.json
  detox/README.md
  detox/create_android_emulator.sh
  detox/e2e/support/ui/screen/auto_responder_notification_settings.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/create_or_edit_channel.ts
  detox/e2e/support/ui/screen/email_notification_settings.ts
  detox/e2e/support/ui/screen/invite.ts
  detox/e2e/support/ui/screen/login.ts
  detox/e2e/support/ui/screen/mention_notification_settings.ts
  detox/e2e/support/ui/screen/push_notification_settings.ts
  detox/e2e/support/ui/screen/server.ts
  detox/e2e/support/ui/screen/team_dropdown_menu.ts
  detox/e2e/support/ui/screen/timezone_display_settings.ts
  detox/e2e/test/account/custom_status.e2e.ts
  detox/e2e/test/account/mention_notification_settings.e2e.ts
  detox/e2e/test/autocomplete/at_mention.e2e.ts
  detox/e2e/test/autocomplete/channel_mention.e2e.ts
  detox/e2e/test/channels/channel_info.e2e.ts
  detox/e2e/test/channels/channel_list.e2e.ts
  detox/e2e/test/channels/create_direct_message.e2e.ts
  detox/e2e/test/channels/favorite_and_unfavorite_channel.e2e.ts
  detox/e2e/test/messaging/emojis_and_reactions.e2e.ts
  detox/e2e/test/search/saved_messages.e2e.ts
  detox/e2e/test/search/search_messages.e2e.ts
  detox/e2e/test/server_login/connect_to_server.e2e.ts
  detox/e2e/test/smoke_test/account.e2e.ts
  detox/e2e/test/smoke_test/messaging.e2e.ts
  detox/e2e/test/smoke_test/server_login.e2e.ts
  detox/e2e/test/smoke_test/threads.e2e.ts
  detox/e2e/test/teams/invite_people.e2e.ts
  detox/inject-detox-settings.js
  detox/package-lock.json
  detox/package.json
  detox/save_report.js
  detox/utils/generate_detox_config_ci.js
  detox/utils/report.js
Labels: release-note

#8589 Automated cherry pick of #8573
  .github/actions/prepare-node-deps/action.yaml
  android/settings.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/expo-image+2.0.4.patch
  scripts/postinstall.sh
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8588 Update supported iOS version in Readme
  README.md
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#8591 Automated cherry pick of #8588
  README.md
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8585 Websocket extension
  app/actions/local/scheduled_post.ts
  app/actions/remote/scheduled_post.test.ts
  app/actions/remote/scheduled_post.ts
  app/actions/websocket/scheduled_post.test.ts
  app/actions/websocket/scheduled_post.ts
Labels: release-note-none

#8459 Fix MM-61975
  app/actions/remote/session.test.ts
  app/actions/remote/session.ts
  app/client/rest/tracking.ts
  app/managers/session_manager.test.ts
  app/managers/session_manager.ts
  app/screens/home/account/components/options/logout/index.tsx
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/select_team/header.tsx
  app/screens/terms_of_service/terms_of_service.tsx
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note-none

#8592 Random Cleanup
  android/app/src/main/java/com/mattermost/helpers/RandomId.kt
  libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/helpers/NotificationHelper.kt
Labels: release-note-none

#8594 Used button instead of TouchableOpacity
  app/screens/scheduled_post_options/footer/scheduled_post_footer.tsx
Labels: release-note-none

#8599 Automated cherry pick of #8459
  app/actions/remote/session.test.ts
  app/actions/remote/session.ts
  app/client/rest/tracking.ts
  app/managers/session_manager.test.ts
  app/managers/session_manager.ts
  app/screens/home/account/components/options/logout/index.tsx
  app/screens/home/channel_list/categories_list/header/header.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/screens/select_team/header.tsx
  app/screens/terms_of_service/terms_of_service.tsx
  assets/base/i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8606 feat/Add-dependabot-for-gha
  .github/dependabot.yaml
Labels: release-note, kind/feature

#8610 fix: Add multiple directories for dependabot
  .github/dependabot.yaml
Labels: release-note, kind/feature

#7900 Implementing the Audio Playback/Download on the chat
  app/components/channel_bookmarks/channel_bookmark/bookmark_document.tsx
  app/components/document/index.tsx
  app/components/files/audio_file.tsx
  app/components/files/document_file.tsx
  app/components/files/file.tsx
  app/components/progress_bar/index.tsx
  app/hooks/files.test.ts
  app/hooks/files.ts
  app/hooks/throttled.ts
  app/utils/file/index.ts
  assets/base/i18n/en.json
Labels: 4: Reviews Complete, Build Apps for PR, release-note, Contributor

#8612 fix: Proper glob path
  .github/dependabot.yaml
Labels: release-note, kind/bug

#8557 [MM-62701] [MM-62176]Edit custom profile attributes in user profile
  app/actions/remote/user.test.ts
  app/actions/remote/user.ts
  app/client/rest/base.ts
  app/client/rest/custom_profile_attributes.test.ts
  app/client/rest/custom_profile_attributes.ts
  app/components/floating_text_input_label/index.tsx
  app/hooks/field_refs.test.ts
  app/hooks/field_refs.ts
  app/screens/edit_profile/components/email_field.tsx
  app/screens/edit_profile/components/field.tsx
  app/screens/edit_profile/components/form.test.tsx
  app/screens/edit_profile/components/form.tsx
  app/screens/edit_profile/edit_profile.tsx
  app/screens/edit_profile/index.ts
  types/screens/edit_profile.ts
Labels: Build Apps for PR, QA Review Done, 2: UX Review, release-note

#8608 Pin and bump nokogiri
  fastlane/Gemfile
  fastlane/Gemfile.lock
Labels: release-note-none

#8593 Scheduled post feature popup
  app/actions/app/global.test.ts
  app/actions/app/global.ts
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/send_action/index.tsx
  app/components/post_draft/send_button/index.tsx
  app/components/post_draft/send_button/scheduled_post_tooltip.test.tsx
  app/components/post_draft/send_button/scheduled_post_tooltip.tsx
  app/components/post_draft/send_button/send_button.test.tsx
  app/components/post_draft/send_button/send_button.tsx
  app/constants/tutorial.ts
  assets/base/i18n/en.json
  test/setup.ts
Labels: 2: Dev Review, release-note-none

#8617 Bump package-lock.json version to 2.26
  package-lock.json
Labels: 2: Dev Review, release-note-none

#8555 Add ios native logs
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.mm
  ios/NotificationService/NotificationService.swift
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#8631 Automated cherry pick of #8555
  ios/Mattermost.xcodeproj/project.pbxproj
  ios/Mattermost/AppDelegate.mm
  ios/NotificationService/NotificationService.swift
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8618 [MM-62666] Cpa sort order
  app/actions/remote/user.test.ts
  app/actions/remote/user.ts
  app/client/rest/custom_profile_attributes.ts
  app/screens/edit_profile/components/form.test.tsx
  app/screens/edit_profile/components/form.tsx
  app/screens/user_profile/custom_attributes.tsx
  app/screens/user_profile/user_info.test.tsx
  app/screens/user_profile/user_info.tsx
  app/utils/user/index.ts
  types/api/custom_profile_attributes.d.ts
  types/api/users.d.ts
  types/screens/edit_profile.ts
Labels: 4: Reviews Complete, Build Apps for PR, QA Review Done, release-note-none

#8639 Enforce names for singleton imports
  app/database/manager/__mocks__/index.ts
  app/database/manager/index.ts
  app/init/managed_app.ts
  app/init/push_notifications.ts
  app/managers/apps_manager.test.ts
  app/managers/apps_manager.ts
  app/managers/draft_upload_manager/index.test.ts
  app/managers/draft_upload_manager/index.ts
  app/managers/global_event_handler.ts
  app/managers/integrations_manager.ts
  app/managers/network_manager.ts
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
  app/managers/session_manager.test.ts
  app/managers/session_manager.ts
  app/managers/websocket_manager.ts
  app/store/ephemeral_store.ts
  app/store/navigation_store.ts
  app/utils/error_handling.ts
  test/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#8622 fix(MM-62375): OutOfMemoryError issue with better catching
  .github/actions/prepare-node-deps/action.yaml
  package-lock.json
  package.json
  scripts/postinstall.sh
Labels: Build Apps for PR, release-note, kind/bug
