Repository mattermost/mattermost-mobile, pull requests merged in 2025-01, with the labels that each got.

#8443 MM-62394 Add unit tests to utils/message_attachment
  app/utils/message_attachment.test.ts
  app/utils/message_attachment.ts
  app/utils/message_attachment_colors.test.ts
Labels: 4: Reviews Complete, release-note

#8439 fix: improve parallel requests calculation
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
Labels: release-note

#8444 MM-59600 Add unit tests to utils/opengraph
  app/utils/opengraph.test.ts
  app/utils/opengraph.ts
Labels: 2: Dev Review, release-note

#8447 MM-59683 + more - Add tests to client/rest
  app/actions/remote/search.ts
  app/client/rest/categories.test.ts
  app/client/rest/channel_bookmark.test.ts
  app/client/rest/channels.test.ts
  app/client/rest/emojis.test.ts
  app/client/rest/files.test.ts
  app/client/rest/files.ts
  app/client/rest/general.test.ts
  app/client/rest/groups.test.ts
  app/client/rest/integrations.test.ts
  app/client/rest/nps.test.ts
  app/client/rest/plugins.test.ts
  app/client/rest/posts.test.ts
  app/client/rest/preferences.test.ts
  app/client/rest/teams.test.ts
  app/client/rest/threads.test.ts
  app/client/rest/tos.test.ts
  app/client/rest/users.test.ts
Labels: 4: Reviews Complete, release-note

#8456 MM-59579 Add tests for utils/server
  app/utils/server/index.test.ts
  app/utils/server/server.test.ts
Labels: 4: Reviews Complete, release-note

#8455 MM-59583 Add tests for utils/theme
  app/utils/theme/index.test.ts
  app/utils/theme/test.ts
Labels: 4: Reviews Complete, release-note

#8445 MM-59433 Add unit tests to actions/remote/retry
  app/actions/remote/retry.test.ts
Labels: 4: Reviews Complete, release-note

#8452 MM-59684 Add tests for client/websocket
  app/client/websocket/index.test.ts
  app/client/websocket/index.ts
Labels: 4: Reviews Complete, release-note

#8453 MM-59586 Add tests for utils/user
  app/utils/user/index.test.ts
  app/utils/user/index.ts
Labels: 4: Reviews Complete, release-note

#8424 test(MM-59431): file.ts unit test
  app/actions/remote/file.test.ts
Labels: release-note

#8280 Mobile drafts
  app/actions/app/global.ts
  app/actions/local/draft.test.ts
  app/actions/local/draft.ts
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/draft/draft.tsx
  app/components/draft/draft_post/draft_files/index.ts
  app/components/draft/draft_post/draft_message.tsx
  app/components/draft/draft_post/index.tsx
  app/components/draft/index.tsx
  app/components/draft_post_header/draft_post_header.tsx
  app/components/draft_post_header/index.tsx
  app/components/draft_post_header/profile_avatar.tsx
  app/components/drafts_buttton/drafts_button.tsx
  app/components/files/files.tsx
  app/components/post_draft/draft_input/index.tsx
  app/components/post_draft/post_input/post_input.tsx
  app/components/post_draft/send_handler/index.ts
  app/components/post_draft/send_handler/send_handler.tsx
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
  app/components/threads_button/threads_button.tsx
  app/constants/events.ts
  app/constants/screens.ts
  app/constants/tutorial.ts
  app/hooks/handle_send_message.ts
  app/hooks/persistent_notification_props.ts
  app/queries/servers/drafts.ts
  app/screens/draft_options/delete_draft.tsx
  app/screens/draft_options/edit_draft.tsx
  app/screens/draft_options/index.tsx
  app/screens/draft_options/send_draft.tsx
  app/screens/global_drafts/components/draft_empty_component.tsx
  app/screens/global_drafts/components/global_drafts_list/draft_swipe_actions.tsx
  app/screens/global_drafts/components/global_drafts_list/draft_tooltip.tsx
  app/screens/global_drafts/components/global_drafts_list/global_drafts_list.tsx
  app/screens/global_drafts/components/global_drafts_list/index.tsx
  app/screens/global_drafts/index.tsx
  app/screens/home/channel_list/additional_tablet_view/additional_tablet_view.tsx
  app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
  app/screens/home/channel_list/categories_list/categories/categories.tsx
  app/screens/home/channel_list/categories_list/categories_list.tsx
  app/screens/home/channel_list/categories_list/index.test.tsx
  app/screens/home/channel_list/categories_list/index.tsx
  app/screens/index.tsx
  app/utils/draft/index.ts
  app/utils/post/index.ts
  app/utils/url/index.test.ts
  app/utils/url/index.ts
  assets/base/i18n/en.json
  assets/base/images/Draft_Message.png
  assets/base/images/emojis/swipe.png
  package-lock.json
  package.json
Labels: CherryPick/Approved, Build Apps for PR, 3: QA Review, 2: UX Review, release-note

#8460 View custom profile attributes
  app/client/rest/base.ts
  app/client/rest/custom_profile_attributes.test.ts
  app/client/rest/custom_profile_attributes.ts
  app/client/rest/index.ts
  app/client/rest/users.ts
  app/screens/user_profile/custom_attributes.tsx
  app/screens/user_profile/index.ts
  app/screens/user_profile/label.tsx
  app/screens/user_profile/user_info.tsx
  app/screens/user_profile/user_profile.tsx
  types/api/config.d.ts
  types/api/custom_profile_attributes.d.ts
  types/api/users.d.ts
Labels: Build Apps for PR, QA Review Done, 3: Security Review, release-note, E2E iOS tests for PR

#8465 MM-59656 Add tests for actions/websocket/posts
  app/actions/websocket/posts.test.ts
  app/actions/websocket/posts.ts
Labels: 4: Reviews Complete, release-note

#8470 MM-59653 Add tests for actions/websocket/event
  app/actions/websocket/event.test.ts
Labels: 4: Reviews Complete, release-note

#8462 MM-59585 Add tests for utils/url
  app/utils/url/index.test.ts
Labels: 2: Dev Review, release-note

#8475 Automated cherry pick of #8460
  app/client/rest/base.ts
  app/client/rest/custom_profile_attributes.test.ts
  app/client/rest/custom_profile_attributes.ts
  app/client/rest/index.ts
  app/client/rest/users.ts
  app/screens/user_profile/custom_attributes.tsx
  app/screens/user_profile/index.ts
  app/screens/user_profile/label.tsx
  app/screens/user_profile/user_info.tsx
  app/screens/user_profile/user_profile.tsx
  types/api/config.d.ts
  types/api/custom_profile_attributes.d.ts
  types/api/users.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8477 MM-59776 Add queries/app/servers tests
  app/queries/app/servers.test.ts
Labels: 4: Reviews Complete, release-note

#8478 fix: RN 0.76.5 issue with bottom sheet disappearing
  app/screens/bottom_sheet/index.tsx
Labels: release-note, Build App for iOS

#8405 Add android detox apk build workflow
  .github/workflows/e2e-android-detox.yml
  detox/README.md
Labels: release-note-none, E2E Android tests for PR

#8407 Add some improvements to thread handling
  android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
  android/app/src/main/java/com/mattermost/helpers/database_extension/Thread.kt
  app/actions/remote/entry/common.ts
  app/actions/remote/thread.ts
  app/database/operator/server_data_operator/transformers/thread.ts
  app/queries/servers/thread.ts
  app/screens/global_threads/threads_list/index.ts
  app/screens/global_threads/threads_list/threads_list.tsx
  app/utils/thread/index.ts
  ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+FetchData.swift
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note

#8481 Automated cherry pick of #8407
  android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
  android/app/src/main/java/com/mattermost/helpers/database_extension/Thread.kt
  app/actions/remote/entry/common.ts
  app/actions/remote/thread.ts
  app/database/operator/server_data_operator/transformers/thread.ts
  app/queries/servers/thread.ts
  app/screens/global_threads/threads_list/index.ts
  app/screens/global_threads/threads_list/threads_list.tsx
  app/utils/thread/index.ts
  ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+FetchData.swift
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8458 MM-62411 Retrying SSO does not trigger a redirect
  app/screens/sso/index.tsx
  app/screens/sso/sso.test.tsx
  app/screens/sso/sso_authentication.tsx
  app/screens/sso/sso_authentication_with_external_browser.tsx
Labels: 4: Reviews Complete, Build Apps for PR, release-note-none, Contributor

#8484 Fix package lock identation
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#8479 MM-59661 Add tests for actions/websocket/teams
  app/actions/websocket/teams.test.ts
Labels: 4: Reviews Complete, release-note

#8485 Fix timezone crash
  app/components/formatted_date/__snapshots__/index.test.tsx.snap
  app/components/formatted_date/index.test.tsx
  app/components/formatted_date/index.tsx
  assets/base/i18n/en.json
  index.ts
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note

#8487 cherry pick of #8420: Request metrics improvements (#8420)
  app/actions/local/channel.ts
  app/actions/remote/channel.ts
  app/actions/remote/channel_bookmark.ts
  app/actions/remote/entry/app.ts
  app/actions/remote/entry/common.ts
  app/actions/remote/entry/login.ts
  app/actions/remote/entry/notification.ts
  app/actions/remote/groups.ts
  app/actions/remote/post.test.ts
  app/actions/remote/post.ts
  app/actions/remote/preference.ts
  app/actions/remote/role.ts
  app/actions/remote/systems.ts
  app/actions/remote/team.test.ts
  app/actions/remote/team.ts
  app/actions/remote/thread.ts
  app/actions/remote/user.ts
  app/actions/websocket/index.ts
  app/client/rest/apps.ts
  app/client/rest/categories.ts
  app/client/rest/channel_bookmark.test.ts
  app/client/rest/channel_bookmark.ts
  app/client/rest/channels.ts
  app/client/rest/general.test.ts
  app/client/rest/general.ts
  app/client/rest/groups.test.ts
  app/client/rest/groups.ts
  app/client/rest/posts.ts
  app/client/rest/preferences.test.ts
  app/client/rest/preferences.ts
  app/client/rest/teams.ts
  app/client/rest/threads.test.ts
  app/client/rest/threads.ts
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
  app/client/rest/users.ts
  app/constants/general.ts
  app/init/launch.ts
  app/managers/apps_manager.ts
  app/managers/performance_metrics_manager/constant.ts
  app/managers/performance_metrics_manager/index.test.ts
  app/managers/performance_metrics_manager/index.ts
  app/managers/performance_metrics_manager/performance_metrics_batcher.ts
  app/managers/performance_metrics_manager/types.d.ts
  app/managers/websocket_manager.ts
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/client/rest.ts
  app/products/calls/components/call_notification/call_notification.tsx
  app/products/calls/screens/call_screen/call_screen.tsx
  app/queries/servers/channel.test.ts
  app/queries/servers/channel.ts
  app/queries/servers/entry.ts
  app/screens/home/channel_list/channel_list.tsx
  app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
  app/utils/deep_link/index.test.ts
  app/utils/deep_link/index.ts
  app/utils/file/file_picker/index.test.ts
  fastlane/Fastfile
  types/api/client.d.ts
Labels: release-note

#8488 Cherrypick 592b380 to version 2.24
  app/components/formatted_date/__snapshots__/index.test.tsx.snap
  app/components/formatted_date/index.test.tsx
  app/components/formatted_date/index.tsx
  assets/base/i18n/en.json
  index.ts
  package-lock.json
  package.json
Labels: release-note-none

#8489 Cherrypick 592b380 to 2.25
  app/components/formatted_date/__snapshots__/index.test.tsx.snap
  app/components/formatted_date/index.test.tsx
  app/components/formatted_date/index.tsx
  assets/base/i18n/en.json
  index.ts
  package-lock.json
  package.json
Labels: release-note-none

#8468 Fix edit attachments
  app/components/files/file.tsx
  app/components/files/files.test.tsx
  app/components/files/files.tsx
  app/components/files_search/file_results.tsx
  app/database/operator/server_data_operator/handlers/post.test.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/hooks/files.test.ts
  app/hooks/files.ts
  app/hooks/gallery.ts
  app/hooks/utils.test.tsx
  app/hooks/utils.ts
  test/api_mocks/file.ts
Labels: Build Apps for PR, 3: QA Review, release-note-none

#8492 Automated cherry pick of #8468
  app/components/files/file.tsx
  app/components/files/files.test.tsx
  app/components/files/files.tsx
  app/components/files_search/file_results.tsx
  app/database/operator/server_data_operator/handlers/post.test.ts
  app/database/operator/server_data_operator/handlers/post.ts
  app/hooks/files.test.ts
  app/hooks/files.ts
  app/hooks/gallery.ts
  app/hooks/utils.test.tsx
  app/hooks/utils.ts
  test/api_mocks/file.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8486 Add tests to index, group and users websocket actions
  app/actions/websocket/group.test.ts
  app/actions/websocket/index.test.ts
  app/actions/websocket/users.test.ts
  app/actions/websocket/users.ts
Labels: 4: Reviews Complete, release-note

#8500 Automated cherry pick of #8499
  NOTICE.txt
Labels: release-note-none

#8502 Added types and model for scheduled post
  app/constants/database.ts
  app/database/models/server/scheduled_post.ts
  types/database/models/servers/scheduled_post.ts
  types/database/raw_values.d.ts
Labels: release-note-none

#8448 MM-59740 + others - Add tests for various files in hooks/
  app/hooks/android_back_handler.test.ts
  app/hooks/emoji_category_bar.test.ts
  app/hooks/files.test.ts
  app/hooks/gallery.test.ts
  app/hooks/gallery.ts
  app/hooks/markdown.test.ts
Labels: 4: Reviews Complete, release-note

#8495 Add tests to remaining actions/websocket files
  app/actions/websocket/category.test.ts
  app/actions/websocket/category.ts
  app/actions/websocket/integrations.test.ts
  app/actions/websocket/preferences.test.ts
  app/actions/websocket/reactions.test.ts
  app/actions/websocket/roles.test.ts
  app/actions/websocket/system.test.ts
  app/actions/websocket/threads.test.ts
Labels: 4: Reviews Complete, release-note

#8496 MM-59772 Add websocket manager tests
  app/managers/websocket_manager.test.ts
Labels: 4: Reviews Complete, release-note

#8480 [MM-59773] Add unit tests for Calls
  app/products/calls/actions/calls.test.ts
  app/products/calls/actions/calls.ts
  app/products/calls/actions/index.ts
  app/products/calls/actions/permissions.test.ts
  app/products/calls/alerts.test.ts
  app/products/calls/calls_manager.test.ts
  app/products/calls/client/rest.test.ts
  app/products/calls/client/rest.ts
  app/products/calls/connection/connection.test.ts
  app/products/calls/connection/websocket_client.test.ts
  app/products/calls/connection/websocket_client.ts
  app/products/calls/connection/websocket_event_handlers.test.ts
  app/products/calls/hooks.test.ts
  app/products/calls/observers/index.test.ts
  app/products/calls/observers/index.ts
  app/products/calls/state/actions.test.ts
  app/products/calls/utils.test.ts
Labels: 4: Reviews Complete, release-note-none

#8469 E2E: Mobile Drafts tests cases
  app/components/drafts_buttton/drafts_button.tsx
  app/components/option_item/index.tsx
  app/components/post_draft/draft_input/header.tsx
  app/components/post_priority/post_priority_label.tsx
  app/screens/post_priority_picker/post_priority_picker.tsx
  detox/e2e/support/ui/component/alert.ts
  detox/e2e/support/ui/screen/channel.ts
  detox/e2e/support/ui/screen/channel_list.ts
  detox/e2e/support/ui/screen/draft_screen.ts
  detox/e2e/support/ui/screen/index.ts
  detox/e2e/test/messaging/message_local_drafts.e2e.ts
Labels: release-note-none

#8494 Fix styles for add people ephemeral message
  app/components/post_list/post/body/add_members/add_members.tsx
Labels: 4: Reviews Complete, Build Apps for PR, release-note

#8505 Update environment variable COLLECT_NETWORK_METRICS
  fastlane/.env.android.beta
  fastlane/.env.android.pr
  fastlane/.env.android.release
  fastlane/.env.ios.beta
  fastlane/.env.ios.pr
  fastlane/.env.ios.release
  fastlane/Fastfile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, kind/chore

#8511 Automated cherry pick of #8505
  fastlane/.env.android.beta
  fastlane/.env.android.pr
  fastlane/.env.android.release
  fastlane/.env.ios.beta
  fastlane/.env.ios.pr
  fastlane/.env.ios.release
  fastlane/Fastfile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8518 fix(MM-60645): missing bookmark emoji
  app/components/channel_bookmarks/channel_bookmark/bookmark_icon.test.tsx
  app/components/channel_bookmarks/channel_bookmark/bookmark_icon.tsx
  app/components/files/file_icon.tsx
Labels: release-note, kind/bug

#8406 Fix broken windows
  app/screens/gallery/video_renderer/error.tsx
  app/screens/gallery/video_renderer/index.tsx
  app/screens/share_feedback/index.tsx
  app/utils/images/index.test.ts
  app/utils/images/index.ts
Labels: Build Apps for PR, 3: QA Review, release-note

#8523 MM-62726 fix the active label color for channel and thread
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
Labels: CherryPick/Approved, 3: QA Review, release-note-none

#8525 Automated cherry pick of #8523
  app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
  app/components/channel_item/channel_item.tsx
  app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8504 MM-59771 Add tests for session manager
  app/managers/session_manager.test.ts
  app/managers/session_manager.ts
Labels: 4: Reviews Complete, release-note

#8515 MM-59426 Add tests for entry common functions
  app/actions/remote/entry/common.test.ts
  app/actions/remote/entry/common.ts
Labels: 4: Reviews Complete, release-note

#8517 MM-59741 + others - Add tests for remaining app/hooks files
  app/hooks/apps.test.tsx
  app/hooks/autocomplete.test.ts
  app/hooks/channel_switch.test.ts
  app/hooks/device.test.tsx
  app/hooks/device.ts
  app/hooks/did_update.test.tsx
  app/hooks/fetching_thread.test.ts
  app/hooks/freeze.test.ts
  app/hooks/handle_send_message.test.tsx
  app/hooks/header.test.tsx
  app/hooks/input.test.ts
  app/hooks/navigate_back.test.ts
  app/hooks/navigation_button_pressed.test.ts
  app/hooks/persistent_notification_props.test.ts
  app/hooks/show_more.test.ts
  app/hooks/team_switch.test.ts
  app/hooks/teams_loading.test.ts
  app/hooks/why_did_you_update.test.ts
Labels: 4: Reviews Complete, release-note

#8507 Show scheduled post options
  app/actions/remote/scheduled_post.ts
  app/client/rest/base.ts
  app/client/rest/index.ts
  app/client/rest/scheduled_post.ts
  app/components/formatted_time/index.tsx
  app/components/post_draft/draft_input/draft_input.tsx
  app/components/post_draft/send_action/index.tsx
  app/components/post_draft/send_handler/send_handler.tsx
  app/constants/screens.ts
  app/screens/channel_bookmark/index.tsx
  app/screens/custom_status_clear_after/components/date_time_selector.tsx
  app/screens/index.tsx
  app/screens/scheduled_post_options/core_options/core_options.tsx
  app/screens/scheduled_post_options/core_options/index.ts
  app/screens/scheduled_post_options/footer/index.ts
  app/screens/scheduled_post_options/footer/scheduled_post_footer.tsx
  app/screens/scheduled_post_options/index.ts
  app/screens/scheduled_post_options/scheduled_post_picker.tsx
  assets/base/i18n/en.json
  types/api/config.d.ts
  types/api/scheduled_post.d.ts
Labels: 4: Reviews Complete, release-note-none

#8524 [MM-62712] Fix hashtag loop
  app/screens/home/search/search.tsx
Labels: 2: Dev Review, CherryPick/Approved, Build Apps for PR, QA Review Done, release-note

#8529 Automated cherry pick of #8524
  app/screens/home/search/search.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8533 Fix flaky client/rest/general/ping test
  app/client/rest/general.test.ts
Labels: 4: Reviews Complete, release-note

#8530 MM-59787 Add tests for preference query functions
  app/queries/servers/preference.test.ts
Labels: 4: Reviews Complete, release-note

#8528 fix(MM-62461): uploading image attachment shows new message
  app/components/post_list/post_list.test.tsx
  app/components/post_list/post_list.tsx
  app/components/post_list/scroll_to_end_view.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Build Apps for PR, release-note, kind/bug

#8537 Automated cherry pick of #8528
  app/components/post_list/post_list.test.tsx
  app/components/post_list/post_list.tsx
  app/components/post_list/scroll_to_end_view.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8535 MM-59766 Add tests for push notifications module
  app/init/push_notifications.test.ts
Labels: 4: Reviews Complete, release-note

#8532 MM-59789 Add tests for role queries
  app/queries/servers/role.test.ts
Labels: 4: Reviews Complete, release-note

#8527 MM-59790 Add tests for team queries
  app/queries/servers/team.test.ts
Labels: 4: Reviews Complete, release-note

#8531 [MM-62777] Fix errors being nested. Make MFA code more resilient to this situation
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
  app/screens/login/form.tsx
  app/utils/errors.test.ts
  app/utils/errors.ts
Labels: CherryPick/Approved, Build Apps for PR, release-note-none

#8542 Automated cherry pick of #8531
  app/client/rest/tracking.test.ts
  app/client/rest/tracking.ts
  app/screens/login/form.tsx
  app/utils/errors.test.ts
  app/utils/errors.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8540 Add logs for push errors on android
  android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
Labels: CherryPick/Approved, release-note-none

#8544 Automated cherry pick of #8540
  android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8534 MM-59782 Add entry query function tests
  app/queries/servers/entry.test.ts
Labels: 4: Reviews Complete, release-note

#8510 MM-59761 Add tests for i18n functionality
  app/i18n/index.test.ts
  app/i18n/index.ts
Labels: 4: Reviews Complete, release-note

#8539 fix: remove from channel
  app/actions/remote/channel.ts
  package-lock.json
Labels: CherryPick/Approved, Build Apps for PR, QA Review Done, release-note-none

#8546 Automated cherry pick of #8539
  app/actions/remote/channel.ts
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none
